### ISSUE TITLE
After restarting OpenDDS, calling TransportRegistry::create_inst fails 

### ISSUE THREAD

**Issue by kmarcey** [objectcomputing/OpenDDS#1005]
I am working on integrating OpenDDS into an existing library as an additional protocol to interface with our product. Because of the way this library is used, a user may have several instances of it instantiated at once and the instances may be created and destroyed at any time.

I maintain a reference count of current instances using DDS and wait until the last one is destroyed before calling things like Service_Participant::shutdown. However if at some later time a user creates a new instance, I restart OpenDDS and attempt to redo the transport configuration, recreate the DomainParticipant, etc. Currently, using the 3.13 release this fails when I call TransportRegistry::create_inst. The call returns null and I see a message "TransportRegistry::create_inst: transport_type=rtps_udp is not registered." in the log. 

If I run my test client with the ACE_DEBUG=1 environment variable set, I see OpenDDS_Rtps_Udpd.dll being opened, seemingly successfully and I don't see any other obvious errors being reported.

I have attached the output when ACE_DEBUG=1 in case it is of any use. There are a few comments describing when I initialize OpenDDS for the first time, when I call Service_Participant::shutdown, and when I try to restart OpenDDS.

It seems that this might be the same issue described in #991 but I wasn't able to find any existing bug reports on this.

Is there anything special I need to do when restarting OpenDDS versus when I start it for the first time?

[ACE_DEBUG.txt](https://github.com/objectcomputing/OpenDDS/files/2658148/ACE_DEBUG.txt)

**Comment by mitza-oci** [comment]
Fixed in #1081
