### ISSUE TITLE
make install does not provide a complete development environment

### ISSUE THREAD

**Issue by rcmcminn** [objectcomputing/OpenDDS#1006]
I configure OpenDDS-3.13 with the following command:

./configure --prefix=/opt/OpenDDS

After the configuration script completes, I run the "make" command as instructed.

After "make" completes, I issue the "make install" command from. At that point, a series of folders and folder content is copied from the build area to the install area.

What I want to do at this point is eliminate the build area, but I cannot due to the following:

1. I cannot compile IDL using the install directories. The process begins, but ends quickly with fatal errors. The errors are due to the absence of referenced #includes. The included files exist in the build area, but not in the installed area.

After I use the build area to auto-generate DDS Topic code, I then attempt to use MPC to create a Make file. The mwc.pl command terminates with errors due to missing MPC modules.

The INSTALL file indicates that the "make install" provides a complete development environment, but it appears this is not the case. Am I missing a step or multiple steps? For example, in the install area, there are three scripts that set DDS_ROOT, ACE_ROOT and TAO_ROOT, but there is no setting for MPC_ROOT.

**Comment by dreamtale90** [comment]
I've had the same problem before. After executing "make install" command,  some functions of OpenDDS are not available. After a few days, I found that a manual copy would be OK. This may help you.
`cp /root/OpenDDS-3.12_Source/ACE_wrappers/MPC/config/* /root/OpenDDS-3.12/share/tao/MPC/config/ -arf
cp /root/OpenDDS-3.12_Source/ACE_wrappers/MPC/modules/* /root/OpenDDS-3.12/share/tao/MPC/modules/ -arf`

**Comment by mitza-oci** [comment]
This has been on my list to clarify in the `INSTALL` document for a little while, as you're not the first to run into it.  The phrase "development environment" here refers to the headers, libraries, and code generators needed for you to develop an application built on OpenDDS.  

Your own application can use any build system, but we've always supported MPC.  We now have initial support for CMake as well.  You could use something else but then you're on your own for setting it up.  If you do chose to use MPC, the MPC code itself (`MPC_ROOT`) needs to be available for your development environment.  You may want it installed to the same prefix, but that's up to you.  You can just copy it to a location of your choice and set `MPC_ROOT`.  This is a significant difference from what @dreamtale90 mentioned above.

If there are still problems please list the exact steps to reproduce and the exact error message in your reply.

**Comment by rcmcminn** [comment]
Yes. Placing the MPC directory into the INSTALL solves a portion of the problem.

For my installation, the --prefix option was set to /opt/OpenDDS.

I copied the OpenDDS-3-13/ACE_Wrappers/MPC folder to /opt/OpenDDS/share. I then set the MPC_ROOT variable to point to the new directory.

Once that was done, I could then run the mwc.pl script to generate my Make files.

All was fine until I reached a folder with IDL content. The mwc.pl script generated the Makefiles as before, but when I run the "make " command I get the following:

make[1]: Entering directory `/media/psf/Home/Development/CCTT_M3/Messages'
/opt/OpenDDS/share/ace/bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I/opt/OpenDDS/share/tao -Sa -St -I/opt/OpenDDS/share/dds cctt_m3TypeSupport.idl
cctt_m3TypeSupport.idl:7:41: fatal error: dds/DdsDcpsInfrastructure.idl: No such file or directory
 #include "dds/DdsDcpsInfrastructure.idl"
                                         ^
compilation terminated.

I noted that the missing IDL file was in a different spot in the INSTALL area than it is in the BUILD area. I copied a set of IDL files into /opt/OpenDDS/share/dds/dds from the /opt/OpenDDS/include directory and re-ran the "make" command.

The Infrastructure.idl file was located, but now there were errors in the #includes of that IDL file where it was looking for other IDL files.

The "make" step for building OpenDDS appears to rely heavily on MPC. I have trouble understanding why the "make install" step severs support for MPC.

**Comment by mitza-oci** [comment]
Please see #1086 for the updated documentation.

Aside from the issue of copying MPC to the desired location, it wasn't clear to me from the previous post if there was another problem using `make install`.  We are using it on a few projects and not experiencing the type of problems mentioned.  If we have the step-by-step instructions to reproduce the issue we can take a look.
