### ISSUE TITLE
How to disable build targets and/or MPC features using configure script

### ISSUE THREAD

**Issue by ajkerzner** [objectcomputing/OpenDDS#1024]
Anyone know how to disable a build target using the configure script? I have a target being enabled by an optional dependency, but failing. Specifically, the Monitor target being enabled by detecting a system Qt 5.12 installation. The corresponding MPC feature is "qt5". I tried "--no-qt", but that seemed to not work. Using OpenDDS 3.13.

**Comment by mitza-oci** [comment]
Please paste here the output of `tools/scripts/show_build_config.pl` so we know what the configure script generated.  Should be a simple adjustment to that to make it skip Qt.

Also `--no-qt` should work, could you submit a pull request for that?

**Comment by ajkerzner** [comment]
I had a moment to go back to this, and I figured out my immediate problem. The improvements (for said problem) that I would have requested and/or worked on were already made in pull requests like #932 .

### Immediate problem ###
I have a system with both Qt4 and Qt5 environments. In this environment, Qt4 was detected and used. However, the moc/uic binaries had the "-qt4" suffix, so I had to export QT4_SUFFIX="-qt4" according to [the qt4_gui.mpb file of the MPC project](https://github.com/DOCGroup/MPC/blob/master/config/qt4_gui.mpb). Otherwise, the Qt5 binaries would be used, and compilation would fail with Qt5-generated headers and source files.

The build process has changed a bit with the move to Qt5 after the 3.13 release, so I doubt that this will be a big problem in the future.

### --no-qt ###

I just confirmed with the latest from master, that the configure script does not accept "--no-qt", printing the following message followed by the help text:
`Unknown option: no-qt`

I assume that this is due to the difference between how "Optional OpenDDS features" and "Optional dependencies for OpenDDS" are handled. Regardless, I don't know much about how the configure script handles both _and_ a strong dislike for perl mean I have no desire to put in a pull request for this at this time.

(Also, qt failed, but that's a different issue (with a known resolution) - #1033 .)

**Comment by mitza-oci** [comment]
@iguessthislldo please look at support for `--no-qt` in the master version of the configure script

**Comment by iguessthislldo** [comment]
Looking at `./configure --help` again, `--no-qt` is not a valid option. It's works like @ajkerzner described: Things that are default enabled, like most of the optional features, have a inverse option (`--no-debug`), while all the optional dependencies are by default not to be configured, so there would be no need for a `--no-qt`. This script, at least from the point of view of `--help` looks correct in this respect. There is the inconsistency that default enabled options like `--no-debug` have a unnecessary inverse option (`--debug`) while the default disabled options, like `--security`, don't.
