### ISSUE TITLE
Broken links on Intro to OpenDDS page

### ISSUE THREAD

**Issue by neeleym** [objectcomputing/OpenDDS#1034]
The following two links are broken at the bottom of this page:
http://opendds.org/about/articles/Article-Intro.html

Broken:
OMG Data Distribution Service (DDS) for Real-Time Systems (http://www.omg.org/docs/formal/07-05-02)
OMG "Introduction to DDS" Whitepaper (http://www.omg.org/news/whitepapers/Intro_To_DDS.pdf)

**Comment by mitza-oci** [comment]
You can use a pull request to change pages hosted on opendds.org since GitHub Pages is the "content management system"
