### ISSUE TITLE
OpenDDS and Connext Micro (RTI) interoperability. RTPS discovery process problem.

### ISSUE THREAD

**Issue by mafr90** [objectcomputing/OpenDDS#1062]
Hello,

I'm trying to comunicate a Connext Micro node (RTI) with an OpenDDS node. I have some problems in discovery process. DATA(p) meesages are sent by both nodes. OpenDDS node read DATA(p) message from Connext Micro node and send HEARTBEATs messages but Connext Micro node don't get read DATA(p) or HEARTBEATs message. 

RTPS messages are attached by wireshark file.

In those messages you can see:
1. Connext Micro node is launch. INFO_TS and DATA(p) messages are sent.
2. OpenDDs node is launch. First DATA(P) message is capture at 52.255390 s (message number 1051)
3. DATA(p) message from Connext Micro is readed by OpenDDS and Heartbeat is sent at 66.630805 s (message number 1281).
4. HEARBEATs from OpenDDS and DATA(p)s from Connext Micro are sent periodically.

Participants are never discovered. Any idea? 

Thanks in advances and best regards

![1 discovery process](https://user-images.githubusercontent.com/47210751/52935025-826f9480-3358-11e9-912e-2343db404061.PNG)
![2 connext micro data p message](https://user-images.githubusercontent.com/47210751/52935035-88657580-3358-11e9-97b0-fe3334991773.PNG)
![3 opendds data p message](https://user-images.githubusercontent.com/47210751/52935042-8d2a2980-3358-11e9-9202-0cb71a7e88cd.PNG)
![4 opendds heartbeat message](https://user-images.githubusercontent.com/47210751/52935047-90251a00-3358-11e9-8830-f8f73b7deb64.PNG)
![5 opendds heartbeat heartbeat message](https://user-images.githubusercontent.com/47210751/52935049-93b8a100-3358-11e9-881f-fdc85fe08de9.PNG)

**Comment by mitza-oci** [comment]
First, just a hint to make things easier to analyze: add the source and destination ports to the columns in Wireshark's main view.

There are a few things to look into.
- Is there any evidence (from logging or the network messages generated) that the RTI Micro process has discovered OpenDDS?
- When OpenDDS sends a heartbeat that doesn't have the "final flag" set (as in "4") above, the peer is required to respond to it.  Can you see those responses happening?

**Comment by mafr90** [comment]
Hello,

First of all, thaks for your quick response. 

I added source and destination ports' columns in Wireshark's main view. You can check it in the attached image.


![captura](https://user-images.githubusercontent.com/47210751/53239006-20d26180-369b-11e9-9fd5-569ab338cc0c.PNG)

1. RTI Micro node don't print messages about communication status so I can't check if OpenDDS was discovered. I'm trying to contact with the developers of the project but It was not possible yet.

2. How can I see those responses? Are those response RTPS messages that I can capture by using wireshark? All of RTPS messages that I could capture by using Wireshark were attached in my previous post.

Thanks and best regards.

**Comment by mitza-oci** [comment]
Based on the lack of messages being sent to the ports 7402 and 51630, which are listed as metatraffic locators in the participant announcement from OpenDDS, I would have to guess that the peer process has not recognized the announcement from OpenDDS.

**Comment by mafr90** [comment]
Hello,

If I understand you, OpenDDS recognized  the announcement from RTI Micro but RTI Micro didn't.
I checked the OpenDDS and RTI Connext (full functionality) interoperability by using Shapes Demo, but RTI Micro has some restrictions. Do you know If any issue in RTI Micro and OpenDDS interoperatibily exists? What configuration I need to get interoperability between OpenDDS and RTI or any other DDS framework?

Thanks in advance and best regards.

**Comment by jwillemsen** [comment]
Have you tried to enable full logging at the RTI side and see what it logs, maybe there are some error messages that would help.

**Comment by mitza-oci** [comment]
> If I understand you, OpenDDS recognized the announcement from RTI Micro but RTI Micro didn't.

That is correct.  There's nothing to indicate that the peer (non-OpenDDS) process is working in this scenario.

> I checked the OpenDDS and RTI Connext (full functionality) interoperability by using Shapes Demo, but RTI Micro has some restrictions. 

Without knowing anything more, we should consider RTI DDS and RTI Micro to be two distinct products.  they use different "Vendor IDs" in the headers.

> Do you know If any issue in RTI Micro and OpenDDS interoperability exists?

We have not tested that.  Since we don't have the RTI Micro software available, we are not in a position to test it.

> What configuration I need to get interoperability between OpenDDS and RTI or any other DDS framework?

Use the interoperable (RTPS-based) options for both discovery and transport.  
If data types with alignment of 8 bytes are used in your IDL, set the `DCPSRTISerialization` flag (see Table 7-2 in the OpenDDS developers guide).

**Comment by mitza-oci** [comment]
I don't know if there's a bug in OpenDDS, but I also don't see evidence of one.  Unfortunately we'll have to close this without confirmation that OpenDDS can work with RTI Connext Micro.

Users can also encourage the provider of RTI Connext Micro to add their code to https://github.com/omg-dds/dds-rtps which allows anyone to test interoperability.
