### ISSUE TITLE
Documentation for datalink_release_delay setting incorrect

### ISSUE THREAD

**Issue by oth3r1if3** [objectcomputing/OpenDDS#1076]
The OpenDDS_latest.pdf documentation for the datalink_release_delay (Section 7.4.5.1) says the value is "in seconds" while the code treats the value as milliseconds

dds/DCPS/transport/framework/TransportInst.cpp
dds/DCPS/transport/framework/DataLink.cpp

The documentation needs to be updated to say in milliseconds.

**Comment by iguessthislldo** [comment]
The problem might be that comment that says it's using milliseconds is wrong. `datalink_release_delay` is converted to a `int` in `TransportInst.cpp` and looking at `ACE_Time_Value` it should be using `ACE_Time_Value::operator= (time_t tv)` which is using the seconds field, although [`time_t` isn't officially an `int`](https://en.cppreference.com/w/cpp/chrono/c/time_t). Have you seen behavior that might suggest that it's interpreting the number as milliseconds?

**Comment by oth3r1if3** [comment]
TransportInst has a default of 10000 for the value. The DataLink.cpp file
shows assignment to ACE_Time_Value by division of 1000 for seconds and mod
1000 * 1000 for nanoseconds.

**Comment by iguessthislldo** [comment]
Okay, yea you're right, that looks like it's wrong. I didn't see that there were two `datalink_release_delay_`s, one that's a `long` from config and the `ACE_Time_Value` that's being used in `DataLink`. For convenience of anyone else looking at this, [this is what they are talking about ](https://github.com/objectcomputing/OpenDDS/blob/fd72488d7c9bb7048845b64580c96e7906c6d70b/dds/DCPS/transport/framework/DataLink.cpp#L56). It looks like it's been like that for a [very long time](https://github.com/objectcomputing/OpenDDS/commit/9272a96d5d05d152bd8367d304e597744d82380b#diff-53c638747e15d883eeb3cd8b6584e843R36). I can correct it in the developer's guide, but I don't think it will appear in the public until we make a new release.

**Comment by mitza-oci** [comment]
We can post a revised Dev Guide at any time
