### ISSUE TITLE
How to use the test case of OpenDDS Modeling SDK ?

### ISSUE THREAD

**Issue by dreamtale90** [objectcomputing/OpenDDS#1078]
Hello, everyone !
I‘m learning how to use OpenDDS Modeling SDK tool recently. I configure OpenDDS with "configure --no-tests" command and compile it with VS2013. Then install Eclipse 4.4 and OpenDDS plugin. I can create an opendds project in Eclipse and generate all files, then compile these. So far everything is OK. 

I found an example of $DDS_ROOT/tools/modeling/testdata directory. So I create an empty project in Eclipse, then select "Import" ->"General"->"File System", click "Browse" and select $DDS_ROOT/tools/modeling/testdata directory, click "Select All"->"Finish". I add a "OpenDDS SDK Code Generator" and select "MainDiagramTest.opendds_diagram" model file.  An error occurred when I clicked the "Generate All" button. Plugin prompts "model name not present in model". So I want to know how to use it?  If have any other information need, please let me know.

**Comment by dreamtale90** [comment]
I also found that null was the place where the model name should be on the default.codegen page. For example, the "Generate IDL" button should be followed by "ModelName.idl", but it's "null.idl", and "null_T.h", "null_T.cpp", "nullTraits.h", "nullTraits.cpp", "null.mpc", "null.mpb", "null_paths.mpb".
How to solve this problem? Please help me, thanks.

**Comment by mitza-oci** [comment]
> I found an example of $DDS_ROOT/tools/modeling/testdata directory. So I create an empty project in Eclipse, then select "Import" ->"General"->"File System", click "Browse" and select $DDS_ROOT/tools/modeling/testdata directory, click "Select All"->"Finish". I add a "OpenDDS SDK Code Generator" and select "MainDiagramTest.opendds_diagram" model file. An error occurred when I clicked the "Generate All" button. Plugin prompts "model name not present in model". So I want to know how to use it? If have any other information need, please let me know.

I think the problem is that you have MainDiagramTest.opendds_diagram instead of MainDiagramTest.opendds.  The file ending in _diagram is just the visual layout information, it's not used for code generation from the model.

If that doesn't help, can you try a similar procedure using tools\modeling\tests\Messenger\Messenger.opendds (and Messenger.codegen, or create your own *.codegen)?

**Comment by dreamtale90** [comment]
@mitza-oci Thank you very much. It's really like what you said. However, I encountered another compilation problem, as shown in the following figure: 
![build_roblem](https://user-images.githubusercontent.com/15827447/55696344-1243cd80-59ef-11e9-90a7-c45b5c861aa9.PNG)
If I change it to like this `child_inst->local_address("127.0.0.1");` on line 30，there will be a link error.  So now I've commented out this sentence.

**Comment by mitza-oci** [comment]
There is a test for this in tools/modeling/tests/Messenger.  The generated code in model/MessengerTraits.cpp contains:
```
child_inst->local_address("127.0.0.1");
```
Is your *.codegen file significantly different from this one?

**Comment by jhenchen** [comment]
Same error too. The *.codegen did't change.

**Comment by mitza-oci** [comment]
@jhenchen I don't see how your response follows from the question that I posed to other user.

If you are having problems generating code using the Modeling SDK my suggestion would be to start with the included tests such as `tools/modeling/tests/Messenger`.  If those don't work in your installation please let us know.

**Comment by jhenchen** [comment]
I use the Modeling SDK with the  "tools/modeling/tests/Messenger" to generate code.And I use the mwc.pl with -gnuace to generate make file.After I run make, I meet the error.

![error](https://user-images.githubusercontent.com/18344904/56936498-41e78080-6b2a-11e9-91b6-f08a7f0a8619.png)

**Comment by mitza-oci** [comment]
Did you build the Modeling SDK from source or install it from the Eclipse update site?  It's possible that the Eclipse update site is out of date.

**Comment by jhenchen** [comment]
I install it from update site and I install  the *.zib file offline. I will build from source. Thanks!

**Comment by mitza-oci** [comment]
We can update the Eclipse site.  It should be synced up with OpenDDS releases, but we must have missed this change.

**Comment by mitza-oci** [comment]
The update site for OpenDDS's Modeling SDK plugins has been updated.
