### ISSUE TITLE
No working on ubuntu 18.04

### ISSUE THREAD

**Issue by leochan2009** [objectcomputing/OpenDDS#1088]
Hi,
I just build the library using the master branch. (need to configure the project to the latest MPC) the build was successful, but i can not run the examples. here is the steps i did:

1. run the application in $ddsroot/bin using the command  "./DCPSInfoRepo -o simple.ior", the app is running fine.
2. run the example program publisher at $ddsroot/DevGuideExamples/DCPS/Messenger, "./publisher -DCPSInfoRepo file://simple.ior" it failed. Here is the error output:

> (23933|140495632934720) ERROR: InfoRepoDiscovery::get_dcps_info: unable to narrow DCPSInfo (file://simple.ior) for key DEFAULT_REPO.
(23933|140495632934720) ERROR: DomainParticipantImpl::enable, add_domain_participant returned invalid id.
(23933|140495632934720) ERROR: DomainParticipantFactoryImpl::create_participant, unable to enable DomainParticipant.
ERROR: Publisher.cpp:41: main() - create_participant failed!
ERROR: InfoRepoDiscovery::~InfoRepoDiscovery - Exception caught during ORB shutdown: system exception, ID 'IDL:omg.org/CORBA/BAD_INV_ORDER:1.0'
OMG minor code (4), described as 'ORB has shutdown.', completed = NO

My compiler version for c/c++ are both:
(Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

Hope you could help me to solve the issue, Thanks!

Best,
leochan

**Comment by mitza-oci** [comment]
The file simple.ior was written in one directory and being looked for in a completely different directory.
