### ISSUE TITLE
system exception, ID 'IDL:omg.org/CORBA/TRANSIENT:1.0'

### ISSUE THREAD

**Issue by tiedun001** [objectcomputing/OpenDDS#1103]
subscriber -DCPSDebugLevel=5 -DCPSInfoRepo HostB:12345 -DCPSConfigFile rtps_uni.ini
(3227|140250644592448) NOTICE: using DCPSDebugLevel value from command option (overrides value if it's in config file).
(3227|140250644592448) NOTICE: using DCPSInfoRepo value from command option (overrides value if it's in config file).
(3227|140250644592448) EXCEPTION, ERROR: InfoRepoDiscovery::get_dcps_info: failed to resolve ior - 
system exception, ID 'IDL:omg.org/CORBA/TRANSIENT:1.0'
OMG minor code (2), described as 'No usable profile in IOR.', completed = NO

(3227|140250644592448) ERROR: DomainParticipantImpl::enable, add_domain_participant returned invalid id.
(3227|140250644592448) ERROR: DomainParticipantFactoryImpl::create_participant, unable to enable DomainParticipant.
ERROR: /home/lc/OpenDDS/OpenDDS-3.13.2/DevGuideExamples/DCPS/Messenger/Subscriber.cpp:41: main() - create_participant failed!
Segmentation fault (core dumped)

**i want to solve the problem help thanks**

**Comment by mitza-oci** [comment]
Is there a DCPSInfoRepo server listening on TCP port 12345 of HostB?  Is HostB reachable from this one?

**Comment by anuran-Chakraborty** [comment]
I got this same error when running subscriber and publisher on Android. Android cannot connect to the dcpsinforepo though it is reachable from adnroid. Please help me with this issue ASAP.

**Comment by mitza-oci** [comment]
@tiedun001 since this issue has gone quiet, we'll close it now
@anuran-Chakraborty I don't know of anything different on Android, or anything platform-specific, with this issue.  It's just opening a TCP socket to connect to that server.
