### ISSUE TITLE
Examples not working in Windows version

### ISSUE THREAD

**Issue by game2sim** [objectcomputing/OpenDDS#1104]
The IntroductionToOpen example runs fine on Ubuntu but not in Windows.
I'm getting errors messages from the DCPInfoRepo process.
The message is:
"(16120:34752) TCPTransport::connect_datalink error address family not supported."

I'm using OpenDDS version 3.13.2
Visual Studio 2015
Windows 10 & Window 7

I've also tried turning off the Firewall but that didn't help. It runs on that same machine with Ubuntu running on VirtualBox with the Firewall turned on.  I've also tried OpenDDS version 3.12.2 with the same result.

I'm new to OpenDDS so any help would be appreciated.

**Comment by mitza-oci** [comment]
In your Windows build try running (with environment set as usual):
```
cd DevGuideExamples\DCPS\Messenger
run_test.pl
```

**Comment by game2sim** [comment]
That example also has the same issue.  I've made sure the environment variables are set.
From the DCPSInfoRepo.log:

TAO (20068|20024) - Invocation_Adapter::invoke_i, making a TAO_CS_THRU_POA_STRATEGY invocation
(20068|20024) TcpTransport::connect_datalink error address family not supported.
TAO (20068|20024) - Invocation_Adapter::invoke_i, making a TAO_CS_REMOTE_STRATEGY invocation

If you want I can attach the log files.

**Comment by mitza-oci** [comment]
Please paste in the output of `ipconfig`.
In `subscriber.log` you should see some lines like the following, though I don't know how far yours is getting.
```
(26392|2568) TcpTransport::configure_i listening on 0.0.0.0:62073
(26392|2568) ip interface 192.168.56.1:0 maps to hostname FOO
(26392|2568) ip interface 127.0.0.1:0 maps to hostname FOO
(26392|2568) found fqdn FOO.bar.com from 10.2.3.4:0
(26392|2568) TransportImpl::open()
   transport_type:               tcp
   name:                         _OPENDDS__BITTCPTransportInst_DEFAULT_REPO
   queue_messages_per_pool:      10
   queue_initial_pools:          5
   max_packet_size:              2147481599
   max_samples_per_packet:       10
   optimum_packet_size:          4096
   thread_per_connection:        false
   datalink_release_delay:       0
   datalink_control_chunks:      32

   local_address:                FOO.bar.com:62073
   pub_address:
   enable_nagle_algorithm:       false
   conn_retry_initial_delay:     500
   conn_retry_backoff_multiplier:2
   conn_retry_attempts:          3
   passive_reconnect_duration:   2000
   max_output_pause_period:      -1
(26392|2568) TcpTransport public address str FOO.bar.com:62073
```

**Comment by game2sim** [comment]
From ipconfig:

Windows IP Configuration


Ethernet adapter Local Area Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::e993:977:31e4:5a92%14
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 

Wireless LAN adapter Local Area Connection* 4:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Wireless LAN adapter Local Area Connection* 5:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Wireless LAN adapter Wireless Network Connection 2:

   Connection-specific DNS Suffix  . : lan
   Link-local IPv6 Address . . . . . : fe80::45be:6610:8bb1:2ed2%12
   IPv4 Address. . . . . . . . . . . : 192.168.84.20
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.84.1

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

---------------------------------------------------------------------------------------------
From the subscriber.log file:

(22796|23328) TcpTransport::configure_i listening on 0.0.0.0:51148
(22796|23328) found fqdn HomeWork-PC.lan from 192.168.86.118:0
(22796|23328) TransportImpl::configure()
   transport_type:               tcp
   name:                         _OPENDDS__BITTCPTransportInst_DEFAULT_REPO
   queue_messages_per_pool:      10
   queue_initial_pools:          5
   max_packet_size:              2147481599
   max_samples_per_packet:       10
   optimum_packet_size:          4096
   thread_per_connection:        false
   datalink_release_delay:       0
   datalink_control_chunks:      32

   local_address:                HomeWork-PC.lan:51148
   pub_address:                  
   enable_nagle_algorithm:       false
   conn_retry_initial_delay:     500
   conn_retry_backoff_multiplier:2
   conn_retry_attempts:          3
   passive_reconnect_duration:   2000
   max_output_pause_period:      -1
(22796|23328) TcpTransport public address str HomeWork-PC.lan:51148

**Comment by mitza-oci** [comment]
These two IP addresses differ.  Based on your network configuration, do you know why that's the case?
```
IPv4 Address. . . . . . . . . . . : 192.168.84.20
(22796|23328) found fqdn HomeWork-PC.lan from 192.168.86.118:0
```

**Comment by game2sim** [comment]
I forget the log is accumulative so cleaned the logs and re-ran the example.
My ipconfig ouput is:

Windows IP Configuration


Ethernet adapter Local Area Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . : 
   Link-local IPv6 Address . . . . . : fe80::e993:977:31e4:5a92%14
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 

Wireless LAN adapter Local Area Connection* 4:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Wireless LAN adapter Local Area Connection* 5:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

Wireless LAN adapter Wireless Network Connection 2:

   Connection-specific DNS Suffix  . : lan
   Link-local IPv6 Address . . . . . : fe80::45be:6610:8bb1:2ed2%12
   IPv4 Address. . . . . . . . . . . : 192.168.86.124
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.86.1

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

==========================================================
And from the subscriber.log:

16424|14152) TcpTransport::configure_i listening on 0.0.0.0:52887
(16424|14152) found fqdn HomeWork-PC.lan from 192.168.86.124:0
(16424|14152) TransportImpl::open()
   transport_type:               tcp
   name:                         _OPENDDS__BITTCPTransportInst_DEFAULT_REPO
   queue_messages_per_pool:      10
   queue_initial_pools:          5
   max_packet_size:              2147481599
   max_samples_per_packet:       10
   optimum_packet_size:          4096
   thread_per_connection:        false
   datalink_release_delay:       0
   datalink_control_chunks:      32

   local_address:                HomeWork-PC.lan:52887
   pub_address:                  
   enable_nagle_algorithm:       false
   conn_retry_initial_delay:     500
   conn_retry_backoff_multiplier:2
   conn_retry_attempts:          3
   passive_reconnect_duration:   2000
   max_output_pause_period:      -1
(16424|14152) TcpTransport public address str HomeWork-PC.lan:52887

**Comment by mitza-oci** [comment]
The DNS name is `HomeWork-PC.lan`.  If you run `ping HomeWork-PC.lan` does it resolve the correct IP address?

**Comment by game2sim** [comment]
No the DNS does not resolve HomeWork-PC.lan if I try to ping it.

**Comment by mitza-oci** [comment]
My suggestion then is to get DNS hostname resolution working properly.  If that's not feasible, see the DCPSDefaultAddress option in the Developer's Guide Table 7-2.  That option can work with a hostname or a dotted-decimal IP address.
