### ISSUE TITLE
Update gtest dependency?

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#1107]
Looks there is a gtest 1.8.1 release (see https://github.com/google/googletest/releases/tag/release-1.8.1), maybe the gtest dependency can be upgraded?

Triggered by the fact that gtest 1.8.0 doesn't compile warning free with gcc9 (default in fc30)

**Comment by mitza-oci** [comment]
Sure, we can give it a try and make sure it still works on the other platforms.  Please create a PR that updates the submodule.
