### ISSUE TITLE
OpenSplice and OpenDDS interoperability problem

### ISSUE THREAD

**Issue by LaurentB38** [objectcomputing/OpenDDS#1117]
Hi,

I am working with OpenSplice for a long time, and now, I am testing the interoperability between OpenSplice and OpenDDS.
However, I do not success.

I downloaded the **OpenDDS mater, latest version 3.13**, then I built it on my CentOS 7.
I built and run the Messenger tests without problems.
My **OpenSplice version is 6.10.2.**

I have developed a very small OpenDDS application which reads (through a reader and a listener) in loop a very simple topic (I took such as example the tests/DCPS/Messenger/, and I adapted it) with a QOS volatile/best effort.
On the other side, I developed a similar OpenSplice application which writes in loop the same topic. 

OpenDDS application is configured in RTPS.
OpenSplice application is configured in single process DDSI2.

Through two different shells, I run the 2 applications and it seems to work. The OpenDDS reader sees and receives the topics. However, I think it uses the local interface and not the Ethernet interface.

Now, when I run an application on another PC (still CentOS 7), which is connected to mine by Ethernet, it does NOT work: the 2 applications does not communicate.
For example, ip addresses are:  PC1 (OpenDDS application) is 192.168.5 and PC2 is 192.168.1.15 (OpenSplice application), directly connected by Ethernet.

After having read the issue #665 , I changed the RTPS protocol version to 2.1 as the OpenSplice's one. It does NOT solve anything.

I use very "standard" configuration on both sides (to avoid complications).
See the following files for each vendor.

**OpenDDS configuration**

>  [common]
DCPSDefaultAddress=192.168.1.5
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSGlobalTransportConfig=myconfig
> 
> [domain/0]
DiscoveryConfig=uni_rtps
> 
> [config/myconfig]
transports=the_rtps_transport
> 
> [rtps_discovery/uni_rtps]
SedpMulticast=1
SedpLocalAddress=192.168.1.5:
ResendPeriod=2
> 
> [transport/the_rtps_transport]
multicast_interface=eth4
transport_type=rtps_udp
use_multicast=1
local_address=192.168.1.5:

**OpenSplice configuration**

> <OpenSplice>
    <Domain>
        <Name>ospl_sp_ddsi</Name>
        <Id>0</Id>
        <SingleProcess>true</SingleProcess>
        <Description>Stand-alone 'single-process' deployment and standard DDSI networking.</Description>
        <Service name="ddsi2">
            <Command>ddsi2</Command>
        </Service>
        <Service name="durability">
            <Command>durability</Command>
        </Service>
        <Service name="cmsoap">
            <Command>cmsoap</Command>
        </Service>
    </Domain>
    <DDSI2Service name="ddsi2">
        <General>
            <NetworkInterfaceAddress>192.168.1.15</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <EnableMulticastLoopback>true</EnableMulticastLoopback>
            <CoexistWithNativeNetworking>false</CoexistWithNativeNetworking>
        </General>
        <Compatibility>
            
            <StandardsConformance>lax</StandardsConformance>
            
            
        </Compatibility>
        <Tracing>
            <AppendToFile>true</AppendToFile>
            <EnableCategory>trace</EnableCategory>
            <OutputFile>ddsi2.log</OutputFile>
            <Verbosity>finest</Verbosity>
        </Tracing>
    </DDSI2Service>
    <DurabilityService name="durability">
        <Network>
            <Alignment>
                <TimeAlignment>false</TimeAlignment>
                <RequestCombinePeriod>
                    <Initial>2.5</Initial>
                    <Operational>0.1</Operational>
                </RequestCombinePeriod>
            </Alignment>
            <WaitForAttachment maxWaitCount="100">
                <ServiceName>ddsi2</ServiceName>
            </WaitForAttachment>
        </Network>
        <NameSpaces>
            <NameSpace name="defaultNamespace">
                <Partition>*</Partition>
            </NameSpace>
            <Policy alignee="Initial" aligner="true" durability="Durable" nameSpace="defaultNamespace"/>
        </NameSpaces>
    </DurabilityService>
    <TunerService name="cmsoap">
        <Server>
            <PortNr>Auto</PortNr>
        </Server>
    </TunerService>
</OpenSplice>

Under Wireshark, I can see both frames with both vendor ids (1.3: OpenDDS ; 1.2: OpenSplice).

I did tried many things:
- Test the different RTPS configuration.
- Change QOS (volatile, transient, transient_local, ...).
- Disable Durability service on OpenSplice side.
- The contrary case: OpenDDS publishes and OpenSplice subscribes.
- ...

**Then, the important note is:**
On the OpenDDS computer, when I launch another OpenSplice tool (such as Tuner or home-made application) on the same Domain Id in addition to the OpenDDS application, the communication will be established and then the OpenDDS application will be able to communicate with the initial OpenSplice application.
This means it is a "network" problem or missing configuration.

**What did I miss? 
What am I doing "wrong"?**
If anyone can help me, I would be fully grateful!

Regards,
Laurent

**Comment by mitza-oci** [comment]
> I downloaded the OpenDDS master, latest version 3.13

These are two different versions.  The master branch is a pre-release version that still reports its version number as 3.13.  Once it's ready for release it will get an actual version number.  There is a 3.13 tag if that's what you'd like to use (there are also source archives available for download).  I will assume for now you are using master.

> Under Wireshark, I can see both frames with both vendor ids (1.3: OpenDDS ; 1.2: OpenSplice).

Does this refer to the failed scenario?  If so please attach that capture file and we'll take a look.

Also with DCPSDebugLevel set to 1 (or higher) you can look for the log message
`Spdp::data_received - <guid1> discovered <guid2>`
If it's there and guid2 refers to an OpenSplice GUID then at least SPDP (Simple Participant Discovery Protocol) is working this direction.

**Comment by LaurentB38** [comment]
Hi,

Thank you for your quick answer.
Yes, I am using the OpenDDS master, sorry for misunderstanding.

I finally succeeded to make working the communication OpenDDS / OpenSplice.
It was a networking problem: it missed a route rule for the multicast rule. 
After added it, it now works! I can read topic sent by OpenSplice without problems.

Now, I am testing **DDS Security** (this was the main subject I was intended to test) and still the interoperability.

I have the same applications: both are working **alone with DDS Security enabled and my own certificates**.
However, when I try to make them communicate (same test as before), I did NOT succeed.

**Governance file**
It has all deactivated:
>  <allow_unauthenticated_participants>true</allow_unauthenticated_participants>
            <enable_join_access_control>false</enable_join_access_control>
            <discovery_protection_kind>NONE</discovery_protection_kind>
            <liveliness_protection_kind>NONE</liveliness_protection_kind>
            <rtps_protection_kind>NONE</rtps_protection_kind>
            <topic_access_rules>
                <topic_rule>
                    <topic_expression>*</topic_expression>
                    <enable_liveliness_protection>false</enable_liveliness_protection>
                    <enable_discovery_protection>false</enable_discovery_protection>
                    <enable_read_access_control>false</enable_read_access_control>
                    <enable_write_access_control>false</enable_write_access_control>
                    <metadata_protection_kind>NONE</metadata_protection_kind>
                    <data_protection_kind>NONE</data_protection_kind>
                </topic_rule>
            </topic_access_rules>
        </domain_rule>
    </domain_access_rules>

**Permission file**
It has all allowed:

> <permissions>
          <grant name="Perm_P3">
            <subject_name>/CN=TXL_P3</subject_name>
            <validity>
                <not_before>2015-09-15T01:00:00</not_before>
                <not_after>2115-09-15T01:00:00</not_after>
            </validity>
            <allow_rule>
                <domains>
                  <id>0</id>
                </domains>
                <publish>
                    <topics>
                        <topic>*</topic>
                    </topics>
                    <partitions>
                        <partition>*</partition>
                    </partitions>
                </publish>
                <subscribe>
                    <topics>
                        <topic>*</topic>
                    </topics>
                    <partitions>
                        <partition>*</partition>
                    </partitions>
                </subscribe>
            </allow_rule>
            <default>DENY</default>
        </grant>

**Errors**
But, I suppose the handshake failed.
On the OpenDDS side, starting the application triggers the following errors :

> (300|140350188148480) DEBUG: Spdp::attempt_authentication() - Attempting authentication (sending request) for participant:   fd90e47e.f2592137.03520fd6.000001c1(434bf518)
(300|140350188148480) DEBUG: Spdp::check_auth_states()      - Removing discovered participant due to authentication timeout: fd90e47e.f2592137.03520fd6.000001c1(434bf518)
(300|140350425999104) WARNING: Sedp::generate_remote_matched_reader_crypto_handle() - Unable to lookup remote participant crypto info.
(300|140350425999104) WARNING: Sedp::generate_remote_matched_reader_crypto_handle() - Unable to lookup remote participant crypto info.
(300|140350425999104) WARNING: Sedp::generate_remote_matched_reader_crypto_handle() - Unable to lookup remote participant crypto info.
(300|140350425999104) WARNING: Sedp::generate_remote_matched_reader_crypto_handle() - Unable to lookup remote participant crypto info.
(300|140350425999104) WARNING: Sedp::create_and_send_datareader_crypto_tokens() - Unable to create local datareader crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote writer handle
(300|140350425999104) WARNING: Sedp::create_and_send_datareader_crypto_tokens() - Unable to create local datareader crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote writer handle
(300|140350425999104) WARNING: Sedp::create_and_send_datareader_crypto_tokens() - Unable to create local datareader crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote writer handle
(300|140350425999104) WARNING: Sedp::create_and_send_datareader_crypto_tokens() - Unable to create local datareader crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote writer handle
(300|140350425999104) WARNING: Sedp::create_and_send_datawriter_crypto_tokens() - Unable to create local datawriter crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote reader handle
(300|140350425999104) WARNING: Sedp::create_and_send_datawriter_crypto_tokens() - Unable to create local datawriter crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote reader handle
(300|140350425999104) WARNING: Sedp::create_and_send_datawriter_crypto_tokens() - Unable to create local datawriter crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote reader handle
(300|140350425999104) WARNING: Sedp::create_and_send_datawriter_crypto_tokens() - Unable to create local datawriter crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote reader handle

On the OpenSplice side, I got errors about handshake failed.
=> Any ideas why it fails to authenticate?

Thanks again.
Laurent

**Comment by mitza-oci** [comment]
> Yes, I am using the OpenDDS master, sorry for misunderstanding.

No problem, we will look into making this more clear.

> I finally succeeded to make working the communication OpenDDS / OpenSplice.
> It was a networking problem: it missed a route rule for the multicast group (239.255.0.1), so it was routing on the incorrect network interface.
> After added it, **it now works!** I can read topic sent by OpenSplice without problems.

Great, thanks for letting us know.

> Now, I am testing **DDS Security** (this was the main subject I was intended to test) and still the interoperability.

Please create a new GitHub Issue for this.  If it results in a code change in OpenDDS we'd like to have clean traceability back to the issue.

It appears that the Security features in splice are new and are not available in their open source version.  There is also no test code for splice in https://github.com/omg-dds/dds-security.  We haven't done testing with it so I don't know what will work.
