### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no messenger_idl_test in java.library.path

### ISSUE THREAD

**Issue by tiedun001** [objectcomputing/OpenDDS#1120]
```
java -Xcheck:jni -ea -cp classes:/home/pi/OpenDDS/OpenDDS-3.13.2/build/target/lib/i2jrt.jar:/home/pi/OpenDDS/OpenDDS-3.13.2/build/target/lib/OpenDDS_DCPS.jar:/home/pi/OpenDDS/OpenDDS-3.13.2/build/target/lib/i2jrt_compact.jar:/home/pi/OpenDDS/OpenDDS-3.13.2/build/target/java/tests/messenger/messenger_idl/messenger_idl_test.jar:subscriber/classes TestSubscriber -DCPSInfoRepo 192.168.1.158:12345 -DCPSConfigFile rtps_uni.ini
Exception in thread "main" java.lang.UnsatisfiedLinkError: no messenger_idl_test in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at Messenger._MessageTypeSupportTAOPeer.<clinit>(_MessageTypeSupportTAOPeer.java:30)
        at TestSubscriber.main(TestSubscriber.java:41)
```
please help me the path in the exex commond

**Comment by iguessthislldo** [comment]
The Java messenger IDL library is asking the JVM to load the native C++ IDL library but the JVM can't find it in the native library path. Try running `source /home/pi/OpenDDS/OpenDDS-3.13.2/build/target/setenv.sh` before running TestSubscriber.

**Comment by tiedun001** [comment]
i solve the problem by myself.thank you for all

**Comment by yuan-ge** [comment]
> i solve the problem by myself.thank you for all

How did you solve it? I get the same problem.

**Comment by jrw972** [comment]
> > i solve the problem by myself.thank you for all
> 
> How did you solve it? I get the same problem.

Probably need to set environment variables.  See previous comment with `source /home/pi/OpenDDS/OpenDDS-3.13.2/build/target/setenv.sh`.
