### ISSUE TITLE
DDS Security interoperability problem

### ISSUE THREAD

**Issue by LaurentB38** [objectcomputing/OpenDDS#1122]
Hi,

I am testing DDS Security and especially the interoperability with OpenSplice (which I am working with for a long time).

**OpenDDS version is master.**
**OpenSplice version is 6.10.2.**

I have developed a very small OpenDDS application which reads (through a reader and a listener) in loop a very simple topic (I took such as example the tests/DCPS/Messenger/, and I adapted it) with a QOS volatile/best effort.
On the other side, I developed a similar OpenSplice application which writes in loop the same topic.

**With DDS Security enabled, both applications work alone and my own certificates.**
However, when I try to make them communicate with DDS Security enabled.

OpenSplice application is participant 1.
OpenDDS application is participant 2.
Both of them have configuration files such as identity_ca, own identity and private key, governance, permission_ca and own permission.

In governance file, all protections is deactivated:
> allow_unauthenticated_participants true
enable_join_access_control false
discovery_protection_kind NONE
liveliness_protection_kind NONE
rtps_protection_kind NONE
topic_access_rules
		topic_rule
				topic_expression *
				enable_liveliness_protection false
				enable_discovery_protection false
				enable_read_access_control false
				enable_write_access_control false
				metadata_protection_kind NONE
				data_protection_kind NONE
		topic_rule
topic_access_rules

In each permissions file, all topics accesses are allowed.

My OpenDDS configuration file, named `rtps_lbo_sec.ini`:
> [common]
DCPSDefaultAddress=192.168.1.5
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSGlobalTransportConfig=myconfig
DCPSSecurity=1
[domain/0]
DiscoveryConfig=uni_rtps
[config/myconfig]
transports=the_rtps_transport
[rtps_discovery/uni_rtps]
SedpMulticast=1
SedpLocalAddress=192.168.1.5:
ResendPeriod=2
[transport/the_rtps_transport]
transport_type=rtps_udp
use_multicast=1
local_address=192.168.1.5:

**The problem is that the handshake failed between participants.**
First, I start OpenSplice's application.
Second, I start OpenDDS's application: 
`./opendds_appli -DCPSConfigFile ./rtps_conf/rtps_lbo_sec.ini` 
(no matter the order of starting applications).

OpenDDS generates the following errors:
> (300|140350188148480) DEBUG: Spdp::attempt_authentication() - Attempting authentication (sending request) for participant:   fd90e47e.f2592137.03520fd6.000001c1(434bf518)
(300|140350188148480) DEBUG: Spdp::check_auth_states()      - Removing discovered participant due to authentication timeout: fd90e47e.f2592137.03520fd6.000001c1(434bf518)
(300|140350425999104) WARNING: Sedp::generate_remote_matched_reader_crypto_handle() - Unable to lookup remote participant crypto info.
(300|140350425999104) WARNING: Sedp::create_and_send_datareader_crypto_tokens() - Unable to create local datareader crypto tokens with crypto key exchange plugin. Security Exception[-1.0]: Invalid remote writer handle

OpenSplice generates the following error:
> handshake failed: time Time out

**=> Any ideas why does it fail to handshake and authenticate?**

Reading the latest commit on OpenDDS, I found Security Fixes #1091.
I found 2 new options: -DCPSSecurityDebugLevel and -DCPSSecurityDebug.

Then, wanting more information about my problem, I tried:
`./opendds_appli -DCPSSecurityDebug -DCPSSecurityDebugLevel 1 -DCPSConfigFile ./rtps_conf/rtps_lbo_sec.ini` 

**=> No error! I can read the corresponding topic. Is it a bug or did I misunderstand something?**

Thanks for helping me.
Laurent.

**Comment by mitza-oci** [comment]
Please attach a wireshark capture of the failed authentication and we'll take a look.

**Comment by iguessthislldo** [comment]
`-DCPSSecurityDebug` and ` -DCPSSecurityDebugLevel` are two ways to set the same thing. Running it with `-DCPSSecurityDebugLevel 4` is a good level to try, but the logging the option controls is geared towards key exchange and encryption/decryption. As for why the handshake is failing, I'm not sure. I can see OpenDDS has determined that it's the authentication leader because it's sending the request. Somehow OpenSplice isn't getting that though and both timeout. If I'm reading this right, you didn't have an error when you ran `./opendds_appli -DCPSSecurityDebug -DCPSSecurityDebugLevel 1 -DCPSConfigFile ./rtps_conf/rtps_lbo_sec.ini`?

**Comment by LaurentB38** [comment]
@mitza-oci 
>  Please attach a wireshark capture of the failed authentication and we'll take a look.

Ok, thank you.

@iguessthislldo 
>  If I'm reading this right, you didn't have an error when you ran ./opendds_appli -DCPSSecurityDebug -DCPSSecurityDebugLevel 1 -DCPSConfigFile ./rtps_conf/rtps_lbo_sec.ini?

Yes, this is what I said: launching my application with theses options does NOT trigger errors.

Find, my attached captures:
[capture_ddssecurity_interop.zip](https://github.com/objectcomputing/OpenDDS/files/3165166/capture_ddssecurity_interop.zip)

- **Case of error**
Running `./opendds_appli -DCPSConfigFile ./rtps_conf/rtps_lbo_sec.ini`
Wireshark capture is: `capture_ddssecurity_auth_fail.pcapng`

- **Case of NO error**
Running `./opendds_appli -DCPSSecurityDebug -DCPSSecurityDebugLevel 1 -DCPSConfigFile ./rtps_conf/rtps_lbo_sec.ini`
Wireshark capture is: `capture_ddssecurity_auth_seemsok.pcapng`


Thanks!
Laurent.

**Comment by LaurentB38** [comment]
Hi,

I worked again on the story of options `-DCPSSecurityDebug -DCPSSecurityDebugLevel 1`.
**=> This is not a bug or something else, this is my own mistake.**
Launching the application will disable the DDS Security (this overwrites the `DCPSSecurity=1`), and it is possible to read topic from the OpenSplice application because I have allowed it in governance file, by setting `allow_unauthenticated_participants true`.

Consequently, do not take matter of the "Case of NO error" with the options adding, it has no sense.

**Comment by forevermirin94** [comment]
@LaurentB38 
Hey Laurent, this is off topic but could you have a look at my topic? #1125 
I'm having the same issue with the interoperability between OpenDDS and OpenSplice. It seems you found a way to solve the issue. Thanks!

**Comment by mitza-oci** [comment]
The auth handshake reply generated by splice is not compliant.  The spec requires the `related_message_identity` field to be set to correspond to the message its responding to.  In this case the `related_message_identity` was all zeros.  See DDS Security 1.1 section 8.3.2.11.5.
