### ISSUE TITLE
OpenDDS sometimes work and sometimes not

### ISSUE THREAD

**Issue by AyalaIsakov** [objectcomputing/OpenDDS#1124]
Hi :) 
I have a problem that sometimes the openDDS works (it sends and receives messages). But sometimes it doesn't. I'll give an example.
I have 2 computers, they are in the same domain. I run the application on the first computer, i see that the message has been send, and i can see on the other computer that the massage has arrived. I close the application, and i try to run again the SAME application and it doesn't work.
I thought that the problem can be the firewall..So i tried to connect the two computers peer2peer.. (Of course i changed the rtsp.ini for the peer2peer) and again sometimes it works and sometimes not.. There is NO difference between one run of the application to the another run...
Do you guys have a idea what is happening? 

Thank you very much,
Ayala.

**Comment by c4m3lc4s3** [comment]
I've seen a similar problem. For me it happened when I had my publisher running for a longer time (with some load), and I started and stopped my subscribers several times. After a while the subscribers did not receive anything until I restarted the publisher. This happened from time to time, i.e. more than once or twice.

**Comment by jmccabe** [comment]
I have similar issues.

I have 3 builds of DDS, one for MS Windows (Debug build using VS2017), one on Ubuntu and one running on a Digilent CoraZ7-10 Zynq-7000 ARM processor with Petalinux. The Ubuntu install is a VM running on VirtualBox on MS-Windows (let's call the UB1). Another Ubuntu VM has the Cora's USB port captured, so is being used as the TTY to run the publisher/subscriber commands. The Cora's connected to the same ethernet switch as the MS-Windows box.

Using the Messenger example, if I run the subscriber on the Cora, and the publisher on UB1, or vice versa, it works every time. However if I use the Cora as one end, and the MS-Windows build as the other end, it works occasionally, but not very often; most of the time I get the "main() - wait failed!" message on each end, but there have been times when it looks like it's started working then failed. Sometimes, when it does work, it takes a very long time to communicate.

I haven't yet seen subscriber on MS-Windows and publisher on UB1 working (actually, that's not true now; it worked once while I was writing this!)

I thought it may be firewall related (even though Windows popped up the firewall access thing when I first ran publisher/subscriber), so I've switched off the firewall.

The rtps.ini file contents are something like this:

```
[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=TheRTPSConfig

[rtps_discovery/TheRTPSConfig]
SedpLocalAddress=<ip-address-of-the-machine-as-acquired-through-DHCP>

[transport/the_rtps_transport]
transport_type=rtps_udp

```

I'm not sure what else to look at or whether there are any other configuration options that might help. It's never worked without the SedpLocalAddress setting in the Windows version.

**Comment by AyalaIsakov** [comment]
> I've seen a similar problem. For me it happened when I had my publisher running for a longer time (with some load), and I started and stopped my subscribers several times. After a while the subscribers did not receive anything until I restarted the publisher. This happened from time to time, i.e. more than once or twice.

Thank you very much. There is a specific way to restart the publisher and subscriber? Or you meant you restarted your application?

**Comment by AyalaIsakov** [comment]
> I have similar issues.
> 
> I have 3 builds of DDS, one for MS Windows (Debug build using VS2017), one on Ubuntu and one running on a Digilent CoraZ7-10 Zynq-7000 ARM processor with Petalinux. The Ubuntu install is a VM running on VirtualBox on MS-Windows (let's call the UB1). Another Ubuntu VM has the Cora's USB port captured, so is being used as the TTY to run the publisher/subscriber commands. The Cora's connected to the same ethernet switch as the MS-Windows box.
> 
> Using the Messenger example, if I run the subscriber on the Cora, and the publisher on UB1, or vice versa, it works every time. However if I use the Cora as one end, and the MS-Windows build as the other end, it works occasionally, but not very often; most of the time I get the "main() - wait failed!" message on each end, but there have been times when it looks like it's started working then failed. Sometimes, when it does work, it takes a very long time to communicate.
> 
> I haven't yet seen subscriber on MS-Windows and publisher on UB1 working (actually, that's not true now; it worked once while I was writing this!)
> 
> I thought it may be firewall related (even though Windows popped up the firewall access thing when I first ran publisher/subscriber), so I've switched off the firewall.
> 
> The rtps.ini file contents are something like this:
> 
> ```
> [common]
> DCPSGlobalTransportConfig=$file
> DCPSDefaultDiscovery=TheRTPSConfig
> 
> [rtps_discovery/TheRTPSConfig]
> SedpLocalAddress=<ip-address-of-the-machine-as-acquired-through-DHCP>
> 
> [transport/the_rtps_transport]
> transport_type=rtps_udp
> ```
> 
> I'm not sure what else to look at or whether there are any other configuration options that might help. It's never worked without the SedpLocalAddress setting in the Windows version, but that does have the virtualbox network adapter so I can kinda understand that.

Thank you very much!

**Comment by c4m3lc4s3** [comment]
Yes, I restarted the whole publisher application.

**Comment by AyalaIsakov** [comment]
> Yes, I restarted the whole publisher application.

Thank you!

**Comment by AyalaIsakov** [comment]
It still doesn't work if anyone has some more ideas i will be happy to try :)

**Comment by simpsont-oci** [comment]
What durability qos policy are you using? If you're not using durability (I'm guessing no), you may need to be careful about when your datawriter writes its data. Any data written before the datareader and datawriter are associated by the transport will be dropped. One common way of determining if they're associated already is to check the status given by the datawriter listener's on_publication_matched().

**Comment by mitza-oci** [comment]
@AyalaIsakov We can try to help you if you provide enough detail like log files or packet captures.  Since there has been no response on this issue, we'll close it.
@c4m3lc4s3 @jmccabe thank you for providing additional context here.  If you have documented cases where OpenDDS appears to be not functioning correctly, please open issues for those cases.
