### ISSUE TITLE
OpenDDS and OpenSplice interoperability 

### ISSUE THREAD

**Issue by forevermirin94** [objectcomputing/OpenDDS#1125]
Hi,

I'm running an OpenDDS publisher on my Windows 10 PC and Opensplice on a Raspberry Pi. Both are connected to the same network using ethernet.
OpenDDS version: 3.13.1
OpenSplice version: HDE Release 6.10.0p2 For armv7l.linux.
For some reason the data sent from the publisher won't arrive at the Raspberry Pi. 
I checked #665 and I changed the RTPS version for OpenDDS from 2.3 to 2.1.
Both OpenDDS and OpenSplice are running RTPS 2.1 and confirmed in the Wireshark capture.

My RTPS config file looks like this:

> [common]
>DCPSDefaultAddress=137.17.136.212
>DCPSGlobalTransportConfig=$file
>DCPSDefaultDiscovery=DEFAULT_RTPS
>[transport/the_rtps_transport]
>transport_type=rtps_udp

The ospl_shmem_ddsi.xml looks as follows:
`<OpenSplice>
   <Domain>
      <Name>ospl_shmem_ddsi</Name>
      <Id>0</Id>
      <Description>Federated deployment using shared-memory and standard DDSI networking.</Description>
      <Database>
         <Size>10485760</Size>
      </Database>
      <Service name="ddsi2">
         <Command>ddsi2</Command>
      </Service>
      <Service name="durability">
         <Command>durability</Command>
      </Service>
      <Service name="cmsoap">
         <Command>cmsoap</Command>
      </Service>
   </Domain>
   <DDSI2Service name="ddsi2">
      <General>
         <NetworkInterfaceAddress>AUTO</NetworkInterfaceAddress>
         <AllowMulticast>true</AllowMulticast>
         <EnableMulticastLoopback>true</EnableMulticastLoopback>
         <CoexistWithNativeNetworking>false</CoexistWithNativeNetworking>
      </General>
      <Compatibility>
         
         <StandardsConformance>lax</StandardsConformance>
         
         
      </Compatibility>
   </DDSI2Service>
   <DurabilityService name="durability">
      <ClientDurability enabled="true" />
      <Network>
         <Alignment>
            <TimeAlignment>false</TimeAlignment>
            <RequestCombinePeriod>
               <Initial>2.5</Initial>
               <Operational>0.1</Operational>
            </RequestCombinePeriod>
         </Alignment>
         <WaitForAttachment maxWaitCount="100">
            <ServiceName>ddsi2</ServiceName>
         </WaitForAttachment>
      </Network>
      <NameSpaces>
         <NameSpace name="defaultNamespace">
            <Partition>*</Partition>
         </NameSpace>
         <Policy alignee="Initial" aligner="true" durability="Durable" nameSpace="defaultNamespace" />
      </NameSpaces>
   </DurabilityService>
   <TunerService name="cmsoap">
      <Server>
         <PortNr>Auto</PortNr>
      </Server>
   </TunerService>
</OpenSplice>`

Domain ID is set to 0, just like the domain ID in my OpenDDS application. The port number is set to Auto. 

Below two Wireshark captures.
![inter wireshark 1](https://user-images.githubusercontent.com/31957251/57925609-1c3bd480-78a9-11e9-97e0-1e9be61cbd70.JPG)
![inter wireshark 2](https://user-images.githubusercontent.com/31957251/57925610-1cd46b00-78a9-11e9-80ce-9ad2f11a7333.JPG)

It seems that OpenSplice can detect my PC with OpenDDS but not the other way around. The destination is suddenly 239.255.0.1 and port number 7400. What am I doing wrong? #1117 had the same issue, but has solved it by creating a route rule for a multicast group? If this is the case, how do I do this?

If anyone can help me, I would be really grateful.

Thanks!

**Comment by LaurentB38** [comment]
Hi @forevermirin94 

I did open #1117 issue which describes similarly the same problem. 
But I work on Linux (CentOS), and you on Windows 10.

My approach was first to disable all network interfaces (especially the interface connected to internet) and just let activated he usefull one (computer plugged to the target).
Then, launching both applications, I got errors on OpenDDS side :

> (28504|140498056472384) ERROR: Spdp::SpdpTransport::SpdpTransport() - failed to join multicast group 239.255.0.1:7400 ACE_SOCK_Dgram_Mcast::join: Operation not supported

Regarding to the route rules, I observed that there was no route rules for the multicast address (239.255.0.1) (by executing route command).
Consequently, on my PC (CentOS), I created a route rule on the corresponding interface:
`sudo route add 239.255.0.1 dev eth4`

I advice you to try the same approach, and maybe you need to create a roule rule under you Windows (very similar I had a look).
Hope this helps,
Laurent

**Comment by forevermirin94** [comment]
> Hi @forevermirin94
> 
> I did open #1117 issue which describes similarly the same problem.
> But I work on Linux (CentOS), and you on Windows 10.
> 
> My approach was first to disable all network interfaces (especially the interface connected to internet) and just let activated he usefull one (computer plugged to the target).
> Then, launching both applications, I got errors on OpenDDS side :
> 
> > (28504|140498056472384) ERROR: Spdp::SpdpTransport::SpdpTransport() - failed to join multicast group 239.255.0.1:7400 ACE_SOCK_Dgram_Mcast::join: Operation not supported
> 
> Regarding to the route rules, I observed that there was no route rules for the multicast address (239.255.0.1) (by executing route command).
> Consequently, on my PC (CentOS), I created a route rule on the corresponding interface:
> `sudo route add 239.255.0.1 dev eth4`
> 
> I advice you to try the same approach, and maybe you need to create a roule rule under you Windows (very similar I had a look).
> Hope this helps,
> Laurent

Thanks for your answer!
So I should disable all the network adapters on my Windows 10 laptop? Also the ethernet adapter? Do I then connect an ethernet cable directly from my laptop to the Raspberry Pi?

Where exactly did you get to see the OpenDDS error you mentioned? Was this in a log file or directly in the Linux terminal?

Ill try to create a route rule for 239.255.0.1 on my Windows machine.

**Comment by LaurentB38** [comment]
Hi,
Yes disable all network interfaces, excepting the interface connected to the Raspberry PI (by ethernet).

I got the OpenDDS errors on the Linux terminal, when launching the OpenDDS application.

Let me know your progress.
Laurent.

**Comment by forevermirin94** [comment]
> Hi,
> Yes, disable all network interfaces, excepted the interface connected to the Raspberry PI (by ethernet).
> 
> I got the OpenDDS errors on the Linux terminal, when launching the OpenDDS application. But you can have the errors also in the logs if you activate it.
> 
> Let me know your progress.
> Laurent.

Ok, so I have disabled all the network adapters, except the Ethernet adapter which is connected from my Laptop to the Raspberry Pi.
![network adapters](https://user-images.githubusercontent.com/31957251/58009202-31ee0b80-7aee-11e9-9394-0092d154c6ce.JPG)

When I do ipconfig, I get the following:
![ipconfig](https://user-images.githubusercontent.com/31957251/58009291-63ff6d80-7aee-11e9-9d28-c270e8136e25.JPG)

I have used the following command to add the route rules.
route -p ADD 239.255.0.1 MASK 255.255.0.0 169.254.237.26

This is the Wireshark trace I am getting:
![wireshark 1](https://user-images.githubusercontent.com/31957251/58009404-ab85f980-7aee-11e9-885d-e021750dfeaf.JPG)

Still no luck :(. What could the issue be?

**Comment by LaurentB38** [comment]
Do you have errors from OpenDDS and/or OpenSplice?
Any errors **without or with** the new route rule?
Did you have a look to the OpenDDS logs?

239.255.0.0 is for multicast discovery.
But I missed the other one: the multicast group 224.0.0.0 (by default).
No need to specify the mask and to make it persistent at this time.
Try easier:

> route ADD 239.255.0.0  169.254.237.26
> route ADD 224.0.0.0  169.254.237.26

Be careful with your firewall, flush dns cache and/or deactivate your firewall.

**Comment by forevermirin94** [comment]
> Do you have errors from OpenDDS and/or OpenSplice?
> Any errors **without or with** the new route rule?
> Did you have a look to the OpenDDS logs?
> 
> 239.255.0.0 is for multicast discovery.
> But I missed the other one: the multicast group 224.0.0.0 (by default).
> No need to specify the mask and to make it persistent at this time.
> Try easier:
> 
> > route ADD 239.255.0.0  169.254.237.26
> > route ADD 224.0.0.0  169.254.237.26
> 
> Be careful with your firewall, flush dns cache and/or deactivate your firewall.

Sorry for the noob question, where can I find the OpenDDS logs? I checked the OpenSplice logs and ther e are no errors. Ill try the new route rules you just gave.

**Comment by forevermirin94** [comment]
> Do you have errors from OpenDDS and/or OpenSplice?
> Any errors **without or with** the new route rule?
> Did you have a look to the OpenDDS logs?
> 
> 239.255.0.0 is for multicast discovery.
> But I missed the other one: the multicast group 224.0.0.0 (by default).
> No need to specify the mask and to make it persistent at this time.
> Try easier:
> 
> > route ADD 239.255.0.0  169.254.237.26
> > route ADD 224.0.0.0  169.254.237.26
> 
> Be careful with your firewall, flush dns cache and/or deactivate your firewall.

I tried out the new route rules, it's still sending to 239.255.0.1 from my laptop. Could the issue be with the firewall?

**Comment by mitza-oci** [comment]
@forevermirin94 Please change the subject line so we know what this issue is about.

**Comment by forevermirin94** [comment]
> @forevermirin94 Please change the subject line so we know what this issue is about.

Changed :)

**Comment by forevermirin94** [comment]
@mitza-oci Do you know what I am doing wrong? The messages are being sent but always to the multicast address. I have connected the PC and the Raspberry Pi straight with an ethernet cable.

**Comment by mitza-oci** [comment]
@forevermirin94 would you please describe why this was closed?  Was the issue resolved?
