### ISSUE TITLE
Messages type sequence doesn't work

### ISSUE THREAD

**Issue by AyalaIsakov** [objectcomputing/OpenDDS#1130]
I have in my messages.idl type of messages which doesn't work at all.... for example:
sequence<foo,10>bar;
foo can be any kind of variable.. most of them are structs.
In WireShark I see that the messages are sended.... But in the receiving computer, I see on WireShark black fields and it says that the header checksum is wrong, it is 0x00.... (for all the messages....) 
Maybe someone knows what can I do?
Thank you, Ayala.

**Comment by iguessthislldo** [comment]
`sequence<foo,10> bar;` would be an anonymous type, which is not supported at the moment and `opendds_idl` will error if it encountered it. This is an example of the correct syntax:

```
  typedef sequence<foo, 10> FooSeq;

  struct MessageType {
    ...
    FooSeq bar;
    ...
  };
```

> In WireShark I see that the messages are sended.... But in the receiving computer, I see on WireShark black fields and it says that the header checksum is wrong, it is 0x00.... (for all the messages....)

What kind of discovery/transport are you using? Also is your application working, cause it just sounds like Wireshark is saying something is wrong.

**Comment by mitza-oci** [comment]
There are many examples of using IDL sequences in the OpenDDS test suite.  You can read more about wireshark header checksums (this has nothing to do with OpenDDS) here https://wiki.wireshark.org/TCP_Checksum_Verification
