### ISSUE TITLE
How the cached samples persist,when durability qos is sent to PERSISTENT_DURABILITY_QOS

### ISSUE THREAD

**Issue by yuxuchang** [objectcomputing/OpenDDS#1134]
When DurabilityQos is sent to PERSISTENT_DURABILITY_QOS, the cached samples would be persisted. But I cannot find file created in current directory where the samples persist into, so who can tell me how the cached samples persist, thanks

**Comment by mitza-oci** [comment]
You can use the configuration option `DCPSPersistentDataDir` (on the command line or in the ini file) to customize the directory for persistent data.  See Table 7-2 in the OpenDDS Developer's Guide.
