### ISSUE TITLE
How to hard code configuration file instead of passing it using command-line argument

### ISSUE THREAD

**Issue by forevermirin94** [objectcomputing/OpenDDS#1152]
I'm trying to hard code my configuration file rtps.ini instead of passing the file using the command-line argument. I'm creating an application using Qt.
`int ddspub(void) {
	
	try {
		if (i == 0) {
			command = 0;
			//Initialize DomainParticipantFactory
			DDS::DomainParticipantFactory_var dpf =
				TheParticipantFactoryWithArgs(1, "-DCPSConfigFile", "rtps.ini");`

I tried doing the above, but it won't work obviously. How can I exactly do this? 

Thanks!

**Comment by simpsont-oci** [comment]
The 2nd parameter of TheParticipantFactoryWithArgs needs to be an ACE_TCHAR* array, normally what comes from main(). Try something like:

const ACE_TCHAR* args[2] = { "-DCPSConfigFile", "rtps.ini" };
TheParticipantFactoryWithArgs(2, args);

**Comment by forevermirin94** [comment]
> The 2nd parameter of TheParticipantFactoryWithArgs needs to be an ACE_TCHAR* array, normally what comes from main(). Try something like:
> 
> const ACE_TCHAR* args[2] = { "-DCPSConfigFile", "rtps.ini" };
> TheParticipantFactoryWithArgs(2, args);

Thanks for your answer!

I changed it to the following: 
`int ddspub(void) {
	
	try {
		if (i == 0) {
			command = 0;
			const ACE_TCHAR* args[2] = {"-DCPSConfigFile", "rtps.ini"};
			//Initialize DomainParticipantFactory
			DDS::DomainParticipantFactory_var dpf =
				TheParticipantFactoryWithArgs(2,args);`

I'm getting the error: `Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'DDS::DomainParticipantFactory_ptr OpenDDS::DCPS::Service_Participant::get_domain_participant_factory(int &,ACE_TCHAR *[])': cannot convert argument 1 from 'int' to 'int &'	RobotController	c:\users\jonathan\source\repos\robotcontroller\robotcontroller\robotcontroller.cpp	41	
`
and `Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0461	initial value of reference to non-const must be an lvalue	RobotController	C:\Users\jonathan\source\repos\RobotController\RobotController\RobotController.cpp	41	
`

**Comment by simpsont-oci** [comment]
Based on the compiler warning, it looks like it's telling you it wants reference to the integer count instead of a constant literal value:

int argc = 2;
TheParticipantFactoryWithArgs(argc, args);

**Comment by forevermirin94** [comment]
> Based on the compiler warning, it looks like it's telling you it wants reference to the integer count instead of a constant literal value:
> 
> int argc = 2;
> TheParticipantFactoryWithArgs(argc, args);

I tried that out too, but I get other errors now.
`Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0167	argument of type "const ACE_TCHAR **" is incompatible with parameter of type "ACE_TCHAR **"	RobotController	C:\Users\jonathan\source\repos\RobotController\RobotController\RobotController.cpp	43	
`

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'DDS::DomainParticipantFactory_ptr OpenDDS::DCPS::Service_Participant::get_domain_participant_factory(int &,ACE_TCHAR *[])': cannot convert argument 2 from 'const ACE_TCHAR *[2]' to 'ACE_TCHAR *[]'	RobotController	c:\users\jonathan\source\repos\robotcontroller\robotcontroller\robotcontroller.cpp	43	
`

**Comment by simpsont-oci** [comment]
Right, it looks like it wants the ability to modify both parameters, so it wants a reference to the integer and it wants non-const pointers. And the compiler probably won't let you just switch from "const ACE_TCHAR* args[2]" to "ACE_TCHAR* args[2]" because the it doesn't want you to have a non-const pointer to a string literal. Looks like you'll have to build the array up manually.

**Comment by iguessthislldo** [comment]
> Right, it looks like it wants the ability to modify both parameters

OpenDDS does indeed manipulate the `argv` that it is passed. It processes options it recognizes and leaves ones it doesn't recognize for the user application to process.

**Comment by forevermirin94** [comment]
> Right, it looks like it wants the ability to modify both parameters, so it wants a reference to the integer and it wants non-const pointers. And the compiler probably won't let you just switch from "const ACE_TCHAR* args[2]" to "ACE_TCHAR* args[2]" because the it doesn't want you to have a non-const pointer to a string literal. Looks like you'll have to build the array up manually.

I'll try building up the array manually.
Thanks!

**Comment by forevermirin94** [comment]
Got it to work :)
Thank you very much!!
