### ISSUE TITLE
OpenDDS-3.12: --target=android => android not a valid target

### ISSUE THREAD

**Issue by binary42** [objectcomputing/OpenDDS#1199]
OpenDDS-3.12: Check android.md, android target does not exist.

**Comment by binary42** [comment]
More to the point, OpenDDS-3.14 isn't available from downloads. Do we have to build OpenDDS from source to acquire 3.14?

**Comment by iguessthislldo** [comment]
> OpenDDS-3.12: Check android.md, android target does not exist.

You're reading documentation for the wrong version. 3.12 doesn't have `android.md` or support for Android at all. Basic support was added for Android in 3.13.1.

> Do we have to build OpenDDS from source to acquire 3.14?

Sorta. That version of `android.md` is for the Java Android support in master and *will* be part of 3.14 when it comes out soon. If you want the most basic C++ support, 3.13.2 has that, if you want Java support, that only exists in master at the moment.

**Comment by binary42** [comment]
Copy that, thanks. Missed it in the readme. Any timeline on 3.14 release?

**Comment by iguessthislldo** [comment]
I can't say exactly when because we still have two major pull requests to merge, but we're inching towards it. I'm hoping to have my PR ready for review by tomorrow and merged sometime next week.
