### ISSUE TITLE
-Wb,export_include flag for opendds_idl and tao_idl doesn't seem to work

### ISSUE THREAD

**Issue by ieglandDRS** [objectcomputing/OpenDDS#1204]
Just getting started with OpenDDS, so I may just be missing something. I found this Problem-Report-Form, so I filled it out. I'll rewrite this post if that's better for a GitHub issue.

---
OpenDDS VERSION: **3.13.2** (also verified problem in 3.13)
TAO VERSION: **2.2a** (auto-downloaded by configure.cmd)

HOST MACHINE and OPERATING SYSTEM: **x86_64, Windows 10**

TARGET MACHINE and OPERATING SYSTEM, if different from HOST: **same as host**
COMPILER NAME AND VERSION (AND PATCHLEVEL): **Microsoft Visual Studio Professional 2013 Update 5 (aka version 12)**

CONTENTS OF $ACE_ROOT/ace/config.h: `#include "ace/config-win32.h"`

CONTENTS OF $ACE_ROOT/include/makeinclude/platform_macros.GNU (unless this isn't used in this case, e.g., with Microsoft Visual C++): **I don't think one is used in this case - one isn't present in that path.**
CONTENTS OF $ACE_ROOT/bin/MakeProjectCreator/config/default.features (used by MPC when you generate your own makefiles):
```
ssl=1
xerces3=1
openssl11=1
no_opendds_security=0
```
LEVEL OF URGENCY (LOW, MEDIUM, or HIGH): **LOW**

AREA/CLASS/EXAMPLE AFFECTED:
**%DDS_ROOT%\examples\IntroductionToOpenDDS\**

DOES THE PROBLEM AFFECT:
COMPILATION? **Yes.**
LINKING? **No.**
EXECUTION? **No.**
OTHER (please specify)? **IDL Code Generation** 

SYNOPSIS:
**The -Wb,export_include flag doesn't work on either %DDS_ROOT%\bin\opendds_idl.exe nor %ACE_ROOT%\bin\tao_idl.exe** 

DESCRIPTION:
I've been working through the StockQuoter example in [Introduction To OpenDDS](http://opendds.org/about/articles/Article-Intro.html). One of the steps is to set up an [MPC](https://github.com/DOCGroup/MPC) file to build the StockQuoterCommon library, publisher executable, and subscriber executable. So far I am unable to build the StockQuoterCommon library. Here is what I have so far for the MPC, including comments that describe my understanding of idlflags and dcps_ts_flags.

```
project(*Common) : dcps {
  sharedname = StockQuoterCommon
  dynamicflags = STOCKQUOTERCOMMON_BUILD_DLL
  libout = .

  requires += tao_orbsvcs
  requires += no_opendds_safety_profile
  after += Svc_Utils

  includes			+= $(TAO_ROOT)/orbsvcs

  // idlflags is a custom MPC keyword defined in
  // <tao_root>/MPC/config/taobaseidldefaults.mpb
  // https://github.com/objectcomputing/OCITAO/blob/tao_2_3a/TAO/MPC/config/taobaseidldefaults.mpb
  // it is used to define tao_idl flags
  // tao_idl flags
  idlflags			+=	-I$(TAO_ROOT)/orbsvcs \
							-Wb,export_macro=StockQuoterCommon_Export \
							-Wb,export_include=StockQuoterCommon_Export.h \
							-Wb,pch_include=StockQuoterCommon_Export.h
  
  // dcps_ts_flags is a legacy name that means opendds_idl flags
  // opendds_idl is documented in the OpenDDS developer's guide
  // the MPC project base file that defines this custom keyword is in
  // <openddsroot>/MPC/config/dcps_ts_defaults.mpb
  // for details on MPB files, used by MPC, go to
  // https://github.com/DOCGroup/MPC
  // opendds_idl flags
  dcps_ts_flags	+= -Wb,export_macro=StockQuoterCommon_Export
  
  
  TypeSupport_Files {
    StockQuoter.idl
  }

  IDL_Files {
    StockQuoterTypeSupport.idl
    StockQuoter.idl
  }

  Header_Files {
  }

  Source_Files {
  }
}
```
For comparison, with what should be in this file, see [%DDS_ROOT%\examples\DCPS\IntroductionToOpenDDS\StockQuoter.mpc](https://github.com/objectcomputing/OpenDDS/tree/latest-release/examples/DCPS/IntroductionToOpenDDS/StockQuoter.mpc) When I try to build the Microsoft Visual Studio Project in the Microsoft Visual Studio Solution that `perl %ACE_ROOT%/bin/mwc.pl -type vc12 StockQuoter.mwc` produces, I get multiple instances of the following error.
`StockQuoterC.cpp(31): fatal error C1083: Cannot open include file: 'StockQuoterCommon_Export.h': No such file or directory`

As far as I can tell, my MPC file (above) correctly specifies that the StockQuoterCommon_Export.h file should be generated.

As a sanity check, I tried building the copy of [IntroductionToOpenDDS that comes with OpenDDS](https://github.com/objectcomputing/OpenDDS/tree/latest-release/examples/DCPS/IntroductionToOpenDDS), instead of the one that I wrote out by hand through the course of the article. It built fine, but I noticed that the [StockQuoterCommon_Export.h](https://github.com/objectcomputing/OpenDDS/tree/latest-release/examples/DCPS/IntroductionToOpenDDS/StockQuoterCommon_Export.h) file was already present before I built it. Additionally, if I were to remove that file, the project no longer builds, citing a missing StockQuoterCommon_Export.h.

Since it seemed like there was a bug in code generation, I did some digging to make sure my flags are right.

First off, they seem right based on the example provided in [%DDS_ROOT%\examples\DCPS\IntroductionToOpenDDS\StockQuoter.mpc](https://github.com/objectcomputing/OpenDDS/tree/latest-release/examples/DCPS/IntroductionToOpenDDS/StockQuoter.mpc)

Furthermore, according to %TAO_ROOT%/docs/compiler.html ([this seems to be a copy](http://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/TAO/docs/compiler.html)), -Wb,export_include=StockQuoterCommon_Export.h should produce a StockQuoterCommon_Export.h file. Additionally, Chapter 8 in the [OpenDDS 3.13 developer's guide](http://download.objectcomputing.com/OpenDDS/OpenDDS-latest.pdf) states that the -Wb,export_include=StockQuoterCommon_Export.h file should also produce a StockQuoterCommon_Export.h file.

Later in the developer's guide, however, there's mention of a `generate_export_file.pl` to create *_export.h files, but that's for use with Java.

REPEAT BY:
Based on the following build output produced while building the StockQuoter_Common Project...
```
1>------ Build started: Project: StockQuoter_Common, Configuration: Debug x64 ------
1>  Invoking "C:\Users\ian.egland\lib\opendds\bin\opendds_idl and C:\Users\ian.egland\lib\opendds\ACE_wrappers\bin\tao_idl on StockQuoter.idl"
1>  tao-idli_HpKAiV.cpp
1>  processing StockQuoter.idl
1>  tao-idli_zR1YqD.cpp
1>  processing StockQuoter.idl
1>  Invoking "C:\Users\ian.egland\lib\opendds\ACE_wrappers\bin\tao_idl on StockQuoterTypeSupport.idl"
1>  tao-idli_BeFFJ4.cpp
1>  processing StockQuoterTypeSupport.idl
1>  StockQuoterC.cpp
1>StockQuoterC.cpp(31): fatal error C1083: Cannot open include file: 'StockQuoterCommon_Export.h': No such file or directory
1>  StockQuoterS.cpp
1>StockQuoterS.cpp(32): fatal error C1083: Cannot open include file: 'StockQuoterCommon_Export.h': No such file or directory
1>  StockQuoterTypeSupportC.cpp
1>StockQuoterTypeSupportC.cpp(31): fatal error C1083: Cannot open include file: 'StockQuoterCommon_Export.h': No such file or directory
1>  StockQuoterTypeSupportImpl.cpp
1>c:\users\ian.egland\code\stockquoter\StockQuoterC.h(44): fatal error C1083: Cannot open include file: 'StockQuoterCommon_Export.h': No such file or directory
1>  StockQuoterTypeSupportS.cpp
1>StockQuoterTypeSupportS.cpp(32): fatal error C1083: Cannot open include file: 'StockQuoterCommon_Export.h': No such file or directory
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
I created the following batch file that let me try to directly add and remove the flags in question as parameters to the IDL compilers in question. This batch file lives in a directory with a copy of StockQuoter.idl and nothing else.
```
@echo off
echo First invoke: opendds_idl and tao_idl on StockQuoter.idl
 
C:\Users\ian.egland\lib\opendds\bin\opendds_idl -I%TAO_ROOT%/orbsvcs -Wb,export_macro=StockQuoterCommon_export StockQuoter.idl
C:\Users\ian.egland\lib\opendds\ACE_wrappers\bin\tao_idl.exe -I%TAO_ROOT%/orbsvcs -Wb,stub_export_macro=StockQuoterCommon_export -Wb,stub_export_include=StockQuoterCommon_export.h StockQuoter.idl 

echo Second invoke: tao_idl on StockQuoterTypeSupport.idl

C:\Users\ian.egland\lib\opendds\ACE_wrappers\bin\tao_idl.exe -I%DDS_ROOT% -I%TAO_ROOT%/orbsvcs -Wb,stub_export_macro=StockQuoterCommon_export -Wb,stub_export_include=StockQuoterCommon_export.h StockQuoterTypeSupport.idl
```
Running it (in a visual studio command prompt with the OpenDDS environment variables set) confirms that the _export.h file isn't produced.

```
C:\Users\ian.egland\code\StockQuoter\test>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 661D-5B1A

 Directory of C:\Users\ian.egland\code\StockQuoter\test

07/11/2019  10:47 AM    <DIR>          .
07/11/2019  10:47 AM    <DIR>          ..
07/08/2019  10:30 AM               619 StockQuoter.idl
07/11/2019  09:18 AM               707 test_idl_seq.bat
               2 File(s)          1,326 bytes
               2 Dir(s)  402,774,462,464 bytes free
```
```
C:\Users\ian.egland\code\StockQuoter\test>test_idl_seq.bat
First invoke: opendds_idl and tao_idl on StockQuoter.idl
tao-idli_lCBrda.cpp
processing StockQuoter.idl
tao-idli_UnlGCl.cpp
processing StockQuoter.idl
Second invoke: tao_idl on StockQuoterTypeSupport.idl
tao-idli_3aI4SB.cpp
processing StockQuoterTypeSupport.idl
```
```
C:\Users\ian.egland\code\StockQuoter\test>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 661D-5B1A

 Directory of C:\Users\ian.egland\code\StockQuoter\test

07/11/2019  10:47 AM    <DIR>          .
07/11/2019  10:47 AM    <DIR>          ..
07/08/2019  10:30 AM               619 StockQuoter.idl
07/11/2019  10:47 AM            13,712 StockQuoterC.cpp
07/11/2019  10:47 AM             9,910 StockQuoterC.h
07/11/2019  10:47 AM               752 StockQuoterC.inl
07/11/2019  10:47 AM               951 StockQuoterS.cpp
07/11/2019  10:47 AM             2,633 StockQuoterS.h
07/11/2019  10:47 AM            17,070 StockQuoterTypeSupport.idl
07/11/2019  10:47 AM            43,140 StockQuoterTypeSupportC.cpp
07/11/2019  10:47 AM            38,201 StockQuoterTypeSupportC.h
07/11/2019  10:47 AM               752 StockQuoterTypeSupportC.inl
07/11/2019  10:47 AM            25,108 StockQuoterTypeSupportImpl.cpp
07/11/2019  10:47 AM            11,094 StockQuoterTypeSupportImpl.h
07/11/2019  10:47 AM               984 StockQuoterTypeSupportS.cpp
07/11/2019  10:47 AM             2,130 StockQuoterTypeSupportS.h
07/11/2019  09:18 AM               707 test_idl_seq.bat
              15 File(s)        167,763 bytes
               2 Dir(s)  402,774,261,760 bytes free

C:\Users\ian.egland\code\StockQuoter\test>
```

SAMPLE FIX/WORKAROUND:
Use the following command to generate the _export.h file manually.
`perl %ACE_ROOT%\bin\generate_export_file.pl DesiredName > DesiredName_export.h`
Example:
`perl %ACE_ROOT%\bin\generate_export_file.pl StockQuoterCommon > StockQuoterCommon_export.h`

**Comment by simpsont-oci** [comment]
I think what you'll want is %DDS_ROOT%/ACE_wrappers/MPC/
generate_export_header.pl.

**Comment by mitza-oci** [comment]
> I think what you'll want is %DDS_ROOT%/ACE_wrappers/MPC/ generate_export_header.pl.

That can work but I'd recommend following what the OpenDDS tests do and using the one from ACE.
https://github.com/objectcomputing/OpenDDS/blob/0810ffc3f5c410e64975d66d82159fa4eb0bc394/tests/DCPS/Messenger/Messenger_export.h#L4

**Comment by ieglandDRS** [comment]
Thank you. Yes, generate_export_file.pl solved the problem. I tested it with the ACE version and it worked.

`perl %ACE_ROOT%\bin\generate_export_file.pl StockQuoterCommon > StockQuoterCommon_export.h`

Is there a way to get MPC to execute this automatically?

**Comment by mitza-oci** [comment]
> Thank you. Yes, generate_export_file.pl solved the problem. I tested it with the ACE version and it worked.
> 
> `perl %ACE_ROOT%\bin\generate_export_file.pl StockQuoterCommon > StockQuoterCommon_export.h`
> 
> Is there a way to get MPC to execute this automatically?

Yes, there is a script `%DDS_ROOT%\bin\expfile.pl` which calls ACE's generate_export_file.pl and is designed to be run from a project's prebuild step.
Examples of this are used in the Modeling SDK's generated code (`tools\modeling\plugins\org.opendds.modeling.sdk.model\xsl\mpc.xsl`), but it's not tied to the Modeling SDK in any way.

**Comment by mitza-oci** [comment]
Closing this one.  If you think that changes to the source code or website are necessary, please open a Pull Request targeted to the branch `master` or `gh-pages` respectively.
