### ISSUE TITLE
Messages synchronize Problem

### ISSUE THREAD

**Issue by Mrils** [objectcomputing/OpenDDS#1205]
Hello.
I'm working  on a job about Multi-sensor Information Fusion on OpenDDS, while i meet a problem that any sensor has its rate and I need to pick out messages that are at the same time or at a similar time to synchronize the output. Is there any good way to figure out it? Thanks!

**Comment by iguessthislldo** [comment]
So in the OpenDDS Developer's Guide, Section 3.2.21 "TIME_BASED_FILTER" goes over having a minimum period between samples/messages. I'm not sure what you want though, do you want the messages within a certain a certain period? If not, time based filter isn't what you'd want. I don't think OpenDDS has something like that builtin. The only thing I can think of is taking the `source_timestamp` from `SampleInfo` for a given sample and using that to get what you want. If you want me to elaborate on this I can.

**Comment by Mrils** [comment]
Well,I have read what you said but it doesn't seem to be what I wanted. 
In my job, there is al least two Publisher thread but each has different frequency to publish messages. For example, Thread A posts messages at an interval of 30ms, which sequence is MA1,MA2,MA3,etc.. and Thread B posts messages at an interval of 10ms, which is MB1,MB2,MB3,etc.. Then we got Thread C to read messages from Thread A and Thread B at same time. In the example above, we want a tuple sequence (MA1,MB1),(MA2,MB4) and so on. 
So did we get the method to drop the messages with unaligned timestamp such as MB2,MB3, and publish the tuple sequence with aligned timestamp?

**Comment by iguessthislldo** [comment]
Okay, I think I understand now. No OpenDDS doesn't have that ability built-in as far as I'm aware. You're going to have to look at the `source_timestamp` of each message as it comes in and build up these tuples on your own. That doesn't sound too hard to do on your own though. In a loop you read from topics A and B. Say if you get a message from A, you could set a timer and if a message from B comes within that period you combine it with the message from A and you have your tuple. If not you drop the message from A and reset.

**Comment by Mrils** [comment]
Right，thansk for your response! I will try it soon.

**Comment by iguessthislldo** [comment]
@Mrils did you get it working? Can I close this issue?

**Comment by Mrils** [comment]
Yeah.I'm sorry I forgot it.

**Comment by tottens** [comment]
@Mrils Glad you got it working! Let us know if we can be of further help.
https://opendds.org
https://objectcomputing.com/products/opendds
