### ISSUE TITLE
rtps_udp dropping messages

### ISSUE THREAD

**Issue by rcmcminn** [objectcomputing/OpenDDS#1213]
Our applications are attempting to exchange data using the rtps_udp transport_type: Here is the common configuration file in use at this time.

[common]
DCPSDebugLevel=0
DCPSTransportDebugLevel=0
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS

[transport/the_rtps_transport]
transport_type=rtps_udp
thread_per_connection=1

We are using OpenDDS-3.13.2.  

Development Environment:
Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)
Release:        6.9
Codename:       Final

Test Environment:
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 6.9 (Santiago)
Release:	6.9
Codename:	Santiago

For all Topics, Data Writers and Data Readers, the following QoS settings:
Durability Kind:    DDS::TRANSIENT_LOCAL_DURABILITY_QOS
History Kind:        DDS::KEEP_LAST_HISTORY_QOS
History Level:      1
Reliability Kind:    DDS::RELIABLE_RELIABILITY_QOS

We are encountering dropped messages (Reliability QoS not working). WE are noting that a Data Reader that comes on line after a Topic is published is not notified of the Topic (Durability QoS not working).

I see a number of items on the web that use the term reliable mode, but I cannot determine what code and/or configuration settings would place our applications in "reliable mode" to exchange topics.

Any insights would be much appreciated.

**Comment by mitza-oci** [comment]
Please attach a packet capture and we'll take a look.

There's no additional configuration you need for reliability/durability other than what you've shown above.

**Comment by mitza-oci** [comment]
Is this fixed with the latest changes on master?
