### ISSUE TITLE
Duplicate messages received by Subscriber

### ISSUE THREAD

**Issue by nikhilbagul** [objectcomputing/OpenDDS#1214]
Hello all,

While trying to work with the Open DDS example of Messenger.minimal at 
`DevGuideExamples/DCPS/Messenger.minimal` 
I was able to set up the Publisher and Subscriber successfully on a Mac with High Sierra. Everything works as expected when I am publishing 'n' number of messages from Publisher. I am receiving exactly 'n' number of messages on the Subscriber. 
But, whenever I try to modify the Publisher to send messages on ad-hoc basis/waiting for user input to publish a message, the Subscriber receives duplicate messages i.e > 1 of the same message for the one Published message. 
I am trying to get my head around the message QoS policies but haven't had any luck so far. 

I am using RTPS as my communication service and OpenDDS version 3.13. 
Any pointers are much appreciated. 

Best,
Nikhil

**Comment by mitza-oci** [comment]
Please share the code so we can reproduce the issue.  I suggest using either a forked repo of OpenDDS or an independent GitHub repo containing just your application code.

**Comment by nikhilbagul** [comment]
`#include <QGuiApplication>
#include <QQmlApplicationEngine>

#include <Boilerplate.h>

#include "dds/DCPS/StaticIncludes.h"
#include <dds/DCPS/Service_Participant.h>
#include <model/Sync.h>
#include <stdexcept>
#include <thread>         // std::thread, std::this_thread::sleep_for

int initializeDDSPublisher(int argc, char *argv[]);
int sendMessage(int argc, char *argv[], Messenger::MessageDataWriter_var& msg_writer_ref);
using namespace boilerplate;

int main(int argc, char *argv[])
{
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));
    if (engine.rootObjects().isEmpty())
        return -1;

    initializeDDSPublisher(argc, argv);
    //std::thread th(initializeDDSPublisher,argc, argv);

    return app.exec();
}

int initializeDDSPublisher(int argc, char *argv[])
{
    // Initialize DomainParticipantFactory, handling command line args
    DDS::DomainParticipantFactory_var dpf =
            TheParticipantFactoryWithArgs(argc, argv);

    // Create domain participant
    DDS::DomainParticipant_var participant = createParticipant(dpf);

    // Register type support and create topic
    DDS::Topic_var topic = createTopic(participant);

    // Create publisher
    DDS::Publisher_var publisher = createPublisher(participant);

    // Create data writer for the topic
    DDS::DataWriter_var writer = createDataWriter(publisher, topic);

    // Set Data writer QOS policy to prevent redundancy due to delay
    DDS::DataWriterQos policy;
    policy.writer_data_lifecycle.autodispose_unregistered_instances = true;
    writer->set_qos(policy);

    // Safely downcast data writer to type-specific data writer
    Messenger::MessageDataWriter_var msg_writer = narrow(writer);


    // Block until Subscriber is available
    OpenDDS::Model::WriterSync ws(writer);

    bool isPublisherRunning = true;
    char input;
    while (isPublisherRunning)
    {
        std::cout << " Do you want to publish the next message (Y or N) : ";
        std::cin >> input;

        //input = 'y';
        if (input == 'Y' || input == 'y')
        {
            sendMessage(argc, argv, msg_writer);
            input = 'n';
            isPublisherRunning = true;
        }
        else
        {
            isPublisherRunning = false;
        }
    }

    // Clean-up!
    cleanup(participant, dpf);

    return 0;
}

int sendMessage(int argc, char *argv[], Messenger::MessageDataWriter_var& msg_writer_ref)
{
    // Initialize samples
    Messenger::Message message;
    message.fixed_id = "TIRE_PRESSURE_FL";
    message.type = "number";
    message.value = "39";

    // Publish the message
    DDS::ReturnCode_t error = msg_writer_ref->write(message,
                                                    DDS::HANDLE_NIL);
    if (error != DDS::RETCODE_OK) {
        ACE_ERROR((LM_ERROR,
                   ACE_TEXT("ERROR: %N:%l: main() -")
                   ACE_TEXT(" write returned %d!\n"), error));
    }

    // End of WriterSync scope - block until messages acknowledged
}

`

**Comment by nikhilbagul** [comment]
@mitza-oci 
Hey Adam, Much apologies for the delay. Please find below the link to the repository that I have created like you mentioned. Please let know if you need any other info from my end. 

[Github repo link](https://github.com/nikhilbagul/OpenDDS-PubSub-QtPrototype/blob/master/README.md)

**Comment by mitza-oci** [comment]
Appears to be replaced by #1252

**Comment by nikhilbagul** [comment]
Hey Adam, yes I did that. I was assuming that my post got buried and hence I created a new one. Apologies for that.
