### ISSUE TITLE
the transport time is too long with rtps+udp

### ISSUE THREAD

**Issue by Mrils** [objectcomputing/OpenDDS#1217]
Well, I want to use OpenDDS to transfer an image（about 2MB） using rtps+udp with Publisher thread and Subscriber thread on the same PC. And I find that the transport time is so long (about 250ms) to accept it. Is there a problem with my configuration file or QoS? Here is my configuration file and i'm using default QoS configuration:

```
[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS
[transport/the_rtps_transport]
transport_type=rtps_udp
```

**Comment by mitza-oci** [comment]
What's the latency you're trying to get it down to?  Have you tried changing nak_response_delay, heartbeat_period, and/or heartbeat_response_delay in the transport settings?  See Table 7-17 in the developer's guide.

**Comment by Mrils** [comment]
well，When I set use_multicast to zero, the delay was reduced to less than 10ms. But it may lost message about 10%.  And now I'm using shmem transport method and the delay could be reduced to 2~5ms. Is this for the best?Can the delay be reduced to less than 1ms？
And i found TCP performs better than rtps_udp in terms of latency. It's weird. Maybe i use the wrong config but i cannot find reason.

**Comment by jrw972** [comment]
Please create a fork and add a representative test program in `performance-tests/DCPS/` so that we can reproduce your results.
