### ISSUE TITLE
Duplicate messages received by Subscriber

### ISSUE THREAD

**Issue by nikhilbagul** [objectcomputing/OpenDDS#1252]
Hello all,

While trying to work with the Open DDS example of Messenger.minimal at
DevGuideExamples/DCPS/Messenger.minimal
I was able to set up the Publisher and Subscriber successfully on a Mac with High Sierra. Everything works as expected when I am publishing 'n' number of messages from Publisher. I am receiving exactly 'n' number of messages on the Subscriber.
But, whenever I try to modify the Publisher to send messages on ad-hoc basis/waiting for user input to publish a message, the Subscriber receives duplicate messages i.e > 1 of the same message for the one Published message.
I am trying to get my head around the message QoS policies but haven't had any luck so far.

I am using RTPS as my communication service and OpenDDS version 3.13.
Any pointers are much appreciated.

Please find below the link to the repository that I have created as you mentioned. Please let know if you need any other info from my end.

[Github repo link](https://github.com/nikhilbagul/OpenDDS-PubSub-QtPrototype)

Best,
Nikhil

**Comment by mitza-oci** [comment]
Please set the data reader's Reliability QoS to RELIABLE.

**Comment by mitza-oci** [comment]
Is this problem fixed with the latest changes on master?
