### ISSUE TITLE
Using Bitset and BitFields in IDL

### ISSUE THREAD

**Issue by bbetulbayram** [objectcomputing/OpenDDS#1275]
Hello, 

I'm trying to use bitset and bitfields because I need them in my project. For the beginning I followed 
https://www.omg.org/spec/IDL/4.2/PDF spesification, and tried to building followin IDL

```
* Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module PubSubData
{
 
#pragma DCPS_DATA_TYPE "PubSubData::State"

   struct State
   {
     octet angle_info;
	 short temperature;

	 bitset MyBitset {	
		bitfield<3> a; // a is stored in 3 bits (and will be manipulable as a char)
		bitfield<1> b; // b is stored in 1 bit (and will be manipulable as a boolean)
		bitfield<4>; // 4 unused bits
		bitfield<10> c; // c is stored in 10 bits (and will be manipulable as an unsigned short)
		bitfield<12, short> d; // d is stored in 12 bits (and will be manipulable as a short)
		};
	 short 	side_angle_info;
	 short out_temperature_info;

	 
	 
   };

};
```

But when I compile it with "%DDS_ROOT%/bin/opendds_idl MessageTest.idl" I got the following error;

> Error - C:\OpenDDS-3.13.2/bin/opendds_idl: "MessageTest.idl", line 18: error in lookup of symbol: bitset
> syntax error
> Error - C:\OpenDDS-3.13.2/bin/opendds_idl: "MessageTest.idl", line 18: Illegal syntax following member declarator(s)

I search all the sources I could find but I could not receive any example about it. I found another notation from another DDS company's site ;

```
struct system_status{
  unsigned short status0: 4;
  unsigned short status1: 4;
  unsigned short status2: 4;
  unsigned short status3: 4;
 };
```
It did not compiled with same kind of error. How can we use bitset and bitfields or maybe more general question can we use them?

**Comment by iguessthislldo** [comment]
OpenDDS uses the TAO IDL Compiler for processing IDL. For now it only supports annotations from the IDL 4.2 Spec, not bitset or any other IDL 4 feature, so OpenDDS does not support bitsets either. They might be supported one day, but they're currently not being considered for the IDL 4 features we're planning on implementing.

Your second example would be a valid [C bit field](https://en.cppreference.com/w/cpp/language/bit_field), but it's definitely not a valid standard IDL bitset, although they are the same concept.

Finally, I'm not sure if most situations would warrant it, but you can always do bit manipulation directly if you desire the compactness that a bitset would give.

**Comment by payal-talati** [comment]
> OpenDDS uses the TAO IDL Compiler for processing IDL. For now it only supports annotations from the IDL 4.2 Spec, not bitset or any other IDL 4 feature, so OpenDDS does not support bitsets either. They might be supported one day, but they're currently not being considered for the IDL 4 features we're planning on implementing.
> 
> Your second example would be a valid [C bit field](https://en.cppreference.com/w/cpp/language/bit_field), but it's definitely not a valid standard IDL bitset, although they are the same concept.
> 
> Finally, I'm not sure if most situations would warrant it, but you can always do bit manipulation directly if you desire the compactness that a bitset would give.


I also need to specify message struct with packed bits in IDL, I am also getting same compiler error as mentioned above.
Is bitset supported now on latest OpenDDS version? If it is supported than what is the syntax?
I checked IDL 4.0 and 4.2 both. They both have support, but different syntax. I also specify --idl_version to tao_idl binary but not working for me, can someone help here?
