### ISSUE TITLE
How to build opendds on VxWorks6.8.2

### ISSUE THREAD

**Issue by alonehitters** [objectcomputing/OpenDDS#1290]
I want to run the opendds on the platform of VxWorks6.8.2. I can not find any tips to run the configure script to generate the target code that can be make by VxWorks6.8.2

**Comment by mitza-oci** [comment]
We don't currently have configure script support for Wind River's VxWorks 6.8.  We also don't list 6.8 as supported on https://opendds.org/documents/building.html, although you can probably get it to work with some manual configuration.  VxWorks 6.8 is listed as EOL by Wind River (https://support2.windriver.com/index.php?page=plc).
We can assist you as part of our commercial support (https://objectcomputing.com/products/opendds).
