### ISSUE TITLE
Restart Participant after shut down with TheParticipantFactoryWithArgs

### ISSUE THREAD

**Issue by yosoufe** [objectcomputing/OpenDDS#1303]
Hi,
I am trying to restart a DDS Participant after the `TheServiceParticipant->shutdown();` and recreate it using `TheParticipantFactoryWithArgs`. I have seen [this restart test code](https://github.com/objectcomputing/OpenDDS/blob/master/tests/DCPS/Restart/RestartTest.cpp) but that is using directly `TheTransportRegistry`.

I am using OpenDDS 3.13.2 but I prefer to have it on 3.12.

The constructor and destruct of my wrapper is **similar** to the following:

**Constructor**
```C++
{
  ACE::init();
  DDS::DomainParticipantFactory_var dpf = TheParticipantFactoryWithArgs(argc, argv);
  m_participant = dpf->create_participant(m_domainID, PARTICIPANT_QOS_DEFAULT, 
                         DDS::DomainParticipantListener::_nil(), 
                         OpenDDS::DCPS::ALL_STATUS_MASK); 
  // create publishers and subscribers
}
```

**Destructor**
```C++
{
  // delete publishers and subscribers
  DDS::DomainParticipantFactory_var dpf = TheParticipantFactory;
  if (!CORBA::is_nil(m_participant.in()))
  {
    m_participant->delete_contained_entities();
    if (!CORBA::is_nil(dpf.in()) ) 
    {
      dpf->delete_participant(m_participant); 
    }
  }
  {
    TheServiceParticipant->shutdown();
    TheTransportRegistry->release();
    ACE::fini();
  }
}
```

The first time I use the object, everything is fine, But when it gets deleted and try to recreate the object **for the second time**, in the constructor, it says:
```
(7879|7879) ERROR: Service_Participant::load_discovery_configuration Unable to load libraries for rtps_discovery
(7879|7879) ERROR: DomainParticipantImpl::enable, no repository found for domain id: 1066.
(7879|7879) ERROR: DomainParticipantFactoryImpl::create_participant, unable to enable DomainParticipant.
```

Am I doing something wrong?
Is this an OpenDDS bug?

Thanks

**Comment by mitza-oci** [comment]
Is there a reason you can use the same techniques as the restart test you referenced?

**Comment by yosoufe** [comment]
@mitza-oci I need to pass a config file with `TheParticipantFactoryWithArgs` I could not mix the test with `TheParticipantFactoryWithArgs`. Do you have any sample for that?
I use `TheParticipantFactoryWithArgs` with `-DCPSConfigFile` argument.

**Comment by yosoufe** [comment]
I am not using OpenDDS any more. I am closing this.
