### ISSUE TITLE
how to reference corba::TimeT in modeling sdk?

### ISSUE THREAD

**Issue by jhenchen** [objectcomputing/OpenDDS#1305]
hello everyone!
I'm modeling my application in opendds modeling sdk, and some data types need time stamp.I want to maintain my model in modeling sdk other than idl files.So how to reference corba types in modeling sdk? 
Thanks!

**Comment by mitza-oci** [comment]
I don't think this is currently supported.  Since TimeT is just a typedef, defining your own typedef results in compatible data types.
