### ISSUE TITLE
create_participant takes ages to come back

### ISSUE THREAD

**Issue by nashorn123** [objectcomputing/OpenDDS#1340]
Dear all. 
I am using Open DDS under Linux and windows (here with the DCPSInfoRepo and the Simple Pub/Sub example coming with OpenDDS 3.13.2) and have the following problem:
I have tested on serveral computers (win&linux) and on exactly one windows computer i have a problem which i cannot solve: 
Whenever this computer is running the DCPSInfoRepo the create_participant() function  on the this specific computer but also on all other computers in the network take several minutes (!!) to come back. Amazingly after create_participant is done everything works normally (pub/sub) also pub/sub on this specific computer. 
As said before this holds true also for the example delivered with OpenDDS 3.13.2. 
If i run the DCPSInfoRepo somewhere else, the create_participant on all computers except this single computer work fine. On this specific  computer it takes again minutes to get a response. Afterwards the communication again -also here- works fine.
I disabled anti-virus software and firewall. I also verified to have same windows version.
Any idea what could cause this?
Any help is appreciated
Thank you very much
christian

**Comment by nashorn123** [comment]
sorry - i mixed up versions- i tested for **3.13.2** (not 3.12)

**Comment by mitza-oci** [comment]
What do the OpenDDS debug logs show?  You can include -ORBDebugLevel to get the TAO log messages as well.  Using Wireshark, do you see TCP connections refused/retried?

**Comment by nashorn123** [comment]
Dear Adam thanks for your response. In the meanwhile i found out that it probably has nothing to do with DDS, there is a thunderbold box involved, if i remove it and connect the computer directly things work fine, may some driver issue. Strange only that there are no other problems with this computer. I will check out and let you know.... best regards Christian
