### ISSUE TITLE
Connecting 2 Machines using OpenDDS

### ISSUE THREAD

**Issue by zgabriellez** [objectcomputing/OpenDDS#1353]
Hi,
I'm very new to OpenDDS - and programming in general - and I'm trying to connect 2 hosts: one is a server and the subscriber, and the other one is a publisher both Ubuntu 18.04 and 19.04(a VM), they are in the same network. I'm also using the Messenger example and the IntroductionToOpenDDS one. 
However, as I'm trying, I seem to fail using and manipulating the .ini file for them to communicate to each other, as it follows: 

my ini file: 
[common]
DCPSDebugLevel=0
DCPSInfoRepo=corbaloc::localhost::12345/DCPSInfoRepo
DCPSGlobalTransportConfig=config1

[config/config1]
transports=udp1

[transport/udp1]
transport_type=udp

And I use the sintax: 
./publisher -DCPSConfigFile conf.ini

I have also tried to use spdp, but failed in doing so.

**Comment by mitza-oci** [comment]
If both machines are pointed to `localhost` as their location of DCPSInfoRepo, that's not going to work.
This link may help: https://opendds.org/faq.html#general-connections

**Comment by iguessthislldo** [comment]
I'm marking this as closed since it appears she is satisfied with [my answer on stackoverflow](https://stackoverflow.com/q/58676843/9189546).
