### ISSUE TITLE
Compile OpenDDS on different folders for 32 and 64 bit

### ISSUE THREAD

**Issue by mariomastrodicasa** [objectcomputing/OpenDDS#1361]
I tried to find configuration parameters to instruct OpenDDS to build for both 32 and 64 bit, but in any case the deploy folder is the same. So 32 bit overwrite 64 bit and viceversa.
Which is the correct configuration parameters to instruct compilers to build to something like lib (32 bit) and lib64 (64 bit)?

**Comment by mitza-oci** [comment]
Which OS and compiler?

**Comment by mariomastrodicasa** [comment]
Excuse me for the missing information.
Now I'm building OpenDDS on Windows 10, Visual Studio 2015.
The version I'm using is the latest one: 3.13.3.
Do you need other information?
I'm thinkng the problem is in some parameters I'm missing during configuration phase or OpenDDS is not able to compile both 32/64 bit vrsion at the same time.

**Comment by mitza-oci** [comment]
We have done this for Linux (actually any GNU Make-based build), but not yet for Visual Studio.  We can look into how to customize those build variables.  Do you need separate exes or just separate dlls?

**Comment by mariomastrodicasa** [comment]
My actual need is that my MPC project is able to generate visual studio project targeted for 32 and 64 bit. Since my project links to OpenDDS DLLs (plus ACE/TAO DLLs) the primary needs is to have ready DLLs targeted for 32 and 64 bit. About the exe of OpenDDS: using my knowledge it is not a problem to have only 32 bit version; MPC generate Visual Studio projects and they use opendds_idl.exe and tao_idl.exe, both can run in 32 bit mode to convert IDLs into C++ files.
In my personal vision: it can be usesul to generate all EXEs (not only the one I highlighted before) in both 32 and 64 bit to have an homogeneous installation.

**Comment by mitza-oci** [comment]
This worked for me in a limited test.  Make sure to also adjust `PATH` so that `tao_idl` and `opendds_idl` can load the DLLs they need.
```
%ACE_ROOT%\bin\mwc.pl -type vc14 -value_template Win32::dllout=%CD%\lib32 -value_template x64::dllout=%CD%\lib64 DDS_TAOv2.mwc
```
If using the `configure` script, the `--mpcopts` parameter can be used to adjust how `configure` runs MPC.

**Comment by mitza-oci** [comment]
I missed one thing here... it turns out that `libout` is still used for the import library (such as `ACEd.lib`), so that variable can be set the same way as `dllout`.
