### ISSUE TITLE
DockerHub documentation links are not found

### ISSUE THREAD

**Issue by Cingulara** [objectcomputing/OpenDDS#1376]
https://hub.docker.com/r/objectcomputing/opendds/ 

This looks like it is the README.md in GitHub and has GitHub links that are local that do not work in DockerHub.

**Comment by iguessthislldo** [comment]
Interesting. I don't think we should change the README file that's intended for Github. Dockerhub doesn't even support the anchor links in the table of contents. @jrw972, how the README on Dockerhub work? Does it do this automatically like Github does or can we give it a specific file? Maybe we could make a small Dockerhub specific README.

**Comment by Cingulara** [comment]
When I did my DockerHub readme on my containers, I had to put the text in there. They use MD type of markdown but links don't work that are GH relative like the GH issue link, problem report link, etc. I saw.

I pulled down the container to test locally this week and just happen to click on some figuring they would go back to GH.

**Comment by mitza-oci** [comment]
I updated it on DockerHub, however DockerHub's help says:
> If automated build is enabled, readme will be synced from the source code repository on successful build.

... so it may change back (?).  I'm open to suggestions from anyone who knows how this should work.
