### ISSUE TITLE
Question: publisher-subscriber at the same time

### ISSUE THREAD

**Issue by zgabriellez** [objectcomputing/OpenDDS#1393]
Hi guys, 
I'm new to OpenDDS and I'm trying to use it in a Internet of Vehicles scenario. So, as we have cars, they will always be publishing information - to the infrastructure or to other cars - and they will also be receiving information. 
I've been thinking in that and searching a little, but I didn't find anything on OpenDDS about it, so I would like some help.
My idea is that a publisher is a writer and a subscriber is a reader, so I would use both of their base-codes to create a pub/sub that is both a writer and reader - all that in a condicional case. 

Thanks in advance.

**Comment by mitza-oci** [comment]
I'm not sure I completely understand the question, but the DDS DCPS API is based on the idea that you, as the application developer, can create whichever Entity objects you need (DomainParticipant, Topic, Publisher, Subscriber, DataWriter, DataReader).
If you'd like to learn more, please consider joining one of our online training sessions next week: https://opendds.org/news/2019/09/20/online-training.html
