### ISSUE TITLE
OpenDDS not compiling in Arch Linux at the moment

### ISSUE THREAD

**Issue by G-Pereira** [objectcomputing/OpenDDS#1394]
Hello, I don't know if this is the way to ask this but I've seen your post on AUR opendds package page and you said to open an issue here when needed.
It happens that opendds is not compiling at the moment and I've tried also with version 3.13.3 (version in AUR is outdated) and it doesn't work.
From my understanding, the linux kernel dropped support for streams and now it doesn't compile because of that. The error message is:
```
fatal error: stropts.h: No such file or directory
```
Can you help me debug it? And if possible update it.

**Comment by G-Pereira** [comment]
I am the maintainer of opendds package on AUR

**Comment by G-Pereira** [comment]
I am the maintainer of opendds package on AUR as you are @iguessthislldo

**Comment by iguessthislldo** [comment]
Sorry, I've not been keeping up with the AUR package since I don't use Arch much anymore, I know it's out of date though. The good new is there is a single line fix for this in https://github.com/DOCGroup/ACE_TAO/pull/939. Bad news is that this hasn't made it into the latest version of OCI ACE/TAO, which is what the opendds AUR package is currently using. So there are at least are two options:

1. Package a patch with the AUR package until the next OCI ACE/TAO is released.
2. Have the AUR package download [DOC Group ACE/TAO](https://github.com/DOCGroup/ACE_TAO) instead. The latest release of that does have the fix for this.

**Comment by jwillemsen** [comment]
I would be in favor of using the DOC Group ACE/TAO, makes it also easier for us to package next year [AXCIOMA](http://www.axcioma.org) with OpenDDS integraton

**Comment by jwillemsen** [comment]
When you use https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-6_5_7/ACE+TAO-src-6.5.7.tar.gz you can reduce https://aur.archlinux.org/cgit/aur.git/tree/build.patch?h=opendds to not patch CIAO/DAnCE, these are not part of that package

**Comment by mitza-oci** [comment]
> 
> 
> Hello, I don't know if this is the way to ask this but I've seen your post on AUR opendds package page and you said to open an issue here when needed.
> It happens that opendds is not compiling at the moment and I've tried also with version 3.13.3 (version in AUR is outdated) and it doesn't work.
> From my understanding, the linux kernel dropped support for streams and now it doesn't compile because of that. The error message is:
> 
> ```
> fatal error: stropts.h: No such file or directory
> ```
> 
> Can you help me debug it? And if possible update it.

Which version of glibc are you using?  I think that's the upstream change that broke ACE.

**Comment by iguessthislldo** [comment]
> I would be in favor of using the DOC Group ACE/TAO, makes it also easier for us to package next year AXCIOMA with OpenDDS integraton

Ideally I would like it to rely on the [`ace`](https://aur.archlinux.org/packages/ace) and [`tao`](https://aur.archlinux.org/packages/tao), but `opendds_idl` makes that hard. Also those packages are out of date as well.

> Which version of glibc are you using? I think that's the upstream change that broke ACE.

Arch is at [2.30](https://www.archlinux.org/packages/core/x86_64/glibc/) right now, so it's definitely the same problem I linked to.

**Comment by jwillemsen** [comment]
Hmm, upgrading ace/tao should be easy, preferable update the download URL to github and a newer release version

**Comment by mitza-oci** [comment]
> > Which version of glibc are you using? I think that's the upstream change that broke ACE.
> 
> Arch is at [2.30](https://www.archlinux.org/packages/core/x86_64/glibc/) right now, so it's definitely the same problem I linked to.

My point here is that this is not specific to Arch Linux.  Any system that uses the impacted version of glibc is affected.  The title and description of an issue should say so.  That is to help others who are impacted but not using Arch Linux.

**Comment by mitza-oci** [comment]
I don't know of any change to be made to this repository to address the issue, since it's an ACE/glibc incompatibility.

**Comment by iguessthislldo** [comment]
> When you use https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-6_5_7/ACE+TAO-src-6.5.7.tar.gz you can reduce https://aur.archlinux.org/cgit/aur.git/tree/build.patch?h=opendds to not patch CIAO/DAnCE, these are not part of that package

One of my goals was removing the need for the patch file entirely.

> I don't know of any change to be made to this repository to address the issue, since it's an ACE/glibc incompatibility.

Yes that is true, I will make the change the AUR package to use DOC Group.

**Comment by iguessthislldo** [comment]
**Update to this:** I've updated the `opendds` AUR package to use DOC Group ACE/TAO. It took me a while to get around to because I had to fix some issues with my Arch installation. Also it's a little scary to have to do a `pacman -Syu` after about a year.

> When you use https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-6_5_7/ACE+TAO-src-6.5.7.tar.gz you can reduce https://aur.archlinux.org/cgit/aur.git/tree/build.patch?h=opendds to not patch CIAO/DAnCE, these are not part of that package

@jwillemsen Yes I pulled out those patches.
