### ISSUE TITLE
Support of DDS-XTypes 1.2

### ISSUE THREAD

**Issue by rnareddy646** [objectcomputing/OpenDDS#1397]
Hello,

I would like to ask if the Open DDS implementation supports any of the
Extensible and Dynamic Topic Types for DDS as seen in the
https://www.omg.org/spec/DDS-XTypes/1.2

Please help us on this , we are trying to check interoperability test between different vendors to see if this supports.
Thanks 
Sudharsan

**Comment by mitza-oci** [comment]
OpenDDS (master branch, will soon be 3.14) has XTypes annotations support.  Other features are planned for upcoming releases.  Which features of XTypes are you looking to use?
