### ISSUE TITLE
Does OpenDDS support type inheritance (XTypes)

### ISSUE THREAD

**Issue by subhamdas88** [objectcomputing/OpenDDS#1409]
I came across the section in OMG Xtype spec which talks about type inheritance.
(7.2.1.2 Type Inheritance Example).
Does OpenDDS support features like this?

Scenario I am looking at is as below
Two applications appA  appB currently communicate using  BaseType.
appA wants to increase the fields in the type for some purpose.
When appA  dev creates an inherited type DerivedType , I want appA still to be able to communicate with appB.

If any other way is there to achieve this scenario is also fine.

Reagards,
Subham

**Comment by mitza-oci** [comment]
These parts of XTypes are not yet implemented in OpenDDS.  We are continuing to add features and these are among those that we are targeting.  We have some features scheduled for addition in the near future as part of a funded project.  If you or your organization would like to do this same, please see https://objectcomputing.com/products/opendds/consulting-support.  We can also review and accept code contributions, but for XTypes we need to get some of the foundational components in first.
