### ISSUE TITLE
opendds_idl union type generation

### ISSUE THREAD

**Issue by vladfux4** [objectcomputing/OpenDDS#1417]
I've faced with issue during generation of support code for union type, that is not intended to be attached to any topic, with `--default-nested` option
For example for one like this:
```
union Foo switch(long) {
  case 0: long foo_0;
  case 1: long foo_1;
};
```
```
$ opendds_idl --default-nested union.idl 
```
When I am trying to compile `*TypeSupportImpl.cpp`, it fails due to `MetaStruct` type incompleteness in that translation unit.
Looks like include for that type is missed in generated code.

opendds_idl input and output files are in attachment.
[files.zip](https://github.com/objectcomputing/OpenDDS/files/3989226/files.zip)

**Comment by mitza-oci** [comment]
There should be a number of `#include` lines at the top of the TypeSupportImpl.cpp.  Compare to what's generated in the Messenger test, for example.

**Comment by vladfux4** [comment]
Thanks for info. Probably I've found the root cause. `#include "dds/DCPS/FilterEvaluator.h"`, where `MetaStruct` is defined, missed there. I fixed it locally, will prepare PR.
