### ISSUE TITLE
macro naming conflict with other libraries

### ISSUE THREAD

**Issue by xieshuaix** [objectcomputing/OpenDDS#1433]
The following macro in dds/DCPS/Definitions.h is not namespace guarded and causes naming conflicts when using your library with popular ones including boost, torch (C++ distributions of PyTorch), etc. Could you please fix this? Thanks.

```
#define DUP true
#define NO_DUP false
```

**Comment by iguessthislldo** [comment]
By "namespace guarded", I assume you mean that the macros should be called something like `OPENDDS_DUP`. We have do have a rule that says that for the reasons you described and this is breaking that rule. Thanks for pointing it out.

As for fixing it I think we should probably just get rid of the macros all together and have the callers use true and false.

**Comment by mitza-oci** [comment]
@xieshuaix please create a PR to remove it

**Comment by xieshuaix** [comment]
> @xieshuaix please create a PR to remove it

Done. Please check the PR: [https://github.com/objectcomputing/OpenDDS/pull/1442](url)

**Comment by iguessthislldo** [comment]
I'm closing this because of #1442 was merged. From #1366 I can see there are other macros that don't follow the `OPENDDS` rule, but this what the shortest I think.
