### ISSUE TITLE
Adding sequence of octets causes SEGV in tests/DCPS/messenger

### ISSUE THREAD

**Issue by seanrowens** [objectcomputing/OpenDDS#1462]
1) Versions;

a) OS X; Note, that this error first happened with the previous
version of OS X, but I've upgraded since then and before preparing
this report.

OS X 10.15.2

```
MacBook-Pro:~ sean$ uname -a
Darwin MacBook-Pro.fios-router.home 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
MacBook-Pro:~ sean$
```

b) C compiler version;

```
MacBook-Pro:~ sean$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
MacBook-Pro:~ sean$ 
```

2) Download OpenDDS-3.13.3.tar.gz, extract it, open a shell, cd into
that dir, do "configure --java", then "make".  Note, while I'm
compiling with Java, the test program I'm using/altering,
DCSP/messenger, does not use Java.

3) Source setenv.sh, then cd into tests/DCPS/messenger and run;

run_tests.pl

and check the output to see no SEGV, verify that messages were
exchanged.

4) Add a sequence of octets to the IDL file;

OpenDDS-3.13.3/tests/DCPS/Messenger/Messenger.idl

a) If I add the sequence of octets directly to the Messenger struct
and run make then I get this error;

```
/Users/sean/OpenDDS-3.13.3/bin/opendds_idl -Sa -St -Wb,export_macro=Messenger_Export Messenger.idl
Error - /Users/sean/OpenDDS-3.13.3/bin/opendds_idl: "Messenger.idl", line 20: Error: anonymous types are deprecated by OMG spec
processing Messenger.idl
/Users/sean/OpenDDS-3.13.3/bin/opendds_idl: Messenger.idl: found 1 error
make[1]: *** [MessengerTypeSupportImpl.cpp] Error 2
make: *** [DDS_Messenger_Idl] Error 2
bash-3.2$ 
```

b) Therefore add this typedef;

  typedef sequence <octet, 102400> FrameBuf;

c) Add this field to Message struct;

```
    FrameBuf buf;
```

resulting in:

```
/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module Messenger {

  typedef sequence <octet, 102400> FrameBuf;

#pragma DCPS_DATA_TYPE "Messenger::Message"
#pragma DCPS_DATA_KEY "Messenger::Message subject_id"

  struct Message {
    string from;
    string subject;
    long subject_id;
    string text;
    long   count;
    FrameBuf buf;
  };
};
```

d) Run 'make' in the top dir, compiles without errors.  

5) Source setenv.sh, then cd into tests/DCPS/messenger and run;

run_tests.pl

and check the output to see the following error;

```
bash-3.2$ ./run_tests.[K[K.pl
/Users/sean/Documents/perceptronics/ATEAM/OpenDDS-3.13.3/bin/DCPSInfoRepo -ORBDebugLevel 1 -ORBLogFile DCPSInfoRepo.log  -o repo.ior -DCPSPendingTimeout 3 
InfoRepo PID: 45895
/Users/sean/OpenDDS-3.13.3/tests/DCPS/Messenger/subscriber -ORBDebugLevel 1 -DCPSConfigFile sub.ini -DCPSDebugLevel 4 -ORBVerboseLogging 1 -DCPSTransportDebugLevel 2 -ORBLogFile subscriber.log -DCPSPendingTimeout 3 
subscriber PID: 45896
/Users/sean/OpenDDS-3.13.3/tests/DCPS/Messenger/publisher -ORBDebugLevel 1 -DCPSConfigFile pub.ini -DCPSDebugLevel 4 -ORBVerboseLogging 1 -DCPSTransportDebugLevel 2 -ORBLogFile publisher.log -DCPSPendingTimeout 3 
publisher PID: 45897
Starting publisher
Starting publisher with 1 args
Reliable DataWriter
Creating Writer
Starting Writer
Transport is RELIABLE
Reliable DataReader
ERROR: <publisher> exited with signal 11 : SEGV
2020-01-20 20:30:27: ERROR: publisher returned 255 (started at 2020-01-20 20:30:26)
ERROR: received 0 messages, but expected 40
ERROR: <subscriber> failed: No such file or directory
2020-01-20 20:30:32: ERROR: subscriber returned 255 (started at 2020-01-20 20:30:27)
```

[opendds_tests_dcps_messenger_unaltered.txt](https://github.com/objectcomputing/OpenDDS/files/4088796/opendds_tests_dcps_messenger_unaltered.txt)
[opendds_tests_dcps_messenger_with_sequence_inline.txt](https://github.com/objectcomputing/OpenDDS/files/4088797/opendds_tests_dcps_messenger_with_sequence_inline.txt)
[opendds_tests_dcps_messenger_with_sequence_typedef.txt](https://github.com/objectcomputing/OpenDDS/files/4088798/opendds_tests_dcps_messenger_with_sequence_typedef.txt)

**Comment by simpsont-oci** [comment]
Did you run 'make depend' at any point? The generated code will change
based on your idl changes, but code that depends on the generated headers
won't know it needs to be recompiled unless you've generated the makefile
dependencies.

**Comment by mitza-oci** [comment]
In this case I don't think "make depend" matters.  The timestamps on the changed files are enough to get it to build.
This problem may be related to allocation based on the sequence bound.  Try an unbounded sequence, or one with smaller bounds, and see how it compares.  Pre-allocated buffers are configurable by changing parameters -- however there may be a bug since the overall struct is not bounded.

**Comment by mitza-oci** [comment]
> In this case I don't think "make depend" matters. The timestamps on the changed files are enough to get it to build.

Now that I've looked at it some more... there are cases where template/inline code from the generated headers gets included into the user-provided cpp.  It's certainly worth a try to explicitly clean (just that test directory is sufficient) or generate dependencies.

**Comment by seanrowens** [comment]
Make clean/make depend does seem to fix the problem in the messenger test.

I originally had this problem trying to build a similar message using Java,
it causes a FATAL ERRORl

FATAL ERROR in native method: Non-array passed to JNI array operations\
at Messenger._MessageDataWriterTAOPeer.register_instance(Native Method)
at TestPublisher.main(TestPublisher.java:161)

I chose to use the non java test to provide a minimal test case mainly
because in the java/tests/messenger Messenger.idl there is a comment;

// This must match the Messenger.idl in the DDS distribution,
// but the file is copied here to more accurately reflect a
// user's project setup.

But I can't figure out which of the 96 copies of Messenger.idl in the
distribution should be modified.

On Tue, Jan 21, 2020 at 9:13 AM Adam Mitz <notifications@github.com> wrote:
>
> In this case I don't think "make depend" matters. The timestamps on the
changed files are enough to get it to build.
>
> Now that I've looked at it some more... there are cases where
template/inline code from the generated headers gets included into the
user-provided cpp. It's certainly worth a try to explicitly clean (just
that test directory is sufficient) or generate dependencies.

**Comment by mitza-oci** [comment]
In the 3.13.x branch it's `tests/DCPS/Messenger`.  This is what the scripts in `java/tests/messenger/publisher` (for example) refer to.

**Comment by seanrowens** [comment]
Many thanks!  I've altered the .idl in both java/tests/messenger and in tests/DCPS/Messenger in the same way, ran make clean, make depend, and make in both directories, the test/DCPS/Messenger directory first.   When I fire up run_test.pl in  java/tests/messenger I get;

FATAL ERROR in native method: Non-array passed to JNI array operations
	at Messenger._MessageDataWriterTAOPeer.register_instance(Native Method)
	at TestPublisher.main(TestPublisher.java:161)

Logs of both builds and the run attached.
[opendds_3_13_3_tests_dcps_messenger_build.txt](https://github.com/objectcomputing/OpenDDS/files/4113031/opendds_3_13_3_tests_dcps_messenger_build.txt)
[opendds_3_13_3_java_tests_messenger_build.txt](https://github.com/objectcomputing/OpenDDS/files/4113032/opendds_3_13_3_java_tests_messenger_build.txt)
[opendds_3_13_3_java_tests_messenger_run.txt](https://github.com/objectcomputing/OpenDDS/files/4113033/opendds_3_13_3_java_tests_messenger_run.txt)

**Comment by mitza-oci** [comment]
When you change the IDL, you have to change the code that uses the classes generated from IDL:
```
    159         Message msg = new Message();
    160         msg.subject_id = 99;
    161         int handle = mdw.register_instance(msg);
```
If object `msg` has a new field, make sure to initialize that field before passing it to an IDL operation.

This is in the java-specific FAQ as "I'm seeing a null pointer exception or a JVM crash in an OpenDDS native method.  What should I check first?"

**Comment by seanrowens** [comment]
My apologies, I started from a fresh extract of the tarball, altering the two IDL files and TestPublisher.java to fill in the field, and I'm still getting a FATAL ERROR albeit in a different location, presumably in the TestSubscriber;

FATAL ERROR in native method: Non-array passed to JNI array operations
	at Messenger._MessageDataReaderTAOPeer.take_next_sample(Native Method)
	at DataReaderListenerImpl.on_data_available(DataReaderListenerImpl.java:45)
	- locked <0x000000076ad903b0> (a DataReaderListenerImpl)


[opendds_3_13_3_take_2_configure.log](https://github.com/objectcomputing/OpenDDS/files/4119998/opendds_3_13_3_take_2_configure.log)
[opendds_3_13_3_take_2_make.log](https://github.com/objectcomputing/OpenDDS/files/4119999/opendds_3_13_3_take_2_make.log)
 [opendds_3_13_3_take_2_compare.log](https://github.com/objectcomputing/OpenDDS/files/4120000/opendds_3_13_3_take_2_compare.log)
[opendds_3_13_3_take_2_run.log](https://github.com/objectcomputing/OpenDDS/files/4120003/opendds_3_13_3_take_2_run.log)

**Comment by mitza-oci** [comment]
Did you change the code in DataReaderListenerImpl? Same principle applies

**Comment by seanrowens** [comment]
Aha, did not realize that.  Thanks yep, everything seems to work now.
Thanks very much.
