### ISSUE TITLE
Problem of building with static link

### ISSUE THREAD

**Issue by XiaoLeS** [objectcomputing/OpenDDS#1604]
Hi, 

I'm now trying to build the Messenger example with static link to the library. I have try to add the `-static` flag of gcc to the `CMakeList.txt` with following cmake instruction.
```
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
```
And then, I build the Messenger example with following process.
```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/home/my/opendds/src/tree ..
cmake --build .
```
The error message shows as following
```
[  5%] Linking CXX executable publisher
/usr/bin/ld: attempted static link of dynamic object `/home/xiaole/DDS/OpenDDS/OpenDDS_src/lib/libOpenDDS_Dcps.so'
collect2: error: ld returned 1 exit status
CMakeFiles/publisher.dir/build.make:228: recipe for target 'publisher' failed
make[2]: *** [publisher] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/publisher.dir/all' failed
make[1]: *** [CMakeFiles/publisher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
If I remove the static flag setting, the building process will be successfully completed. But I need the library to be build with static library link.

I have tried to configure and build the OpenDDS libraries with following instructions.
```
./configure --static
make
```
However, the static build of the Messenger example still got the same error message.

I am working on Ubuntu 18.04 and OpenDDS 3.14.
Cloud you please help me for this problem? Thanks in advance!

XiaoLe

**Comment by ClaytonCalabrese** [comment]
I think your build directory might be in a bad state. Please try a fresh install.

I attempted a clean build on OpenDDS 3.14 with the static flag and it worked. 

If you follow these instructions it should work:

./mkdir ~/staticopendds
cd ~/staticopendds
git clone https://github.com/objectcomputing/OpenDDS.git -b DDS-3.14
cd OpenDDS
./configure --static
make
source setenv.sh
cd DevGuideExamples/DCPS/Messenger
./run_test.pl


Please let me know if this does not work.

**Comment by XiaoLeS** [comment]
> I think your build directory might be in a bad state. Please try a fresh install.
> 
> I attempted a clean build on OpenDDS 3.14 with the static flag and it worked.
> 
> If you follow these instructions it should work:
> 
> ./mkdir ~/staticopendds
> cd ~/staticopendds
> git clone https://github.com/objectcomputing/OpenDDS.git -b DDS-3.14
> cd OpenDDS
> ./configure --static
> make
> source setenv.sh
> cd DevGuideExamples/DCPS/Messenger
> ./run_test.pl
> 
> Please let me know if this does not work.


I have just followed your instructions and after running `./run_test.pl`, I got the error message as following:
```
/home/xiaole/staticopendds/OpenDDS/bin/DCPSInfoRepo -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
/home/xiaole/staticopendds/OpenDDS/bin/DCPSInfoRepo: error while loading shared libraries: libOpenDDS_InfoRepoServ.so.3.14.0: cannot open shared object file: No such file or directory
ERROR: waiting for Info Repo IOR file
```
It seemed that it couldn't find the libraries, so I check the env ${LD_LIBRARY_PATH} and found it is empty. As the result, I set the ${LD_LIBRARY_PATH} to the `/home/xiaole/staticopendds/OpenDDS/lib`. But I got the same error with running `./run_test` again.

Please let me know if there is any additional details needed.
Thanks for your help!

**Comment by mitza-oci** [comment]
When you've completed a `--static` build there will be no `lib*.so*` files from ACE, TAO, OpenDDS.  Instead there will be `lib*.a` files.
Seems like you need to start from a completely fresh workspace with no environment variables set, and re-do it from the configuration step.

**Comment by XiaoLeS** [comment]
Thanks a lot! I have successfully build up statically linked version.
I think the main problem is the environment variables set and the instructions in above comments are just fine.
