### ISSUE TITLE
use mpc file build jar  was wrong

### ISSUE THREAD

**Issue by Make-Stlye-Change** [objectcomputing/OpenDDS#1611]
Hi.

I want bulid a self defined jar file .

When I was writed my idl file , and use tao_idl and opendds_idl to compile it ,everthing was all right .and i also use generate_export_file.pl command correct(that can generate .h file ) .

But when i use mwc.pl -type vc14 command to compile my mpc file,that was a error . it shows a error :No workspace was defined!
error :Unabel to process:UserManager.mpc

My  enviroment is windows 7 x64 .  vs2015. opendds 3.13.3

The error file in the attach file .

I need your help,thak you!

![error](https://user-images.githubusercontent.com/11957996/77937062-5e65dd00-72e6-11ea-8e21-f9b453b19ffd.PNG)

**Comment by jwillemsen** [comment]
You have a mpc file (just one project), so use `mpc.pl` instead of `mwc.pl`

**Comment by Make-Stlye-Change** [comment]
> ad

Thanks you for answer!

I use mpc.pl instead of mwc.pl . the command line shows it requires java. and that don't generate jar package.

I already config the enviroment of java(jdk 1.8).  did i miss some configurating?

![mpl](https://user-images.githubusercontent.com/11957996/77977555-9266ef80-7332-11ea-9f97-05778177ece9.PNG)

**Comment by Make-Stlye-Change** [comment]
> You have a mpc file (just one project), so use `mpc.pl` instead of `mwc.pl`

Thanks you for answer!

I use mpc.pl instead of mwc.pl . the command line shows it requires java. and that don't generate jar package.

I already config the enviroment of java(jdk 1.8). did i miss some configurating?
![mpl](https://user-images.githubusercontent.com/11957996/77978171-f342f780-7333-11ea-8c3a-7f2c4dddca75.PNG)

**Comment by iguessthislldo** [comment]
Try passing `-features java=1` to mpc.

**Comment by Make-Stlye-Change** [comment]
> If you want a "workspace" to be created, which for VS means a solution file, you should indeed use `mwc.pl`. You don't need to specify a `.mpc` file name on the command line since the default workspace is the current directory.

Thanks your answer!

I try this method.

**Comment by Make-Stlye-Change** [comment]
> Try passing `-features java=1` to mpc.

Thanks.

I try it.

**Comment by mitza-oci** [comment]
> 
> 
> > Try passing `-features java=1` to mpc.
> 
> Thanks.
> 
> I try it.

This is not necessary if OpenDDS is configured with Java support.  To help diagnose problems with the configuration process, please run `tools\scripts\show_build_config.pl` and paste the results in to your reply.

**Comment by Make-Stlye-Change** [comment]
> process



> > > Try passing `-features java=1` to mpc.
> > 
> > 
> > Thanks.
> > I try it.
> 
> This is not necessary if OpenDDS is configured with Java support. To help diagnose problems with the configuration process, please run `tools\scripts\show_build_config.pl` and paste the results in to your reply.

This is the result of run the show_build_config.pl
Please to take a look.

![script](https://user-images.githubusercontent.com/11957996/78089055-b856c780-73f8-11ea-87dd-ab6324d0cc4c.PNG)

**Comment by Make-Stlye-Change** [comment]
> Try passing `-features java=1` to mpc.

I use the -features java=1 on my mpc command .
That happened some errors .

**Comment by Make-Stlye-Change** [comment]
> Try passing `-features java=1` to mpc.

I use the -features java=1 on my mpc command line.
That happened some errors .

![java error](https://user-images.githubusercontent.com/11957996/78089228-534fa180-73f9-11ea-9a23-ee36ddf513dc.PNG)

I checked my dds directory . it has no file like :DdsDcpsInfrastructureCJ.h ...
Is  this mean my opendds java support configure was wrong?

**Comment by iguessthislldo** [comment]
> This is the result of run the show_build_config.pl
Please to take a look.

That looks like end of the contents of `tools/scripts/setenv.sh`.

@mitza-oci: It looks like this is what it does when the script is run from `tools/scripts`. Maybe we could make it more a little more aware of where it's being run or at least do more error checking since it does little now. Also we could remove the setenv files in tools/scripts since I don't think they're being used.

@Make-Stlye-Change: Could you run it from the OpenDDS source directory, so you have to run `perl tools\scripts\show_build_config.pl`?

> I checked my dds directory . it has no file like :DdsDcpsInfrastructureCJ.h ...
Is this mean my opendds java support configure was wrong?

Yes, that's what it looks like.

**Comment by Make-Stlye-Change** [comment]
> > This is the result of run the show_build_config.pl
> > Please to take a look.
> 
> That looks like end of the contents of `tools/scripts/setenv.sh`.
> 
> @mitza-oci: It looks like this is what it does when the script is run from `tools/scripts`. Maybe we could make it more a little more aware of where it's being run or at least do more error checking since it does little now. Also we could remove the setenv files in tools/scripts since I don't think they're being used.
> 
> @Make-Stlye-Change: Could you run it from the OpenDDS source directory, so you have to run `perl tools\scripts\show_build_config.pl`?
> 
> > I checked my dds directory . it has no file like :DdsDcpsInfrastructureCJ.h ...
> > Is this mean my opendds java support configure was wrong?
> 
> Yes, that's what it looks like.

@mitza-oci @iguessthislldo When I run from source directory.the result turns like below
![1](https://user-images.githubusercontent.com/11957996/78092003-1687a880-7401-11ea-88e4-12f9fdca9b3b.PNG)

@iguessthislldo How did I configure java support ? I rebuild the opendds many times(follow the install instruction), the VS 2015 x64 command prompt command : cd $DDS_ROOT ; configure --java ; Build--Buid Solution.But there is still cannot compile mpc file with jar name .

@mitza-oci @iguessthislldo  By the way , this is my mpc file 
![2](https://user-images.githubusercontent.com/11957996/78092600-c3165a00-7402-11ea-8b8f-675e8a35e764.PNG)

**Comment by iguessthislldo** [comment]
You're just running `configure --java`? You will need to tell it where Java is. It should've complained about that.

**Comment by Make-Stlye-Change** [comment]
> It should've complained about that

Yes. I just running configure --java .
I am new for opendds. I need help.
If I want built opendds support  java , what command should I give ?
Thanks.

**Comment by Make-Stlye-Change** [comment]
> You're just running `configure --java`? You will need to tell it where Java is. It should've complained about that.

@iguessthislldo 
Yes. I just running configure --java .
I am new for opendds. I need help.
If I want built opendds support java , what command should I give ?
Thanks.

**Comment by mitza-oci** [comment]
> 
> 
> > You're just running `configure --java`? You will need to tell it where Java is. It should've complained about that.
> 
> @iguessthislldo
> Yes. I just running configure --java .
> I am new for opendds. I need help.
> If I want built opendds support java , what command should I give ?
> Thanks.

This process is documented here:
https://opendds.org/quickstart/GettingStartedWindows.html

There is a default for `configure --java` which applies when the JDK tools like `javac` are on the `PATH`.

**Comment by Make-Stlye-Change** [comment]
> > > You're just running `configure --java`? You will need to tell it where Java is. It should've complained about that.
> > 
> > 
> > @iguessthislldo
> > Yes. I just running configure --java .
> > I am new for opendds. I need help.
> > If I want built opendds support java , what command should I give ?
> > Thanks.
> 
> This process is documented here:
> https://opendds.org/quickstart/GettingStartedWindows.html
> 
> There is a default for `configure --java` which applies when the JDK tools like `javac` are on the `PATH`.

@mitza-oci  Thanks for you answer.
I already configured java enviroment, that include JAVA_HOME/CLASSPATH/PATH.
And javac are on the PATH.
This is my java test: Run a test Java application to verify the build 
![1](https://user-images.githubusercontent.com/11957996/78210415-b9f9bb80-74dc-11ea-963c-474f5ba46dc7.PNG)

But when I  bulid self defined java applycation(because it need jar package).
It occurred error : no dds/DdsDcpsInfraStructureJC.h
