### ISSUE TITLE
Android make_standalone_toolchain.py is obsolete in NDK r19+

### ISSUE THREAD

**Issue by kuzai** [objectcomputing/OpenDDS#1612]
Are there any plans to move to the new way that android attempts to make cross-compiling easier? https://developer.android.com/ndk/guides/other_build_systems

It looks like the big difference is targeting the correct version of the compiler based on the arguments (which android implies autoconf can handle)

**Comment by iguessthislldo** [comment]
This is technically more of a ACE/TAO issue, but yes eventually we do plan on supporting using the NDK directly. It should be noted that the standalone toolchains isn't obsolete and taking Google's wording literally, isn't even deprecated. Also we don't use autoconf, so what it does it doesn't affect us.

**Comment by kuzai** [comment]
Fair enough and good to hear! I was having trouble using the standalone toolchains that are generated from any NDK version above 18 which is what prompted my question

**Comment by mitza-oci** [comment]
I just used make_standalone_toolchain.py today, doesn't seem obsolete.  I understand that they'd like downstream users not to use it, however it is provided and it does seem to work.
I will close this issue since it needs to be changed in https://github.com/DOCGroup/ACE_TAO first.

**Comment by kuzai** [comment]
I will say that I was unable to get OpenDDS to cross compile with any standalone toolchain version >r18. Should I file a specific issue for that?

**Comment by mitza-oci** [comment]
> 
> 
> I will say that I was unable to get OpenDDS to cross compile with any standalone toolchain version >r18. Should I file a specific issue for that?

Yes, if you're following the steps in `android.md` and it's failing, we'd appreciate an Issue with all relevant details.

**Comment by iguessthislldo** [comment]
Support for building with Android NDK directly was added in ACE/TAO in https://github.com/DOCGroup/ACE_TAO/pull/1318 and https://github.com/DOCGroup/ACE_TAO/pull/1322 and directions for building OpenDDS in the same way is being added in #2296.
