### ISSUE TITLE
 What are these threads for? Debugging with GDB very simple OpenDDS application running over RTPS

### ISSUE THREAD

**Issue by BottCode** [objectcomputing/OpenDDS#1615]
I'm debugging with GDB the [StockQuoterUDPInfoRepo](https://github.com/objectcomputing/OpenDDS/tree/master/examples/DCPS/IntroductionToOpenDDS) example just for understanding what happen under the hood. Actually I've changed the configuration in order to use RTPS either for discovery and for transport protocol.

    [common]
    DCPSGlobalTransportConfig=$file
    DCPSDefaultDiscovery=DEFAULT_RTPS

    [transport/the_rtps_transport]
    transport_type=rtps_udp

Debugging the [publisher](https://github.com/objectcomputing/OpenDDS/blob/master/examples/DCPS/IntroductionToOpenDDS/publisher.cpp), GDB shows that there are 8 thread allocated (the first one is the main thread).

I need to understand what is the role of each thread, so lets see when they are allocated step-by-step.

1. [Main thread](https://github.com/objectcomputing/OpenDDS/blob/master/examples/DCPS/IntroductionToOpenDDS/publisher.cpp#L36) starts.

2. The execution of [this line](https://github.com/objectcomputing/OpenDDS/blob/master/examples/DCPS/IntroductionToOpenDDS/publisher.cpp#L43), which concerns the initialization of a DomainParticipant, allocate a new thread and GDB prints `[New Thread 0x7f76416cd700 (LWP 903)]`. GDB `info threads` prints the following:
![image](https://user-images.githubusercontent.com/16674092/78265931-651e6b00-7505-11ea-9f15-7b8c64505428.png)

So thread no. 2 is blocked on `select ()` syscall function. What is this thread waiting for?

3. The [participant creation](https://github.com/objectcomputing/OpenDDS/blob/master/examples/DCPS/IntroductionToOpenDDS/publisher.cpp#L45) allocates 4 new threads. Now GDB `info threads` prints the following:
![image](https://user-images.githubusercontent.com/16674092/78266416-0c030700-7506-11ea-8029-59ec3fdc7d1c.png)
What is the purpose of this threads? From the picture we can see that threads 3 and 5 are waiting on a condition variable, while threads 4 and 6 are blocked on `select ()`. What are they waiting for?
I guess that one of these new threads (threads no. 3-6) is the one who is in charge of periodically sends messages to announce the participant's presence on the network. If so, there must also be its "correspondent listener", i.e. the thread who is in charge of detect this kind of messages over the network. Isn't it? However, what I've just said explain only two out of four threads.
What about the two remaining? DDS and RTPS specification say that 4 built-in topics must be provided, and for each of them there are the related data reader and data writer. A _data reader/data writer_ is associated to a _Subscriber/Publisher_ (as DDS specification dictates). So, the two thread remaining could be these Subscriber and Publisher. 

4. The [application's data_writer creation](https://github.com/objectcomputing/OpenDDS/blob/master/examples/DCPS/IntroductionToOpenDDS/publisher.cpp#L123) allocates 2 new threads. Now GDB `info threads` prints the following:
![image](https://user-images.githubusercontent.com/16674092/78270100-af561b00-750a-11ea-9682-202a156e2183.png)
What are this threads useful for?

What is happening under the hood? Thanks in advance.

**Comment by mitza-oci** [comment]
Since you have all the source code available and running in the debugger, go ahead and break on thread creation to see the context of where a thread is started.  From there you can see if it is used to respond to events (network input, timers) or service a message queue, etc.

**Comment by mitza-oci** [comment]
Your initial post has some links to code at the application layer (for example, publisher.cpp), I'm suggesting you instead look into the implementation of the OpenDDS libraries.  Since you're already running in GDB that's a great tool for this exploration.  If there are specific questions about why certain implementation choices were made, we can try to answer those.

**Comment by mitza-oci** [comment]
Please let us know what we can add to this (see comment above), or if it should be closed.

**Comment by BottCode** [comment]
Sorry for the late.

I've discovered something about threads' purpose, but not everything yet.

- Thread **2** is what in ACE is called _reactor task_. Its purpose should be to listen and discover new participant in the domain. Not really sure about that.
- Thread **3** is what in OpenDDS is called _SEDP task_. It listen for SEDP traffic and performs associations between local and remote entities. 
- Thread **4** is another _reactor task_. What is its purpose? It seems it manages SPDP traffic, but this task should be accomplished by Thread **2**. Isn't it?
- Thread **5** is what in OpenDDS is called _QueueTaskBase_, i.e. [a task which manage a queue of messages/requests](https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/transport/framework/QueueTaskBase_T.h#L34).` What kind of requests? I've set various breakpoint its methods and what I've observed is:

    - [`int add(const T& req)`](https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/transport/framework/QueueTaskBase_T.h#L54) is never called. So there is never any request to handle.
    - When the worker thread execute its ["mainline"](https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/transport/framework/QueueTaskBase_T.h#L105), it is always blocked on [`this->work_available_.wait();`](https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/transport/framework/QueueTaskBase_T.h#L117) condition. When it restart, [`break`](https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/transport/framework/QueueTaskBase_T.h#L121) is always executed, so [`this->execute(req);`](https://github.com/objectcomputing/OpenDDS/blob/master/dds/DCPS/transport/framework/QueueTaskBase_T.h#L136) never is. Cannot figure out what this task is useful for.
- Thread **6** is another _reactor task_, no idea on its purpose.
- Thread **7** is a _reactor task_ and it is the writer's listener.
- Thread **8**, same of Thread **5**.

**Comment by mitza-oci** [comment]
The thread numbers listed are arbitrary, based on your particular debug session.  It's hard to use this to relate them to the parts of the code involved.

ACE's reactor class is well documented so that may be a good place to start some research.

I think you'll make more progress if you start with some specific questions about parts of the code.  As with all Issues, this is open to the entire user and maintainer community to discuss.  In other words, don't wait for me to reply.

(Also, GitHub doesn't notify on edits so I had no idea this post was here.)
