### ISSUE TITLE
Problem with setting the multicast_group_address in rtps.ini

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1627]
I was trying to change the multicast group address for my publisher to 239.255.255.250:1900 and I was trying to do it via the rtps.ini which looks like this:

```
[common]
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSGlobalTransportConfig=$file
use_multicast=1
multicast_group_address=239.255.255.250:1900
ttl=4

[transport/the_rtps_transport]
transport_type=rtps_udp
use_multicast=1
multicast_group_address=239.255.255.250:1900
ttl=4
```

However it seems that the change is not applied and my publisher keeps using the default_multicast_group_ address set in the RtpsDiscovery.cpp

Do you know why might that be?
Is there something obviously wrong in my rtps.ini configuration?

**Comment by mitza-oci** [comment]
The settings for customizing the RTPS Discovery behavior belong to their own section of the configuration file.  Please check the developer's guide for this.
