### ISSUE TITLE
Can not access libOpenDDS_Dcps.so.3.14.0 library when running as sudo

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1632]
I have a simple publisher-subscriber project that uses OpenDDS, and it works fine when run it without `sudo`, but I am getting the following error when I run it with `sudo`:

```
error while loading shared libraries: libOpenDDS_Dcps.so.3.14.0: cannot open shared object file: No such file or directory
```
PS
1. It is necessary for me to run my project with sudo

2. I run my project in a Debian machine

**Comment by mitza-oci** [comment]
If you are depending on `LD_LIBRARY_PATH` to locate shared libraries, you're probably seeing sudo interfere with that.  There are other ways to locate shared libraries, like rpath and ld.so.conf.  Or you can set up your sudo environment to have the LD_LIBRARY_PATH you need.
Also, you should try to avoid running as root.  Yes, I read item 1 in your post.

**Comment by KiriakosD** [comment]
Thanksf for the information @mitza-oci !
