### ISSUE TITLE
converting rti idl to opendds compatible ones

### ISSUE THREAD

**Issue by kashif68** [objectcomputing/OpenDDS#1635]
Anyone came across taking RTI idl files and ported/modified over to OpenDDS IDL?

For instance, RTI valuetype?

**Comment by mitza-oci** [comment]
Start by changing the valuetype to a struct

**Comment by kashif68** [comment]
thanks
experimenting with that now.

The problem is that RTI using inheritance! For example:
Not sure if interface will help?
module DDS_Messages{
 valuetype Ack : DDS_infrastructureservices::DDS_common::Message_T
  {
};
};

**Comment by mitza-oci** [comment]
We don't have support for IDL4 struct inheritance yet.  However, struct inheritance can be emulated by having the first member of the "derived" struct be the "base" struct.

**Comment by kashif68** [comment]
just curious about IDL4 do you have it planned to be implemented?

So, I can just do in the posted example:
struct Ack
{
    DDS_infrastructureservices::DDS_common::Message_T msg;
};
};

**Comment by mitza-oci** [comment]
> 
> 
> just curious about IDL4 do you have it planned to be implemented?

We will keep adding features from IDL4 and XTypes based on a combination of project needs and developer availability.  We'd welcome your help with this as well.


> So, I can just do in the posted example:
> struct Ack
> {
> DDS_infrastructureservices::DDS_common::Message_T msg;
> };

Yes, this pattern is already in OpenDDS in fact.  See `dds/DdsSecurityCore.idl` around line 113.

**Comment by kashif68** [comment]
Thanks!
I am willing to help.
What should I be reading/reviewing to come up to speed.

**Comment by mitza-oci** [comment]
> I am willing to help.
> What should I be reading/reviewing to come up to speed.

If you're talking about the struct inheritance feature in particular, it would have to start in the TAO_IDL_FE library which is part of the https://github.com/DOCGroup/ACE_TAO repository.  The spec for the IDL grammar is https://www.omg.org/spec/IDL/4.2/PDF
@iguessthislldo may have some more notes on where to look to get started.
