### ISSUE TITLE
Is it possible to use different ports for different writers/readers?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1637]
In our application we assume to have about 10 different writers/readers running in 10 different publishers/subscribers. Is it possible to differentiate the used ports per writer/reader or per publisher/subscriber?

PS
We also considered having all the writers in one publisher and all the readers in one subscriber, but that might lead to colorful concurrency problem, right?

**Comment by mitza-oci** [comment]
> 
> 
> In our application we assume to have about 10 different writers/readers running in 10 different publishers/subscribers. Is it possible to differentiate the used ports per writer/reader or per publisher/subscriber?

Yes, you can attach different transport configurations to the various DDS Entities.  This is described in section 7.4.2.3 of the OpenDDS Developer's Guide.


> We also considered having all the writers in one publisher and all the readers in one subscriber, but that might lead to colorful concurrency problem, right?

I don't know what problem you're referring to.  OpenDDS works with multiple readers/writers in a single subscriber/publisher.  This is a core feature of the DDS specification.

**Comment by KiriakosD** [comment]
Thank you @mitza-oci , this was very helpful and now I have sorted things out.
