### ISSUE TITLE
cmake using OpenDDS::OpenDDS, TAO::TAO, and ACE::ACE among others but still undefined reference?

### ISSUE THREAD

**Issue by kashif68** [objectcomputing/OpenDDS#1638]
Just wanted to post it if someone may know the answer? I thought I included all libs?

In function `__static_initialization_and_destruction_0(int, int)':
[build] /usr/local/include/tao/Valuetype/Valuetype_Adapter_Factory_Impl.h:54: undefined reference to `TAO_Valuetype_Adapter_Factory_Impl::Initializer()'

**Comment by kashif68** [comment]
TAO_Valuetype

Linked the above to get it build. This is in addition to TAO::TAO

**Comment by iguessthislldo** [comment]
Yeah, `OpenDDSConfig.cmake` says `TAO::TAO` just refers to the core TAO library (`libTAO`). So it's like `ACE::ACE` (`libACE` but not the xml library), not `OpenDDS::OpenDDS` (Everything). Also we don't use valuetype library as far as I know, so you'll have to include TAO libraries like that if you want to use them.

**Comment by mitza-oci** [comment]
If we want to determine what was using Valuetype, please add a test to the repository.
