### ISSUE TITLE
HistoryCache in OpenDDS?

### ISSUE THREAD

**Issue by BottCode** [objectcomputing/OpenDDS#1640]
The RTPS specification define HistoryCache and CacheChange classes. These are used as interface between RTPS Writer (Reader) and DDS DataWriter (DataReader). However, I cannot find where these classes are implemented in OpenDDS. 

1. Could you tell me where I can find them?
2. How a RTPS Writer is notified about a new CacheChange added by its associated DDS Writer?

**Comment by mitza-oci** [comment]
These are conceptual items in the spec to define behavior and interfaces.  They are not 1:1 with actual implementation classes.
