### ISSUE TITLE
OpenDDS Integration Crashes - Perhaps Win32 vs Win64

### ISSUE THREAD

**Issue by muxado** [objectcomputing/OpenDDS#1667]
My first OpenDDS.  I have successfully run the tests.  Windows 10.017763 Build 17763.  Visual C++ 2019.  Integrating OpenDDS into legacy application.  Installed OpenDDS using DDS_TAOv2.sln.  Linking the legacy app projects to ACEd.lib, TAOd.lib, Dcpsd.lib, TAO_AnyTypeCoded.lib with Preprocessor flags to suppress warnings.  Linking required me to add WIN32 to Preprocessor definitions (from config-win32-common.h via config.h).  I compiled everything from Visual Studios Build selecting Debug|x64.  I ran the OpenDDS-supplied tests using Active Perl.  I am not using Active Perl to run the legacy application.

In one attempted integration, the caller sets a local variable to the instance from TheTransportRegistry.  The debugger shows the singleton instance in the TransportRegistry stack frame pointing to reasonable values.  In the calling stack frame, the pointer is unchanged, the memory is unchanged, but the debugger shows the values being pointed to are interpreted as garbage.  If the caller executes until the instance.get_config() is called with a string argument, the TransportRegistry stack frame shows the instance pointing to the same reasonable values again, but the string argument passed in is unreadable in the TransportRegistry frame.  Memory values did not change.  The program crashes in TransportRestry trying to compare the unreadable string argument after giving it to the internal std::map.  This looks like a WIN32/WIN64 mismatch, but maybe it's something else.

In another integration attempt, avoiding TheTransportRegistry, I noticed the debugger executing ACE code as if ACE_WIN32 was not #defined.  This seems like evidence that part or all of ACE was built without WIN32, but I don't know how a Windows installation would have done that.

I'm hoping I failed to set the environment and preprocessor flags correctly on the integration side to build a consistent executable.

**Comment by mitza-oci** [comment]
> My first OpenDDS. I have successfully run the tests. Windows 10.017763 Build 17763. Visual C++ 2019. 

Welcome, I'm glad that worked.

> Integrating OpenDDS into legacy application. Installed OpenDDS using DDS_TAOv2.sln. Linking the legacy app projects to ACEd.lib, TAOd.lib, Dcpsd.lib, TAO_AnyTypeCoded.lib with Preprocessor flags to suppress warnings. Linking required me to add WIN32 to Preprocessor definitions (from config-win32-common.h via config.h). 

I'm not sure what you mean here by "required me to add...".  Before we get to the specifics, however, when you compile the translation units that `#include` ACE/TAO/OpenDDS headers, you should make sure that all potential ABI-impacting compiler settings (including but not limited to preprocessor defines) are set up.

>I compiled everything from Visual Studios Build selecting Debug|x64. I ran the OpenDDS-supplied tests using Active Perl. I am not using Active Perl to run the legacy application.

Right, we wouldn't expect Perl to be part of the legacy application.  It's just used as a platform-neutral way to coordinate running tests.

> In one attempted integration, the caller sets a local variable to the instance from TheTransportRegistry. The debugger shows the singleton instance in the TransportRegistry stack frame pointing to reasonable values. In the calling stack frame, the pointer is unchanged, the memory is unchanged, but the debugger shows the values being pointed to are interpreted as garbage. If the caller executes until the instance.get_config() is called with a string argument, the TransportRegistry stack frame shows the instance pointing to the same reasonable values again, but the string argument passed in is unreadable in the TransportRegistry frame. Memory values did not change. The program crashes in TransportRestry trying to compare the unreadable string argument after giving it to the internal std::map. This looks like a WIN32/WIN64 mismatch, but maybe it's something else.

This certainly seems like something isn't set up right.  If you can send an example .vcxproj we could take a look at it.


> In another integration attempt, avoiding TheTransportRegistry, I noticed the debugger executing ACE code as if ACE_WIN32 was not #defined. This seems like evidence that part or all of ACE was built without WIN32, but I don't know how a Windows installation would have done that.

The ACE code that checks for ACE_WIN32 would have included the config.h first to get that defined.  What's the file and line number?

**Comment by mitza-oci** [comment]
Also keep in mind that "Win32" is the name of the OS API.  Even though it has the 3 and 2 digits in there, it's not limited to 32-bit platforms, or even the x86(_64) instruction set architecture.

https://docs.microsoft.com/en-us/windows/win32/

**Comment by muxado** [comment]
Adam,

Thank you for responding.  Since posting I have learned that the WIN32 flag simply means Windows.  This is my first Windows project as I have always used Unix and Linux in the past.  The observation that ACE_WIN32 is not defined seems likely to mean that ACE is compiled as x64.  This would be correct, as I am running a 64-bit OS.  I didn’t track down how ACE_WIN32 gets set.  If this still concerns you I can track down code that exhibits the behavior I described and verify.

Please see two vcxproj files attached.  The DDS_Manager makes calls to functions in the OpenDDS installation.  The DataInterface makes calls to DDS_Manager functions and references the OpenDDS installation through the generated code, from the IDL, for the Topic I am using.  There are other projects in my solution that use the DataInterface functions, but nothing else references OpenDDS directly.

I am also pursuing a compilation pattern used by another department that have a development environment built an CMake.

V/r,

Ned Bent
Senior Engineer

Be aware that I do not have authority to change the obligations associated with any government contract.

CRL Technologies, Inc.
46591 Expedition Dr. Suite 300
Lexington Park, MD 20653
703-785-6623

**Comment by mitza-oci** [comment]
> Adam, Thank you for responding. Since posting I have learned that the WIN32 flag simply means Windows. This is my first Windows project as I have always used Unix and Linux in the past. 

OK, I hope the link I posted to this issue was useful in learning some background on Windows platform programming.

>The observation that ACE_WIN32 is not defined seems likely to mean that ACE is compiled as x64. This would be correct, as I am running a 64-bit OS. I didn’t track down how ACE_WIN32 gets set. If this still concerns you I can track down code that exhibits the behavior I described and verify.

I don't agree that this has anything to do with a 64-bit OS.

> Please see two vcxproj files attached. The DDS_Manager makes calls to functions in the OpenDDS installation. The DataInterface makes calls to DDS_Manager functions and references the OpenDDS installation through the generated code, from the IDL, for the Topic I am using. There are other projects in my solution that use the DataInterface functions, but nothing else references OpenDDS directly. 

Have you compared this to the vcxproj files that OpenDDS itself uses?

> I am also pursuing a compilation pattern used by another department that have a development environment built an CMake. 

Is the "legacy app" built using CMake?  If so you can integrate with OpenDDS's provided CMake support, see `docs/cmake.md` in the OpenDDS source.

By the way - looks like GitHub's email interface didn't process your email quite right, it maybe better to use the web interface.

**Comment by muxado** [comment]
Thanx again for your attention.  I compared the vcxproj files in my projects to those in OpenDSS, specifically ace, tao, and dds.  I found similar warning suppression and similar WIN32 preprocessor flags, similar x64 sections, and no surprises in additional directories.  My legacy software did not originally use CMake to compile, but a third party included it in a CMake based development environment.  I'm trying to learn enough about CMake to attempt adapting my project to that DE.

While trying to learn about CMake, I was able to make it generate VS projects for some of the constituents, one of which was the DDS_Manager project I sent previously.  This is the interface project that makes calls to OpenDDS to create and register participants, topics, and readers.  While I had made mine a static library, the CMake made a DLL.  I tried linking my code to this DLL and after some work, it ran successfully past where the TransportRegistry instance originally seemed to have different representations.  Unfortunately, the DataTypesRegistry seemed to be unable to search the map when trying to register the first topic.  Instead the first iterator of participant_ returned as garbage and the topic could not be registered.  This seems like the object image got corrupted.  Note that my previous failure occurred in an ACE Singleton containing a std::map.

I seem to get the same behavior whether or not I'm running the DCPSInfoRepo process, which I assume is the broker that should own the registries, but I'm very unclear how that works.

When I changed to DLL for the DDS_Manager project, I was forced to put the DLL file into the same root folder as my app executable.  However, the OpenDDS DLLs for ACE, TAO, and DCPS are not required to be in that root directory.  This may just show I'm new to DLLs and don't understand what makes them private or shared, but this may be a clue for you.

**Comment by muxado** [comment]
I did more work to describe the behavior.  Just focusing on the error, I discovered the Registered_Data_Types singleton is showing me two instances.  One instance registers the BUILT_IN_TOPIC_TYPEs when I call create_participant() and also is the instance I see when I call TopicGroup->create_topic().  I see a different instance when I call TypeSupportImpl->register_type().  Both cases seem to be accessing the ACE_Singleton<OpenDDS::DCPS::Data_Types_Register, ACE_Thread_Mutex>::instance().

In the previous comment (5/8), the second paragraph describes the debugger behavior when the Type that goes with the Topic is not found on the Map in the registry.  A deallocation is done on a copy of the string for my topic type and I mistook that for the original string.  This looked like clobbering, but it could simply be an artifact of the VS debugger, since the return value of zero is correct.

So how am I getting two instances of this singleton?  I checked to see that when the second is created, the instance() function sees a null pointer for the internal instance.  Later when creating the Topic, the instance is the first one and it looks healthy with the five BUILT_IN_TOPIC_TYPEs still where they should be.  So the first instance is not being destroyed.  These calls can be traced to the same compilation unit, so I would assert they are in the same thread.

**Comment by mitza-oci** [comment]
Is the Visual C++ "Runtime Library" setting the same for the projects you're building and the OpenDDS projects?

**Comment by muxado** [comment]
For my projects, the Runtime Library settings are all Multi-threaded DLL (/MD).  For all of the installed OpenDDS projects, the Runtime Library setting is a boldface <**different options**>, with no explicit selection.

**Comment by muxado** [comment]
Problem solved.  I needed to compile the OpenDDS code with optimization disabled.  In response to your suggestion about runtime library, I saw optimization flags as a setting and discovered the OpenDDS installation does not specify optimization.  Further investigation of multiple Singletons led me to believe I could be looking at optimized code, since the debugger was skipping statements and some variables, including "this", were sometimes unavailable for inspection.

Here is a behavior from before I disabled optimization.  The registry for topic types is implemented from the ACE Singleton template.  The instance is built at startup and five built in types register with the lone participant.  The optimizer seems to build the first instance at startup without checking the value of the static instance pointer.  The instance is not stored in the static instance pointer, but instead lives at an inaccessible location.  The built in types access the instance and the optimized code returns the instance pointer without explicitly executing the accessor code.  In the debugger, the "step into" button doesn't step into the accessor, it just steps over it and the instance pointer is assigned.  So it works fine within OpenDDS.  When my application code calls register_type(), the accessor does not behave like the optimized code.  Instead it follows the source code as written and checks the value of the static instance pointer, sees a null pointer, and creates a new instance of the Singleton.  My topic type is the only now stored in this second registry.  When create_topic() is called, the first instance is retrieved and the topic type is not found, causing an error and prohibiting the topic from being usable.

So I think this is either a bug or a users note about how to install.  I suspect my issue had to do with me building my application in pieces rather than building it as a monolith, but I am new to Windows programming and don't know any tricks for managing optimization.  Thank you for the help.  Perhaps the title of this issue should be changed to something like Optimization Singleton Failure.

**Comment by mitza-oci** [comment]
I don't think it's a bug.  I also don't have enough information to change documentation.  It does seem like the build settings were somehow inconsistent.

**Comment by muxado** [comment]
Adam,

Thank you for the help on this!

V/r,

Ned Bent
Senior Engineer

Be aware that I do not have authority to change the obligations associated with any government contract.

CRL Technologies, Inc.
46591 Expedition Dr. Suite 300
Lexington Park, MD 20653
703-785-6623
