### ISSUE TITLE
IntroductionToOpenDDS example error when using UDP

### ISSUE THREAD

**Issue by XiaoLeS** [objectcomputing/OpenDDS#1680]
Hi,

I'm now running the provided example in IntroductionToOpenDDS folder.
It works fine when I running with TCP transportation with following instructions.
```
$DDS_ROOT/bin/DCPSInfoRepo -ORBListenEndpoints iiop://192.168.1.39:12345
subscriber -DCPSConfigFile dds_tcp_conf.ini
publisher -DCPSConfigFile dds_tcp_conf.ini
```

However, when I change the tcp to udp as following, the error occurred.
```
$DDS_ROOT/bin/DCPSInfoRepo -ORBListenEndpoints iiop://192.168.1.39:12345
subscriber -DCPSConfigFile dds_udp_conf.ini
```
Error message:
```
subscriber -DCPSConfigFile dds_udp_conf.ini 
(12502|12502) TransportRegistry::create_inst: transport_type=udp is not registered.
(12502|12502) TransportRegistry::load_transport_configuration: Unable to create transport instance in [transport/udp1] section.
(12502|12502) ERROR: Service_Participant::load_configuration Unable to locate specified global transport config: config1
(12502|12502) ERROR: Service_Participant::get_domain_participant_factory: load_configuration() failed.
Segmentation fault (core dumped)
```

I have tried to change the port number to 12346, but the error still occurred.

Please let me know if there is any other information that I need to provide for figuring out this issue.

Thanks in advance!

XiaoLe

**Comment by iguessthislldo** [comment]
I see that we do provide this udp config file, but I don't think it can actually be run as is with that config file. We will have to fix it, or else remove that file and references to it, but the fix is simple.

`StockQuoter.mpc` shows that IntroductionToOpenDDS applications only link to the TCP transport library:

https://github.com/objectcomputing/OpenDDS/blob/68ad2f231d74ff208959632805fe10467d74e458/examples/DCPS/IntroductionToOpenDDS/StockQuoter.mpc#L23

https://github.com/objectcomputing/OpenDDS/blob/68ad2f231d74ff208959632805fe10467d74e458/examples/DCPS/IntroductionToOpenDDS/StockQuoter.mpc#L52

You would have to add `dcps_udp` or replace `dcps_tcp` with `dcps_udp` in the publisher and subscriber in `StockQuoter.mpc`.For example:

```
project(*Publisher) : dcpsexe, dcps_tcp, svc_utils, dcps_udp {
```

```
project(*Subscriber) : dcpsexe, dcps_tcp, dcps_udp {
```

Then regenerate the make files and run make again.

**Comment by mitza-oci** [comment]
As long as it's not a static library build, you can dynamically load a transport library at runtime without modifying the build.  OpenDDS will use the system's dynamic library loader (Windows LoadLibrary or Linux dlopen) to find and load OpenDDS_Udp.dll (or OpenDDS_Udpd.dll or libOpenDDS_Udp.so).

**Comment by XiaoLeS** [comment]
> I see that we do provide this udp config file, but I don't think it can actually be run as is with that config file. We will have to fix it, or else remove that file and references to it, but the fix is simple.
> 
> `StockQuoter.mpc` shows that IntroductionToOpenDDS applications only link to the TCP transport library:
> 
> https://github.com/objectcomputing/OpenDDS/blob/68ad2f231d74ff208959632805fe10467d74e458/examples/DCPS/IntroductionToOpenDDS/StockQuoter.mpc#L23
> 
> https://github.com/objectcomputing/OpenDDS/blob/68ad2f231d74ff208959632805fe10467d74e458/examples/DCPS/IntroductionToOpenDDS/StockQuoter.mpc#L52
> 
> You would have to add `dcps_udp` or replace `dcps_tcp` with `dcps_udp` in the publisher and subscriber in `StockQuoter.mpc`.For example:
> 
> ```
> project(*Publisher) : dcpsexe, dcps_tcp, svc_utils, dcps_udp {
> ```
> 
> ```
> project(*Subscriber) : dcpsexe, dcps_tcp, dcps_udp {
> ```
> 
> Then regenerate the make files and run make again.

Thanks for reply!

The problem is still...
I have tried both to add `dcps_udp` or replace `dcps_tcp` with `dcps_udp` in the publisher and subscriber in `StockQuoter.mpc`.
And then, I regenerate the make files (even remove the make files manually) and run make again. 

Both of the results are as following.
```
subscriber -DCPSConfigFile dds_udp_conf.ini 
(2684|2684) TransportRegistry::create_inst: transport_type=udp is not registered.
(2684|2684) TransportRegistry::load_transport_configuration: Unable to create transport instance in [transport/udp1] section.
(2684|2684) ERROR: Service_Participant::load_configuration Unable to locate specified global transport config: config1
(2684|2684) ERROR: Service_Participant::get_domain_participant_factory: load_configuration() failed.
Segmentation fault (core dumped)
```

I found that the message of `make` process shows that it still links the TCP library, even if I replace the `dcps_tcp` with `dcps_udp`.
(I am not sure if this message can help for debugging, but... just mention.)
```
...
-lStockQuoterCommon -lOpenDDS_Udp -lOpenDDS_Tcp -lOpenDDS_InfoRepoDiscovery -lOpenDDS_Dcps 
...
```

**Comment by XiaoLeS** [comment]
> As long as it's not a static library build, you can dynamically load a transport library at runtime without modifying the build. OpenDDS will use the system's dynamic library loader (Windows LoadLibrary or Linux dlopen) to find and load OpenDDS_Udp.dll (or OpenDDS_Udpd.dll or libOpenDDS_Udp.so).

Thanks for mentioned! It is useful for my future experiments!

**Comment by iguessthislldo** [comment]
So I looked at this again, and I see there is an option for running UDP in the test script: `perl run_test.pl --udp`. This does work for me, well at least it gets work until the end where the test doesn't look like it shuts down right, but that's unrelated to your problem. Looking at the source it looks like it tries to load the library if it's not already linked, which is what I didn't know. I also ran it manually like you are describing and that works as well.

Could you tell us what exact OpenDDS you have (version if it's a release or commit if you cloned it using git) and post the result of `perl tools/scripts/show_build_config.pl`? It might be a bug in a particular version/build configuration of OpenDDS. If also might be the build is messed up some how, like if the build was stopped, configure was ran again with different options and then the build was resumed without cleaning.

**Comment by XiaoLeS** [comment]
According to `git log`, the first commit is shown as following:
```
commit 16b426a3ccdba5360b06d9bff625c56dc04e511f (HEAD, tag: DDS-3.14, origin/branch-DDS-3.14
```

And the `perl tools/scripts/show_build_config.pl` shows:
```
================ setenv.sh ================
# OpenDDS configure script: ./configure --static
export ACE_ROOT=/home/xiaole/staticopendds/OpenDDS/ACE_wrappers
export CIAO_ROOT=unused
export TAO_ROOT=/home/xiaole/staticopendds/OpenDDS/ACE_wrappers/TAO
export PATH=${PATH}:/home/xiaole/staticopendds/OpenDDS/ACE_wrappers/bin:/home/xiaole/staticopendds/OpenDDS/bin
export DDS_ROOT=/home/xiaole/staticopendds/OpenDDS
export DANCE_ROOT=unused
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export MPC_ROOT=/home/xiaole/staticopendds/OpenDDS/ACE_wrappers/MPC
================ default.features ================
no_cxx11=0
================ platform_macros.GNU ================
optimize = 0
static_libs_only = 1
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
================ config.h ================
#include "ace/config-linux.h"
```

**Comment by iguessthislldo** [comment]
Okay so it's static. Static builds can't load a transport library automatically like @mitza-oci mentioned. The transports have headers that have to included in the application when using a static OpenDDS. Try adding this line to the top of `subscriber.cpp` and `publisher.cpp`:

```c++
#include <dds/DCPS/transport/udp/Udp.h>
```

The files already include the TCP transport equivalent when the build is static.

**Comment by XiaoLeS** [comment]
Oh!!!!! I'm sorry that I misunderstand what @mitza-oci means... I thought the static library build to the static build for the executable.
After including the header, it works!!
Thanks for your help and also @mitza-oci !
