### ISSUE TITLE
ERROR: Spdp::SpdpTransport::handle_input() - failed to deserialize RTPS header for SPDP

### ISSUE THREAD

**Issue by ethanshattuck** [objectcomputing/OpenDDS#1697]
When using OpenDDS to subscribe to an RTI publisher, I get the following error: "ERROR: Spdp::SpdpTransport::handle_input() - failed to deserialize RTPS header for SPDP". Both instances are using RTPS version 2.1.

**Comment by mitza-oci** [comment]
This is probably an older OpenDDS if it's RTPS 2.1.  Which OpenDDS version are you using?

**Comment by ethanshattuck** [comment]
The RTPS version of RTI is 2.1, and the OpenDDS RTPS version was 2.3. After getting the same error, we tried manually changing the RTPS version to 2.1 to fix the error. OpenDDS version 3.13.2.

**Comment by cbade0** [comment]
To be clear, we first tried using the latest-release branch (3.14) that uses RTPS 2.3 to connect to the older RTI publisher that uses RTPS 2.1 and got the failed to deserialize error with that. Then we tried to connect with OpenDDS 3.13.2, to rule out the RTPS version mismatch, and got the same deserialization error.

**Comment by mitza-oci** [comment]
You can ignore the error message.  OpenDDS is dropping that datagram that doesn't start with a proper RTPS header.  In later versions we gave up on issuing the error message.
https://github.com/objectcomputing/OpenDDS/blob/5c73412f5eaf378447a4b3a19bcdbbb4cc990b52/dds/DCPS/RTPS/Spdp.cpp#L2241
