### ISSUE TITLE
Version of Perl & Cmake

### ISSUE THREAD

**Issue by lywilliam** [objectcomputing/OpenDDS#1698]
Where can I find out the version of Perl & Cmake to compile OpenDDS?

Thanks

**Comment by mitza-oci** [comment]
https://opendds.org/documents/building.html

**Comment by lywilliam** [comment]
**I am completely new to OpenDDS.    Does it matter what version of Active Perl?  As far as GNU Make concerned, what about compilling & linking on Windows 10?**

GNU Make 
GNU Make 3.80 or higher is used for automating the compiling and linking of OpenDDS on Unix and Linux systems.
Perl 
Perl is used for running the automated tests and examples included in this source tree and for generating Makefiles or Visual Studio project files.
The "configure" script also uses Perl.
On Windows platforms, we recommend the use of Strawberry Perl or ActiveState Perl.

**Comment by mitza-oci** [comment]
>I am completely new to OpenDDS. 

Welcome

> Does it matter what version of Active Perl?

Not that I know of.  Please report any problems here and we'll take a look.

> As far as GNU Make concerned, what about compilling & linking on Windows 10?**

GNU make is not used when building OpenDDS with Visual Studio.

**Comment by lywilliam** [comment]
I will try to use either 5.8.8 or 5.12.3 & let you know ASAP, thanks
