### ISSUE TITLE
compile error: missing stropts.h

### ISSUE THREAD

**Issue by vermaete** [objectcomputing/OpenDDS#1726]
When compiling the OpenDDS version 3.14 with the meta-opendds layer at the Dunfell Yocto release, the compilation failed.
It failed because it could not find the stropts.h file.
When configuring with --doc-group, it was passing.
When being at the Warriror release of Yocto, the compilation was successfull.
The glibc version of Warrrior 2.29 is and Dunfell is at 2.31.

Related issue: http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel/commit/?id=0c265b1fb5049180800c0697440f468b8add79c8

**Comment by mitza-oci** [comment]
ACE's OCIChangeLog says this was fixed last October (at least I think it's the same issue).  So we'll have to look into why it's not working in your configuration:
```
Tue Oct 15 21:44:07 UTC 2019  Fred Hornsey  <hornseyf@objectcomputing.com>

        * ace/config-linux-common.h:

          Cherry-picked fix for glibc 2.30 from DOCGroup #939 submitted by
          Naveen Saini <naveen.kumar.saini@intel.com>
          https://github.com/DOCGroup/ACE_TAO/pull/939

```

**Comment by vermaete** [comment]
It could be I'm wrong.  I still try to find my way in OpenDDS.
But when running the configure script **without** --doc-group, is it not the ociweb.com version that is used?  And with the --doc-group, it's that version that if fixed at github.com/DocGroup.

**Comment by iguessthislldo** [comment]
> But when running the configure script without --doc-group, is it not the ociweb.com version that is used? And with the --doc-group, it's that version that if fixed at github.com/DocGroup?

Yes, that's correct.

Can you check if the changed line from https://github.com/DOCGroup/ACE_TAO/pull/939 is in `ace/config-linux-common.h` of your copy of OCI ACE? If it's there maybe something is setting `_XOPEN_STREAMS` when it shouldn't be and if it's not then I think you have an older copy of OCI ACE/TAO.

**Comment by kdopen** [comment]
We are moving our platform from Thud through to Dunfell, one Yocto release at a time. As we go, we will be pushing up new branches and version on the recipes.

However, if you find fixes ahead of us which get it working for new releases then pull requests are always appreciated.

**Comment by mitza-oci** [comment]
I was not able to reproduce this error using the Yocto Project Extensible SDK (Dunfell release) https://www.yoctoproject.org/docs/current/sdk-manual/sdk-manual.html

**Comment by vermaete** [comment]
So, I'm using version 3.14 of OpenDDS.
The configure script was downloading the file 'ACE+TAO-2.2a_with_latest_patches_NO_makefiles.tar.gz'.
And, a bit weird, the VERSION file in the ACE_wrappers directory has in one if its first lines 'This is ACE version 6.2a_p16, released Mon Jul  1 15:44:17 UTC 2019.'.  It's not a '2.2a' as I was expection.

This file is downloaded probably because I did not specify something as at the configure script.
https://github.com/objectcomputing/OpenDDS/blob/branch-DDS-3.14/configure#L26
At the master, it's still the same version.

@iguessthislldo
I have this in the './ACE_wrappers/ace/config-linux-common.h' file:

```
#if defined _XOPEN_STREAMS && _XOPEN_STREAMS == -1
#  define ACE_LACKS_STROPTS_H
#  define ACE_LACKS_STRRECVFD
#endif
```
Note: I get this file from the OCI's TAO version 2.2a.

**Comment by mitza-oci** [comment]
6.2a is the ACE version that matches TAO's version 2.2a.  This convention comes from upstream ACE_TAO.  As you've seen, the related convention is that the ACE+TAO combination takes on TAO's version number.

You can browse the files at http://download.ociweb.com/TAO-2.2a -- the one being downloaded has a 2020 timestamp, and should be the latest patch release, p18.

**Comment by vermaete** [comment]
@mitza-oci 
Hi,  Thanks for the info.  I found it!
They keep the same file name for the releases (ACE+TAO-2.2a_with_latest_patches_NO_makefiles.tar.gz).
But they change the content of it!

At our mirror server, there was a version from some time ago.  And I didn't *saw* any reason to update it.  Note, we're using a mirror because we do not have Internet connection.
The md5sum of the one at our mirror site and the one at Internet is different.
Well, even the VERSION / VERSION.txt file is different.

```
$ diff internet/ACE_wrappers/VERSION.txt  mirror/ACE_wrappers/VERSION
1c1
< This is ACE version 6.2a_p18, released Wed Apr 22 15:28:21 UTC 2020.
---
> This is ACE version 6.2a_p16, released Mon Jul  1 15:44:17 UTC 2019.
```

A bit of a strange and uncommon habit of releasing, if you ask me. 

Thanks for the support.

**Comment by mitza-oci** [comment]
Yes, we (not "they") keep the same file name.  This is by design, though there are both pros and cons.  Using the timestamp or md5 would be good.

**Comment by jwillemsen** [comment]
See https://github.com/objectcomputing/OpenDDS/issues/1032 for a related issue, for that a md5 would also be helpful

**Comment by mitza-oci** [comment]
> 
> 
> See #1032 for a related issue, for that a md5 would also be helpful

That's a bit of a different issue.  I think in that one the idea would be for the configure script to verify hashes.  Seems like a good idea if someone wants to implement.

For this issue, if someone is maintaining their own mirror, the md5 hashes (or timestamps) on the files should be checked.
http://download.ociweb.com/TAO-2.2a/TAO-2.2a.md5
