### ISSUE TITLE
Error parsing configuration file for SpdpLocalAddress

### ISSUE THREAD

**Issue by jmccabe** [objectcomputing/OpenDDS#1738]
RTPS Discovery doesn't correctly parse IP addresses specified in an ini file. SedpLocalAddress is one, but the code below in RtpsDiscovery.cpp shows that SpdpLocalAddress uses the same technique, which is to incorrectly use ACE_INET_Addr::set() (that treats a string WITHOUT a ':' a being only a port number - see https://github.com/objectcomputing/OpenDDS/issues/1717#issuecomment-638369785.

NOTE: If the IP address is specified with a trailing colon (e.g. "169.254.5.198:") they are parsed correctly. This doesn't seem 'normal'.

```
        } else if (name == "SedpLocalAddress") {
          ACE_INET_Addr addr;
          if (addr.set(it->second.c_str())) {
            ACE_ERROR_RETURN((LM_ERROR,
                              ACE_TEXT("(%P|%t) ERROR: RtpsDiscovery::Config::discovery_config(): ")
                              ACE_TEXT("failed to parse SedpLocalAddress %C\n"),
                              it->second.c_str()),
                             -1);
          }
          config->sedp_local_address(addr);
        } else if (name == "SpdpLocalAddress") {
          ACE_INET_Addr addr;
          if (addr.set(it->second.c_str())) {
            ACE_ERROR_RETURN((LM_ERROR,
                              ACE_TEXT("(%P|%t) ERROR: RtpsDiscovery::Config::discovery_config(): ")
                              ACE_TEXT("failed to parse SpdpLocalAddress %C\n"),
                              it->second.c_str()),
                             -1);
          }
          config->spdp_local_address(addr);

```

**Comment by mitza-oci** [comment]
Please see the Developer's Guide table that shows how these are used.

**Comment by jmccabe** [comment]
> Please see the Developer's Guide table that shows how these are used.

Thanks Adam; I had checked the Developer's Guide after I posted this Issue and noticed the following:

![image](https://user-images.githubusercontent.com/693900/84389093-78c50c80-abed-11ea-9e3e-8c3c8a1816dc.png)

You're correct, it does say the SedpLocalAddress must have a trailing ':' (actually, even the 3.13 Dev Guide says that, but I've been using it for months on 3.13 without a trailing ':').

However, the SpdpLocalAddress setting in the dev guide explicitly says "no port", but the code shown above for the SpdpLocalAddress is identical to the SedpLocalAddress code, so will fail if you specify an SpdpLocalAddress in the format the dev guide appears to suggest.

**Comment by mitza-oci** [comment]
> However, the SpdpLocalAddress setting in the dev guide explicitly says "no port", but the code shown above for the SpdpLocalAddress is identical to the SedpLocalAddress code, so will fail if you specify an SpdpLocalAddress in the format the dev guide appears to suggest.

Thanks for reporting this.  Please create a pull request that updates `tests/DCPS/ConfigFile`.

**Comment by jmccabe** [comment]
Sorry if this is a dim question, but do you mean just to generate a failing test?

**Comment by jmccabe** [comment]
Pull request created (https://github.com/objectcomputing/OpenDDS/pull/1743) with a fix in for the SpdpLocalAddress. The build log for it shows the Execute DPCS Messenger example doesn't always work on Windows, but that appear to be an existing issue on master.
