### ISSUE TITLE
Question on running a publisher and subscriber in separate Docker containers

### ISSUE THREAD

**Issue by Cingulara** [objectcomputing/OpenDDS#1755]
I have a question on how I would open up the right ports/protocols to run a publisher in one container and a subscriber in a different container wrt Docker. I can run them both inside a single container and all works fine of course, using UDP like below. 

I tried running them separately in separate containers, with an InfoRepo as the 2nd config below, and I could see them both connect to the InfoRepo. I ran that with something like `DCPSInfoRepo.exe  -ORBListenEndpoints iiop://:12345/hostname_in_ior=xxx.xxx.13.81 -DCPSDebugLevel 5` (I removed the first two octets of the IP I used). I could see them both try to connect, but the handshake that works with them both running natively (outside of Docker) does not work correctly when both are inside Docker. 

I tried setting the Publisher in Docker to use the port "12001" and do a TCP connection, sharing the 12001 port out to expose it but still no go. I am missing something. Something in the way the 2 applications need to shake hands to get going correctly. So I am asking out loud if there is something glaring I am missing? Or if this is just not supported? Or I need to run in something like Kubernetes to allow software networking inside the "docker network". 

Any help or insights would be appreciated. Thank you.

-----------------
[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSDebugLevel=5

[transport/the_rtps_transport]
transport_type=rtps_udp

-----------------
[common]
DCPSDebugLevel=1
DCPSInfoRepo=xxx.xxx.13.81:12345
DCPSGlobalTransportConfig=myconfig
[config/myconfig]
transports=mytcp
[transport/mytcp]
transport_type=tcp
local_address=xxx.xxx.13.81:12001

**Comment by jrw972** [comment]
Take a look at https://opendds.org/quickstart/GettingStartedDocker.html (and if it doesn't work let me know).

My guess is that the containers are not using the same network.

**Comment by Cingulara** [comment]
I will have different services (publishers / subscribers) on different machines on the same physical network. They will not be in the same docker network no. I cannot have them all within one docker compose setup. That is the point. I want to make them and deploy in containers. However, I need to know all the ports/protocols to open up for the docker containers to talk to each other over TCP. I have something like below as a start and I have an INI file in the container I can point to for the commands to run. They run fine. But they never see each other. 

I also have a fat client app in Windows that will never be in a container. But it has to talk to them as well. So is it possible to mix/match like that and have some in containers? And if so, what ports/protocols do I need to open up as I won't be able to have all open. I will need known ports and protocols for firewall settings even with boxes on the same physical local network. I just cannot seem to find the answer on that.

[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSDebugLevel=1

[transport/the_rtps_transport]
transport_type=tcp

**Comment by Cingulara** [comment]
I have tried the DCPSInfoRepo running and I can get the publisher and subscriber inside the container to talk to the info repo on the named port I gave it to run on. That works fine. But the pub and sub never see each other. 

I even tried something like below giving it the host IP and port to use, and shared out the port in the docker-compose file that brings up the publisher. 

[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSDebugLevel=1

[transport/the_rtps_transport]
transport_type=tcp
local_address=xxx.xxx.13.28:12001

**Comment by simpsont-oci** [comment]
Since multicast isn't fully implemented for docker networking (it works local to the same container, but not between containers on the same docker network... not sure about out to the host), I would stick with the InfoRepo & TCP transport approach. The TCP transport typically (but not always) has the writer side connect to the subscriber, so you'll probably want to hard-code & expose the subscriber's port as well.

**Comment by Cingulara** [comment]
ahhh OK I knew I was missing something. So I need to try that then and see what I get thank you. That makes much more sense I wish I would have ask you that THREE DAYS AGO! :)

**Comment by mitza-oci** [comment]
https://github.com/oci-labs/cloud-multicast-repeater

https://objectcomputing.com/resources/publications/sett/march-2019-multicast-to-cloud-for-dds-applications

**Comment by Cingulara** [comment]
I saw the cloud piece as well and was going to go there next if I could not get what I wanted to work.

**Comment by Cingulara** [comment]
@simpsont-oci you are my hero-of-the-day thank you. Your info to me helped me fix it. What I used is below. This made my setup work across 2 different OSes, 1 in docker, 2 native on Windows, and my Cyber guy knows the IPs and ports to open for all this so he also is appreciative!

1. I ran the InfoRepo on my WindowsVM as "DCPSInfoRepo.exe  -ORBListenEndpoints iiop://:12345/hostname_in_ior=xxx.xxx.13.81 -DCPSDebugLevel 2"

2. I ran my Publisher on a MacBook in a docker-compose setup with the following INI file:

[common]
DCPSInfoRepo=192.168.13.81:12345
DCPSDebugLevel=1
DCPSGlobalTransportConfig=myconfig

[config/myconfig]
transports=mytcp

[transport/mytcp]
transport_type=tcp
transport_type=tcp
local_address=xxx.xxx.13.28:12001

3. I ran the following as my subscriber on my Windows VM on the Mac (and a second subscriber on port 13002):

[common]
DCPSInfoRepo=xxx.xxx.13.81:12345
DCPSDebugLevel=1
DCPSGlobalTransportConfig=myconfig

[config/myconfig]
transports=mytcp

[transport/mytcp]
transport_type=tcp
transport_type=tcp
local_address=xxx.xxx.13.81:13001
