### ISSUE TITLE
VS2019 compiling issues

### ISSUE THREAD

**Issue by xumepoc** [objectcomputing/OpenDDS#1758]
Hi guys,
I know it is not OpenDDS problem, but suddenly from last week I can't compile OpenDDS 3.14 Release using VS2019 Community Edition . I am getting tons of std::string errors. Everything before that was coring just fine

Does anyone have similar experience and has found a solution about it?

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/OpenDDS/pull/1701
