### ISSUE TITLE
Is building with mingw32-make supported on Windows? If so, are there any caveats on the script options?

### ISSUE THREAD

**Issue by joostm8** [objectcomputing/OpenDDS#1762]
I'm trying to install with gcc and mingw32make, so for I'm running into issues. The INSTALL.md document only notes Visual Studio builds on windows, so I'm unsure if what I'm doing is completely supported. If not I'll just build with Visual Studio.

gcc version is 8.1.0
mingw32-make is GNU Make 4.2.1

**Installation steps done so far**

So far I've done the following:

`configure --compiler=gcc`

this fails with the error

`...
ERROR: Invalid type:
...
Command "perl C:\Users\Joost\Documents\Git\dds_testing\OpenDDS-3.14\ACE_wrappers/bin/mwc.pl -type  C:\Users\Joost\Documents\Git\dds_testing\OpenDDS-3.14\DDS_TAOv2.mwc" Returned 1
ERROR: Error from MPC, stopped at configure line 2052.`

Indeed, the perl command gives an empty type. I fixed this error by changing line 1846 in configure to:

`  my $make = "make";
  my $mpctype = (!$is_windows || ($cross_compile && $is_target))
               ? 'gnuace' : $make;`

after which the configuration completes. I then run a setenv to get all the environment variables set. Now I suppose all is ready to build with make, so I run 

`mingw32-make -j all`

which unfortunately fails with the error:

`'test' is not recognized as an internal or external command,
operable program or batch file.
A subdirectory or file C:\Users\Joost\Documents\Git\dds_testing\OpenDDS-3.14\ACE_wrappers/lib/ already exists.
Error occurred while processing: C:\Users\Joost\Documents\Git\dds_testing\OpenDDS-3.14\ACE_wrappers/lib/.
mingw32-make[1]: *** [Makefile.ACE:54: C:\Users\Joost\Documents\Git\dds_testing\OpenDDS-3.14\ACE_wrappers/lib/libACE.so] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/Joost/Documents/Git/dds_testing/OpenDDS-3.14/ACE_wrappers/ace'
mingw32-make: *** [Makefile:98: ACE] Error 2`

So now I'm at a bit of a loss at what to do further.

Like I said, if mingw32-make is simply not supported just let me know and I'll try to continue on with Visual Studio, so any response is appreciated.

**Comment by mitza-oci** [comment]
Configure script is definitely not ready for this, but the actual libraries may be OK.  I think we had some issue with ACE but you could start working on it if you'd like.

**Comment by joostm8** [comment]
Thanks for the rapid response, in that case I'll stick with Visual Studio for now as getting up and running is my first priority. I really have no perl experience so I don't know if I could get the configure script up and running by myself, though I might give it a shot if I find some spare time.

In any case, I'll close the issue as my question is resolved, thanks again!

**Comment by mitza-oci** [comment]
If you want to pursue mingw support, don't start with the configure script.  Configure manually (write a few very short text files) until it's working, then we can update the configure script to do that automatically.

**Comment by jwillemsen** [comment]
We did some testing with mingw-64 in the past, did had a runtime issue, see https://github.com/objectcomputing/OpenDDS/issues/367

**Comment by jwillemsen** [comment]
Which perl are you using, we have issues with for example cygwin perl, activestate perl or strawberry perl are the ones we know that work

**Comment by joostm8** [comment]
> 
> 
> Which perl are you using, we have issues with for example cygwin perl, activestate perl or strawberry perl are the ones we know that work

I used Strawberry Perl 5.30.2, also thanks for bringing up issue #367, I'll give it a read.

**Comment by jwillemsen** [comment]
Ok, then it is not a perl issue, configure should be updated for gcc on windows.

**Comment by mitza-oci** [comment]
First ACE and OpenDDS would need to work for that platform/compiler combination (as in, fix #367), then we can look at the configure script.
