### ISSUE TITLE
Problems when switching to another LAN

### ISSUE THREAD

**Issue by XiaoLeS** [objectcomputing/OpenDDS#1770]
Hi,

I was running the example in  `IntroductionToOpenDDS`. (`examples/DCPS/IntroductionToDDS`) on Ubuntu 18.04.
I found a bit strange when I connected to another LAN (`192.168.50.206`).

Then, I execute DCPSInfoRepo (`$DDS_ROOT/bin/DCPSInfoRepo -ORBListenEndpoints iiop://localhost:12345`) and a subscriber (`./subscriber -DCPSConfigFile dds_tcp_conf.ini`). And I got the error message as following at DCPSInfoRepo part.

```
xiaole@big-white:~/staticopendds/OpenDDS$ $DDS_ROOT/bin/DCPSInfoRepo -ORBListenEndpoints iiop://localhost:12345
(12012|12012) WARNING: Could not find FQDN. Using "big-white" as fully qualified hostname, please correct system configuration.
(12012|13423) TcpConnection::handle_timeout, this->reconnect_state_=INIT_STATE
(12012|13423) TcpConnection::handle_timeout, failed connection initialization due to timeout.: _OPENDDS_InfoRepoBITTCPTransportInst to 192.168.1.39:45865.
(12012|13423) ERROR: Failed to make active connection.
```

The strange point is the ip in the error message is `192.168.1.39` that is in my previous LAN.

My `dds_tcp_conf.ini` of the subscriber is shown as following:
```
[common]

# Debug Level
DCPSDebugLevel=0

# IOR of DCPSInfoRepo process.
DCPSInfoRepo=corbaloc::localhost:12345/DCPSInfoRepo

# Sets the global transport configuration (used by default in the
# process to config1, defined below
DCPSGlobalTransportConfig=config1


# Transport configuration named config1, contains a single transport
# instance named tcp1 (defined below)
[config/config1]
transports=tcp1


# Transport instance named tcp1, of type "tcp".  Uses defaults for
# all configuration paramaters.
[transport/tcp1]
transport_type=tcp

```

Is there any cache needed to be cleaned?

Thanks.

**Comment by mitza-oci** [comment]
Which address does the hostname `big-white` resolve to?

**Comment by XiaoLeS** [comment]
> Which address does the hostname `big-white` resolve to?

Oh!!!!! My fault, I forgot that I had set that before!
It works.

Thanks alot!!!!
