### ISSUE TITLE
transport_type=shmem is not registered error

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1782]
We have the following setup in our application.
Three different threads, running two writers and one reader.
We originally used rtps_udp (and use_multicast=0) in our rtps.ini configuration, and things were working fine.

In an effort to reduce the latency, we decided to experiment with the shared memory, however once we changed the transport_type in the rtps.ini configuration, we started getting this error in the TransportRegistry:
```
(21046|21046) NOTICE: using DCPSDebugLevel value from command option (overrides value if it's in config file)
(21046|21046) NOTICE: using DCPSTransportDebugLevel value from command option (overrides value if it's in config file)
(21046|21046) TransportRegistry::create_inst: transport_type=shmem is not registered.
(21046|21046) TransportRegistry::load_transport_configuration: Unable to create transport instance in [transport/shmem1] section.
(21046|21046) ERROR: Service_Participant::load_configuration Unable to locate specified global transport config: rtps.ini
(21046|21046) ERROR: Service_Participant::get_domain_participant_factory: load_configuration() failed.
```

Our rtps.ini file looks like this:
```
[common]
DCPSGlobalTransportConfig=$file

[transport/shmem1]
transport_type=shmem
```

Is there something obviously wrong?
Should we change something on the way we build OpenDDS or in our application code?

Also, is there any other improvements that could help us reduce latency and especially execution time that you would recommend? There seems to be a lot of overhead, especially when we start to increase the writer threads (up to 15ms on average with 30 writers).

Our original rtps.ini was like this:

```
[common]
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSGlobalTransportConfig=$file

[transport/the_rtps_transport]
transport_type=rtps_udp
use_multicast=0
```

**Comment by iguessthislldo** [comment]
The ini file looks fine. If OpenDDS is a static build then it sounds like you need to include `dds/DCPS/transport/shmem/Shmem.h` in you application. If it's not static, then it might not be finding the `OpenDDS_Shmem` library for some reason. If you are using macOS, I know the shared memory transport doesn't work there, but I don't think it stops the transport from being built or registered.

Just so we have more info, could you run `tools/scripts/build_config.pl` form the root of the OpenDDS source?

**Comment by iguessthislldo** [comment]
Sorry I meant run `tools/scripts/show_build_config.pl`. Then could you post the results?

**Comment by iguessthislldo** [comment]
I should also add that if build is static, the application should also be linked to the `OpenDDS_Shmem` library, which can be done using the `dcps_shmem` MPC base project. You can also do if the build is not static, but I don't believe it is required.

**Comment by KiriakosD** [comment]
Thanks a lot for the great tips @iguessthislldo !
We are building dds static, and we are using CMake for building our application.
Here is the output of the show_build_config.pl

'''
================ setenv.sh ================
# OpenDDS configure script: ./configure --static --no-built-in-topics
export DANCE_ROOT=unused
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export PATH=${PATH}:/reps/smartness/ToyotaSmartness/third-party/OpenDDS-3.14/ACE_wrappers/bin:/reps/smartness/ToyotaSmartness/third-party/OpenDDS-3.14/bin
export MPC_ROOT=/reps/smartness/ToyotaSmartness/third-party/OpenDDS-3.14/ACE_wrappers/MPC
export ACE_ROOT=/reps/smartness/ToyotaSmartness/third-party/OpenDDS-3.14/ACE_wrappers
export CIAO_ROOT=unused
export DDS_ROOT=/reps/smartness/ToyotaSmartness/third-party/OpenDDS-3.14
export TAO_ROOT=/reps/smartness/ToyotaSmartness/third-party/OpenDDS-3.14/ACE_wrappers/TAO
================ user_macros.GNU ================
built_in_topics=0
================ default.features ================
no_cxx11=0
built_in_topics=0
================ platform_macros.GNU ================
optimize = 0
static_libs_only = 1
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
================ config.h ================
#include "ace/config-linux.h"
'''

**Comment by KiriakosD** [comment]
After linking the libOpenDDS_Shmem.a the problem I seem to be getting is this:
```
(22405|22405) NOTICE: using DCPSDebugLevel value from command option (overrides value if it's in config file)
(22405|22405) NOTICE: using DCPSTransportDebugLevel value from command option (overrides value if it's in config file)
(22405|22405) WARNING: Could not find FQDN. Using "127.0.0.1" as fully qualified hostname, please correct system configuration.
(22405|22405) ERROR: InfoRepoDiscovery::get_dcps_info: unable to narrow DCPSInfo (file://repo.ior) for key DEFAULT_REPO.
(22405|22405) ERROR: DomainParticipantImpl::enable, add_domain_participant returned invalid id.
(22405|22405) ERROR: DomainParticipantFactoryImpl::create_participant, unable to enable DomainParticipant.
```

**Comment by iguessthislldo** [comment]
Okay, it's trying to start the Participant, so that means the transport was registered.

Now it's saying it couldn't find InfoRepo, which is the default discovery method. You can set up an InfoRepo, which is shown in our Developer's Guide Messenger example and documented in the InfoRepo chapter of the guide, or you can use RTPS discovery like you where using earlier (The `DCPSDefaultDiscovery=DEFAULT_RTPS` line in your `rtps.ini`). If you need to communicate with other hosts, but still want to use the shared memory transport locally, you can define both a RTPS transport and a shared memory transport:

```
[common]
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSGlobalTransportConfig=$file

[transport/shmem1]
transport_type=shmem

[transport/the_rtps_transport]
transport_type=rtps_udp
use_multicast=0
```
