### ISSUE TITLE
SEDP Packet is discarded by subscriber when simulating the discovery of RTPS

### ISSUE THREAD

**Issue by fouzhe** [objectcomputing/OpenDDS#1808]
Hi, all!
To simulate the discovery of RTPS. I run the `subscriber` in folder `OpenDDS/DevGuideExamples/DCPS/Messenger` by executing:
```shell
./subscriber  -ORBDebugLevel 10 -DCPSDebugLevel 10 -DCPSConfig File rtps.ini -DCPSTransportDebugLevel 6 -ORBLogFile subscriber.log
```
Then, I send the SPDP and SEDP packets constructed manually to verify whether the connection can be built. However, It seems that the `subscriber` only received the SPDP packet while discarded the SEDP packet. Here is the log file of the `subscriber`:
[subscriber.log](https://github.com/objectcomputing/OpenDDS/files/4977699/subscriber.log)

The SPDP and SEDP packets I send is construted by referring the packets sampled on the network (when executing `./run_test.pl --rtps`) and are attached as below: 
[Rtps-SPDP+SEDP.pcap.zip](https://github.com/objectcomputing/OpenDDS/files/4977711/Rtps-SPDP%2BSEDP.pcap.zip)

I don't know how to simulate correctly, could you please help me?
Thanks for your time!

**Comment by mitza-oci** [comment]
What was the answer?

**Comment by fouzhe** [comment]
@mitza-oci The submessage INFO_DST in SEDP should not be transmitted.

**Comment by mitza-oci** [comment]
> 
> 
> @mitza-oci The submessage INFO_DST in SEDP should not be transmitted.

Why not? There are good uses for the InfoDestination submessage.  Could you clarify how this statement connects to the original problem statement?
