### ISSUE TITLE
Is there any way to guarantee reliability in DDS?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1814]
We have been doing some tests using OpenDDS v3.14 in our application regarding reliability, and in all our different configurations we never managed to get 0% loss when increasing the writers above ~10 (except when using the ownership QoS policy). We tried using shared memory instead of RTPS, and we also tried using Reliable and keep all as QoS policies. Is there anything more we can do to improve our loss?

![def_vs_history_vs_reliability_loss](https://user-images.githubusercontent.com/8714981/88986775-3017fe80-d2d4-11ea-8d5c-3942f29291e9.png)

![rtps_vs_shared_loss](https://user-images.githubusercontent.com/8714981/88986784-360ddf80-d2d4-11ea-8f78-d07dd580bb7b.png)

PS
We are using the latency statistics from DCPS::DataReaderImpl::get_latency_stats()

**Comment by simpsont-oci** [comment]
Yes, many of the tests require lossless transmission in order to pass (see
the Messenger test for an example).

Some questions to help diagnose your issue:

Are you using reliable reliability qos on both the reader/s and the writer?
Are you waiting for publication matched status before doing your writes?
And waiting for acknowledgement before deleting your writer?

**Comment by KiriakosD** [comment]
Thanks for your quick reply @simpsont-oci 

One thing that I forgot to mention is that we are running everything in one machine have 1 separate thread handling each writer and reader. The process goes like this:

1. Every writer starts writing with a frequency of 100ms
2. Every writer stops writing after 2000 publishes
3. After all writers stop writing, we wait about 10 seconds and then stop the application.

Are you using reliable reliability qos on both the reader/s and the writer?
**Yes**
Are you waiting for publication matched status before doing your writes?
**Yes**
And waiting for acknowledgement before deleting your writer?
**Not exactly, as mentioned above every writer is alive and writes 2000 messages and then stops writing (not deleted). After that we wait for a few seconds and then terminate the application**

**Comment by mitza-oci** [comment]
rtps_udp is reliable when tuned for the specific scenario (buffer sizes are large enough, etc.).
Keep in mind that with "keep last" History QoS, reliable doesn't mean 1-to-1 send to receive for data samples.

**Comment by KiriakosD** [comment]
Thanks @mitza-oci 

**rtps_udp is reliable when tuned for the specific scenario (buffer sizes are large enough, etc.).**
I guess you are referring to the sender_history_size and the receiver_buffer_size? Or are you referring to the shared memory configuration?

**Keep in mind that with "keep last" History QoS, reliable doesn't mean 1-to-1 send to receive for data samples.**
Aha, I thought that might be the case. So in order to have proper reliability one needs both "keep all" History QoS and "reliable" Reliability Qos. Is that what you mean?

**Comment by mitza-oci** [comment]
> 
> 
> Thanks @mitza-oci
> 
> **rtps_udp is reliable when tuned for the specific scenario (buffer sizes are large enough, etc.).**
> I guess you are referring to the sender_history_size and the receiver_buffer_size? Or are you referring to the shared memory configuration?

Both transport and QoS settings are invovled


> **Keep in mind that with "keep last" History QoS, reliable doesn't mean 1-to-1 send to receive for data samples.**
> Aha, I thought that might be the case. So in order to have proper reliability one needs both "keep all" History QoS and "reliable" Reliability Qos. Is that what you mean?

That is not the same definition of "proper reliability" as the one used in the DDS spec.

**Comment by KiriakosD** [comment]
It took me a while to come back to this, but in the end I had lossless communication (in the same host) using the reliable Reliability and transient_local Durability. I will test it on different hosts as well.

Thanks @mitza-oci !

PS
I am guessing there is no point on using keep_all in history when using transient_local in Durability, right?

Also in the chapter 3.2.5 it says that:
"A durability kind of TRANSIENT_LOCAL_DURABILITY_QOS means that data readers that are associated/connected with a data writer will be sent all of the samples in the data writer’s history."

But I am guessing the the samples that have already been send and delivered are not resend every time, right?
I am assuming the latter because I haven't seen an increase in the latency between:
a) reliable
and 
b) reliable and transient_local

**Comment by mitza-oci** [comment]
> PS
> I am guessing there is no point on using keep_all in history when using transient_local in Durability, right?
> 
> Also in the chapter 3.2.5 it says that:
> "A durability kind of TRANSIENT_LOCAL_DURABILITY_QOS means that data readers that are associated/connected with a data writer will be sent all of the samples in the data writer’s history."
> 
> But I am guessing the the samples that have already been send and delivered are not resend every time, right?

They are resent to a reader that associates with this writer after they have been written.

**Comment by KiriakosD** [comment]
Thanks for the clarification @mitza-oci !
