### ISSUE TITLE
Are lost messages registered as 0ms in DCPS::DataReaderImpl::get_latency_stats() ?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1815]
We fell upon the strange phenomena.
When using best effort, it seems that the latency is decreasing, the more writers we have (we are using multiple writers vs 1 reader). Our writers and reader run in separate threads in the same machine. Is there any plausible explanation for this? We are using the latency statistics from DCPS::DataReaderImpl::get_latency_stats(). When using reliability.reliable in QoS we get the expected increase in latency.

The loss of course increases according to the number of writers, so we had a strange hypothesis, could it be that when there is a lost message, it registered as 0ms latency?

![def_vs_history_vs_reliability_mean](https://user-images.githubusercontent.com/8714981/88987304-cac50d00-d2d5-11ea-9e07-fff7186ba9dd.png)

![def_vs_history_vs_reliability_loss](https://user-images.githubusercontent.com/8714981/88987303-c993e000-d2d5-11ea-9ff2-05fe337a2b99.png)

PS
We calculate the latency by taking all the mean latencies for each instance and divide them by their number in order to get an average mean latency.

**Comment by KiriakosD** [comment]
The raw values for the extremes (1 and 40 writers) when using best effort and keep last one are:

**1 writer**
stats[0]:
 n = 2000
 max = 0.000956
 min = 0.000305
 mean = 0.00036653
 variance = 9.14359e-10


**40 writers**
stats[0]:
 n = 2000
 max = 0.027205
 min = 0.000208
 mean = 0.000274831
 variance = 3.67025e-07
stats[1]:
 n = 1999
 max = 0.001631
 min = 0.00021
 mean = 0.000277558
 variance = 4.89937e-09
stats[2]:
 n = 1999
 max = 0.001495
 min = 0.000208
 mean = 0.000266151
 variance = 4.12345e-09
stats[3]:
 n = 1999
 max = 0.001694
 min = 0.00021
 mean = 0.000260604
 variance = 3.8047e-09
stats[4]:
 n = 2000
 max = 0.021423
 min = 0.00021
 mean = 0.000273788
 variance = 2.30802e-07
stats[5]:
 n = 2000
 max = 0.02059
 min = 0.000209
 mean = 0.000281856
 variance = 2.11468e-07
stats[6]:
 n = 2000
 max = 0.021167
 min = 0.00021
 mean = 0.000276781
 variance = 2.22399e-07
stats[7]:
 n = 2000
 max = 0.020321
 min = 0.00021
 mean = 0.000277653
 variance = 2.05885e-07
stats[8]:
 n = 2000
 max = 0.020083
 min = 0.000213
 mean = 0.000285269
 variance = 1.99377e-07
stats[9]:
 n = 2000
 max = 0.021342
 min = 0.000209
 mean = 0.000271162
 variance = 2.26166e-07
stats[10]:
 n = 2000
 max = 0.020454
 min = 0.000211
 mean = 0.000279297
 variance = 2.07557e-07
stats[11]:
 n = 2000
 max = 0.019934
 min = 0.000211
 mean = 0.000268839
 variance = 1.9709e-07
stats[12]:
 n = 2000
 max = 0.019291
 min = 0.00021
 mean = 0.00026657
 variance = 1.85318e-07
stats[13]:
 n = 2000
 max = 0.018664
 min = 0.00021
 mean = 0.000269282
 variance = 1.74574e-07
stats[14]:
 n = 2000
 max = 0.018045
 min = 0.000209
 mean = 0.000256925
 variance = 1.62149e-07
stats[15]:
 n = 2000
 max = 0.017427
 min = 0.00021
 mean = 0.000264383
 variance = 1.50814e-07
stats[16]:
 n = 2000
 max = 0.016832
 min = 0.000208
 mean = 0.000257325
 variance = 1.40796e-07
stats[17]:
 n = 2000
 max = 0.016223
 min = 0.000212
 mean = 0.000264723
 variance = 1.31303e-07
stats[18]:
 n = 2000
 max = 0.015652
 min = 0.00021
 mean = 0.000262287
 variance = 1.24853e-07
stats[19]:
 n = 2000
 max = 0.015095
 min = 0.00021
 mean = 0.000256311
 variance = 1.13234e-07
stats[20]:
 n = 2000
 max = 0.014545
 min = 0.000209
 mean = 0.000258808
 variance = 1.10609e-07
stats[21]:
 n = 2000
 max = 0.013973
 min = 0.000206
 mean = 0.000245983
 variance = 1.03183e-07
stats[22]:
 n = 2000
 max = 0.013439
 min = 0.000208
 mean = 0.000252956
 variance = 9.11383e-08
stats[23]:
 n = 2000
 max = 0.012915
 min = 0.000209
 mean = 0.000253032
 variance = 9.34237e-08
stats[24]:
 n = 2000
 max = 0.012409
 min = 0.000211
 mean = 0.000273798
 variance = 8.67908e-08
stats[25]:
 n = 2000
 max = 0.011911
 min = 0.000206
 mean = 0.000251562
 variance = 7.82633e-08
stats[26]:
 n = 2000
 max = 0.011428
 min = 0.000209
 mean = 0.000249777
 variance = 6.65254e-08
stats[27]:
 n = 2000
 max = 0.01096
 min = 0.000207
 mean = 0.00031206
 variance = 6.80378e-08
stats[28]:
 n = 2000
 max = 0.010497
 min = 0.000208
 mean = 0.000253011
 variance = 6.48176e-08
stats[29]:
 n = 2000
 max = 0.010061
 min = 0.000209
 mean = 0.000250857
 variance = 5.31272e-08
stats[30]:
 n = 2000
 max = 0.009622
 min = 0.000209
 mean = 0.000266961
 variance = 4.93482e-08
stats[31]:
 n = 2000
 max = 0.009485
 min = 0.000207
 mean = 0.000274339
 variance = 5.01941e-08
stats[32]:
 n = 2000
 max = 0.009131
 min = 0.000209
 mean = 0.000258468
 variance = 4.52194e-08
stats[33]:
 n = 2000
 max = 0.008789
 min = 0.000209
 mean = 0.000258782
 variance = 4.41113e-08
stats[34]:
 n = 2000
 max = 0.008448
 min = 0.000206
 mean = 0.000265801
 variance = 4.09639e-08
stats[35]:
 n = 2000
 max = 0.002803
 min = 0.000212
 mean = 0.000260898
 variance = 1.08412e-08
stats[36]:
 n = 2000
 max = 0.002047
 min = 0.000212
 mean = 0.000295217
 variance = 8.6388e-09
stats[37]:
 n = 2000
 max = 0.002012
 min = 0.00021
 mean = 0.000271864
 variance = 7.28444e-09
stats[38]:
 n = 2000
 max = 0.002366
 min = 0.000216
 mean = 0.000280017
 variance = 7.00531e-09
stats[39]:
 n = 2000
 max = 0.002337
 min = 0.000212
 mean = 0.000263785
 variance = 6.47226e-09

**Comment by mitza-oci** [comment]
Take a look at the code that writes to `DataReaderImpl::statistics_`.  Looks like only about 4 methods are involved.

**Comment by KiriakosD** [comment]
Thanks @mitza-oci.

From a first look it seems that my hypothesis was wrong. I will look it up a bit more.
