### ISSUE TITLE
Multiple instances received in the reader when using ownership QoS

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1816]
We wanted to measure the latency when using the ownership QoS policy with multiple writers and 1 reader.
Our understanding was that when using the ownership QoS policy, only 1 writer is allowed to write to the topic.
To our surprise, when we used the  DCPS::DataReaderImpl::get_latency_stats() we saw that there were many instances registered (e.g. when we used 5 writers with writer [1] having the highest strength) we got the following:

stats[0]:
 n = 2000
 max = 0.002774
 min = 0.000414
 mean = 0.000766629
 variance = 4.02978e-08
stats[1]:
 n = 2000
 max = 0.002949
 min = 0.000168
 mean = 0.000763577
 variance = 5.91272e-08
stats[2]:
 n = 2000
 max = 0.00275
 min = 0.000381
 mean = 0.000794359
 variance = 5.22823e-08
stats[3]:
 n = 2000
 max = 0.002574
 min = 0.000169
 mean = 0.000732819
 variance = 5.15746e-08
stats[4]:
 n = 2000
 max = 0.002567
 min = 0.000224
 mean = 0.000749558
 variance = 5.11532e-08

The loss was 0% in all instances, even when we increased the number of writers to 40, so that means that the ownership QoS policy is working as expected. However we were unsure as to why we got multiple instance in the stats. Is our understanding wrong?

**Comment by mitza-oci** [comment]
`process_latency` is called early in `DataReaderImpl::data_received`, before ownership is determined

**Comment by KiriakosD** [comment]
Thanks @mitza-oci !

My impression was the writers that don't have the highest strength are blocked from writing (or their messages are discarded from the topic). But now I think I understand. Still a bit strange that there was 0% loss (given all the other tests I have done, that I always had some loss).
