### ISSUE TITLE
Problems with DevGuideExamples/Messenger

### ISSUE THREAD

**Issue by cpdeivis** [objectcomputing/OpenDDS#1820]
Hello, I am facing some problems when I try to run the DevGuideExamples/Messenger example.

I tried to use de script "run_test.pl" but without success, so i opened the script file and tried execute the commands in the console one by one.
In the $DDS_ROOT/bin, I opened a console
````cmd
DCPSInfoRepo.exe -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
````
In the DevGuideExamples/Messenger (I copied the repo.ior to this folder)
````cmd
publisher.exe -ORBDebugLevel 10 -DCPSDebugLevel 10 -ORBLogFile publisher.log -DCPSInfoRepo file://repo.ior
````
````cmd
subscriber.exe -ORBDebugLevel 10 -DCPSDebugLevel 10 -DCPSTransportDebugLevel 6 -ORBLogFile subscriber.log -DCPSInfoRepo file://repo.ior
````
I couldn't get it to work, but I got the following error: "ACE_ASSERT: file C:\OpenDDS-3.14\ace_wrappers\ace\OS_NS_Thread.cpp, line 954 assertion failed for 'info.thread_count_ > 0'.Aborting..." in the subscriber.exe and publisher.exe, and these log files: [DCPSInfoRepo.log](https://github.com/objectcomputing/OpenDDS/files/5008509/DCPSInfoRepo.log), [publisher.log](https://github.com/objectcomputing/OpenDDS/files/5008512/publisher.log), [subscriber.log](https://github.com/objectcomputing/OpenDDS/files/5008513/subscriber.log).

When I use the "--rtps" flag in the Perl script the example works fine.

Another Info:
OS: Windows 10 x64
Visual Studio: 2019

**Comment by mitza-oci** [comment]
The ACE_ASSERT isn't the primary failure.  That just happens when the test fails and opts not to clean anything up when exiting.

The issue is that the FQDN doesn't look right:
>   local_address:                DESKTOP-LU76V45.gmicro:51432

The OS reports that this is the host's proper address on the network.  However it seems like that is not a usable domain name address (that resolves to a routable IP for this host).
