### ISSUE TITLE
DDS_ROOT not used in generated makefiles

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#1827]
When I moved locally a test to a different directory level I noticed that `DDS_ROOT` is not used in the generated GNU makefiles, a relative path is generated.

To reproduce generate the gnuace project files in `examples/DCPS/ishapes` and open the `GNUmakefile.ishapes` file. I would expect to find

```
LIBPATHS := . "$(ACE_ROOT)/lib" "$(DDS_ROOT)/lib" "$(QTDIR)/lib" "$(BOOST_ROOT)/lib"
```

but found

```
LIBPATHS := . "$(ACE_ROOT)/lib" "../../../lib" "$(QTDIR)/lib" "$(BOOST_ROOT)/lib"
````
Same for `LIBCHECK`, `LDFLAGS`

**Comment by jwillemsen** [comment]
Just noticed that also the check for boost is generated twice in this file

```
ifneq ($(boost),1)
requires_disabled_macros += boost
endif
ifneq ($(boost),1)
requires_disabled_macros += boost
endif
```

**Comment by mitza-oci** [comment]
I think this is by design.  There are MPC options to change how it generates makefiles.

**Comment by jwillemsen** [comment]
ACE_ROOT and TAO_ROOT are not expanded, any suggestions why ACE_ROOT/TAO_ROOT are not expanded but DDS_ROOT is? This makes it hard to work with multiple source trees

**Comment by mitza-oci** [comment]
I think that's based on whether or not the project is in a child directory of that path.  You can change the MPC options.

**Comment by jwillemsen** [comment]
Which options @mitza-oci, I tried `-use_env` but that doesn't add DDS_ROOT

**Comment by mitza-oci** [comment]
I'm not sure, it's been a long time since I've used those options.  I don't think there's anything that we're doing in this repo to impact this, so maybe create an MPC issue?
