### ISSUE TITLE
Add user/project listing to opendds.org

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#1832]
In order to let everyone know who is using opendds maybe add a new page to opendds.org with user/project listings like ACE/TAO has http://www.dre.vanderbilt.edu/~schmidt/TAO-users.html. With some short docu about how to create a PR to add a listing to the page the user community can maintain this page directly.

**Comment by mitza-oci** [comment]
Duplicate of #512

**Comment by jwillemsen** [comment]
See #2341
