### ISSUE TITLE
Why the default Reliability  QoS is different between the writer and the reader?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1862]
I understand from the development guide that this is done in order to conform with the DDS Specification, but it sounds rather strange to me.

I guess the Reliability QoS is by default Best Effort as there is a mismatch between the writer and the reader. So in order to have it to Reliable, one needs to set the reader's Reliability QoS to Reliable as well. Is that right? Are there perhaps different levels of Reliability?

Also, what does it mean to set the topic Reliability QoS? Is the case that when the writer and reader don't explicitly define a QoS policy, then the topic's QoS is applied to both when applicable?

**Comment by mitza-oci** [comment]
> I guess the Reliability QoS is by default Best Effort as there is a mismatch between the writer and the reader.

They are not equal but they are compatible.

> So in order to have it to Reliable, one needs to set the reader's Reliability QoS to Reliable as well. Is that right? 

It's opt-in for readers.  

> Are there perhaps different levels of Reliability?

Not sure what you mean by that.  The Reliability QoS is defined by the spec.  Details of how the various transports work and can be configured are provided in the Developer's guide.

> Also, what does it mean to set the topic Reliability QoS? Is the case that when the writer and reader don't explicitly define a QoS policy, then the topic's QoS is applied to both when applicable?

Topic QoS doesn't "do" anything on its own.  It can be used to communicate QoS settings and can be used with `copy_from_topic_qos` and the related `DATAWRITER_QOS_USE_TOPIC_QOS` and `DATAREADER_QOS_USE_TOPIC_QOS` values.

**Comment by KiriakosD** [comment]
Thanks @mitza-oci, it makes much more sense now.

So if I understand it correctly it works like this:

**Writer**    -  **Reader**  ->   **Result**
Best Effort   -  Best Effort   ->  Best Effort
Reliable       -  Best Effort   ->  Best Effort
Reliable       -  Reliable       ->  Reliable
Best Effort   -  Reliable       ->  Incompatible

Is that right?

**Comment by mitza-oci** [comment]
Yes, one way to read the "Result" column in your previous comment is this: if a given Writer-Reader pair are compatible, then the Reader will get (at least) the Quality of Service "level" that it requested.

**Comment by KiriakosD** [comment]
Great! Thanks a lot for the clarification @mitza-oci
