### ISSUE TITLE
Is reliable reliability QoS supported for shmem transport?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1878]
I fell upon the following in the Developers guide, that I thought it was a bit unclear.

In Chapter 1.2.1.1 "DDS Compliance", it says that reliable is only supported for RTPS_UDP, TCP and Multicast:
_"RELIABILITY.kind = RELIABLE is supported by the RTPS_UDP transport, the TCP transport, or the IP Multicast transport (when configured as reliable)"_

I was aware that it is not supported for UDP transport as it is clearly stated (7.4.5.3 UDP/IP Transport Configuration Options), however it was not clearly stated in Shared Memory Chapter (7.4.5.6 Shared-Memory Transport Configuration Options).

On the same note, is best effort reliability QoS supported for TCP transport? I guess the answer is no since TCP is by default reliable? Or does the QoS provide an extra layer of reliability?

**Comment by mitza-oci** [comment]
The statement in 1.2.1.1 is not meant to be an exhaustive list, and the statement is silent about shmem.  I agree that this is not completely clear.

The "shmem" transport does support the Reliable setting of Reliability QoS policy.
The "tcp" transprot does support the Best Effort setting of the Reliability QoS policy.

**Comment by KiriakosD** [comment]
Thank you for the clarification @mitza-oci
