### ISSUE TITLE
Is rtps_udp the only transport type for interoperable communication between implementations?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1883]
I saw the following in the Development Guide (Chapter 7.4.5.5) and I was not sure if I understood correctly:
"The rtps_udp transport is one of the pluggable transports available to a developer and is necessary for interoperable communication between implementations."

I took a look into the eprosima fast-dds guide, and they didn't have it listed as one of the available transport types:
https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/transport.html

**Comment by simpsont-oci** [comment]
RTPS over UDP is required for interoperability between DDS implementations,
per the DDSI-RTPS spec. Some vendors have chosen to extend the RTPS
protocol format to TCP, though exactly how this is implemented isn't
standardized yet (specification is still under work).

**Comment by KiriakosD** [comment]
Thank you for the clarification @simpsont-oci!
I am still a little confused as to how the RTPS over UDP provides reliable Reliability QoS (or how tcp provides best effort Reliability QoS), but I am guessing this is not handled in the Transport Layer, but rather in the middle-ware.

**Comment by iguessthislldo** [comment]
RTPS (`rtps_udp`) can be reliable be over UDP because reliability is implemented in the `rtps_udp` transport itself. Without getting into details, if the reader detects it's missing a message it asks the writer to resend it. I believe the `tcp` transport on the other hand is inherently reliable because it's using TCP.

**Comment by mitza-oci** [comment]
> I saw the following in the Development Guide (Chapter 7.4.5.5) and I was not sure if I understood correctly:
> "The rtps_udp transport is one of the pluggable transports available to a developer and is necessary for interoperable communication between implementations."

What is this missing?

> I took a look into the eprosima fast-dds guide, and they didn't have it listed as one of the available transport types:
> https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/transport.html

Let's not confuse the issue by bringing some other project's terminology into the discussion.  You can find out from this project exactly which OMG Standards are supported.

**Comment by KiriakosD** [comment]
Thank you all for the clarifications!
I guess it was a terminology confusion after all...

I checked again the DDSI-RTPS spec and I think I get it now.

Thanks again!
