### ISSUE TITLE
Where is the actual publishing done in the source code?

### ISSUE THREAD

**Issue by KiriakosD** [objectcomputing/OpenDDS#1896]
I have been looking into the source code trying to figure out how exactly the publishing is done from a code perspective, but I am a little confused.

Is it done in the send_suspended_data function in the DataWriterImpl class?
I somehow had the impression that it is done in the PublisherImpl because in the Developers guide it is stated that "The data writer is responsible for marshaling the data and passing it to the publisher for transmission".

But it doesn't seem to be the case (although the send_suspended_data is called from within the PublisherImpl).

**Comment by KiriakosD** [comment]
On a similar note, I assume that the data when using History and Durability QoS policies are also held in the Writer and not the Publisher, right?

Is it the InstanceDataSampleList and the DataDurabilityCache in the WriteDataContainer that hold these?

**Comment by mitza-oci** [comment]
I'm not sure I'm following the question here.  Using a debugger you can break when a socket `send()` function is called.
