### ISSUE TITLE
Enum-discriminated union with all cases covered in C++11 mapping

### ISSUE THREAD

**Issue by ClaytonCalabrese** [objectcomputing/OpenDDS#1900]
Unsure the importance of this but it was something I noticed while doing tryconstruct. I removed all such instances from my c++11 test but the problem is still there.

A seg fault occurs in the idl 

my.idl:
```
enum EnumType {VALUE1, VALUE2};

union NestedUnion switch (EnumType) {
  case VALUE1: boolean u_b;
  case VALUE2: short u_s;
  default: float u_f;
};
```

console to replicate:
gdb opendds_idl
run -Lc++11 my.idl

the `e->value_to_name(dv.u.enum_val)` in  langmap_generator will be a null causing the segfault.

**Comment by mitza-oci** [comment]
The difference between this one and the enum-discriminated unions we've already tested is that the `default:` branch is not possible to reach given the two other branches already cover all enumerators.

**Comment by mitza-oci** [comment]
This is not a valid union according to OMG IDL.  Unfortunately `TAO_IDL_FE` is not rejecting it.

>  A union type can contain a default label only where the values given in the non-default labels do not cover the entire range of the union's discriminant type.

**Comment by jwillemsen** [comment]
It is marked as illegal by ridlc, maybe something to report as issue to TAO_IDL?

```
IDL::ParseError: 'default' case label superfluous for IDL::AST::Union NestedUnion
```

**Comment by ClaytonCalabrese** [comment]
enum EnumType {VALUE1, VALUE2};

union NestedUnion switch (EnumType) {
  case VALUE1: boolean u_b;
  case VALUE2: short u_s;
};

Still causes the seg fault.

**Comment by mitza-oci** [comment]
`AST_Union::default_value` results in a value that's not in the range of the enum.   I guess we need to check for that and correct it.
