### ISSUE TITLE
RTPS discovery and multicast in OpenDDS 3.14

### ISSUE THREAD

**Issue by kgobin-gallon** [objectcomputing/OpenDDS#1928]
Hello there,

I'm having trouble running my OpenDDS 3.14 application in localhost. When running the application, I always have the following exception raised:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to register multicast input handler
Abandon (core dumped)
```

which comes from that code snippet in dds/DCPS/RTPS/Spdp.cpp :

```
void
Spdp::SpdpTransport::open()
{
  reactor_task_.open(0);

  ACE_Reactor* reactor = reactor_task_.get_reactor();
  if (reactor->register_handler(unicast_socket_.get_handle(),
                                this, ACE_Event_Handler::READ_MASK) != 0) {
    throw std::runtime_error("failed to register unicast input handler");
  }

  if (reactor->register_handler(multicast_socket_.get_handle(),
                                this, ACE_Event_Handler::READ_MASK) != 0) {
    throw std::runtime_error("failed to register multicast input handler");
  }
[...]
```

It appears that my local loop does not have multicast enabled:

```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

But instead of activating multicast on lo, I would prefer to deactivate multicast for Spdp and only use unicast. It is quite difficult for us to change the network configuration of all our machines.

My configuration file:

```
[common]
DCPSGlobalTransportConfig=myconfig
DCPSDefaultDiscovery=myrtps
ORBLogFile=opendds.log

DCPSBit=0

[config/myconfig]
transports=mytcp

[transport/mytcp]
transport_type=tcp
local_address=localhost:

[rtps_discovery/myrtps]
ResendPeriod=5
SedpMulticast=0
SedpLocalAddress=localhost:
SpdpSendAddrs=localhost:17900
GuidInterface=lo
```

This is a regression from OpenDDS 3.13.3 and before, with which I had no problem running my software on localhost.
I checked the last version of master code (tag 3.15-pre18) and it looks it has been fixed, since I can run my software again.

I developped a little test to help you find what commit should have fixed this issue. When no ethernet cable is plugged (only lo interface has an IP address), this test ran in 3.13.3, does not run in 3.14, but runs again in 3.15-pre18.

```
#include <dds/DCPS/Service_Participant.h>
#include <dds/DCPS/Marked_Default_Qos.h>

#include <iostream>

int main(int /*argc*/, char **/*argv*/)
{
    TheServiceParticipant->default_configuration_file("/path/to/conf/file.ini");
    DDS::DomainParticipant_var participant = TheParticipantFactory->create_participant(42, // Domain ID
                                                                                       PARTICIPANT_QOS_DEFAULT,
                                                                                       0, // No listener required
                                                                                       OpenDDS::DCPS::DEFAULT_STATUS_MASK);
    if (!participant)
    {
        std::cerr << "create_participant failed." << std::endl;
        return 1;
    }

    TheParticipantFactory->delete_participant(participant);
    TheServiceParticipant->shutdown();
    return 0;
}
```

Would it be possible to get a 3.14.1 version that fixes this problem?

Thanks a lot!

**Comment by kgobin-gallon** [comment]
Hello,

By any chance, did you succeed in isolating a fix for this problem with OpenDDS 3.14?

We are still struggling with that regression, we cannot really go backwards and we need to run our software without network.

Thanks!

**Comment by simpsont-oci** [comment]
Hi,

Thanks for the report. We've got a few fixes lined up for a potential 3.14.1 release, but we haven't finalized the list yet. We'll be sure to test against this as we continue to work towards a release.

**Comment by kgobin-gallon** [comment]
Hi,

OK I understand. Still we need internally a fast solution, since this issue prevents us from releasing our software.

Do you think I could patch 3.14 by simply removing this code snippet in Spdp::SpdpTransport::open() ?

```
if (reactor->register_handler(multicast_socket_.get_handle(),
                                this, ACE_Event_Handler::READ_MASK) != 0) {
    throw std::runtime_error("failed to register multicast input handler");
  }
```
Would that be an acceptable fix or would it imply too many side effects?

**Comment by simpsont-oci** [comment]
Try changing the following line in LinuxNetworkConfigMonitor.cpp from:
`      add_interface(NetworkInterface(msg->ifi_index, name, msg->ifi_flags & IFF_MULTICAST));`
to:
`      add_interface(NetworkInterface(msg->ifi_index, name, msg->ifi_flags & (IFF_MULTICAST | IFF_LOOPBACK)));`

and then changing the rtps_discovery config section in your .ini to the following:

> [rtps_discovery/myrtps]
> ResendPeriod=5
> SedpMulticast=0
> SpdpLocalAddress=127.0.0.1
> SedpLocalAddress=127.0.0.1:
> SpdpSendAddrs=localhost:17900
> GuidInterface=lo

Or whatever the actual loopback address is for your machine, if it's not 127.0.0.1

I was able to get that to work on my laptop without a network connection. If that works for you, we can include something similar in 3.14.1.

**Comment by kgobin-gallon** [comment]
Hi Timothy,

Thanks a lot for your fix suggestion, it looks like working beautifully on our side too. I can now run my software without network connection, and OpenDDS communication still works, as before 3.14.

I believe you can add this to the upcoming 3.14.1 release.

Thanks for your help!

**Comment by simpsont-oci** [comment]
Glad to hear it!
