### ISSUE TITLE
Data Reader Listener Impl class not triggering on_liveliness_changed

### ISSUE THREAD

**Issue by 16thpolicy** [objectcomputing/OpenDDS#1972]
My program threads a subscriber and publisher, occasionally when I run the program there is a chance that the datareaderlistenerimpl class does not detect the liveliness change. I was wondering if there is a way to refresh detection somehow instead of rerunning the program.

**Comment by mitza-oci** [comment]
Please extend a test in the repository to demonstrate the problem.  Let us know all of the configuration details.

**Comment by rakesh218** [comment]
I'm also facing same problem,  on restart of publisher on Linux machine ,  subscribe running on windows machine stop receiving data

**Comment by rakesh218** [comment]
Using OpenDDD version 3.13.1

**Comment by jrw972** [comment]
Retry with most recent release.
