### ISSUE TITLE
centos7 in vmware cannot use rtps get messenger

### ISSUE THREAD

**Issue by Make-Stlye-Change** [objectcomputing/OpenDDS#1982]
Hi.
I have a problem .
I install opendds on centos7(x64) in vmware.
When I use the example(tests/DCPS/Messenger) on rtps way . Publisher and Subscriber can't communicate each other .
I don't know why .
Can you help me?
Thanks!

**Comment by mitza-oci** [comment]
https://phoenixnap.com/kb/how-to-disable-stop-firewall-centos

**Comment by Make-Stlye-Change** [comment]
Hi.
Thanks for you reply.
In my situation,I can't stop firewall. Did have another way to solve this problem or I can only  use DCPSInfoRepo style?
Thanks again.

**Comment by Make-Stlye-Change** [comment]
> 
> 
> https://phoenixnap.com/kb/how-to-disable-stop-firewall-centos

Hi.
Thanks for you reply.
In my situation,I can't stop firewall. Did have another way to solve this problem or I can only use DCPSInfoRepo style?
Thanks again.

**Comment by mitza-oci** [comment]
Participant discovery messages have to make it through from one process to the other.  You can decide exactly how you want that to happen.  It could involve a combination of specific firewall configuration (not just stopping the firewall service) and configuring OpenDDS's RTPS Discovery with `SpdpSendAddrs` so it doesn't depend on multicast.  See Table 7-5 in the OpenDDS Developer's Guide for details on RTPS Discovery configuration.

You can also adapt the Discovery mechanism to depend on an external service (not purely peer-to-peer).  OpenDDS has two ways of doing this:
- DCPSInfoRepo Discovery
- RtpsRelay (section 15.2 of the Developer's Guide)

**Comment by Make-Stlye-Change** [comment]
> Participant discovery messages have to make it through from one process to the other. You can decide exactly how you want that to happen. It could involve a combination of specific firewall configuration (not just stopping the firewall service) and configuring OpenDDS's RTPS Discovery with `SpdpSendAddrs` so it doesn't depend on multicast. See Table 7-5 in the OpenDDS Developer's Guide for details on RTPS Discovery configuration.
> 
> You can also adapt the Discovery mechanism to depend on an external service (not purely peer-to-peer). OpenDDS has two ways of doing this:
> 
> * DCPSInfoRepo Discovery
> * RtpsRelay (section 15.2 of the Developer's Guide)

Thanks.
I will try it .
