### ISSUE TITLE
exception while running DCPSInfoRepo inside a docker container

### ISSUE THREAD

**Issue by ShayNvidia** [objectcomputing/OpenDDS#1998]
I was working with OpenDDS inside a docker container normally until for no apparent reason I started to get exception with executing DCPSInfoRepo.
now if I run DCPSInfoRepo on the native host it works fine, but if I execute it in a docker container I get the following exception:
> ./DCPSInfoRepo -ORBEndpoint iiop://localhost:12345
(21|21) EXCEPTION, ERROR: DDS DCPS Info Repo caught exception
system exception, ID 'IDL:omg.org/CORBA/BAD_PARAM:1.0'
TAO exception, minor code = 7e (endpoint initialization failure in Acceptor Registry; low 7 bits of errno: 126 Required key not available), completed = NO

can someone help? direct me to where is the problem?

working with Ubuntu 18.04,OpenDDS version  3.12

**Comment by jrw972** [comment]
Can you provide a minimal working example to demonstrate the problem?

**Comment by ShayNvidia** [comment]
Hi Justin,
I already figured what was the problem.
I found out that the root cause for the docker to act so funnily is the /etc/hosts file.
For an unclear reason it was changed, and the 127.0.0.1 ip was not set to localhost.  So the docker container was not able to obtain the address of “localhost” and bind port correctly.
 
**before:**
>cat /etc/hosts
127.0.0.1       salon-ubuntu
127.0.1.1       salon-ubuntu
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
**after:**
>cat /etc/hosts
127.0.0.1       localhost salon-ubunut
127.0.1.1       salon-ubuntu
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

thanks anyway,
Shay
