### ISSUE TITLE
Multiple domain participants do get the same instance handle

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2046]
When we create multiple domain participants they each get the same instance handle. This is in our case problematic because we put the domain participants into a map with the instance handle as key value.

**Comment by mitza-oci** [comment]
This appears to be by design (`docs/design/INSTANCE_HANDLES`) and I don't see it as violating the spec.  But as usual with the spec, there may be something I'm missing.

**Comment by jwillemsen** [comment]
The spec says the following, having the same handle representing multiple entities doens't sound logical when a handle represents the entity

    2.2.2.1.1.8 get_instance_handle This operation returns the InstanceHandle_t that represents the Entity.

RTI talks about a global ID, see https://community.rti.com/static/documentation/connext-dds/5.2.3/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_UsersManual/Content/UsersManual/Getting_an_Entity_s_Instance_Handle.htm

Why not make the InstanceHandle_t process wide unique, that change is minimal and would enable the contains_entity to be correct, the current implementation is not checking if the handle belongs to the domain participant as described in 2.2.2.2.1.31 from the DDS spec, that operation can't be implemented correctly when InstanceHandle_t is not unique in this process

**Comment by jwillemsen** [comment]
Having thought more about this to my idea contains_entity is the main reason instancehandles should be unique within the same process else it is impossible to check if a specific handle belongs to a specific domain participant

**Comment by mitza-oci** [comment]
The spec does not require instance handles to be unique across domain participants.  Changing OpenDDS to do so may have performance implications for multi-participant applications (adding contention where there was none before).

**Comment by jwillemsen** [comment]
Generating new instance handles is an atomic, so that shouldn’t add much overhead and synchronisation. Having process wide unique instance handles would help some, especially in gateways or bridges like we do in AXCIOMA

**Comment by jwillemsen** [comment]
I don’t see a disadvantage when we make them process wide unique

**Comment by mitza-oci** [comment]
> Generating new instance handles is an atomic, so that shouldn’t add much overhead and synchronisation. 

This is the added contention that I mentioned in my previous comment.

> Having process wide unique instance handles would help some, especially in gateways or bridges like we do in AXCIOMA

The application knows which domain participant any given InstanceHandle belongs to.  So changing how InstanceHandles are assigned is not providing additional information to the application.

There is a trade-off here.  I'm not completely opposed to making the change but I don't think it's so clear cut.

**Comment by jrw972** [comment]
It seems like you can save the domain participant or other context with the handle.  Is there some reason you cannot do this in your application?

**Comment by jwillemsen** [comment]
> > Having process wide unique instance handles would help some, especially in gateways or bridges like we do in AXCIOMA
> 
> The application knows which domain participant any given InstanceHandle belongs to. So changing how InstanceHandles are assigned is not providing additional information to the application.

It currently only works when the application knows everywhere to which DomainParticipant a specific InstanceHandle_t is related, we can't use contain_entity to find that in some generic code because the InstanceHandle is not unique, all domain participants get the same handle (6 in our testing). This makes it also not possible to create a map with the InstanceHandle as key and the Domain Participant pointer as value.

I find it very trick that I can obtain a DDS::InstanceHandle_t from any DDS entity and call contains_entity on any DomainParticipant with that handle and that the result is worthless, it doesn't say a thing. What is the meaning of contains_entity at the end, shouldn't that be removed from the spec when the InstanceHandle_t is not unique?

We are storing some user data (for example a C++11 proxy object) related to each DDS entity in some maps, we did this using InstanceHandle_t as key. With OpenDDS it looks we can only use the C++ pointer as key, at the moment the DDS Entity isn't a plain C++ pointer but some proxy object (like with C++11) that also does not work anymore. At the moment the DDS::InstanceHandle_t would be process wide unique we (and others) can use the InstanceHandle_t in maps without having to know to which domain participant they belong to.

**Comment by jwillemsen** [comment]
Closing, with OpenDDS now the DDS::InstanceHandle_t is now process wide unique, thanks for accepting my changes!
