### ISSUE TITLE
domain_participant::contains_entity not working 

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2048]
Accoring to the DDS spec the domain participant provides a contains_entity to check whether a entity belongs to a domain participant. Testing showed that this doesn't work with OpenDDS because the instance handle is only unique within a domain participant itself. 

> This operation checks whether or not the given a_handle represents an Entity that was created from the DomainParticipant. The containment applies recursively. That is, it applies both to entities (TopicDescription, Publisher, or Subscriber) created directly using the DomainParticipant as well as entities created using a contained Publisher, or Subscriber as the factory, and so forth. The instance handle for an Entity may be obtained from built-in topic data, from various statuses, or from the Entity operation get_instance_handle.

**Comment by jwillemsen** [comment]
Related to #2046

**Comment by jwillemsen** [comment]
Could very likely be fixed by moving InstanceHandleGenerator from the domain participant to the domain participant factory singleton

**Comment by mitza-oci** [comment]
I'm not sure the spec requires handles that are generated from different participants work together.  There are many handles generated by participant A that represent entities that are contained in a participant B, for example the Built-In Topic handles.
I will look into this some more.  External code that wants a type for more "universal" handles could use something like `pair<DomainParticipant, InstanceHandle>`.

**Comment by jwillemsen** [comment]
What do you exactly mean with `pair<DomainParticipant, InstanceHandle>`, do you mean the address of the domain participant that is returned by the domain participant factory? Using an address also sounds risky because there is no guarantee as far as I know that the DDS vendor doesn't return a proxy which could mean that you get different address for the same domain participant at the end

**Comment by jwillemsen** [comment]
Also, when the id's are not unique, how would the user when using `lookup_participant` on the domain participant know at the end which domain participant he got when there are multiple dp for the same domain. They all have the same instance handle currently with OpenDDS

**Comment by mitza-oci** [comment]
As far as I can tell `lookup_participant` is working as specified.  Since the return type is the object itself and not an instance handle, this is not related to handles.

**Comment by jwillemsen** [comment]
`lookup_participant` is not a good example, but there are risks with that operation, there can be multiple domain participants for the same domain id, `lookup_participant` returns a random one according to the spec, so no idea to check whether we got the correct one.
