### ISSUE TITLE
Error "Could not find or load main class" on messenger example.

### ISSUE THREAD

**Issue by stefanobianconi3** [objectcomputing/OpenDDS#2119]
I am using Windows 10 with JDK 8, I am trying to run the TestPublisher java class after performing all the required steps from the develepers guide at chapter 10), running the command: 
`%DDS_ROOT%\bin\DCPSInfoRepo -o repo.ior` 
it works but then opening the cmd on massenger publisher classes folder and run:
`java -ea -cp classes:%DDS_ROOT%\lib\i2jrt.jar:%DDS_ROOT%\lib\OpenDDS_DCPS.jar:classes TestPublisher -DCPSConfigFile pub_tcp.ini
`
I got the error "Could not find or load main class TestPublisher", obviously I have the java path in my environment variables and I ran the setenv script. 

I would like to know how to start with simple java application using an IDE, I tried to create a simple java application that contains only a main method as follow:
```
import org.omg.CORBA.StringSeqHolder;
import DDS.DomainParticipant;
import DDS.DomainParticipantFactory;
import OpenDDS.DCPS.TheParticipantFactory;

public class Publisher {
public static void main(String[] args) {
	DomainParticipantFactory dpf = TheParticipantFactory.WithArgs(new StringSeqHolder(args));
}
}
```
 on eclipse by adding the .jars library (the generated ones, the OpenDDS\lib and corba-api-5.0.1.jar downloaded separately) on the classpath. At compile time I don't get any errors or warning but when I try to run the code by configuring the jvm argument  -Dopendds.native.debug=1 I get:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\OpenDDS-3.14.1\lib\OpenDDS_DCPS_Javad.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2669)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at OpenDDS.DCPS.TheParticipantFactory.loadNativeLib(TheParticipantFactory.java:34)
	at OpenDDS.DCPS.TheParticipantFactory.<clinit>(TheParticipantFactory.java:21)
	at Publisher.main(Publisher.java:9)
```

**Comment by stefanobianconi3** [comment]
I also started a new java project on eclipse and added the .jars by editing the existing jre. Now the error is:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/omg/CORBA/StringSeqHolder
	at Publisher.main(Publisher.java:8)
Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.StringSeqHolder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

**Comment by iguessthislldo** [comment]
If Java doesn't have `org.omg.CORBA`, then you'll need to include `i2jrt_corba.jar` if it's been built.

**Comment by stefanobianconi3** [comment]
Thanks for your answer. I started OpenDDS from an  Ubuntu machine and now it is working well. I downloaded the java example from: https://github.com/mitza-oci/opendds-example-java.git, and I ran it using the command prompt to compile and execute the publisher and subscriber. I will try to perform specific example for my porpose both on Ubuntu and Windows, but I would like to compile and run application from an IDE,  Do you know the right settings for eclipse or other java IDE? Thanks again.

**Comment by stefanobianconi3** [comment]
In Windows 10 using jdk1.8.0_271 I have successfully compiled my application by running:
`javac -cp "..\PATH_TO_LIB\*" ExamplePublisher.java  ` 
but if I try to run the generated bytecod with:
`java -cp ".:..\PATH_TO_LIB\*" ExamplePublisher -DCPSConfigFile ..\rtps.ini `
It returns 
`Error: Could not find or load main class ExamplePublisher`
How can I solve that? Am I making a mistake with synstax on the terminal?

**Comment by iguessthislldo** [comment]
>  I would like to compile and run application from an IDE, Do you know the right settings for eclipse or other java IDE? 

Once you have the IDL libraries built just about any Java IDE should work as long as you have your IDL library jar and the OpenDDS jars included in the project and your IDL native library and the OpenDDS native libraries set in `PATH` (Windows) or `LD_LIBRARY_PATH` (Linux). I think to add the jars in Eclipse you would use the "add external jars" option, though I don't know if they still call it that.

> How can I solve that? Am I making a mistake with synstax on the terminal?

I'm not sure. The `ExamplePublisher.class` file is in the `pub` folder, right?

**Comment by stefanobianconi3** [comment]
Yes it is in pub folder. Now I have a doubt: after performing the configure java script and then build the solution using vs2019 should I compile the solution using win32 or x64? My OS is windows 10 64 bit.

**Comment by stefanobianconi3** [comment]
> > I would like to compile and run application from an IDE, Do you know the right settings for eclipse or other java IDE?
> 
> Once you have the IDL libraries built just about any Java IDE should work as long as you have your IDL library jar and the OpenDDS jars included in the project and your IDL native library and the OpenDDS native libraries set in `PATH` (Windows) or `LD_LIBRARY_PATH` (Linux). I think to add the jars in Eclipse you would use the "add external jars" option, though I don't know if they still call it that.
> 
> > How can I solve that? Am I making a mistake with synstax on the terminal?
> 
> I'm not sure. The `ExamplePublisher.class` file is in the `pub` folder, right?

I did all the step as you suggested, but before I have recompiled the solutions in x64 from vs2019. In addition on eclipse -> run configuration there is the window called Environment, here I have copied and pasted the values from setenv.cmd. 
Now It is working, I mean it compile and run the code from the main class. Thanks again.
