### ISSUE TITLE
All tests are failing after build

### ISSUE THREAD

**Issue by aditya-krish** [objectcomputing/OpenDDS#2126]
I have cloned the repository and run the following:
`./configure --java --tests`
`make`
`source setenv.sh`
`perl bin/all_tests.pl`

Attached below is the result of the last command

![Screenshot from 2020-12-04 18-11-19](https://user-images.githubusercontent.com/55757328/101165277-612a8600-365c-11eb-87b8-e00e2e6c94dc.png)

What could be the reason for this?

**Comment by mitza-oci** [comment]
I would not recommend using `bin/all_tests.pl`.  I think that has been in the repository for a while without being used so it's unmaintained.

**Comment by aditya-krish** [comment]
Is there any other means of verifying my installation?

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/OpenDDS/blob/master/INSTALL.md#test

**Comment by aditya-krish** [comment]
I am trying to do the Messenger test by doing the following:
1) create a new directory opendds_test
2) copy the files Messenger.idl and messenger_idl_test.mpc into this folder
3) open terminal from this directory and run the following:
`$ACE_ROOT/bin/generate_export_file.pl Messenger > messenger_idl_test_Export.h`
`$ACE_ROOT/bin/mwc.pl -type gnuace`
`make`

The "make" command is failing with the following error: 
![Screenshot from 2020-12-07 17-37-20](https://user-images.githubusercontent.com/55757328/101349139-e313ec80-38b2-11eb-9f43-fb30574ff77a.png)

What is the reason? Is it a problem with my installation or am I missing some steps?

Note: Messenger.idl and messenger_idl_test.mpc are used without any change from $DDS_ROOT/java/tests/messenger/messenger_idl

**Comment by mitza-oci** [comment]
If you want to use those files unchanged, use the same command to run `generate_export_file.pl`, see the comment at the top of `messenger_idl_test_Export.h`.
