### ISSUE TITLE
wstring java idl2jni support

### ISSUE THREAD

**Issue by thrax130** [objectcomputing/OpenDDS#2140]
IDL2JNI does not support idl type wstring. Do I miss any config entry to enable support for this IDL type?
The error is at idl2jni_runtime and codegen. Codegen generates **unknown** variable types in .java Classes.

**Comment by mitza-oci** [comment]
This would be a small change if you'd like to add it.  Seems like nobody has needed it so far.

**Comment by thrax130** [comment]
Thanks, glad to hear that it would be a small change. I already tried to extend the idl2jni code gen and runtime... Especially a WString_Manager with copy2Java and copy2Cxx functions, but the &source parameter contains only a single wchar_t at runtime. I don‘t know where changes have to be made. 
Can you provide infos about classes to extend or general instructions? Thanks in advance!

**Comment by mitza-oci** [comment]
1. The codegen side is the easy one, you probably have it already:
```
diff --git a/java/idl2jni/codegen/im_java.cpp b/java/idl2jni/codegen/im_java.cpp
index c5dfc01bf..6d3c46d4a 100644
--- a/java/idl2jni/codegen/im_java.cpp
+++ b/java/idl2jni/codegen/im_java.cpp
@@ -294,6 +294,7 @@ std::string idl_mapping_java::type(AST_Type *decl)
     break;
   }
   case AST_Decl::NT_string:
+  case AST_Decl::NT_wstring:
     return "String";
   case AST_Decl::NT_enum: // fallthrough
   case AST_Decl::NT_interface: // fallthrough
diff --git a/java/idl2jni/codegen/im_jni.cpp b/java/idl2jni/codegen/im_jni.cpp
index 1ad159c4d..559dbbf71 100644
--- a/java/idl2jni/codegen/im_jni.cpp
+++ b/java/idl2jni/codegen/im_jni.cpp
@@ -295,6 +295,7 @@ string idl_mapping_jni::jvmSignature(AST_Type *decl)
     break;
   }
   case AST_Decl::NT_string:
+  case AST_Decl::NT_wstring:
     return "Ljava/lang/String;";
   case AST_Decl::NT_enum: // fallthrough
   case AST_Decl::NT_struct:  // fallthrough
```
2. For runtime, create wstring versions of the following:
```
idl2jni_runtime_Export
void copyToCxx(JNIEnv *jni, TAO::String_Manager &target, jobject source);

idl2jni_runtime_Export
void copyToJava(JNIEnv *jni, jobject &target, const TAO::String_Manager &source,
                bool createNewObject = false);

idl2jni_runtime_Export
void copyToCxx(JNIEnv *jni, CORBA::String_var &target, jobject source);
```
3. extend the test in `java/idl2jni/tests/simple/simple.idl`

**Comment by thrax130** [comment]
Thanks for your reply. It works! 
Just have another problem with UTF-16, the other publisher is using. Standard seems to be ANSI.
Do you know any mandatory (build)configuration? I am using msbuild via vs2019.
