### ISSUE TITLE
selected google test version doesn't compile with cmake on RHEL 7.5

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2167]
I am setting up a new build on rhel 7.5 and it looks the google test module used by OpenDDS doesn't work there, cmake fails, see https://buildlogs.remedy.nl/rhel75_opendds_versioned/index.html.

Looks googletest 1.10.x requires C++11 support which shouldn't be a problem on rhel75. Not sure about the correct path forward with this dependency on googletest and the need to support C++03

**Comment by jwillemsen** [comment]
I validated that googletest 1.8.0 does work (see https://github.com/google/googletest/releases/tag/release-1.8.0)

**Comment by iguessthislldo** [comment]
> https://buildlogs.remedy.nl/rhel75_opendds_versioned.

This link leads to a 404 page.

> Not sure about the correct path forward with this dependency on googletest and the need to support C++03

I don't think there is a path forward for now. If memory serves correct we are using the version we're using because it's the last to support C++03.

**Comment by jwillemsen** [comment]
Sorry, internal link, it should be https://buildlogs.remedy.nl/rhel75_opendds_versioned/index.html

**Comment by mitza-oci** [comment]
This doesn't seem like something RHEL would break between 7.4 and 7.5.  Aren't they supposed to be providing stability?

**Comment by jwillemsen** [comment]
We always explicitly validate each minor release, there is always the risk of a breaking change

**Comment by mitza-oci** [comment]
I'm not questioning the approach of trying out new platform versions.  Since this is an error from cmake and not from the code, is there a workaround?

**Comment by jwillemsen** [comment]
A downgrade to googletest 1.8.0 did resolve the cmake error. Are there any features that we really need from 1.8.1, if not, maybe merge #2168, at the moment C++11 support becomes mandatory we could upgrade to a newer googletest

**Comment by jwillemsen** [comment]
Looks this specific compiler triggers some more warning to look at

**Comment by mitza-oci** [comment]
Which version of CMake is this using?

**Comment by mitza-oci** [comment]
Worked for me using a current CMake release.  I'll update documentation since I'm doing a refresh in preparation for 3.15.

**Comment by jwillemsen** [comment]
rhel 7.5 gets shipped with `cmake version 2.8.12.2`

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/OpenDDS/pull/2183
