### ISSUE TITLE
Generic DataTypes, Datawriter and datareader

### ISSUE THREAD

**Issue by huseyin26es** [objectcomputing/OpenDDS#2179]
Hi,

Is opendds supports generictypes like DDSDynamicDataWriter, DDSDynamicDataTypeSupport in RTI DDS ?

**Comment by mitza-oci** [comment]
These are from the XTypes specification.  OpenDDS doesn't have XTypes yet, but we have a number of XTypes features planned for the 3.16 release.  We are starting with the core XTypes type system, encoding, and assignability/compatibility.  Dynamic data will come later.  As always, the timeline for new features is determined by the stakeholders.  Contact us if you're interested in contributing through code or sponsorship.

**Comment by huseyin26es** [comment]
Thank you for reply. Do you have a planned date for 3.16 release ?

**Comment by mitza-oci** [comment]
> Thank you for reply. Do you have a planned date for 3.16 release?

Next month
