### ISSUE TITLE
Issue in OpenDDS Developers Guide

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2201]
In http://download.objectcomputing.com/OpenDDS/OpenDDS-latest.pdf on page 120 there is the following text, looks a link to another section is missing

> You can also configure the publisher and subscriber transport implementations programatically, as described in . Configuring subscribers and publishers should be identical, but different addresses/ports should be assigned to each Transport Instance.

**Comment by mitza-oci** [comment]
Thanks, I added the cross-reference.
