### ISSUE TITLE
JAVA read_instance method

### ISSUE THREAD

**Issue by stefanobianconi3** [objectcomputing/OpenDDS#2220]
I am using the `read_instance` method on the data reader listener. As specified in the DDS specification it requires as fourth argument `InstanceHandle_t`. I have already used the handle on the writer side by call the register_instance method and then pass it as argoument in the `write` method (developer's guide 2.2.1). It works but now I would like to register to a specific instance (with two @key fields) on the data reader listener, how can I create the InstanceHandle_t parameter to pass?

**Comment by mitza-oci** [comment]
Readers have a `lookup_instance` method.  That sounds like what you're looking for.

**Comment by stefanobianconi3** [comment]
Perfect. Now it works perfectly. Thank you so much.
