### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by akyldz** [objectcomputing/OpenDDS#2251]
Hi, I'm trying to compile OpenDDS 3.15 at Visual Studio 2015 at Windows7. 
Project files are generated for 'vc14' configuration succesfully but I am getting 153 errors at compilation.

Please find the error log and output of show_build_config attached below.
[show_build_config.txt](https://github.com/objectcomputing/OpenDDS/files/5779955/show_build_config.txt)
[error.txt](https://github.com/objectcomputing/OpenDDS/files/5779957/error.txt)

What could be the problem with my configuration.
Thanks in advance!

**Comment by jwillemsen** [comment]
Have you installed all updates for Visual Studio 2015? Which ACE version are you using, can you attach ACE_wrappers/VERSION.txt?

**Comment by akyldz** [comment]
Visual Studio 2015 version is 14.0.23107.0
Ace version is 6.2a_p18
[VERSION.txt](https://github.com/objectcomputing/OpenDDS/files/5780217/VERSION.txt)

**Comment by jwillemsen** [comment]
Ok, that is the RTM release of Visual Studio 2015 which did have several bugs, can you install Update 3 for Visual Studio 2015? Would also recommend to upgrade your ACE version, there is a 6.2a_p19 or use the DOC group 6.5.12.

**Comment by akyldz** [comment]
I installed Update 3 for Visual Studio 2015 and solution compiled successfully.
thanks for quick response
