### ISSUE TITLE
Dropping of reliable data 

### ISSUE THREAD

**Issue by rakesh218** [objectcomputing/OpenDDS#2261]
When i am sending reliable and best efforts data,  1000 samples in one second for both with random key using rand function of range long Long  .
My reliable data stop receiving after some time.

Reception is inside wait set

**Comment by rakesh218** [comment]
Please someone should help me

**Comment by mitza-oci** [comment]
> Please someone should help me

I don't think we have sufficient information to help.  If you'd like to add a new test to OpenDDS you can do that through a fork of the repository.  That way we could see the code in question and help out.
