### ISSUE TITLE
test DevGuideExample/DCPS/Messenger case return error: transport layer failed to associate 0103000.02a0****

### ISSUE THREAD

**Issue by Luca-liu** [objectcomputing/OpenDDS#2276]
hi ~
    when i test example Messenger on two Debian linux host, i got the error info: 
     DataReaderImpl::transport_assoc_done: ERROR: transport layer failed to associate 010000.*****.00001c2
     DataReaderImpl::transport_assoc_done: ERROR: transport layer failed to associate 010000.*****.00002c2
     DataReaderImpl::transport_assoc_done: ERROR: transport layer failed to associate 010000.*****.00004c2
     DataReaderImpl::transport_assoc_done: ERROR: transport layer failed to associate 010000.*****.00003c2
     
     the environment as follow:
     OpenDDS: 3.14
     ACE+TAO: 2.2a
     Debian: 4.9.0-210-1,(2020-01-20)  X86_64

     the command as follow:
      on host A:
     ./DCPSInfoRepo -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -ORBListenEndpoints iiop://10.10.28.176:12345
    ./subscriber -ORBDebugLevel 10 -DCPSTransportDebugLevel 6 -ORBLogFile subscriber.log -DCPSInfoRepo 10.10.28.176:12345
     on host B:
    ./publisher -ORBDebugLevel 10 -DCPSTransportDebugLevel 6 -ORBLogFile publisher.log -DCPSInfoRepo 10.10.28.176:12345

    Look forward to your reply， thanks a lot ~

**Comment by Luca-liu** [comment]
hi ~
From the logs, i find the datalink is **nil**, but i don't know why

void
TransportClient::use_datalink_i(const RepoId& remote_id_ref,
                                const DataLink_rch& link,
                                Guard& guard)

**Comment by jwillemsen** [comment]
Please attach the logs and the output of `tools/scripts/show_build_config.pl`

**Comment by Luca-liu** [comment]
hi jwillemsen, thanks for your reply. Follow is the command and log files, please help to check it, thanks again.

**On host A:**
 ./DCPSInfoRepo -ORBDebugLevel 10 -DCPSTransportDebugLevel 5  -ORBLogFile DCPSInfoRepo.log -ORBListenEndpoints iiop://10.10.28.176:1234
./subscriber -ORBDebugLevel 10 -DCPSDebugLevel 10 -DCPSTransportDebugLevel 5 -ORBLogFile subscriber.log -DCPSInfoRepo 10.10.28.176:1234
[DCPSInfoRepo.LOG](https://github.com/objectcomputing/OpenDDS/files/5817996/DCPSInfoRepo.LOG)
[subscriber.LOG](https://github.com/objectcomputing/OpenDDS/files/5817997/subscriber.LOG)
[host_A_show_build_config.LOG](https://github.com/objectcomputing/OpenDDS/files/5817998/host_A_show_build_config.LOG)

**On host B:**
./publisher -ORBDebugLevel 10 -DCPSDebugLevel 10 -DCPSTransportDebugLevel 5 -ORBLogFile publisher.log -DCPSInfoRepo 10.10.28.176:1234
[publisher.log](https://github.com/objectcomputing/OpenDDS/files/5818001/publisher.log)
[host_B_show_build_config.LOG](https://github.com/objectcomputing/OpenDDS/files/5818002/host_B_show_build_config.LOG)

**Comment by Luca-liu** [comment]
configure the /etc/hosts file same on the different linux system
