### ISSUE TITLE
Registration of a customized transport type

### ISSUE THREAD

**Issue by luigima** [objectcomputing/OpenDDS#2291]
I'm trying to register my own transport implementation. However, currently I am simply guessing what I have to do, as the documentation about the Extensible Transport Framework only refers to the UDP implementation. 

Hence, I simply copied the TCP transport implementation, changed `local_info.transport_type = "tcp";` to `local_info.transport_type = "tcp2";` (analogously the same with `const char TCP_NAME[] = "tcp2";`), and configured my application as follows:

```cpp
...
cfg = TheTransportRegistry->create_config("myconfig");
inst = TheTransportRegistry->create_inst("mytcp", // name
                                           "tcp2");  // type
...
```

Further, I included my derived `TCP.h` header file. When I run my application I can observe, that `Tcp_Initializer::Tcp_Initializer()` of my derived implementation is called. So far so good. 
Unfortunately the following `ACE_Service_Config::process_directive(ace_svc_desc_TcpLoader);` seems to load the original TCP implementation.
At least I get the following error: `TransportRegistry::create_inst: transport_type=tcp2 is not registered.` 

Since I am not familiar with ACE at all I have no clue what I have to change at this point. 

I would be glad if you could lead me in the right direction and maybe add a section within the documentation which covers the steps required to actually use a customized transport implementation. I'm sure this could help others as well in future.

**Comment by mitza-oci** [comment]
I'm not sure you'll need to `process_directive`.  Copying the existing `udp` implementation is indeed suggested since it's smaller.  It doesn't have anything to do with how you want the newly-developed transport to work.  It only has to do with how the transport interacts with the other code in OpenDDS (often called "transport framework").  Is your code available in GitHub?

**Comment by luigima** [comment]
No the code is not on Github. 
According to ACE it should have been sufficient for a static service to define the following macros and then call the Service Configurator:
```
ACE_FACTORY_DEFINE(ACE_Local_Service, TcpLoader)
ACE_STATIC_SVC_DEFINE(TcpLoader,
                    ACE_TEXT("OpenDDS_Tcp2"),
                    ACE_SVC_OBJ_T,
                    &ACE_SVC_NAME(TcpLoader),
                    ACE_Service_Type::DELETE_THIS
                    | ACE_Service_Type::DELETE_OBJ,
                    0)
ACE_STATIC_SVC_REQUIRE (TcpLoader)

ACE_Service_Config::process_directive(ACE_TEXT("static OpenDDS_Tcp2"));
```
However, doing this my service cannot be located according to ACE.

This is why I bypassed the ACE way for now. Instead, I directly call the `init()` function of the Loader.
