### ISSUE TITLE
C++ version for OpenDDS

### ISSUE THREAD

**Issue by serkanozen** [objectcomputing/OpenDDS#2354]
Hi,

What is the CPP version of OpenDDS, can I build it with with a g++ with no C++11 support?

Thanks.

**Comment by jwillemsen** [comment]
OpenDDS can be compiled without C++11 support, when you have C++03 support it should work

**Comment by serkanozen** [comment]
What about c++98?

**Comment by jwillemsen** [comment]
Very likely it will work, why not just try it and see whether it works?

**Comment by jwillemsen** [comment]
Which platform/compiler are you using?

**Comment by serkanozen** [comment]
Mingw 4.9.3 on Windows and vxworks 7 as real-time OS.

**Comment by jwillemsen** [comment]
OCI supports OpenDDS on VxWorks, see https://opendds.org/documents/building.html. For MinGW, we did do some builds/tests in the past, it compiled but we had runtime issues, see https://github.com/objectcomputing/OpenDDS/issues/367. Not sure about the current status, something you would have to try.

**Comment by mitza-oci** [comment]
See https://objectcomputing.com/products/opendds/vxworks for more VxWorks info
