### ISSUE TITLE
Communication problems using multicast with performance test multicastListenerTest

### ISSUE THREAD

**Issue by lqxandxl** [objectcomputing/OpenDDS#2359]
I use the demo example in the development manual to use multicast communication, and messages can be received between two machines.
But when I use the multicastListenerTest in the performance test, transport=multicast will report an error.
such as:
When I set reliable=0, an error will be reported in dds\DCPS\Cached_Allocator_With_Overflow_T.h

pub send to sub 10000 msgs,and sub log is here:
```
      if (DCPS_debug_level >= 6)
        if (this->available() % 500 == 0)
          ACE_DEBUG((LM_DEBUG,
                     "(%P|%t) Cached_Allocator_With_Overflow::malloc %@"
                     " %Lu pool allocs %Lu pool free with %Lu available\n",
                     this, this->allocs_from_pool_.value(),//500，1000，1500 ...... 10000
                     this->frees_to_pool_.value(),//483，983，1483 ........ 9983
                     this->available()));//983，983，983 ..........  983
```

my enviroment is:
opendds 3.15
ACE+TAO-6_5_12 
windows7
vs2010

my ini like this:
```
[common]
DCPSGlobalTransportConfig=multicast_config
DCPSDefaultDiscovery=DEFAULT_RTPS
DCPSTransportDebugLevel=1

[config/multicast_config]
transports=multicast

[transport/multicast]
transport_type=multicast
#transport_type=rtps_udp
group_address=224.1.0.129:49401
reliable=0
syn_interval=12000
syn_timeout=1000000

nak_depth=10000
nak_interval=60000
nak_timeout=200000

rcv_buffer_size=2000000
ttl=3

#local_address=192.168.0.110
```

when i use demo in dev guide,multicast is ok. when i change to the performance test multicast can not work correctly.why?
what`s the difference between this two example?

i use wireshark , and can see sub`s machine can receive multicast package in network,but failed return to datareaderlistenerImpl,why?

So what is the possible reason? Supplementary note: If you use rtps_udp to communicate, there is no problem using this example. I am new to opendds, and I mainly want to test the Throughput and performance of multicast, please give me some advice, thanks!

**Comment by lqxandxl** [comment]
https://github.com/lqxandxl/opendds_log/blob/main/log_multicast/pub.log

https://github.com/lqxandxl/opendds_log/blob/main/log_multicast/sub.log

https://github.com/lqxandxl/opendds_log/blob/main/log_multicast/multicast.ini

**Comment by jrw972** [comment]
The only errors that I see from your logs are
```
ERROR: read_interval 10 is not an even divisor of the total number of samples 128
ERROR: The subscriber will never finish!
```

Arbitrarily changing the qos of the transport without changing the qos of the readers and writers may lead to undefined behavior.

In general, we do not recommend using the multicast transport for new applications as it has been superseded by RTPS.

**Comment by lqxandxl** [comment]
I restored the configuration given in the test example and did not misconfigure the qos by myself, but I still have this problem.
in ReliableSession::send_naks()

sub.log repeat this log when pub begin to send msgs.
```
00326   if (!(this->nak_sequence_.low() > 1) && !this->nak_sequence_.disjoint()) {
00327     if (DCPS_debug_level > 5) {
00328       ACE_DEBUG((LM_DEBUG, ACE_TEXT("(%P|%t) ReliableSession::send_naks local %#08x%08x ")
00329                            ACE_TEXT("remote %#08x%08x nak sequence not disjoint, don't send naks \n"),
00330                            (unsigned int)(this->link()->local_peer() >> 32),
00331                            (unsigned int) this->link()->local_peer(),
00332                            (unsigned int)(this->remote_peer_ >> 32),
00333                            (unsigned int) this->remote_peer_));
00334     }

```
@jrw972

**Comment by jrw972** [comment]
Why do you think this is an error?  It looks like debug logging to me.

Yes.  rtps can completely replace multicast.

**Comment by lqxandxl** [comment]
Because the datalistener cannot receive the callback message, there is no other error message in log.
when i change the transport==rtps_udp,it can receive message.
So I suspect that there is a problem with this multicast test example.But I can't find out where the problem is.
@jrw972
