### ISSUE TITLE
VxWorks 7 VSB build error

### ISSUE THREAD

**Issue by serkanozen** [objectcomputing/OpenDDS#2360]
Hi,

When I build VxWorks VSB after adding RPMs to it, It sees all ACE TAO ad OPENDS layers without problem. Howeever I get error below during the build. What might be the reason of error ?

$VSB_HOME/src/oci_ace-6.2.15.0/ace/OS_NS_signal.inl:22:41: error: invalid conversion from 'pid_t {aka long int}' to 'TASK_ID {aka windTcb*}' [-fpermissive]

GCC is 4.8.1.10, VxWorks 7, and C++11 support is disabled in VSB build configurations.

Thanks

**Comment by jwillemsen** [comment]
What is the code exactly in 2.2ap15, this is the code on github master

https://github.com/DOCGroup/ACE_TAO/blob/be2df3244a3cfb5070fa8b5f93c90d9e81d6edf1/ACE/ace/OS_NS_signal.inl#L19

Be aware that VxWorks isn't maintained actively due to the costs involved with it.

**Comment by mitza-oci** [comment]
VxWorks version? (SR followed by digits)
Target CPU architecture?

**Comment by serkanozen** [comment]
VxWorks 7,   BuildId: 2017-11-28T10:16:19Z
Intel X86_64

Thanks

**Comment by serkanozen** [comment]
I see that, ACE_TAO https://github.com/DOCGroup/ACE_TAO/tree/be2df3244a3cfb5070fa8b5f93c90d9e81d6edf1  has ACE version 7.0.0 whereas the ACE RPM package contains ACE version 6.2. Then, should I create new RPM packages with most recent ACE, TAO and OPENDDS source code on Github and use them as VSB layers?

**Comment by mitza-oci** [comment]
Is there a specific change in ACE 7 that resolves the issue you're seeing?
I'm still wondering which VxWorks this is.  As I commented above, the VxWorks versions are identified by the letters SR followed by 3 or digits.

**Comment by serkanozen** [comment]
Simply, ACE 7 doesn't have problematic lines such as reinterpret casting void** to int that would cause lose of precision. It has been removed in ACE 7. Data structures and code have been changed that results in not requiring reinterpret cast anymore. My vxworks version is 7, i cant find anywhere remaining version numbers you are mentioning. Is there any vxworks shell command to find it out. Thanks

**Comment by mitza-oci** [comment]
For example on https://docs.windriver.com/ you can see links for SR0660.
