### ISSUE TITLE
setenv.sh does not work

### ISSUE THREAD

**Issue by tobi4321** [objectcomputing/OpenDDS#2361]
This is my setenv.sh file. 

```Shell
# OpenDDS configure script: ./configure
export TAO_ROOT=/home/buehlto1/OpenDDS-3.16/ACE_wrappers/TAO
export PATH=${PATH}:/home/buehlto1/OpenDDS-3.16/ACE_wrappers/bin:/home/buehlto1/OpenDDS-3.16/bin
export DANCE_ROOT=unused
export DDS_ROOT=/home/buehlto1/OpenDDS-3.16
export CIAO_ROOT=unused
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/buehlto1/OpenDDS-3.16/ACE_wrappers/lib:/home/buehlto1/OpenDDS-3.16/lib
export MPC_ROOT=/home/buehlto1/OpenDDS-3.16/ACE_wrappers/MPC
export ACE_ROOT=/home/buehlto1/OpenDDS-3.16/ACE_wrappers
```

The error i got after setting some paths manually in the run_test.pl is the following:
```
fileparse(): need a valid pathname at /home/buehlto1/OpenDDS-3.16/ACE_wrappers/bin/PerlACE/TestTarget.pm line 122.
```

**Comment by iguessthislldo** [comment]
This issue is continued from [these comments](https://github.com/objectcomputing/OpenDDS/issues/2318#issuecomment-769140515).

So the `setenv.sh` looks fine. The fileparse error is about it having an invalid `$ACE_ROOT`, which would happen if it's not set. As a sanity check, can you run the following?

```Shell
bash -c 'source /home/buehlto1/OpenDDS-3.16/setenv.sh; echo $ACE_ROOT'
```

**Comment by tobi4321** [comment]
i tried the setenv.sh script with sudo su... now if i run run_test.pl im getting the following ouput... i think now thats fine. What do you think, is the output correct?

/home/buehlto1/OpenDDS-3.16/bin/DCPSInfoRepo -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
TAO (28070|28070) - Completed initializing the process-wide service context
TAO (28070|28070) - Default ORB services initialization begins
TAO (28070|28070) - ORBInitializer_Registry::register_orb_initializer 0 @0x55dca683ae70
TAO (28070|28070) - ORBInitializer_Registry::register_orb_initializer 1 @0x55dca683adf0
TAO (28070|28070) - Default ORB services initialization completed
TAO (28070|28070) - We are the default ORB ...
TAO (28070|28070) - Initializing the orb-specific services
/home/buehlto1/OpenDDS-3.16/DevGuideExamples/DCPS/Messenger/publisher  -ORBDebugLevel 10 -DCPSDebugLevel 10 -ORBLogFile publisher.log
/home/buehlto1/OpenDDS-3.16/DevGuideExamples/DCPS/Messenger/subscriber  -ORBDebugLevel 10 -DCPSDebugLevel 10 -DCPSTransportDebugLevel 6 -ORBLogFile subscriber.log
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 99
         from       = Comic Book Guy
         count      = 0
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 100
         from       = Comic Book Guy
         count      = 1
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 101
         from       = Comic Book Guy
         count      = 2
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 102
         from       = Comic Book Guy
         count      = 3
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 103
         from       = Comic Book Guy
         count      = 4
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 104
         from       = Comic Book Guy
         count      = 5
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 105
         from       = Comic Book Guy
         count      = 6
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 106
         from       = Comic Book Guy
         count      = 7
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 107
         from       = Comic Book Guy
         count      = 8
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1
Message: subject    = Review
         subject_id = 108
         from       = Comic Book Guy
         count      = 9
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 2
INFO: /home/buehlto1/OpenDDS-3.16/bin/DCPSInfoRepo being killed.

**Comment by iguessthislldo** [comment]
Yes, the output is correct, but you shouldn't have had to use `su` to do it. If you start a new terminal you should be able to run:

```Shell
source /home/buehlto1/OpenDDS-3.16/setenv.sh
cd /home/buehlto1/OpenDDS-3.16/DevGuideExamples/DCPS/Messenger
perl run_test.pl
```

**Comment by tobi4321** [comment]
This is not working. Here my output:

buehlto1@DESKTOP-9SA7I26:~/OpenDDS-3.16$ source /home/buehlto1/OpenDDS-3.16/setenv.sh
buehlto1@DESKTOP-9SA7I26:~/OpenDDS-3.16$ cd /home/buehlto1/OpenDDS-3.16/DevGuideExamples/DCPS/Messenger
buehlto1@DESKTOP-9SA7I26:~/OpenDDS-3.16/DevGuideExamples/DCPS/Messenger$ perl run_test.pl
/home/buehlto1/OpenDDS-3.16/bin/DCPSInfoRepo -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
TAO (28096|28096) - Completed initializing the process-wide service context
TAO (28096|28096) - Default ORB services initialization begins
TAO (28096|28096) - ORBInitializer_Registry::register_orb_initializer 0 @0x56425b966e70
TAO (28096|28096) - ORBInitializer_Registry::register_orb_initializer 1 @0x56425b966df0
TAO (28096|28096) - Default ORB services initialization completed
TAO (28096|28096) - We are the default ORB ...
TAO (28096|28096) - Initializing the orb-specific services
Unexpected initialization Error: Unable to open IOR file.
ERROR: waiting for Info Repo IOR file
ERROR: </home/buehlto1/OpenDDS-3.16/bin/DCPSInfoRepo> failed: No such file or directory

**Comment by iguessthislldo** [comment]
Okay, then if you needed to use `sudo` earlier, then are the permissions messed up on the directory?

**Comment by tobi4321** [comment]
Yes, i saw that the OpenDDS folder did not have enough permissions...

**Comment by iguessthislldo** [comment]
Okay, well then it sounds like the permissions have to be fixed, you can you `chown` and/or `chmod` to do that. I'm going to go ahead and close the issue because it sounds like `setenv.sh` is working just fine.

**Comment by tobi4321** [comment]
thanks for your help.
