### ISSUE TITLE
opendds_idl depends on opendds core libs with the XTypes additions

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2365]
For cross compilation we did only build ace, tao_idl, and opendds_idl as part of AXCIOMA. With the addition of XTypes we found opendds_idl is now dependent on the opendds core libraries due to the usage of hash_member_name_to_id, which is pulled in from dds/DCPS/XTypes/TypeOpbject.h, see https://github.com/objectcomputing/OpenDDS/blob/952bc530d3b65f6b15ccd921f7a905e747a4da05/dds/idl/be_global.cpp#L13

This means that for cross compilation in the host build also the OpenDDS core has to be compiled, just for this hash function :-(, which at that moment also means that tao itself also has to be compiled in a host build and that we have to generate IDL files and compile a lot of code in the host build compared to just opendds_idl before XTypes

**Comment by jwillemsen** [comment]
Found that we only need OpenDDS_Util.mpc, testing that now

**Comment by mitza-oci** [comment]
Right, it was designed to not have a circular dependency since that would not work.
See the MPC and configure script changes in https://github.com/objectcomputing/OpenDDS/pull/1861

**Comment by jwillemsen** [comment]
Why does OpenDDS_Util.mpc not have its own export file with export macro? OpenDDS_Dcps_Export is used for the core OpenDDS lib and OpenDDS_Util

**Comment by jwillemsen** [comment]
Closing this one as it looks OpenDDS_Util.mpc does the trick, will open a new issue for an unique export file/macro for OpenDDS_Util
