### ISSUE TITLE
OpenDDS_Util should use its own export file/macro

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2366]
The OpenDDS_Util.mpc file and its sources/headers doesn't use its own unique export file, it uses `OpenDDS_Dcps_Export` which is also used for the core OpenDDS library. OpenDDS_Util should use its own file and macro to make clear that the symbols are from a separate library. See #2365

**Comment by mitza-oci** [comment]
There is no need for this.  No other code depends on both libraries.

**Comment by mitza-oci** [comment]
The current scheme has undergone lots of testing with different kinds of builds including safety profile and cross-compiled.  If there are problems with it please post the error you're seeing.

**Comment by jwillemsen** [comment]
It works technically but when there would be a separate export file/macro it would be clear from the header files which files are put in which shared library, when looking at the headers I found everywhere `OpenDDS_Dcps_Export` which gave me the false impression that the hash functions are part of the `OpenDDS_Dcps` library. From a maintenance side it would help to make this explicit through a separate export macro

**Comment by mitza-oci** [comment]
The same code is in both libraries.  This is by design.
