### ISSUE TITLE
Split XTypes IDL test files to reduce memory usage

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2368]
The following XTypes IDL tests result in huge source files which take a lot of memory to compile. When using -j2 a 4GB Linux VM gcc does frequently run out of memory. When the IDL files are split in smaller ones each separate run of gcc will consume less memory

```
tests/DCPS/Compiler/TryConstruct
tests/DCPS/Compiler/xcdr
```

**Comment by ClaytonCalabrese** [comment]
I am currently in the process of splitting these idl files.  It will results in some code duplication across the idl but the TypeSupportImpl.cpp will be smaller. Any duplicated types are going to be prefixed with which idl file they originate from if not the original.
