### ISSUE TITLE
Using OctetSeq

### ISSUE THREAD

**Issue by hyeinkwon798** [objectcomputing/OpenDDS#2371]
Hi I’m a uni student in South Korea 
Im studing dds for real time video sending to sub from pub
I use mat data and I just finished to change the data, mat to chararray
Now i want to use octetseq to send the char (which have been translated from mat data), pub to sub but i cant find any api using octetseq 

char buffer[imagesize]

How could i send this data using octetseq in pub?? 
And how could i receive it in sub???

this project will make me a chance to stay in lab after i graduate
Please help . It will be really helpful
Thank you

**Comment by simpsont-oci** [comment]
OctetSeq will be a typedef of a TAO sequence type. You can call
sequence.length() to set the size of the sequence to be the same size as
your char array, and then call memcpy() to copy your data into the OctetSeq.

**Comment by mitza-oci** [comment]
There are a number of tests in the repository that use IDL sequences of octet.  One example is `tests/DCPS/LargeSample`.

**Comment by hyeinkwon798** [comment]
Thank you all!! I will try it with the informations👍👍👍👍
I wish i could tell that i maked it!! 
See you later😄😄

**Comment by Saurabh996** [comment]
For a project, I also do require to use sequence<octet> data structure, but for some reason the compiler is not able to recognize the variable, help on this will be highly helpful. .idl file is defined as 
`
#include <tao/OctetSeq.pidl>

module Messenger {

  typedef sequence<octet> OctetSeq;
  
  @topic
  struct Message {
    string from;
    string subject;
    @key long subject_id;
    string text;
    long count;
    OctetSeq bfr;
  };
};`

When bfr variable is populated in Publisher.cpp, following error is encountered on running make: 

`[ 23%] Building CXX object CMakeFiles/publisher.dir/Publisher.cpp.o
/home/saurabh/dds2/OpenDDS/DevGuideExamples/DCPS/Messenger/Publisher.cpp: In function ‘int main(int, ACE_TCHAR**)’:
/home/saurabh/dds2/OpenDDS/DevGuideExamples/DCPS/Messenger/Publisher.cpp:164:15: error: ‘struct Messenger::Message’ has no member named ‘bfr’
  164 |       message.bfr.push_back(i);
      |               ^~~
make[2]: *** [CMakeFiles/publisher.dir/build.make:105: CMakeFiles/publisher.dir/Publisher.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/publisher.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
`
Please suggest a way to resolve the error.

Thanks in Advance.

Saurabh

**Comment by jwillemsen** [comment]
Looks you have to rerun `opendds_idl` on your idl file to regenerated the types

**Comment by Saurabh996** [comment]
Yes @jwillemsen, this works. Thanks a lot for helping out. Cheers!!

**Comment by jwillemsen** [comment]
Don't steal an old issue when you have a problem, just open a new one
