### ISSUE TITLE
Using OctetSeq 2

### ISSUE THREAD

**Issue by hyeinkwon798** [objectcomputing/OpenDDS#2373]
I have used OctetSeq ... but  the pub has the error

```
EXCEPTION, Exception caugth in main():
system exception, ID 'IDL:omg.org/CORBA/BAD_PARAM:1.0'
unknown vendor minor code id (0), misor code = 0, completed = NO
WARNIG: DataLink[0x6b617158]::~DataLink() = link still in use by 1 entities when deleted!!
```

the code is this

<idl>

```
module Messenger{

#pragma DCPS_DATA_TYPE "Messenger::Message"
#pragma DCPS_DATA_KEY "Messenger::Message subject_id"

typedef sequence<octet> OctetSeq;

	struct Message{
		string from;
		string subject;
		long subject_id;
		string text;
		long count;
		char ch;    //i didn't use this in my code:)
		OctetSeq data;
	};
};

```

<publisher.cpp>
```C++
Mat img;
img = Mat::zeros(480, 640, CV_8UC3);
int imgSize = img.total*img.elemSize();
char buffer[imgSize];

while(1)
{
cap >> img;
memcpy(buffer, img.data, imgSize);
for(int i=0; i<imgSize; i++)
    message.data[i] = buffer[i];

DDS::ReturnCode_t error = message_writer->writ(message, DDS::HANDLE_NIL);
}
```

<sub-DataReaderListenerImple.cpp>
```C++
Mat image;
image = Mat::zeros(480, 640, CV_8UC3);
int imageSize = image.total*image.elemSize();

while(1)
{
char buffer[imageSize];
for(int i=0; i<imageSize; i++)
    buffer[i] = message.data[i];

Mat img(48, 640, CV_8UC3);
imgshow("OpenCV video Sub", img);
if(waitKey(25) == 27) break;
}
```

Did i do something wrong with the receiving or sending octetdata?? 
Need some help!!!

**Comment by iguessthislldo** [comment]
Sequences need their length to be set before you can assign values, have you done that?

For example this should do what you need:
```C++
message.data.length(imageSize);
```

Also once you set the length you should be able copy to the sequence directly, so instead of:

```C++
memcpy(buffer, img.data, imgSize);
for(int i=0; i<imgSize; i++)
    message.data[i] = buffer[i];
```

You can just do the copy once, which I imagine would be important when moving video frames around.

```C++
memcpy(&message.data[0], img.data, imgSize);
```

I don't know if we have hard guarantees of this like `std::vector`, but it seems to work in a little test I did.

**Comment by hyeinkwon798** [comment]
um then i have a question.
If I just copy the data once, like this in pub
memcpy(&message.data[0], img.data, imgSize);

how could i receive the data in sub??

I am little weak in basic, just a beginner :(

> Sequences need their length to be set before you can assign values, have you done that?
> 
> For example this should do what you need:
> 
> ```c++
> message.data.length(imageSize);
> ```
> 
> Also once you set the length you should be able copy to the sequence directly, so instead of:
> 
> ```c++
> memcpy(buffer, img.data, imgSize);
> for(int i=0; i<imgSize; i++)
>     message.data[i] = buffer[i];
> ```
> 
> You can just do the copy once, which I imagine would be important when moving video frames around.
> 
> ```c++
> memcpy(&message.data[0], img.data, imgSize);
> ```
> 
> I don't know if we have hard guarantees of this like `std::vector`, but it seems to work in a little test I did.

**Comment by hyeinkwon798** [comment]
um then i have a question.
If I just copy the data once, like this in pub
memcpy(&message.data[0], img.data, imgSize);

how could i receive the data in sub??

I am little weak in basic, just a beginner :(

**Comment by hyeinkwon798** [comment]
thank you !! i Did it sending video (but little slowly ) :)

**Comment by guotuLuo** [comment]
@iguessthislldo bro, you are the most handsome man i've ever seen, you save me
