### ISSUE TITLE
QoS transport priority not set

### ISSUE THREAD

**Issue by Purdbull** [objectcomputing/OpenDDS#2379]
Hello,

I tried to set the qou transport priority like this in the publisher:

```
  DDS::TopicQos default_topic_qos;
    participant->get_default_topic_qos(default_topic_qos);
    default_topic_qos.transport_priority.value = 46;

    // Create Topic (Movie Discussion List)
    CORBA::String_var type_name = ts->get_type_name();
    DDS::Topic_var topic =
      participant->create_topic("Movie Discussion List",
                                type_name,
                                TOPIC_QOS_DEFAULT,
                                0,
                                OpenDDS::DCPS::DEFAULT_STATUS_MASK);


```

But the Divserv isnt changing. What am I doing wrong?

Thank you for your help!!

**Comment by jwillemsen** [comment]
Hi,

> I tried to set the qou transport priority like this in the publisher:

You need to pass the changed topic QoS to the `create_topic` call, so use
 
```
  DDS::TopicQos default_topic_qos;
    participant->get_default_topic_qos(default_topic_qos);
    default_topic_qos.transport_priority.value = 46;
 
    // Create Topic (Movie Discussion List)
    CORBA::String_var type_name = ts->get_type_name();
    DDS::Topic_var topic =
      participant->create_topic("Movie Discussion List",
                                type_name,
                                default_topic_qos,
                                0,
                                OpenDDS::DCPS::DEFAULT_STATUS_MASK);
```

The `get_default_topic_qos` call does have a return value which you should check for `DDS::RETCODE_OK`

**Comment by Purdbull** [comment]
Hi,

I changed the Publisher and Subscriber according to your answer and still got no change in the Divserv..

Btw Thank you for the support and fast answer!

**Comment by jwillemsen** [comment]
Would recommend to enable logging and see what is happening, do you see the transport priority used?

**Comment by Purdbull** [comment]
How do I enable logging?

**Comment by jwillemsen** [comment]
See http://download.objectcomputing.com/OpenDDS/OpenDDS-latest.pdf, chapter 7.6

**Comment by Purdbull** [comment]
(2906|2910) RtpsUdpDataLink::process_data_i(DataSubmessage) - data seq: 7763 from 0103dca6.323eafe4.0b15257e.00000002(4454f9d2) to 0103dca6.323eafe4.0b5ae396.00000007(5968797a) OK to deliver
(2906|2910) RtpsUdpReceiveStrategy[0xb451b4d8]::deliver_sample_i: readers_selected ids: 0103dca6.323eafe4.0b5ae396.00000007(5968797a)
 readers_withheld ids:
(2906|2910) RtpsUdpReceiveStrategy[0xb451b4d8]::deliver_sample_i - calling DataLink::data_received_include for seq: 7763 to readers_selected_
(2906|2910) DataLink::data_received_i: from publication 0103dca6.323eafe4.0b15257e.00000002(4454f9d2) received sample: INSTANCE_REGISTRATION (0x02), Length: 12, Byte order: Little Endian, CDR Encapsulation, Key Fields Only, Sequence: 0x1e, Timestamp: 1612274777.970151999, Publication: 0103dca6.323eafe4.0b15257e.00000002(4454f9d2).
(2906|2910) RtpsUdpDataLink::process_data_i(DataSubmessage) - data seq: 7764 from 0103dca6.323eafe4.0b15257e.00000002(4454f9d2) to 0103dca6.323eafe4.0b5ae396.00000007(5968797a) OK to deliver
(2906|2910) RtpsUdpReceiveStrategy[0xb451b4d8]::deliver_sample_i: readers_selected ids: 0103dca6.323eafe4.0b5ae396.00000007(5968797a)
 readers_withheld ids:
(2906|2910) RtpsUdpReceiveStrategy[0xb451b4d8]::deliver_sample_i - calling DataLink::data_received_include for seq: 7764 to readers_selected_
(2906|2910) DataLink::data_received_i: from publication 0103dca6.323eafe4.0b15257e.00000002(4454f9d2) received sample: SAMPLE_DATA (0x00), Length: 72, Byte order: Little Endian, CDR Encapsulation, Sequence: 0x1e, Timestamp: 1612274777.970151999, Publication: 0103dca6.323eafe4.0b15257e.00000002(4454f9d2).
SampleInfo.sample_rank = 0
SampleInfo.instance_state = 1


--------------------------------------------------------------------------------------------------------------------------------

that is my output on level 10

**Comment by jwillemsen** [comment]
See tests/DCPS/Priority for a unit test, would recommend to try that one first
