### ISSUE TITLE
Makefile not created

### ISSUE THREAD

**Issue by Purdbull** [objectcomputing/OpenDDS#2413]
Hello,

I tried to build my own application with DDS. I followed the Dev Guide instructions along and when it came to mpc, the main GNUmakefile wasn't created so i can't "make" my application. I then looked up the Messenger.mpc file in the DevGuideExamples Messenger and found no difference to my .mpc file. When I deleted the GNUmakeFile in the DevGuideExamples Messenger and ran mpc, it wasn't recreated. I found out that when I "make" the whole DDS Directory (I am using a Raspberry Pi 4) the GNUmakeFile in the DevguideExamples Messenger is created. I cant find any Documentation or code in the examples that tell me how to create the main Makefile for my application. Where can i find it?
Thank you for your help!

**Comment by mitza-oci** [comment]
I don't think we have enough details in the issue description, but you can use the MPC documentation to learn how it works: https://github.com/objectcomputing/MPC/tree/master/docs

For additional assistance here please provide the steps to reproduce the issue you're seeing including the commands you've tried running.
