### ISSUE TITLE
Much Ram Allocated

### ISSUE THREAD

**Issue by Purdbull** [objectcomputing/OpenDDS#2425]
Hello

Ive configured and built OpenDDS on a Raspberry pi 4 like this:

./configure --no-built-in-topics
make

Still, a running Publisher or Subscriber allocates around 55 MB. Is this decreasable? 5-10 MB would be perfect!

Thank you for your help

**Comment by mitza-oci** [comment]
Yes, there are a lot of configuration options that can impact memory usage including at build time (see `./configure --help)`, QoS policies, and runtime configuration options (see Developer's Guide).  In particular I suggest considering disabling unused features during `configure`, using a static build, and only including the transport and discovery libraries that you'll be using.
