### ISSUE TITLE
[opendds.org] Update Article-Intro.html to use annotations

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2455]
https://opendds.org/about/articles/Article-Intro.html needs to be updated to use IDL annotations instead of the deprecated pragma's

**Comment by mitza-oci** [comment]
In general the articles are snapshots of that particular time, but this is a good one to change to use the new annotations.
Source is here https://github.com/objectcomputing/OpenDDS/blob/gh-pages/about/articles/Article-Intro.html

**Comment by jwillemsen** [comment]
More could be done to this article, remove the usage of TimeBase to really simplify it and more code looks to be outdated compared to the example code which is in the repo
