### ISSUE TITLE
Support for glibc 2.27 - features.h not found

### ISSUE THREAD

**Issue by RamakrishnanOSS** [objectcomputing/OpenDDS#2480]
Hi. Can you provide support for glibc v2.27.

I always receive features.h not found compilation error.

Reproducible in latest master.

`ACE_wrappers/ace/config-linux-common.h:18:10: fatal error: features.h: No such file or directory
 #include <features.h>
          ^~~~~~~~~~~~
compilation terminated.`

Thanks.

**Comment by jwillemsen** [comment]
glibc v2.27 should work, it does contain a features.h. We really lack details about your environment, can you run `tools/scripts/show_build_config.pl` and give more details about your exact OS/compiler.

**Comment by RamakrishnanOSS** [comment]
================ setenv.sh ================
# OpenDDS configure script: ./configure --no-debug --optimize --java
export JAVA_PLATFORM=linux
export CIAO_ROOT=unused
export PATH=${PATH}:/home/user/DDS/source/OpenDDS/ACE_wrappers/bin:/home/user/DDS/source/OpenDDS/bin
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export TAO_ROOT=/home/user/DDS/source/OpenDDS/ACE_wrappers/TAO
export DDS_ROOT=/home/user/DDS/source/OpenDDS
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/DDS/source/OpenDDS/ACE_wrappers/lib:/home/user/DDS/source/OpenDDS/lib
export RAPIDJSON_ROOT=/usr
export DANCE_ROOT=unused
export ACE_ROOT=/home/user/DDS/source/OpenDDS/ACE_wrappers
export MPC_ROOT=/home/user/DDS/source/OpenDDS/ACE_wrappers/MPC
================ user_macros.GNU ================
java_pre_jpms=0
java=1
no_rapidjson=0
================ VERSION.txt ================
This is OpenDDS version 3.17-dev (NOT A RELEASE)
================ ACE Version ================
#define ACE_VERSION "6.2a_p19"
================ default.features ================
no_cxx11=0
java_pre_jpms=0
java=1
no_rapidjson=0
java_pre_jpms=0
java=1
no_rapidjson=0
java_pre_jpms=0
java=1
no_rapidjson=0
================ platform_macros.GNU ================
debug = 0
optimize = 1
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
================ config.h ================
#include "ace/config-linux.h"

**Comment by jwillemsen** [comment]
[Remedy IT](https://www.remedy.nl) does cross compile OpenDDS for Yocto 2.5.3 as part of our [AXCIOMA](https://www.axcioma.org) integration, see [here](https://www.axcioma.org/scoreboard.html) for our builds. We don't use configure for this, AXCIOMA has some additional tooling which does much more. 

You need to setup a cross compile build, see https://github.com/objectcomputing/OpenDDS/blob/master/INSTALL.md#cross-compiling for some starter information.

**Comment by mitza-oci** [comment]
You can use the Raspberry Pi info as a tutorial on cross-compiling https://opendds.org/quickstart/GettingStartedPi.html

OpenDDS's yocto layer is at https://github.com/oci-labs/meta-opendds
