### ISSUE TITLE
error in lookup of symbol uint32?

### ISSUE THREAD

**Issue by spyhunter99** [objectcomputing/OpenDDS#2483]
Does opendds support uint32 or uint64? Seems like that's part of the idl spec. I went through all the sample idl files and couldn't find any examples of using any variant of integer. Am I missing something?

**Comment by jwillemsen** [comment]
You mean in IDL itself or in C++? The IDL4 extension for stdint types is not supported yet by tao_idl, see https://github.com/DOCGroup/ACE_TAO/pull/840. This needs some sponsoring or someone to dive into to be completed.

**Comment by mitza-oci** [comment]
In IDL, `unsigned long` is always 32-bit and `unsigned long long` is always 64-bit.

There are newer IDL features to have other ways of specifying these types, but they're not really adding any new functionality.

**Comment by spyhunter99** [comment]
Thanks for the confirmation. I have an idl i was trying to implement and uses uint32 and uint64 everywhere.

**Comment by mitza-oci** [comment]
You could add typedefs to make existing IDL work with different type names.
