### ISSUE TITLE
SEDP messages not shown at Wireshark

### ISSUE THREAD

**Issue by akyldz** [objectcomputing/OpenDDS#2498]
When I execute example messenger publisher and subscriber applications with -DCPSConfigFile parameter, SPDP and user defined topic messages can be sniffed with Wireshark. (Publisher and Subscriber applications are running on the same machine.)

But SEDP messages are not shown at Wireshark. Does OpenDDS handle endpoint discovery in a way other than SEDP for this scenario?

**Comment by simpsont-oci** [comment]
Without really knowing anything about your setup: If you can see SPDP
messages in Wireshark and the participants are compatible, you should see
SEDP as well. In wireshark, the publication and subscription announcement
messages will be labeled as "Data(w)" and "Data(r)", respectively.

**Comment by mitza-oci** [comment]
What you're describing could happen if Wireshark is capturing multicast but not unicast traffic.  (SEDP may use multicast as well, depends on configuration.)  Which interface(s) are you using in Wireshark?

**Comment by akyldz** [comment]
My system has single ethernet interface. Wireshark is only capturing RTPS packages with destination IP 239.255.0.1 and 239.255.0.2 .

**Comment by simpsont-oci** [comment]
Which config file are you passing via DCPSConfigFile? If you're using a
custom config file, what's the value of SEDPMulticast in your RtpsDiscovery
section?

Does your machine have a loopback adapter and are you including it in your
capture with Wireshark? Have you tried simply capturing all UDP traffic on
all interfaces on your machine and just using "rtps" as your display filter?

**Comment by mitza-oci** [comment]
On Windows use "Npcap Loopback Adapter", on Linux use the "any" adapter.

**Comment by akyldz** [comment]
After installing "Npcap Loopback Adapter" wireshark can capture SEDP messages. Thanks for quick response.
