### ISSUE TITLE
Raspberry Pi: wrong ELF class: ELFCLASS64 (possible cause:architecture word width mismatch)

### ISSUE THREAD

**Issue by stefanobianconi3** [objectcomputing/OpenDDS#2553]
I have built using cross-compile (--java) OpenDDS using a Linux host as specified in the Quickstart raspberry guide. Then I copied it to my raspberry and I am able to run the tests. Then from it I am also able to run a simple java class just creating TheParticipantFactory and DomainParticipant.

Now I generated my idl and mpc file as specified in the Developer's Guide and I generated on my host computer the libraries for java binding (using OpenDDS compiled for Linux x64) . Then I copied that folder on the raspberry and I linked the library containing the folder to the path. 

Now I am able to compile my java application including write operation but when I try to run it I get the error:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/pi/lib/heating/libHeating.so.3.16.0: /home/pi/lib/heating/libHeating.so.3.16.0: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch) `

This because maybe I generated the libraries from a Linux x64 host, but how should I generate the libraries from idl file to be compatible with raspberry?

**Comment by mitza-oci** [comment]
The cross-compiled OpenDDS for Raspberry Pi workspace includes the example projects in `DevGuideExamples/DCPS/Messenger`.  You can create the libraries from your own IDL the same way.

**Comment by stefanobianconi3** [comment]
Since I am using OpenDDS with java bindings, I checked the build/target/java/tests/messenger and the mpc file used for the generation is similar, the error comes when i try tu run my application because the library is for 64 bit jvm, so I don't know if I have to compile the generated mpc using a specific compiler.

**Comment by mitza-oci** [comment]
When we set up the Raspberry Pi quick start guide there was no 64-bit support available.  (If I remember correctly the hardware on the Pi 3 was 64-bit but the Linux distro was 32-bit only).  To use a 64-bit JVM you will need OpenDDS built for that same architecture.

**Comment by stefanobianconi3** [comment]
Actually on mi raspberry I have the 32 distro, what I think is 64 bit is the idl library generated from OpenDDS (libFoo.so) since I generate it from a 64 linux host machine.
