### ISSUE TITLE
DevGuideExamples are created when configured with --no-tests

### ISSUE THREAD

**Issue by vermaete** [objectcomputing/OpenDDS#2573]
Hi,

In OpenDDS-3.16, configured with `./configure --doc-group3 --no-tests` the make does go into e.g.
`make[1]: Entering directory '.../OpenDDS/DevGuideExamples/DCPS/Messenger.minimal'` and others.

I would expect that this should not be done.

br,

**Comment by vermaete** [comment]
This is related to an older issue:  #1010 
Anyhow: my point of view:
  * When building for embedded devices with Yocto, I prefer to keep things as small as possible.
  * Changing the build system in OpenDDS isn't fun.  Well, changing whatever build system isn't fun. 

So, to have a small bitbake recipe and image having a --no-examples | --examples switch in the configure would be great.

Thanks for all the good work!

**Comment by mitza-oci** [comment]
Right, as has been discussed previously the DevGuideExamples are not tests.  Adding a new option to `configure` is not a problem.

But before changing configure, try running it and tell it to customize how it calls MPC, for example:
```
"--mpcopts=-exclude DevGuideExamples"
```
Note that the quoting (which may be different based on the system or shell you're using) is to make this whole thing appear as one argument to `configure` even though it contains a space.

If this works it would be a very simple enhancement to make `configure --no-examples` a shortcut for this (or something very similar).
