### ISSUE TITLE
Content-Filtered Topic not filtered at the publisher

### ISSUE THREAD

**Issue by luigima** [objectcomputing/OpenDDS#2581]
In my application I implemented a rather simple content-filtered topic which each entity within the network subscribes to. So far it worked without any issues. However, while running scalability tests I noticed that the traffic increased exponentially while I expected linear growth.

It turned out that even data readers who should not receive any samples (due to filtering) are still consuming network traffic, indicating that the filter is not working as intended. Samples are dropped upon receiving though, at least no message is received on higher levels.

The documentation of the `DCPSPublisherContentFilter` argument hints that "...the publisher may drop any samples, before handing them off to the transport when these samples would have been ignored by **all** subscribers". Does this mean that filtering is only done at the publisher if no subscriber at all would consume the sample? Otherwise, filtering is done at the subscriber?

I'm using pretty much default qos policies.

**Comment by mitza-oci** [comment]
> I noticed that the traffic increased exponentially while I expected linear growth.

Which transport type?

> Does this mean that filtering is only done at the publisher if no subscriber at all would consume the sample?

No, it is not that strong of a statement.  The documentation states what will happen at the publisher in a specific case ("would have been ignored by all subscribers").  If you're looking at a different case then it comes down to each transport library to determine if and how it's going to handle writer-side filtering.

**Comment by luigima** [comment]
In my case its TCP.

**Comment by luigima** [comment]
Where can I find more information about how content filtered topics work depending on what transport library is used? I can image that its different for transports using multicast, but what about `dds/DCPS/transport/tcp`?

**Comment by mitza-oci** [comment]
The `tcp` transport creates a distinct object called a `DataLink` for each logical connection between transport instances.  So from a single DataWriter's point of view, it has a set of `DataLink`s representing the associated DataReaders.  Each `DataLink` can potentially be used for more than one DataReader (for example, multiple readers on the same topic in the same application).

When filtering is used, the DataWriter will consider each `DataLink` in turn and only send the data sample to a `DataLink` that has at least one DataReader that should receive the data.

**Comment by luigima** [comment]
Then I suspect a trivial mistake in my implementation. Using Wireshark I noticed that the content filtering flag is indeed set in corresponding samples. However, it also says "Number of Content Filters: 0".

Here's the revelant piece of code which might be the issue:
`std::string topicNameFiltered(XYZ_TOPIC);
    topicNameFiltered.append("-Filtered");

    DDS::StringSeq topicfiltered_params(1);
    topicfiltered_params.length(1);
    topicfiltered_params[0] = instanceName.c_str();

    topicFiltered = participant->create_contentfilteredtopic(
            topicNameFiltered.c_str(), topic,
            "receiving_instance = %0",
            topicfiltered_params);`

**Comment by mitza-oci** [comment]
I don't think there's any issue with the code you posted.

Try running the included test in `tests/DCPS/ContentFilteredTopic`.  Run the script twice, once with publisher-side filtering enabled and again without it.

```
run_test.pl -d > pub_filter.log 2>&1        
                                         
run_test.pl -d nopub > nopub_filter.log 2>&1
```

The two log files (and the corresponding Wireshark capture if you're doing that too) are different.  In particular, search for the string `filtered-out` in the log.
