### ISSUE TITLE
Unsupported MacOS version 11.2.3.  [ACE] Error 2

### ISSUE THREAD

**Issue by sa33ddeveloper** [objectcomputing/OpenDDS#2595]
I was trying to follow the instructions and install OpeDDS on MacOS. after i entered "make"command i got the following error:

/OpenDDS-3.16/ACE_wrappers/include/makeinclude/platform_macosx.GNU:38: *** Unsupported MacOS version 11.2.3.  Stop.
make: *** [ACE] Error 2

is there any way to go around this problem? 
thanks

**Comment by jwillemsen** [comment]
Have you tried to run configure using `--doc-group3` to use the latest DOC group ACE/TAO release?

**Comment by mitza-oci** [comment]
Supported platforms are listed here: https://opendds.org/documents/building.html
Since we don't do testing on macOS 11.x we don't know if this is going to work (no matter which ACE you end up using).
Any help you can provide, in terms of extending support to those platforms that are important to you, would be appreciated.

**Comment by sa33ddeveloper** [comment]
> --doc-group3

Thanks for the reply. I tried but I got the same issue.

**Comment by sa33ddeveloper** [comment]
> Supported platforms are listed here: https://opendds.org/documents/building.html
> Since we don't do testing on macOS 11.x we don't know if this is going to work (no matter which ACE you end up using).
> Any help you can provide, in terms of extending support to those platforms that are important to you, would be appreciated.

Thanks for the reply. Well I've been working to define my phd research work around dds. My research domain is actually about edge computing and service delivery and as I'm at the preliminary stage, yet to define a proper lab setup. I'll seek your help as I go ahead. thanks

**Comment by jwillemsen** [comment]
What is the content of /OpenDDS-3.16/ACE_wrappers/VERSION.txt, that should be ACE 7.0.1, when not, remote the /OpenDDS-3.16/ACE_wrappers directory so that the configure step will download the latest DOC group release

**Comment by jwillemsen** [comment]
You need to remove the ACE_wrappers directory from the file system and rerun configure using `--doc-group3`

**Comment by sa33ddeveloper** [comment]
> You need to remove the ACE_wrappers directory from the file system and rerun configure using `--doc-group3`

Getting different errors after 'make' ...I attached.

Thanks

[VERSION.txt](https://github.com/objectcomputing/OpenDDS/files/6360326/VERSION.txt)
[ACE Error 2.txt](https://github.com/objectcomputing/OpenDDS/files/6360342/ACE.Error.2.txt)

**Comment by jwillemsen** [comment]
This got fixed in ACE 7.0.1 which was not there yet with OpenDDS 3.16, as workaround try to edit `/OpenDDS-3.16/ACE_wrappers/include/makeinclude/platform_macros.GNU` and add as first line `c++11=1` and try make again

**Comment by sa33ddeveloper** [comment]
> This got fixed in ACE 7.0.1 which was not there yet with OpenDDS 3.16, as workaround try to edit `/OpenDDS-3.16/ACE_wrappers/include/makeinclude/platform_macros.GNU` and add as first line `c++11=1` and try make again

Wonderful! It works 👍 

Many thanks.
