### ISSUE TITLE
Send/Receive problems with large data packets

### ISSUE THREAD

**Issue by tkukowski** [objectcomputing/OpenDDS#2597]
I am trying to transmit image data (640x512) using the FACE TSS. Upon running the publisher and subscriber, the image was never being received and the subscriber would freeze until the application killed. 

To break down and isolate the problem, the examples provided in DevGuideExamples were manipulated only to send a massive string to mimic the size of the image. No configuration settings were modified for these tests:

- Using the FACE example, a string of sizes 100,000 and 200,000 characters were sent and only the 100,000 sized string was received. When sending the 200,000 character string, the subscriber froze similarly to the image transport. 

- With the DCPS example, a string of size 10,000,000 characters was sent and received. 100,000 and 200,000 sized strings were also tested and confirmed. 

Is there a data size limitation when using the FACE TSS? I have full stack trace debug logs for the runtime of the image transport as well as running the provided examples.

**Comment by mitza-oci** [comment]
Please add your test(s) to the repository so we can try running them.

**Comment by tkukowski** [comment]
Not sure the best way, so I'll attach the files here. I do recall that we are not working from master, but from version 3.14 of OpenDDS. If there is a better way to share the files, let me know.

The first file (Publisher_FACE.cpp) replaces the Publisher.cpp in OpenDDS/DevGuideExamples/FACE/Simple.

The second file (Publisher_DCPS.cpp) replaces Publisher.cpp in OpenDDS/DevGuideExamples/DCPS/Messenger

The only change from the original versions of these files is a 'for' loop to create a large string.

[PublisherFiles.zip](https://github.com/objectcomputing/OpenDDS/files/6359642/PublisherFiles.zip)

**Comment by mitza-oci** [comment]
Yes, please use a pull request.

**Comment by tkukowski** [comment]
Pull request #2601 has the changes made to the FACE publisher which freezes the subscriber.
