### ISSUE TITLE
DDSTraits::type_name() returns incorrect string

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2669]
From tests/DCPS/Compiler/keyword/classic/testTypeSupportImpl.h

opendds_idl currently generates
```
static const char* type_name() { return "_cxx_case::private"; }
```

But I think it should be

```
static const char* type_name() { return "case::private"; }
```

So no escaping for the modules

**Comment by mitza-oci** [comment]
Are you planning on incorporating this into #2668?

**Comment by jwillemsen** [comment]
Not at this moment, just uncovered this one but will not have time for this one at least until Wednesday late
