### ISSUE TITLE
Implement the DLRL to allow for distribution of an object model

### ISSUE THREAD

**Issue by g19fanatic** [objectcomputing/OpenDDS#271]
As listed on the openDDS website, http://opendds.org/documents/architecture.html, currently openDDS does not fully implement the whole specification.

**Comment by mitza-oci** [comment]
Kind of semantics here, but the OMG has decided to split the specifications.  Now the "core DDS" spec is only DCPS and DLRL is an add-on.
http://www.omg.org/spec/DDS/
http://www.omg.org/spec/DDS-DLRL/

Of course we would be happy to have a DLRL if someone contributes it or sponsors its development.
