### ISSUE TITLE
DomainParticipantFactory::create_participant take long time to process

### ISSUE THREAD

**Issue by AlexSch31** [objectcomputing/OpenDDS#2718]
Hello, 

I have an issue with the function DomainParticipantFactory::create_participant.
The function take quite some time to process (several minutes).
I tried differents configurations, thinking maybe this was a network issue,  but the problem also occured in localhost.
This issue occured with any project (i tried to execute the Messenger example and I have the same problem).

Can you help me ?

Thanks in advance.

**Comment by AlexSch31** [comment]
I forgot to mention that I use the DCPSInfoRepo instance.

**Comment by mitza-oci** [comment]
Is there a log or wireshark capture you can share?
Based on limited information I'd guess it's trying to establish the connection to the DCPSInfoRepo.  Are you providing that as a hostname, IP address, IOR?

**Comment by AlexSch31** [comment]
Hello, 

Sorry for the delay, I found out the problem. The computer that I utilize have several network and several default route. 
I modify the route and I don't have the problem anymore.

FYI
I launch DCPSInfoRepo with an IP and port
```
DCPSInfoRepo -ORBListenEndpoints iiop://<ip>:<port>
```

**Comment by SHGzl** [comment]
@AlexSch31 Good morning, I have the same problem with you, I have no problem under CentOS operating system, but I have a problem under Ubuntu. Can you tell me your specific way to solve this problem? Thank you very much!
