### ISSUE TITLE
recorder and replayer 

### ISSUE THREAD

**Issue by heshiwen1989** [objectcomputing/OpenDDS#2770]
When I use opendds recorder and replayer class to recorder data to file(e.g. test_opendds_data.txt) and replayer, i meet the problem that recorder receive samples(RawDataSample) data size always less than the publisher send data size? and when i republish this saved samples, i meet "on_requested_incompatible_qos"

**Comment by heshiwen1989** [comment]
when message is larger(2Mb per message), it seems that loss data, because that wireshark capture tcp stream find always windows full

**Comment by heshiwen1989** [comment]
![image](https://user-images.githubusercontent.com/28886748/123427505-4a974c80-d5f7-11eb-99a8-79b4f2070282.png)

**Comment by heshiwen1989** [comment]
![image](https://user-images.githubusercontent.com/28886748/123427505-4a974c80-d5f7-11eb-99a8-79b4f2070282.png)

**Comment by heshiwen1989** [comment]
1. receive data size
![image](https://user-images.githubusercontent.com/28886748/123434737-60a90b00-d5ff-11eb-87c1-1ca507dc6631.png)
2. wireshark capture data size 
![image](https://user-images.githubusercontent.com/28886748/123434913-93eb9a00-d5ff-11eb-8fb4-bb0add699263.png)

3. per 10s send 1 frame

**Comment by mitza-oci** [comment]
Please share the code that demonstrates the issue.

**Comment by heshiwen1989** [comment]
> Please share the code that demonstrates the issue.

thank for your replay, and the attach file is my test code, you may not need pcl library which configure in cmakelist.txt
[github_messenger.zip](https://github.com/objectcomputing/OpenDDS/files/6721108/github_messenger.zip)

**Comment by heshiwen1989** [comment]
> > Please share the code that demonstrates the issue.
> 
> thanks, and the attach file is my test code, you may not need pcl library which configure in cmakelist.txt
> [github_messenger.zip](https://github.com/objectcomputing/OpenDDS/files/6721108/github_messenger.zip)

test opendds mode is : tcp + center
