### ISSUE TITLE
[DevGuide] RTPS UDP quick_reply_ratio configuration

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2796]
In table 7-17 on page 130 there is documentation for `quick_reply_ratio` but doesn't seem to exist anymore in rtps udp (https://github.com/objectcomputing/OpenDDS/blob/6da578b0ea3b61055db954550de8b0597a1c6ef8/dds/DCPS/transport/rtps_udp/RtpsUdpInst.cpp#L63)

**Comment by jrw972** [comment]
Take up once documentation is in repo.

**Comment by mitza-oci** [comment]
Fixed in DevGuide source
