### ISSUE TITLE
DevGuideExamples not ran as part of the test suite

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2801]
The DevGuideExamples are not part of the test suite, these are used heavily by users, so we should run them with the various configurations as part of the test suite to make sure they work and keep working

**Comment by iguessthislldo** [comment]
Messenger looks like it's [being ran in the test list](https://github.com/objectcomputing/OpenDDS/blob/11df39477f34a5c0cc01dd95a61c30a8f15b4004/tests/dcps_tests.lst#L191-L193) and I know it's also being run with CMake, so do you mean the other examples?

**Comment by jwillemsen** [comment]
Yes, you are right, I had a build where I couldn't find this example, closing, sorry for the confusion
