### ISSUE TITLE
under Ubuntu, DomainParticipantFactory::create_participant take long time to process

### ISSUE THREAD

**Issue by SHGzl** [objectcomputing/OpenDDS#2900]
Good morning, I have  a problem , , DomainParticipantFactory::create_participant take long time to process, I have no problem under CentOS operating system, but I have a problem under Ubuntu. 
Read the source code, locate the problem and find it

create_participant
   

>   dp->enable() 

       add_domain_participant
         get_dcps_info
              resolve_initial_references
                     root_poa ();
                           poa_adapter->open ();
                                  open_default_resources ();
                                        open_acceptor_registry
                                                open
                                                     open_default
                                                            open_default
                                                                     open_default_i
                                                                           open_default
                                                                                   probe_interfaces
                                                                                          hostname
                                                                                              get_host_name
                                                                                                        get_host_name_i
							                                                       getnameinfo
getnameinfo The return value is not 0！
Cnetos has no problem, so I confirm that there is a problem with the network setting of Ubuntu,
But I've tried many ways, but I still haven't solved the problem. Can you point out the maze ，thank you!!!

**Comment by jrw972** [comment]
I have seen this fail when DNS is broken.  Are other applications not resolving?

**Comment by SHGzl** [comment]
@jrw972 Thank you for your reply！ Just this one。

**Comment by jwillemsen** [comment]
We did make several changes to OpenDDS 3.18 to not do a reverse lookup of the hostname just for logging purposes, we had also some applications that had this problem on some systems. Can you retest with 3.18?

**Comment by SHGzl** [comment]
@jwillemsen Thank you. I'll retest with version 3.18 right away. After the test, I will feed back the test results to you!

**Comment by SHGzl** [comment]
![DCPSInfoRepo](https://user-images.githubusercontent.com/20950014/132649059-f4dcbc41-3cea-4184-96bc-40c4ad508af0.png)
![publisher](https://user-images.githubusercontent.com/20950014/132649063-41bf6d47-a8cd-4961-a4b1-aadfe6155d33.png)
![subscriber](https://user-images.githubusercontent.com/20950014/132649065-e46f421c-3f5b-42d9-89fa-86dfbd93085a.png)
![ubuntu hostname](https://user-images.githubusercontent.com/20950014/132649067-152a1d71-6877-443b-9a0e-392a5e4ae57d.png)

Hello, I use the latest version 3.18, but the problem still exists under the Ubuntu operating system. I use the test program included in version 3.18. It takes about 30 seconds for publisher and subscriber to start. Can you help me analyze the problem?

I uploaded four pictures to describe the above things.

Thank you very much!

**Comment by SHGzl** [comment]
@jwillemsen thank you very much !

**Comment by SHGzl** [comment]
@jrw972 thank you very much !

**Comment by SHGzl** [comment]
![FQDN](https://user-images.githubusercontent.com/20950014/132650946-50e1b256-1bd1-49fb-9d52-3064aebee403.png)

@jwillemsen Hello, is this the DNS problem to be solved? So how should my Ubuntu configure DNS?
