### ISSUE TITLE
Java: Messenger example fails with EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by nxdefiant** [objectcomputing/OpenDDS#291]
Testing OpenDDS 3.8, when trying the Java Messenger I get the attached error. Windows and Java version is in the log. 

[hs_err_pid8096.txt](https://github.com/objectcomputing/OpenDDS/files/422771/hs_err_pid8096.txt)

**Comment by mitza-oci** [comment]
JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
Windows 7 , 64 bit Build 7601 (6.1.7601.23418)
This is a 32-bit Java VM.

Is this OpenDDS 3.8 or master?  Which C++ compiler did you use?  Any options passed to configure script (if used) or any other customizations/code changes?  Any interesting console output from the test?

This configuration (Java + Win7) is working on our Jenkins CI builds.
I wonder why tao_java.dll wasn't loaded (but I'm not sure this is a cause).

**Comment by nxdefiant** [comment]
Your comment got me on the right track: i2jrt.jar was missing. Sorry for that.
