### ISSUE TITLE
memory leak in mfc application

### ISSUE THREAD

**Issue by skyawa** [objectcomputing/OpenDDS#2931]
I created a new dialog based MFC application. Only ace:: init() was called, and  memory leaks occurred when the program exited. Deleak is shown as follows:
![image](https://user-images.githubusercontent.com/57478004/130344917-631f3a0d-6f53-4060-b8a8-e69d71e28dc8.png)

**Comment by skyawa** [comment]
![image](https://user-images.githubusercontent.com/57478004/130344927-5a17575c-8b31-4ab7-a550-1f9bb1f7f7ab.png)

**Comment by jrw972** [comment]
Was `ACE::fini` called?
