### ISSUE TITLE
Docker, Message example, exited with code 126

### ISSUE THREAD

**Issue by sa33ddeveloper** [objectcomputing/OpenDDS#2951]
Hi,
I followed the quick start for Docker implementation. The publisher and subscriber exited with code 126. The output is as the following:

B599:Messenger sxxx$ docker-compose -f docker-compose-inforepo.yml up
Starting messenger_inforepo_1   ... done
Starting messenger_publisher_1  ... done
Starting messenger_subscriber_1 ... done
Attaching to messenger_publisher_1, messenger_subscriber_1, messenger_inforepo_1
publisher_1   | wait-for-it.sh: waiting 15 seconds for inforepo:3897
subscriber_1  | wait-for-it.sh: waiting 15 seconds for inforepo:3897
publisher_1   | wait-for-it.sh: inforepo:3897 is available after 1 seconds
publisher_1   | ./wait-for-it.sh: line 174: /opt/workspace/publisher: cannot execute binary file: Exec format error
publisher_1   | ./wait-for-it.sh: line 174: /opt/workspace/publisher: Success
messenger_publisher_1 exited with code 126
subscriber_1  | wait-for-it.sh: inforepo:3897 is available after 1 seconds
subscriber_1  | ./wait-for-it.sh: line 174: /opt/workspace/subscriber: cannot execute binary file: Exec format error
subscriber_1  | ./wait-for-it.sh: line 174: /opt/workspace/subscriber: Success
messenger_subscriber_1 exited with code 126

**Comment by mitza-oci** [comment]
docker-compose error couldn't be reproduced
