### ISSUE TITLE
Problem compiling user IDL when we want to use a sequence of a topic type

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#2965]
The following IDL leads to a redefinition error `redefinition after use, ::Xyz::My_msg2Seq, ::Xyz, ::Xyz::My_msg2Seq`. We want to use a sequence of a topic type in another topic

```
module Xyz {
  @nested(FALSE)
  @appendable
  struct My_msg2 {
    long myl;
  };
  typedef sequence<Xyz::My_msg2> My_msg2Seq;
  @nested(FALSE)
  @appendable
  struct My_msg3 {
    My_msg2Seq myseq;
  };
};

**Comment by mitza-oci** [comment]
Isn't this always going to be an issue since the DDS spec reserves `FooSeq` for any `Foo` topic struct?

**Comment by jwillemsen** [comment]
See #2966 for a fix, RTI does support something similar. Alternative is to check for the existance of the typedef in the user IDL but that could also be tricky.

This implied type is problematic, DDS shouldn't have done this

**Comment by mitza-oci** [comment]
Yes, I'm not saying that #2966 is a problem.  More just wondering what other problems could occur when the sequence that TypeSupport uses changes.  If the generated code will then be used by Modeling SDK or FACE or ROS2 or ??
I suppose these are special cases and documentation should indicate that this is generating a non-conformant TypeSupport.

**Comment by jwillemsen** [comment]
This is coming from AXCIOMA, there DDS is just one of the available transports and all DDS code is hidden from the user, we use a different suffix for the DDS sequence type

**Comment by jwillemsen** [comment]
With the changes made and some changes to our AXCIOMA code generators this works for all tests we have, including the tests where the user has a Seq typedef
