### ISSUE TITLE
Unsupported MacOS version 11.5.2.  (OpenDDS-3.18)

### ISSUE THREAD

**Issue by Danny875** [objectcomputing/OpenDDS#2993]
Hello,

I would definitely appreciate if someone could help with the following error that I'm getting after I type "make" in the terminal. I would like to mention that I'm using the 11.5.2 MacOS version, the latest one.

/Applications/OpenDDS-3.18/ACE_wrappers/include/makeinclude/platform_macosx.GNU:38: *** Unsupported MacOS version 11.5.2.  Stop.
make: *** [ACE] Error 2

Thank you in advance!

**Comment by jwillemsen** [comment]
Which [ACE](https://github.com/DOCGroup/ACE_TAO) version are you using, have you tried the `--doc-group3` flag to configure to use [ACE 7.0.3](https://github.com/DOCGroup/ACE_TAO/releases/tag/ACE%2BTAO-7_0_3)?

**Comment by Danny875** [comment]
I have tried the --doc-group3 flag now, but it still doesn't work. I think the version of ACE is 2.2a.

**Comment by jwillemsen** [comment]
You need to run `--doc-group3` on a fresh tree, when configure finds an existing ACE tree it will just use that.

**Comment by Danny875** [comment]
I'm getting the following error after executing the "./configure --doc-group3-verbose" on a fresh tree.
<img width="887" alt="Screen Shot 2021-09-13 at 1 21 59 PM" src="https://user-images.githubusercontent.com/56266997/133067788-f75b234a-d25e-4bb1-82e4-73ef7152fe4d.png">

**Comment by Danny875** [comment]
Managed to get rid of the error with the following command: "./configure --doc-group3 --ace=download".

**Comment by jwillemsen** [comment]
Just try what the script proposes, add `--ace=download` to the configure invocation

**Comment by Danny875** [comment]
Thank you!
