### ISSUE TITLE
 EXCEPTION, ERROR: InfoRepoDiscovery::add_domain_participant:  system exception, ID 'IDL:omg.org/CORBA/TRANSIENT:1.0'

### ISSUE THREAD

**Issue by Danny875** [objectcomputing/OpenDDS#3010]
Hello, 

I have an error when trying to run the Messenger example using the subscriber/publisher in separate terminal windows. Is there any way to fix it?

Thank you in advance!
<img width="751" alt="Screen Shot 2021-09-16 at 5 25 10 PM" src="https://user-images.githubusercontent.com/56266997/133630301-5fd392d1-389e-4796-a9b1-16209544eabc.png">

**Comment by jwillemsen** [comment]
Try to start DCPSInfoRepo and Subscriber from the same directory, both read/write the simple.ior file in the current directly by default, can it be that there is an old file in the Messenger directory?

**Comment by iguessthislldo** [comment]
That looks correct to me... Out of curiosity, does it do the same thing if you run `run_test.pl`?

**Comment by iguessthislldo** [comment]
I missed Johnny's reply and the fact that `DCPSInfoRepo` wasn't started in the directory. He is correct.

**Comment by jwillemsen** [comment]
I would recommend to use RTPS discovery and don't use the DCPSInfoRepo at all

**Comment by Danny875** [comment]
Thank you for your response! 

I tried starting DCPSInfoRepo and Subscriber from the same directory, but now I do get another error:
<img width="820" alt="Screen Shot 2021-09-16 at 21 34 38" src="https://user-images.githubusercontent.com/56266997/133666528-736ea67d-0338-497a-a0b7-18b3018b67d2.png">

**Comment by jwillemsen** [comment]
You also have to start the publisher to start publising the examples. As @iguessthislldo asked, have you tried to run the `run_test.pl` script which is in each test directory? That will run the test automatically.

Please use plain text for any output, screenshots are not searchable and can be hard to read on mobile devices

**Comment by Danny875** [comment]
Dear Johnny and Fred, 

Thank you for your response and for the help you both provided to me!

Yes, I have tried to run the "run_test.pl" and it works without any issues. The output of that is the following:

SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 99
         from       = Comic Book Guy
         count      = 0
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 100
         from       = Comic Book Guy
         count      = 1
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 101
         from       = Comic Book Guy
         count      = 2
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 102
         from       = Comic Book Guy
         count      = 3
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 103
         from       = Comic Book Guy
         count      = 4
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 104
         from       = Comic Book Guy
         count      = 5
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 105
         from       = Comic Book Guy
         count      = 6
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 106
         from       = Comic Book Guy
         count      = 7
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 107
         from       = Comic Book Guy
         count      = 8
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 108
         from       = Comic Book Guy
         count      = 9
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE

Also, after I have started the publisher, as you mentioned,  all from the same directory, everything worked fine. 

My issue is solved now!

Thank you both once again!
