### ISSUE TITLE
RawDataSample can't be deserialized in user code

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#3025]
When using the Recorder we try to deserialize the received RawDataSample (see for example https://github.com/objectcomputing/OpenDDS/blob/2db4ae425bb6e5a55724755b9cdad02ce62b7480/tests/DCPS/RecorderReplayer/Relay.cpp#L85) to log it in a custom recorder application. This works when using for example shared memory transport, but not when using rtps_udp. It looks not enough information is available to demarshal the RawDataSample using a Serializer in user code which mimics https://github.com/objectcomputing/OpenDDS/blob/2db4ae425bb6e5a55724755b9cdad02ce62b7480/dds/DCPS/DataReaderImpl_T.h#L1087

**Comment by jwillemsen** [comment]
Problem is the XCDR2 encoding which is used with rtps_udp, @mitza-oci, you can assign this one to me, working on a new unit test and related fixes.

**Comment by mitza-oci** [comment]
OK, also note that there is some overlap here with the xtypes_dynamic branch.  Once that's done, the application code making use of Recorder will have an XTypes::DynamicType and related objects to work with.

**Comment by jwillemsen** [comment]
Do you have an idea when dynamic xtypes will be ready?

**Comment by jwillemsen** [comment]
Dynamic XTypes would be the best solution, working on the changes to make it working with rtps_udp for the moment
