### ISSUE TITLE
DataReader/DataWriter don't log the failure of to_encoding/from_encoding

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#3026]
The DataReader/DataWriter don't log when @to_encoding/from_encoding@ fails, they just return, logging should be added in those places where these operations are called in the DDS core

**Comment by iguessthislldo** [comment]
This is because `to_encoing` and `from_encoding` log their own error messages.

**Comment by jwillemsen** [comment]
Yes, you are right, sorry for the issue
