### ISSUE TITLE
having a branch for the patch release

### ISSUE THREAD

**Issue by vermaete** [objectcomputing/OpenDDS#3031]
Hi,

For bitbake recipes, it would be easier to have a branch on the patch releases to.
e.g. branch-DDS-3.18.1.

The version number normally part of the bitbake recipe.
So opendds_3.18.bb and opendds_3.81.1.bb.
With $PV variable is the the version number that can be used in the SRC_URI variable.

br,

**Comment by vermaete** [comment]
Just some background why a git tag isn't the same as a git branch for git fetcher of Yocto:

"tag": Specifies a tag to use for the checkout. To correctly resolve tags, BitBake must access the network. For that reason, tags are often not used. As far as Git is concerned, the "tag" parameter behaves effectively the same as the "rev" parameter.
-- https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#git-fetcher

And having no Internet access is happening when using DDS technologies :-)

**Comment by mitza-oci** [comment]
I don't understand the difference here.  If you've already done a `git fetch` then the local git has both branches and tags.  There is no further network access needed.

**Comment by vermaete** [comment]
@mitza-oci: Sorry, I also don't see the difference.  But I notice the use of the PV coupled at a git branch more often.
Anyhow: I will check if it's working with a git tag on an air gaped network and will let you know.
Unless it's not an issue to have a tag and a branch on your side.
