### ISSUE TITLE
Use LogGuid instead of GuidConverter with logging

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#3036]
Looks some point `LogGuid` was introduced as helper but still a lot of places in the core use `GuidConverter`, that should be updated

**Comment by JoanneOrozco** [comment]
hello, is this task still open for contribution? If so can I be assigned? Thank you.

**Comment by JoanneOrozco** [comment]
Me and @iamharvir has completed the task and were wondering how to go about making a pull request

**Comment by mitza-oci** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by simpsont-oci** [comment]
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Just to piggyback on this info: OpenDDS uses master as the primary development branch, so a good general workflow would be:
- Fork OpenDDS (if you haven't already)
- create a branch from master in your fork (let's say you name it my_branch)
- apply your changes, do local builds & testing
- commit & push your changes for my_branch to your fork
- Create a pull request from your_repo/my_branch to OpenDDS/master
- Resolve any merge issues (you may need to remerge from master)
- Resolve any linting failures or review comments (style / formatting issues, design choices, etc)
- Resolve any test failures (some can be ignored, we'll help sort out which need to be fixed)

There are other ways to do it, but that's a good general pattern. Hopefully that helps.

**Comment by iamharvir** [comment]
Hi, I am trying to create a branch, but I keep getting a permission error. Do I need certain privileges before I am allowed to create a branch?

**Comment by mitza-oci** [comment]
Create a branch in your fork.  Since the forked repository belongs to your GitHub account, there are no additional permissions needed.
