### ISSUE TITLE
Solaris defines NOSIGNAL

### ISSUE THREAD

**Issue by nxdefiant** [objectcomputing/OpenDDS#310]
FACE/TS_common.hpp defines NOSIGNAL in enum SEND_FLAG_TYPE, but NOSIGNAL is an already existing define on Solaris 11.3. The enum field should probably be
- either renamed, or
- an ifdef/undef NOSIGNAL should be added to the top of FACE/TS_common.hpp

**Comment by mitza-oci** [comment]
The problem with renaming is that the only point of the FACE headers is to conform to the FACE specification from the Open Group (http://www.opengroup.org/face).  There was a similar identifier collision on VxWorks which we addressed by a platform-dependent macro replacement, see line 68 of TS_common.h.  I see that as an option on Solaris 11, along with the undef you proposed.  Neither option is clearly better than the other, I'd be OK with either.

If you'd like us to notice this type of error before a release, you can run automated builds on your Solaris system and post results to a scoreboard.  Let me know if you'd like more information on how to do this.

**Comment by nxdefiant** [comment]
ok, did the undef in #312.

Thanks, I might get back to the automated build system, but might take a few days.

**Comment by mitza-oci** [comment]
OK, we should continue working on this in #312 and hopefully it's OK to close this issue (not sure what's commonly done on github).
