### ISSUE TITLE
ValueWriter API terrible slow with large sequences/arrays of basic types

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#3124]
When the user IDL has sequences/arrays of basic types the ValueWriter API is terrible slow because there is a callback to user code for each element of the sequence/array, when we have a sequence of 1M octet we get 1M callbacks to `write_byte`

**Comment by jrw972** [comment]
My initial reaction would be to add bulk operations for these cases.

Beyond, serializing large sequences and arrays, how are you using the ValueWriter API?  `to_json`?  From a project perspective, we would like ValueWriter and ValueReader to gain enough maturity that they can eventually be a viable replacement for Serializer and other similar pieces of code so any observations and feedback will be useful in evolving that design.

**Comment by jwillemsen** [comment]
Yes, also my idea, add the bulk operations to ValueWriter and update the IDL compiler to call the bulk operations on the ValueWriter, they iterate by default one by one so that existing code keep working, but the user can override a bulk operation to do something special (which our customer does)

**Comment by jwillemsen** [comment]
@mitza-oci Can you assign this one to me, we are going to extend the ValueWriter API with build operations

**Comment by jwillemsen** [comment]
To keep it consistent I think we should also extend the ValueReader, what do you think @jrw972 @mitza-oci

**Comment by jrw972** [comment]
I agree with extending ValueReader in the same way.

**Comment by jwillemsen** [comment]
See #3140

**Comment by jwillemsen** [comment]
Implemented
