### ISSUE TITLE
OpenDDS Wireshark - Can't find glib at /usr (Error)

### ISSUE THREAD

**Issue by Danny875** [objectcomputing/OpenDDS#3137]
Hi,

I'm getting the `ERROR: Can't find glib at /usr.`, when I'm trying to configure OpenDDS with Wireshark. The command that I have used to do this is the following: `./configure --doc-group3 --glib --wireshark=/Applications/Wireshark.app/Contents --ace=download`.

What could be wrong?

Thank you in advance!

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/OpenDDS/blob/master/tools/dissector/README.md#building
