### ISSUE TITLE
Add support for versioned namespaces

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#316]
ACE and TAO have support to put everything into a versioned namespace. Would be useful for IDL2C++11 when at least the IDL generated code can support versioned namespaces.

**Comment by jwillemsen** [comment]
Working on some initial changes for this enhancement

**Comment by mitza-oci** [comment]
See pull request #324

**Comment by jwillemsen** [comment]
Only FACE is not done yet, need to revisit that again

**Comment by jwillemsen** [comment]
Support for FACE is implemented, working on a new PR

**Comment by jwillemsen** [comment]
Implemented support for versioned namespaces
