### ISSUE TITLE
How to improve throughput ? 

### ISSUE THREAD

**Issue by KevKzTW** [objectcomputing/OpenDDS#317]
Hi ,

Because I don't understand how to use your /performance-tests about throughput and latency ,
I have done a program , modified from sample code of other vendor , to test throughput .

But I saw the result was not well in rtps discovery mode . 

When I use rtps discovery mode to publish sequence in 8192 payload size , I get 26 Mbps.
When I use DCPSInfoRepo discovery mode to publish sequence in 8192 payload size , I get 500 Mbps  .

Would you help me fix rtps.ini to improve throughput ? 
 I think the code is fine .
[my github repo](https://github.com/KevKzTW/opendds_test)

OS: Ubuntu 16.04 x86_64 VirtualBox

Thanks

**Comment by mitza-oci** [comment]
I'm a little confused as to exactly what's being measured here.  Your comments refer to changing discovery mode and having this impact data rate.  Discovery is not involved with sending data.  Are you actually changing transports?  Please see the OpenDDS developer's guide for details on how to configure discovery and transport (and what these mean, why they are different, etc.)

**Comment by KevKzTW** [comment]
Hi ,

Actually I just wanted to measure throughput with different payload size .

I was using RTPS dicovery mode first with all default setting , and got the result bad .

Therefore , I changed to repo mode with default setting , and got the result better .

I was confused , and also tried to fix transport setting .

I do not really want to imply rtps worse than repo  here , because I know that discovery is not involved with sending data . 

Sorry ,  I should not give you confusion .

I am going to read more .

Thanks

**Comment by nxdefiant** [comment]
Any details on what you fixed on heartbeat_period and heartbeat_response_delay?

**Comment by mitza-oci** [comment]
There are a number of trade-offs for selecting tcp vs rtps_udp:

- if you need to interoperate with other DDS implementations, only rtps_udp does this
- if you have a network deployment suitable for multicast and want to take advantage of it, rtps_udp can do this while still having reliability
- if you need to traverse subnets that don't route mulitcast traffic, you can use tcp
- if there is a low fanout ratio it may not be worth it to use multicast with rtps_udp, you can use tcp
- there are certain QoS policies that are not supported with rtps_udp (and the DDSI-RTPS spec itself) so you can use tcp if you need those

**Comment by KevKzTW** [comment]
Hey @nxdefiant ,

The default value of 
- heartbeat_period : 1000 msec.
- heartbeat_response_delay : 500 msec.

I think it's too long , so I change both value to 10 msec . ( I am not sure if it's the best value)

The throughput is up to 170 Mbps in rtps_udp transport mode with 8192 bytes per message .
It's close to [Interpreting OpenDDS Performance Testing Results](https://www.ociweb.com/resources/publications/mnb/interpreting-opendds-performance-testing-results/) 

Hey @mitza-oci ,

I have one more question.

I used ACE_OS::gettimeofday(); to do measurement .
Is it suit or any better function ?

Thank you

**Comment by mitza-oci** [comment]
I don't have any other performance test results available at the moment.  We just got a new test server so it would be good to run some performance tests on it.

Of course everyone's numbers will be different running difference scenarios on different hardware.  The important questions are: is performance stable and tunable?  does it meet your needs for your particular implementation?  is it in line with other DDS implementations?
