### ISSUE TITLE
OpenDDS with WCHAR in VS2019 cannot be compiled

### ISSUE THREAD

**Issue by bluenlive** [objectcomputing/OpenDDS#3193]
Hello.

I'm trying to compile OpenDDS with WCHAR in VS2019.
But it failed.

This is all I did.

1. Download and unzip OpenDDS
2. run VS 2019 Developer Command Prompt
3. run `configure.cmd`
4. add `#define ACE_USES_WCHAR 1` to 1st line of config.h
5. run `devenv DDS_TAOv2.sln`
6. Build ACE with Debug x64

![error222](https://user-images.githubusercontent.com/2233617/144197681-f0b2551d-0732-4e44-a412-1f633b930624.png)
AR

It's written in Korean and it means `OS_NS_netdb.inl: error C2440: cannot convert from'char *' to 'const ACE_TCHAR *`

**Comment by mitza-oci** [comment]
Is there a step missing?  Did you run the OpenDDS configure script?
Please use tools/scripts/show_build_config.pl and paste the plaintext output here.
If it turns out to be an ACE problem, those go to https://github.com/DOCGroup/ACE_TAO

**Comment by bluenlive** [comment]
I run `configure.cmd`
(I missed to write it and I added to number 3)

I'll try `show_build_config.pl`

Thank you for your help.

**Comment by bluenlive** [comment]
I've found some problems with Visual Studio.
But, those are ACE problems.
So, I'll report to https://github.com/DOCGroup/ACE_TAO

Thank you for your help.
