### ISSUE TITLE
Too many internal headers pulled into user code

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#320]
When working on the versioned namespace support (issue #316) I noticed that when using OpenDDS a lot of headers are pulled into user code. A lot of coming through the type specific data reader, data writer, and topic. I think it would help our users when we can reduce the amount of headers they pull in when using OpenDDS. I would expect they only need the IDL generated types and stubs and not a lot of the internal headers.

**Comment by mitza-oci** [comment]
I wouldn't be opposed to improving this.  Do you have some examples?  We can examine why it's set up that way or attempt to change it.

**Comment by jwillemsen** [comment]
I encountered this when working on the versioned namespace support but I first need to rework a few things in DDSX11 before I can back to the OpenDDS part. Starting point to look at is the generated TypeSupportImpl.h, that pulls in several templates which pull in way more. Implementing the typed reader/writer/typesupport as templates saves a few lines of code when generating, but does result in a lot of code being included.

**Comment by mitza-oci** [comment]
Doesn't versioned namespace need to apply to all (exported) symbols regardless of where they are in the headers?  I'm not sure exactly what the connection is, or was it just that you were working on it at the time?

We made a deliberate decision to use C++ templates.  It's a good fit because we'd like to have the exact same behavior parameterized only on a data type.  There are some drawbacks with the inclusion model, but there are also advantages in having the IDL compiler(s) generate as little as possible.

**Comment by jwillemsen** [comment]
It was just something I encountered when working on the versioned namespace support.

There are advantages and disadvantages for the usage of C++ templates. It is easy for the IDL compiler, but does result in exposing a lot of internals to user code and probably less efficient in terms of footprint. Personally I think too much is exposed to the user code, something to look at to my idea when there is some time.

**Comment by jwillemsen** [comment]
Implemented first change, see pr #330

**Comment by jwillemsen** [comment]
Looking further I think that a lot of headers can be hided when instead of using OpenDDS::DCPS::TypeSupportImpl_T a type specific factory is generated in TypeSupportImpl.h where the implementation of the factory methods is in the TypeSupportImpl.cpp. At that moment much less headers are exposed to the user code, more hidden through TypeSupportImpl.cpp. That way a type specific datareader/writer can be implemented using templates. 

@mitza-oci What do you think about this approach?

**Comment by mitza-oci** [comment]
Is there more to do on this one, or should we close it?

**Comment by jwillemsen** [comment]
@mitza-oci I would like to keep this one open, the zero copy sequences seem to pull in also too much, want to look at that

**Comment by jwillemsen** [comment]
New #345 as separate rework item

**Comment by jwillemsen** [comment]
Closing this one, implemented several areas, at the moment I find anything left I will create a new issue at that moment
