### ISSUE TITLE
OpenDDS cannot be compiled with VS2019/2022 COM/RPC headers

### ISSUE THREAD

**Issue by bluenlive** [objectcomputing/OpenDDS#3205]
In Visual Studio, `interface` and `small` are declared in `combaseapi.h` and `rpcndr.h` as follows.

`#define interface __STRUCT__`
`#define small char`

And compilation is impossible in Visual Studios because variable names of the names are used in the source of OpenDDS.

The files in which the variable `interface` is used are as follows.
`dds\DCPS\NetworkConfigModifier.h`
`dds\DCPS\RTPS\GuidGenerator.h`
`dds\DCPS\RTPS\Spdp.h`
`dds\DCPS\transport\rtps_udp\RtpsUdpDataLink.h`

Also, the file in which `small` is used is as follows.
`dds\InfoRepo\DCPSInfo_i.cpp`

**Comment by jwillemsen** [comment]
Please open pull request with the necessary changes, at the moment those changes would brake the public API undefine the defines at the points where we use them

**Comment by bluenlive** [comment]
> Please open pull request with the necessary changes, at the moment those changes would brake the public API undefine the defines at the points where we use them

Okay, I opened PR. Thanks.
