### ISSUE TITLE
Configure script could enable C++11 with gcc 4.7 or newer

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#325]
The configure script could enable C++11 for gcc 4.7 or newer as part of the generated platform_macros.GNU file. This enables the user to use C++11 features

**Comment by mitza-oci** [comment]
And I suppose something similar for clang?  The configure script has "--macros=<anything>" to allow the user to pass any other settings through to platform_macros.  This allows it to not get too involved in things that don't impact OpenDDS.  I wouldn't be opposed to adding a --std=<something> but I don't think we enable it by default for certain compilers, this is an ABI-breaking change.

**Comment by jwillemsen** [comment]
clang has several known C++11 bugs which cause some of the ACE C++ compiler tests to fail

**Comment by mitza-oci** [comment]
See pull request #331

**Comment by jwillemsen** [comment]
Implemented in the configure script by @mitza-oci
