### ISSUE TITLE
Running configure --java with VS 2019 and Strawberry Perl doesn't recognize -type vs2019

### ISSUE THREAD

**Issue by kschultz1986** [objectcomputing/OpenDDS#3261]
I am running OpenDDS-3.18.1 out of the box on Windows 10 from the Developer PowerShell for VS 1019 (Community Edition)  with OpenDDS at: C:\OpenDDS-3.18.1 and ACE+TAO at C:\ACE+TAO-2.2a\ACE_wrappers. I get the following when I run ./configure --java:

PS C:\OpenDDS-3.18.1> ./configure --java
javac 1.8.0_291
ACE_ROOT/ace/config.h exists, skipping configuration of ACE+TAO
Running MPC to generate project files.
MPC_ROOT was set to C:\ACE+TAO-2.2a\ACE_wrappers\MPC.
Using .../ACE+TAO-2.2a/ACE_wrappers/bin/MakeProjectCreator/config/MPC.cfg
ERROR: Invalid type: vs2019
mwc.pl v3.9.63
Usage: mwc.pl [-global <file>] [-include <directory>] [-recurse]
              [-ti <dll | lib | dll_exe | lib_exe>:<file>] [-hierarchy]
              [-template <file>] [-relative NAME=VAL] [-base <project>]
              [-noreldefs] [-notoplevel] [-static] [-genins] [-use_env]
              [-value_template <NAME+=VAL | NAME=VAL | NAME-=VAL>]
              [-value_project <NAME+=VAL | NAME=VAL | NAME-=VAL>]
              [-make_coexistence] [-feature_file <file name>] [-gendot]
              [-expand_vars] [-features <feature definitions>]
              [-exclude <directories>] [-name_modifier <pattern>]
              [-apply_project] [-version] [-into <directory>]
              [-gfeature_file <file name>] [-nocomments]
              [-relative_file <file name>] [-for_eclipse]
              [-workers <#>] [-workers_dir <dir> | -workers_port <#>]
              [-language <cplusplus | csharp | java | vb>]
              [-type <automake | bcb2007 | bcb2009 | bds4 | bmake | cc | cdt6 |
                      cdt7 | em3 | ghs | gnuace | gnuautobuild | html | make |
                      nmake | rpmspec | sle | vc6 | vc7 | vc8 | vc9 | vc10 |
                      vc11 | vc71 | vxtest | wb26 | wb30 | wix>]
              [files]

       -base           Add <project> as a base project to each generated
                       project file.  Do not provide a file extension, the
                       .mpb extension will be tried first; if that fails the
                       .mpc extension will be tried.
       -exclude        Use this option to exclude directories or files when
                       searching for input files.
       -expand_vars    Perform direct expansion, instead of performing relative
                       replacement with either -use_env or -relative options.
       -feature_file   Specifies the feature file to read before processing.
                       The default feature file is default.features under the
                       config directory.
       -features       Specifies the feature list to set before processing.
       -for_eclipse    Generate files for use with eclipse.  This is only
                       useful for make based project types.
       -gendot         Generate .dot files for use with Graphviz.
       -genins         Generate .ins files for use with prj_install.pl.
       -gfeature_file  Specifies the global feature file.  The
                       default value is global.features under the
                       config directory.
       -global         Specifies the global input file.  Values stored
                       within this file are applied to all projects.
       -hierarchy      Generate a workspace in a hierarchical fashion.
       -include        Specifies a directory to search when looking for base
                       projects, template input files and templates.  This
                       option can be used multiple times to add directories.
       -into           Place all output files in a mirrored directory
                       structure starting at <directory>.  This should be a
                       full path.  If any project within the workspace is
                       referenced via a full path, use of this option is
                       likely to cause problems.
       -language       Specify the language preference; possible values are
                       [cplusplus, csharp, java, vb].  The default is
                       cplusplus.
       -make_coexistence If multiple 'make' based project types are
                       generated, they will be named such that they can coexist.
       -name_modifier  Modify output names.  The pattern passed to this
                       parameter will have the '*' portion replaced with the
                       actual output name.  Ex. *_Static
       -apply_project  When used in conjunction with -name_modifier, it applies
                       the name modifier to the project name also.
       -nocomments     Do not place comments in the generated files.
       -noreldefs      Do not try to generate default relative definitions.
       -notoplevel     Do not generate the top level target file.  Files
                       are still processed, but no top level file is created.
       -recurse        Recurse from the current directory and generate from
                       all found input files.
       -relative       Any $() variable in an mpc file that is matched to NAME
                       is replaced by VAL only if VAL can be made into a
                       relative path based on the current working directory.
                       This option can be used multiple times to add multiple
                       variables.
       -relative_file  Specifies the relative file to read before processing.
                       The default relative file is default.rel under the
                       config directory.
       -static         Specifies that only static projects will be generated.
                       By default, only dynamic projects are generated.
       -template       Specifies the template name (with no extension).
       -workers        Specifies number of child processes to use to generate
                       projects.
       -workers_dir    The directory for storing temporary output files
                       from the child processes.  The default is '/tmp/mpc'
                       If neither -workers_dir nor -workers_port is used,
                       -workers_dir is assumed.
       -workers_port   The port number for the parent listener. If neither
                       -workers_dir nor -workers_port is used, -workers_dir
                       is assumed.
       -ti             Specifies the template input file (with no extension)
                       for the specific type (ex. -ti dll_exe:vc8exe).
       -type           Specifies the type of project file to generate.  This
                       option can be used multiple times to generate multiple
                       types.  There is no longer a default.
       -use_env        Use environment variables for all uses of $() instead
                       of the relative replacement values.
       -value_project  This option allows modification of a project variable
                       assignment.  Use += to add VAL to the NAME's value.
                       Use -= to subtract and = to override the value.
                       This can be used to introduce new name value pairs to
                       a project.  However, it must be a valid project
                       assignment.
       -value_template This option allows modification of a template input
                       name value pair.  Use += to add VAL to the NAME's
                       value.  Use -= to subtract and = to override the value.
       -version        Print the MPC version and exit.
Command "perl C:\ACE+TAO-2.2a\ACE_wrappers/bin/mwc.pl -type vs2019 C:\OpenDDS-3.18.1\DDS_TAOv2.mwc" Returned 1
ERROR: Error from MPC, stopped at configure line 2185.
ERROR: configure failed with errorcode 1

**Comment by mitza-oci** [comment]
Seems like the version of ACE+TAO is too old.  The `README.md` file in the root of OpenDDS lists compatible versions.  The `configure` script can download one for you.

**Comment by kschultz1986** [comment]
Oh OK, I was following the steps from the java/INSTALL in the Git repository:

 - The ACE ORB (TAO), which includes ACE and MPC as subprojects

    OpenDDS requires the use of TAO.  Three "branches" of TAO are supported:

    - OCI TAO 2.2a <http://download.ociweb.com/TAO-2.2a>
    - DOC Group    <http://download.dre.vanderbilt.edu>

I will try a newer DOC Group version and report back.

**Comment by mitza-oci** [comment]
> Oh OK, I was following the steps from the java/INSTALL in the Git repository:
> 
>     * The ACE ORB (TAO), which includes ACE and MPC as subprojects
>       OpenDDS requires the use of TAO.  Three "branches" of TAO are supported:
>       
>       * OCI TAO 2.2a http://download.ociweb.com/TAO-2.2a

This lists the directory but not the file.  If you download `ACE+TAO-2.2a_with_latest_patches.zip` from that directory, it will work.

Or, as I mentioned before, let the `configure` script do the download for you.

See https://opendds.org/quickstart/GettingStartedWindows.html
