### ISSUE TITLE
'opendds_idl' crashes with C++11 when sequence contains typedef to primitive type

### ISSUE THREAD

**Issue by Erich71** [objectcomputing/OpenDDS#3268]
Invoking opendds_idl with parameters "-Lc++11 DDS_.idl" does not produce any output due to crash.

Reason is in file "dds/idl/marshal_generator.cpp" line 2590:

          AST_PredefinedType* const pt = dynamic_cast<AST_PredefinedType*>(base);
          if (pt->pt() == AST_PredefinedType::PT_octet) {
            octetSeqOnly = field->local_name()->get_string();
          }

dynamic_cast<> fails with null_ptr.
[DDS_.idl.txt](https://github.com/objectcomputing/OpenDDS/files/7862838/DDS_.idl.txt)

**Comment by mitza-oci** [comment]
Thanks for the report.  Please add to the test cases in `tests/DCPS/Compiler/idl_test?_lib`
