### ISSUE TITLE
escaped identifiers generate non-compilable c++ code

### ISSUE THREAD

**Issue by kcpayne** [objectcomputing/OpenDDS#3273]
Does openDDS fully support escaped identifiers per the OMG spec (7.2.3.2)?

When I try to build and compile using escaped identifiers the code will not compile.

module AB {
  module MOD1 {
    enum _Enum {
     NO_STATEMENT,
     STATEMENT
    };
  };
  struct TestSTruct {
    AB::MOD1::_Enum testEnum;
  };
};

In looking at the generated code I see cases where the _ is used and other placed where it is removed.

CommonC.h: ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, AB::MOD1::Enum _tao_enumerator);
CommonTypeSupportImpl.cpp:bool operator<<(Serializer& strm, const AB::MOD1::_Enum& enumval)

I get errors like this when compiling

In file included from ddsIdl/CommonTypeSupportImpl.cpp:2:0:
ddsIdl/CommonTypeSupportImpl.h:30:41: error: '_Enum' in namespace 'AB::MOD1' does not name a type
 bool operator<<(Serializer& strm, const AB::MOD1::_Enum& enumval);
                                         ^

**Comment by mitza-oci** [comment]
Yes, there is support for escaped identifiers.  However, there may be some cases that aren't yet covered.
Please extend the test in `tests/DCPS/Compiler/keywords`.

**Comment by kcpayne** [comment]
Moving to later version fixed this issue, thank you
