### ISSUE TITLE
Illegal redefinition

### ISSUE THREAD

**Issue by kcpayne** [objectcomputing/OpenDDS#3274]
module AB {
  module CORRECTED {
    enum _Enum {
      NO_STATEMENT,
      CORRECTED,
      NOT_CORRECTED
    };
  };
};

Error - /usr/local/share/dds/bin/opendds_idl: "Common.idl", line 5: illegal redefinition "CORRECTED" and "CORRECTED"

I did not see any prohibition in the OMG spec to doing the above.  Is this a IDL compiler issue?

**Comment by mitza-oci** [comment]
It's not valid in IDL.  An enum doesn't start a new scope.

```
The name of a module, structure, union, map, interface, value type, event type, exception or home may not be
redefined within the immediate scope of the module, structure, union, map, interface, value type, event type, exception
or home.
```
(from 7.5.2)

**Comment by kcpayne** [comment]
Right, makes sense.  Thank you.
