### ISSUE TITLE
Having trouble building Messenger by hand

### ISSUE THREAD

**Issue by lhchang** [objectcomputing/OpenDDS#3308]
I'm trying to work with the OpenDDS static libraries and building the example Messenger app with said libraries by hand for practice. However, while attempting to build the mappings for `MessengerTypeSupport.idl` using `tao_idl` binary, I get the following error:

```
../opendds/bin/tao_idl -v -Idir ../opendds/include/  MessengerTypeSupport.idl 

../opendds/bin/tao_idl: preprocessing ../opendds/include/
../opendds/bin/tao_idl: spawning: g++ -D__TAO_IDL=0x060200 -I. -I/home/dds/test/src/opendds/share/tao -I/home/dds/test/src/opendds/share/tao/tao -E -Idir -D__TAO_IDL_IDL_VERSION=0x030000 -D__TAO_IDL_FEATURES="tao/idl_features.h" -I/home/dds/test/src/opendds/share/tao/orbsvcs -I/home/dds/test/src/opendds/share/tao/CIAO -I/home/dds/test/src/opendds/share/tao/CIAO/ciao -I/home/dds/test/src/opendds/share/tao/CIAO/ccm /tmp/tao-idli_JvJoiD.cpp
../opendds/bin/tao_idl: parsing ../opendds/include/
processing ../opendds/include/
../opendds/bin/tao_idl: BE processing on ../opendds/include/
be_visitor_root_ch::init - Error opening client header file
be_visitor_root_ch::init - failed to initialize
BE_visit_root - client header for Root failed
Fatal Error - Aborting

```
Any guidance on how to proceed? Also regarding other build tools, is there documentation or example on how to configure MPC or cmake to use OpenDDS static libs?

Thank you

**Comment by iguessthislldo** [comment]
> `-Idir ../opendds/include/`
> ../opendds/bin/tao_idl: preprocessing ../opendds/include/

I'm not sure what `-Idir ../opendds/include/` is supposed to mean (maybe `-Idir -I../opendds/include`?), but it looks like it's treating `./opendds/include/` as an input because it was given as a separate argument and `tao_idl` isn't catching that error gracefully.

It does a similar thing locally for me when I give it a directory as an input:

```
tao_idl -v DevGuideExamptao_idl: preprocessing DevGuideExamples
tao_idl: spawning: g++ -D__TAO_IDL=0x070004 -I. -I/data/work/oci/ace-tao/doc/ACE_TAO/TAO -I/data/work/oci/ace-tao/doc/ACE_TAO/TAO/tao -E -D__TAO_IDL_IDL_VERSION=0x030000 -D__TAO_IDL_FEATURES="tao/idl_features.h" -I/data/work/oci/ace-tao/doc/ACE_TAO/TAO/orbsvcs -Iunused -Iunused/ciao -Iunused/ccm /tmp/tao-idli_qwOrk7.cpp
tao_idl: parsing DevGuideExamples
processing DevGuideExamples
tao_idl: BE processing on DevGuideExamples
be_visitor_root_ch::init - Error opening client header file
be_visitor_root_ch::init - failed to initialize
BE_visit_root - client header for Root failed
Fatal Error - Aborting
```

**Comment by lhchang** [comment]
Yes `-Idir` option was used because prior to that it was complaining that it couldn't find some idl files that were defined in `MessengerTypeSupport.idl`. Was there a different parameter that is supposed to be used?

**Comment by iguessthislldo** [comment]
What I'm trying to say is you can't pass just `../opendds/include` as a bare argument, it has to be either `-I ../opendds/include` or `-I../opendds/include` option or `tao_idl` will try to treat the directory like an IDL file.

**Comment by lhchang** [comment]
I see, I will give this a try. Thank you

**Comment by lhchang** [comment]
-Idir + -I option worked. Thank you
