### ISSUE TITLE
CPP to Java / Java to CPP

### ISSUE THREAD

**Issue by SafdarSikander** [objectcomputing/OpenDDS#3347]
I have configured two DDS Versions (3.19), one in CPP and other one in Java. I wanted to test the cross language support. it does support if the struct has primitive types (long, string, boolean) it works fine but when I use sequence it doesn't invoke on_data_available method.

**Comment by mitza-oci** [comment]
Are you using the same IDL for both applications?  Please share your code and we can take a look.  Sequences are the same on the wire (CDR encoding) no matter which language writes them.

**Comment by SafdarSikander** [comment]
`@Override
    public void on_data_available(DataReader dataReader) {
        DeviceListDataReader mdr = DeviceListDataReaderHelper.narrow(dataReader);
        if (mdr == null) {
            System.err.println("ERROR: read: narrow failed.");
            return;
        }
        DeviceList list=  new DeviceList();
        list.deviceList = new DeviceList.SeqDeviceList [0];
        DeviceListHolder mh = new DeviceListHolder(list);
        SampleInfoHolder sih = new SampleInfoHolder(new SampleInfo(0, 0, 0, new DDS.Time_t(), 0, 0, 0, 0, 0, 0, 0, false, 0));
        int status = mdr.take_next_sample(mh, sih);
        if (status == RETCODE_OK.value) {
            System.out.println("id -> " + list.id);
        } else if (status == RETCODE_NO_DATA.value) {
            System.err.println("ERROR: reader received DDS::RETCODE_NO_DATA!");
        } else {
            System.err.println("ERROR: read Message: Error: " + status);
        }
    }`
    
    This is my subscriber, when I publish from the CPP side on data available not get called, but when I publish from java on data available gets called.

**Comment by mitza-oci** [comment]
This IDL doesn't compile:
```
Error - tao_idl: "Service.idl", line 17: identifier spellings differ only in case: "OS" and "os"
Error - tao_idl: "Service.idl", line 27: identifier spellings differ only in case: "deviceList" and "DeviceList"
```

**Comment by SafdarSikander** [comment]
@mitza-oci Sorry for inconvenience. I update some variables name for sharing the IDL. I have updated the IDL. You can compile it without error now.

**Comment by mitza-oci** [comment]
> @mitza-oci Sorry for inconvenience. I update some variables name for sharing the IDL. I have updated the IDL. You can compile it without error now.

Thanks, I was able to generate C++ and Java code from the IDL.  I'll try the Java application.

**Comment by SafdarSikander** [comment]
@mitza-oci I figure it out today that if we do not intialize sequence with 0 JVM crashes. 
```Java
list.deviceList = new DeviceList.SeqDeviceList [0];
```

**Comment by mitza-oci** [comment]
Yes, see the `java/FAQ` file in the repository "I'm seeing a null pointer exception or a JVM crash in an OpenDDS native method.  What should I check first?"

**Comment by SafdarSikander** [comment]
I see missed that, but it doesn't make sense to initialize an array with 0 elements?

**Comment by mitza-oci** [comment]
OpenDDS is trying to be as efficient as possible, which includes not doing redundant work.  Arrays are not resizable, so it's up to the user to determine the array size.  This follows the OMG specification for IDL-to-Java.

**Comment by SafdarSikander** [comment]
Make sense, but when I initialize other than 0 it crashes the JVM.

**Comment by mitza-oci** [comment]
When you initialize it to contain a positive number of pointers, are those pointers null?

**Comment by SafdarSikander** [comment]
I debug it, it shows that the array is initialized successfully, it gets the valid pointer address.

**Comment by mitza-oci** [comment]
This worked when I tried it.  I believe the `on_data_available` is close to what you had, but the one I used was adapted from another project.

https://github.com/mitza-oci/OpenDDS/tree/issue-3347/examples/Issue3347
