### ISSUE TITLE
Extend travis configuration with a matrix of configurations

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#335]
Currently on travis-ci only the default configuration is tested. Using the env matrix support more configurations could be tested which reduces the likelihood of problems on the scoreboard. We do this already for the ACE/TAO travis configuration

**Comment by mitza-oci** [comment]
I can add entries to .travis.yml.  Let me know which configurations have been problematic before.  Some of the optional 3rd party dependencies may be hard to set up on travis, but besides that we should be able to add to it.

**Comment by jwillemsen** [comment]
versioned_namespace is one when the pending pull requests are merged and we have a new TAO release. I did notice several ifdef checks, probably you know better which configurations impact the (generated) code heavily.

**Comment by mitza-oci** [comment]
As we discussed on #343, travis should test built_in_topics=0.

**Comment by jwillemsen** [comment]
we should also enable -Werror on travis-ci at the moment my pull request for read/take is in, at that moment we should be able to compile warning free (when the auto_ptr deprecated warnings are disabled)

**Comment by mitza-oci** [comment]
The problem with -Werror on travis is that the compilers are very old.  Our policy has been to try to be warning-free on the latest versions of the major compilers.  Some older versions emit warnings when they shouldn't.

We are working on removing auto_ptr from OpenDDS code.  Unfortunately we'll probably still see some sneak in from ACE headers.

**Comment by jwillemsen** [comment]
Maybe this link gives some ideas http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

**Comment by mitza-oci** [comment]
See PR #420

**Comment by oschwaldp-oci** [comment]
Have added builds to exercise the following:
    - FUZZ=1
    - NO_INLINE=1
    - NO_BIT=1
    - STATIC=1 NO_DEBUG=1
    - SAFETY_PROFILE=1
    - MOD_DEFAULT_FEATURES=1 USES_WCHAR=1

Added builds for modern compilers based on the post from @jwillemsen, now build with:
-g++-4.9
-g++-5
-clang++-3.6
-clang++-3.7

Anything else we're missing? Suggestions?

**Comment by jwillemsen** [comment]
Looks ok, closing
