### ISSUE TITLE
Generated gen_skip_over functions don't check result of length demarshaling

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#337]
I was looking at the generated code and noticed that for example 'BooleanSeqTypeSupportImpl.cpp' the function 'void gen_skip_over(Serializer& ser, CORBA::BooleanSeq*)' is generated as below. The demarshaling of length is not checked, this is done in the 'bool operator>>(Serializer& strm, CORBA::BooleanSeq& seq)' function which is just above. At the moment we get incorrect data just skipping length independent of demarshaling succeeded or not looks a risk

```
void gen_skip_over(Serializer& ser, CORBA::BooleanSeq*)
{
  ACE_UNUSED_ARG(ser);
  ACE_CDR::ULong length;
  ser >> length;
  ser.skip(length, 1);
}
```

**Comment by mitza-oci** [comment]
This isn't data received from the network, it's used on the writer side to manage cached serialized samples.

**Comment by jwillemsen** [comment]
Ok, but it doesn't seem a good thing to ignore all return values which could indicate an error situation
