### ISSUE TITLE
Fail to build the monitor App

### ISSUE THREAD

**Issue by mycrocs** [objectcomputing/OpenDDS#3378]
I have installed the Qt5 and set the environment variable. But when i build the monitor app, there are some errors.

_Invoking "\bin\uic on GvOptions.ui"  System can't find the path.
Invoking "\bin\uic on Monitor.ui"  System can't find the path.
Invoking "\bin\uic on NodeOptions.ui"  System can't find the path.
Invoking "\bin\uic on RepoDialog.ui"  System can't find the path.
Invoking "\bin\moc on GvOptions.h"  System can't find the path.
Invoking "\bin\moc on MonitorDataModel.h"  System can't find the path.
Invoking "\bin\moc on NodeOptions.h"  System can't find the path.
Invoking "\bin\moc on RepoSelect.h"  System can't find the path.
Invoking "\bin\moc on Viewer.h"  System can't find the path.
Invoking "\bin\rcc on Monitor.qrc"  System can't find the path._

Could you help me solve the problem?

**Comment by mitza-oci** [comment]
It looks like `QT5_BINDIR` is expanding to an empty string.  Please see `config/qt5_core.mpb` in the MPC repository for how this is configured.
