### ISSUE TITLE
/bigobj error when build Win64 application in VS2015

### ISSUE THREAD

**Issue by mycrocs** [objectcomputing/OpenDDS#3411]
When i build my OpenDDS  Win64 application in VS2015, it have the /bigobj error.
![image](https://user-images.githubusercontent.com/31428244/158922451-087d8337-aa19-4fae-829c-bb8e642e84ce.png)
How could i solve the problem without openning the switch /bigobj?

**Comment by iguessthislldo** [comment]
This is common when there's a significant amount of IDL. Assuming you're using MPC, you can include the [`msvc_bigobj`](https://github.com/objectcomputing/OpenDDS/blob/master/MPC/config/msvc_bigobj.mpb) subproject. Here is an example:

https://github.com/objectcomputing/OpenDDS/blob/945a0df6f4a2e52be9eb766d7b717d146d1649f1/tests/DCPS/Compiler/xcdr/xcdr.mpc#L1

**Comment by mycrocs** [comment]
It works. Thanks!
