### ISSUE TITLE
No Coverity-scan build

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#342]
Looks there is no build using Coverity Scan (see https://scan.coverity.com/) yet for OpenDDS

**Comment by mitza-oci** [comment]
It is on our list of things to do "soon" but I'm not sure when it will happen.  Depending on what happens with other tasks I'd like to get it by the end of the year.

**Comment by jwillemsen** [comment]
Could you create a project on Coverity scan and send me the submit key/email directly, will see what I can do the coming week or so

**Comment by jwillemsen** [comment]
I think when you make me admin I can also see the key and submit some builds

**Comment by jwillemsen** [comment]
Let us do it the other way around, I will try to setup a build and create a project and add you as admin when I have created the project

**Comment by jwillemsen** [comment]
Created project on coverity scan and the first build is running

**Comment by jwillemsen** [comment]
First results are uploaded, waiting for Coverity to review the project

**Comment by jwillemsen** [comment]
The project is now enabled and all issues can be seen. @mitza-oci you are an administrator and should be able to add users, tweak settings, etc.
