### ISSUE TITLE
Build problem with PR #338

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/OpenDDS#343]
@jwillemsen: There's an error on build dds_doc_master_mosquito_linux_gcc_d0o1i0c1 which disables built-in topics at compile time.  The PR added #include "dds/DdsDcpsCoreTypeSupportC.h" in tests/DCPS/StaticDiscovery/DataReaderListenerImpl.cpp.  That include can be guarded by an ifdef for DDS_HAS_MINIMUM_BIT.

**Comment by mitza-oci** [comment]
And yes, this is a configuration we can try adding Travis CI

**Comment by jwillemsen** [comment]
Fixed
