### ISSUE TITLE
IDL containing an array generated uncompilable JNI code

### ISSUE THREAD

**Issue by tgh5187** [objectcomputing/OpenDDS#3473]
When generating/building a java project with an IDL that contains an array (e.g. char testArray[4];), the JNI *jc.cpp file fails to compile due to "<attributeName>_forany" is undeclared. I've attached a zip file containing the IDL, the project file, the build log, and the export file. This is being build on Windows with VS2017. I've successfully compiled and run the Java Messenger test. If you add an array "char testArray[4];" to the Message struct in the Messenger.idl file in that project, it also fails with the same error.

MPC File:
```
project: dcps_java { 
  idlflags += -Cw -Wb,stub_export_include=Test_Export.h \
	-Wb,stub_export_macro=Test_Export 
	
	dcps_ts_flags += -Cw -Wb,export_macro=Test_Export 
	
	idl2jniflags += -Cw -Wb,stub_export_include=Test_Export.h \
		-Wb,stub_export_macro=Test_Export
	
	dynamicflags += TEST_BUILD_DLL
	
	specific {
		jarname = DDS_Test_types
	}
	
	TypeSupport_Files {
		TestMessage.idl
	}
}
```

IDL:
```
#ifndef TEST_MESSAGE_IDL
#define TEST_MESSAGE_IDL

module base 
{
   module test 
   {         
      @topic
      struct TestMessage
      {      
         char testArray[4];
      };
   };
};

#endif
```

Error snippet from file:
1><base_dir>\minimal_failure\testmessagejc.cpp(23): error C2039: 'testArray_forany': is not a member of 'base::test::TestMessage'
1><base_dir>\minimal_failure\testmessagec.h(111): note: see declaration of 'base::test::TestMessage'
1><base_dir>\minimal_failure\testmessagejc.cpp(23): error C2065: 'testArray_forany': undeclared identifier
1><base_dir>\minimal_failure\testmessagejc.cpp(23): error C2146: syntax error: missing ';' before identifier 'fa'
1><base_dir>\minimal_failure\testmessagejc.cpp(23): error C3861: 'fa': identifier not found
1><base_dir>\minimal_failure\testmessagejc.cpp(24): error C2065: 'fa': undeclared identifier
1><base_dir>\minimal_failure\testmessagejc.cpp(46): error C2039: 'testArray_forany': is not a member of 'base::test::TestMessage'
1><base_dir>\minimal_failure\testmessagec.h(111): note: see declaration of 'base::test::TestMessage'
1><base_dir>\minimal_failure\testmessagejc.cpp(46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1><base_dir>\minimal_failure\testmessagejc.cpp(46): error C2146: syntax error: missing ';' before identifier 'fa'
1><base_dir>\minimal_failure\testmessagejc.cpp(46): error C2061: syntax error: identifier 'testArray'
1><base_dir>\minimal_failure\testmessagejc.cpp(47): error C2065: 'fa': undeclared identifier

[minimal_failure.zip](https://github.com/objectcomputing/OpenDDS/files/8542223/minimal_failure.zip)

**Comment by mitza-oci** [comment]
Anonymous IDL types are not currently supported in the Java code generation.  Please try changing it to.

```
      typedef char CharArray4[4];
      @topic
      struct TestMessage
      {      
         CharArray4 testArray;
      };
```

**Comment by tgh5187** [comment]
Thanks. Will that still be compatible with another product using the IDL with the IDL as it currently is?

**Comment by mitza-oci** [comment]
Yes, it doesn't change the way the data is encoded.

**Comment by tgh5187** [comment]
Thanks
