### ISSUE TITLE
Delayed samples while streaming video over VPN

### ISSUE THREAD

**Issue by tmayoff** [objectcomputing/OpenDDS#3482]
We're trying to stream H264 encoded 1080p@60fps video over OpenDDS but the samples we received are continuously delayed, to the point where the framerate at which we're receiving them is ~41fps. It seems like all the samples are being delayed but the biggest impact coming from keyframes. This was tested with and without a VPN (whether openvpn or wireguard, as well a local VPN server or on a VPS) and only degrades with it, we've also tested using basic TCP sockets (with VPN) and it doesn't have the issue.

Each gap in the below image is a larger sample getting delayed up to 200ms.
![Hitches](https://user-images.githubusercontent.com/10094264/166004176-b776d053-4b07-4c8c-bf5e-20a3a0c5ab28.png)

The current transport configuration used on both subscriber and publisher. I've tried both TCP and UDP.
```
[transport/ovpntransport]
transport_type=tcp
local_address=10.0.7.3
thread_per_connection=1
max_packet_size=5147481599
optimum_packet_size=8192
```

I've also followed the DevGuide for optimizing the DataReader reads.

**Comment by simpsont-oci** [comment]
Hi, could you give a few more details about how you've got your publisher and subscriber application set up? What platform/s are you running on and what configuration options are you using? Are your applications using a single topic / datawriter / datareader or is the setup more complicated? What qos policies are you using for both the writer and reader and how are you dividing frames into instances? How are you measuring latency? Are you using listeners or waitset + readcondition?

Hopefully we can make some suggestions about how to tweak things for performance, and then possibly we can take a look to see what might be causing delays in the code.

**Comment by tmayoff** [comment]
Our setup is fairly simple, we have a small wrapper around OpenDDS itself, it's a single topic and a single datawriter and datareader. As for Qos policies this last test was with just the default policies, I had previously tried messing with durability, reliability, history, but nothing seemed to have a significant impact. For this test frames aren't being divided by us we're taking the encoded frames and passing them directly into OpenDDS, I also experimented with splitting each frame into a fixed number of smaller samples, as well as combining multiple frames into a single sample, and neither seemed to have an impact. We're using listeners and measuring the time between each call to the listener using [tracy ](https://github.com/wolfpld/tracy).

**Comment by tmayoff** [comment]
Okay I'll give that a try thanks! (also topic keys are filled with the camera's serial numbers as we have the potential for multiple cameras in our system)

**Comment by tmayoff** [comment]
Unfortunately that didn't help

Just to make sure, these are the changes I made adapted from the ReadCondition test.
```C++
template <typename TStructure>
inline TStructure DDSSubscriber<TStructure>::BlockForData() {
  DDS::ReadCondition_var condition = reader->create_readcondition(DDS::NOT_READ_SAMPLE_STATE, DDS::ANY_VIEW_STATE, DDS::ANY_INSTANCE_STATE);

  DDS::WaitSet_var ws = new DDS::WaitSet;
  ws->attach_condition(condition);

  TStructure t;

  while (true) {
    DDS::ConditionSeq conditions;
    auto res = ws->wait(conditions, {DEFAULT_TIMEOUT, 0});
    if (res == DDS::RETCODE_TIMEOUT) {
      Log::error("Wait timedout");
    } else if (res == DDS::RETCODE_OK) {
      // Wait succeeded
      using ReaderType = typename TypeTraits<TStructure>::Reader;
      using Sequence = typename TypeTraits<TStructure>::Sequence;
      auto reader_i = ReaderType::_narrow(reader);
      Sequence tSeq;
      DDS::SampleInfoSeq infos{};
      res = reader_i->take_w_condition(tSeq, infos, 1, condition);
      if (infos[0].valid_data) {
        // Valid Data here
        t = tSeq[0];
        break;
      }
    }
  }

  ws->detach_condition(condition);
  return t;
}
```

**Comment by tmayoff** [comment]
Okay so with some more testing of different network configurations (just to make sure we've isolated exactly the conditions that cause this), it might not linked to the VPN but rather the physical distance. We're trying to stream the video over a distance of ~500km, However again this does work with well enough with raw sockets

**Comment by simpsont-oci** [comment]
Have you tried running without thread per connection? I believe thread-per-connection has to copy samples into a separate queue, which might be pretty expensive for large samples.

**Comment by tmayoff** [comment]
Yes initial tests were done without it, this was the initial config
```
[transport/ovpntransport]
transport_type=tcp
local_address=10.0.7.3
```
I'd like to try to simplify and write a more focused and cutdown test however have been busy lately. Are there any general things we can do to optimize for sending large samples

**Comment by jrw972** [comment]
Please reopen when you have created your test.
