### ISSUE TITLE
TcpConnection::close when communicate between two virtual machine

### ISSUE THREAD

**Issue by mycrocs** [objectcomputing/OpenDDS#3489]
I create three virtual machines by VMware and all install opendds3.16. One machine runs the InfoRepo, the others run the Appllications. Applications find the InfoRepo by the repo.ior. However, when i start the applications, TcpConnection::close problem comes up.
![image](https://user-images.githubusercontent.com/31428244/166615018-429786b8-844f-4868-8b68-4b16b3f59f64.png)
Here are the logs.
[DCPSInfoRepo.log](https://github.com/objectcomputing/OpenDDS/files/8628468/DCPSInfoRepo.log)
[Application_log.txt](https://github.com/objectcomputing/OpenDDS/files/8628470/Application_log.txt)

On the side, when i run the applications on only one virtual machine by InfoRepo, it won't have this problem.

**Comment by mitza-oci** [comment]
Please run it with `-DCPSTransportDebugLevel <n>` and try with n = 3 or higher.  Then the debug log should have some more detail about what the tcp transport is doing.
