### ISSUE TITLE
Random Ports on publishers and subscribers

### ISSUE THREAD

**Issue by tfwa77** [objectcomputing/OpenDDS#3490]
While testing OpenDDS on a developement environment I noticed that publishers and subscribers open random ports in listening mode. In our production environment we must define the accessible ports, how these ports are used for? There is a way to configure them?

The programs used for testing are simple programs that creates respectively a Publisher, along with its DataWriter, and a Subscriber, along with its DataReader.

```
$ netstat -tulpn | grep pub
tcp        0      0 0.0.0.0:43107           0.0.0.0:*               LISTEN      2259881/./pub       
tcp        0      0 0.0.0.0:3998            0.0.0.0:*               LISTEN      2259881/./pub       
tcp        0      0 0.0.0.0:3999            0.0.0.0:*               LISTEN      2259881/./pub
```

```
$ netstat -tulpn | grep sub
tcp        0      0 0.0.0.0:3898            0.0.0.0:*               LISTEN      2260004/./sub       
tcp        0      0 0.0.0.0:3899            0.0.0.0:*               LISTEN      2260004/./sub       
tcp        0      0 0.0.0.0:37347           0.0.0.0:*               LISTEN      2260004/./sub 
```

I also tried running pub and sub with the `-ORBListenEndpoints` flag.
```
$ ./pub -ORBListenEndpoints iiop://:4545
```

```
$ ./sub -ORBListenEndpoints iiop://:4546
```

The result, however, did not change

EDIT: I forgot to post the .ini files of pub and sub:
```
$ cat config-pub.ini 
[common]
DCPSBitTransportIPAddress=0.0.0.0
DCPSBitTransportPort=3999
DCPSGlobalTransportConfig=myconfig
[config/myconfig]
transports=mytcp
[transport/mytcp]
transport_type=tcp
local_address=0.0.0.0:3998
pub_address=0.0.0.0:3898
```

```
$ cat config-sub.ini 
[common]
DCPSBitTransportIPAddress=0.0.0.0
DCPSBitTransportPort=3899
DCPSGlobalTransportConfig=myconfig
[config/myconfig]
transports=mytcp
[transport/mytcp]
transport_type=tcp
local_address=0.0.0.0:3898
pub_address=0.0.0.0:3898
```

**Comment by mitza-oci** [comment]
I was not able to reproduce this problem using `tests/DCPS/Messenger` as the example application.  If you're using the program's argc/argv to customize the port number used by TAO, make sure that argv is passed through to OpenDDS using `TheParticipantFactoryWithArgs(argc, argv);`.
