### ISSUE TITLE
Error when trying to re-create participants after participant shutdown

### ISSUE THREAD

**Issue by dvucko** [objectcomputing/OpenDDS#3505]
I'm dealing with a problem where after shutting down/disposing OpenDDS object members, I cannot re-initialize them again. Within a class that represents a publisher (publishing works normally), I have the following members:
```
DDS::DomainId_t domainId;
DDS::DomainParticipantFactory_var participantFactory{nullptr};
DDS::DomainParticipant_var participant{nullptr};
DDS::DataWriter_var writer1{nullptr};
DDS::DataWriter_var writer2{nullptr};

IDL::Msg1DataWriter_var dataWriter1{nullptr};
IDL::Msg2DataWriter_var dataWriter2{nullptr};
IDL::Msg1TypeSupport_var typeSupport1{nullptr};
IDL::Msg2TypeSupport_var typeSupport2{nullptr};
```
I initialize this once after object creation (error checking etc. omitted for brevity):
```
participantFactory = TheParticipantFactoryWithArgs(argc, argv);
participant = participantFactory->create_participant(config->domainId, PARTICIPANT_QOS_DEFAULT, nullptr, OpenDDS::DCPS::DEFAULT_STATUS_MASK);

typeSupport1 = new IDL::Msg1TypeSupportImpl;
typeSupport1->register_type(participant, "")

typeSupport2 = new IDL::Msg2TypeSupportImpl;
typeSupport2->register_type(participant, "")

DDS::Topic_var topic1 = participant->create_topic(topicName1, typeSupport1->get_type_name(), TOPIC_QOS_DEFAULT, nullptr, OpenDDS::DCPS::DEFAULT_STATUS_MASK);        
DDS::Topic_var topic2 = participant->create_topic(topicName2, typeSupport2->get_type_name(), TOPIC_QOS_DEFAULT, nullptr, OpenDDS::DCPS::DEFAULT_STATUS_MASK);
        
DDS::Publisher_var publisher = participant->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr, OpenDDS::DCPS::DEFAULT_STATUS_MASK);        
DDS::DataWriterQos qos;
publisher->get_default_datawriter_qos(qos);
qos.history.kind = DDS::KEEP_ALL_HISTORY_QOS;
qos.reliability.kind = DDS::BEST_EFFORT_RELIABILITY_QOS;

writer1 = publisher->create_datawriter(topic1, qos, nullptr, OpenDDS::DCPS::DEFAULT_STATUS_MASK);
writer2 = publisher->create_datawriter(topic2, qos, nullptr, OpenDDS::DCPS::DEFAULT_STATUS_MASK);
        
dataWriter1 = IDL::Msg1DataWriter::_narrow(writer1);
dataWriter2 = IDL::Msg2DataWriter::_narrow(writer2);
```

Cleanup is done on object destruction essentially like this: 
```
participant->delete_contained_entities();
participantFactory->delete_participant(participant);
TheServiceParticipant->shutdown();
```
However, after this cleanup code executes (successfully), I can no longer run the initialization code above when creating another object. If I try to do that, I get the following error:
```
Service_Participant::load_configuration open() returned -1
Service_Participant::get_domain_participant_factory: load_configuration() failed.
```

Am I doing something wrong?

**Comment by jwillemsen** [comment]
See https://github.com/objectcomputing/OpenDDS/issues/3428, for the load_configuration I made a change, see https://github.com/objectcomputing/OpenDDS/pull/3426

**Comment by mitza-oci** [comment]
Is this still a problem with the current version?

**Comment by iguessthislldo** [comment]
> ```
> (2131|2131) WARNING: Service_Participant::~Service_Participant: There are 1 remaining domain participant(s). It is recommended to delete them before shutdown.
> ../../../dds/DCPS/RcHandle_T.h:112: T* OpenDDS::DCPS::RcHandle<T>::operator->() const [with T = OpenDDS::RTPS::Spdp]: > Assertion `ptr_' failed.
> Aborted
> ```

Could you post the stack trace on that abort if possible?

Also out of curiosity, could you post what the value that `participant->delete_contained_entities();` and
`participantFactory->delete_participant(participant);`. The restart test should probably be checking them, but it isn't.

**Comment by jrw972** [comment]
Reopen when necessary.
