### ISSUE TITLE
Can the application using OpenDDS be built in VS Release mode?

### ISSUE THREAD

**Issue by mycrocs** [objectcomputing/OpenDDS#3523]
When i build the aplication in Release, a error comes up.
error LNK1181	can't open file “ACE.lib”

**Comment by mycrocs** [comment]
I use the configure script in OpenDDS to generate the VS solution. It use the Debug  configuration by default and build the ACE. How can i make it to build ACE in no debug configuration?

**Comment by mycrocs** [comment]
I use the configure script in OpenDDS to generate the VS solution. It use the Debug  configuration by default and build the ACE. How can i make it to build ACE in no debug configuration?

**Comment by mitza-oci** [comment]
Start over from a completely clean working directory (no ACE+TAO download, no files created by configure, etc.).
Run the configure script. Note that for VS `--no-debug` doesn't really do anything significant.
The configure script creates a solution file `DDS_TAOv2.sln` which contains both Debug and Release configurations.
Select your desired Configuration in Visual Studio before building the solution.

**Comment by mycrocs** [comment]
Thanks. I create a clean working directory and build the solution in Release configuration successfully.
