### ISSUE TITLE
Several tests are running for 30 seconds even when there are no executables compiled

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#353]
When working on new windows builds I had a build run where nothing was compiled but several tests seem to run 30 seconds because they don't check if the spawn did success. 

```
tests/DCPS/SharedTransport/run_test.pl udp


X:\BUILD\DOC_ROOT\DDS\bin\.\\DCPSInfoRepo.EXE -o repo.ior
ERROR: Cannot Spawn: <X:\BUILD\DOC_ROOT\DDS\bin\.\\DCPSInfoRepo.EXE> not found
ERROR: waiting for Info Repo IOR file

auto_run_tests_finished: tests/DCPS/SharedTransport/run_test.pl udp Time:31s Result:0

```

A quick parse gives the following tests that need some work

- [ ] tests/DCPS/Prst_delayed_subscriber/run_test.pl
- [ ] tests/DCPS/DCPSInfoRepo/run_test.pl
- [ ] tests/DCPS/FooTest3_0/run_test.pl
- [ ] tests/DCPS/DcpsIntegration/run_test-topic.pl
- [ ] tests/DCPS/FooTest4/run_test.pl
- [ ] tests/DCPS/MultiRepoTest/run_test.pl
- [ ] tests/DCPS/Presentation/run_test.pl
- [ ] tests/DCPS/Reconnect/run_test.pl
- [ ] tests/DCPS/BuiltInTopicTest/prst_repo_run_test.pl
- [ ] tests/transport/simple/run_test.pl bp
- [ ] performance-tests/DCPS/InfoRepo_population/run_test.pl
- [ ] DevGuideExamples/DCPS/Messenger/run_test.pl
- [ ] DevGuideExamples/DCPS/Messenger_ZeroCopy/run_test.pl
- [ ] tests/DCPS/Messenger/run_corbaloc_test.pl
- [ ] tests/DCPS/Messenger/run_ns_test.pl
- [ ] examples/DCPS/Messenger_Imr/run_test.pl
- [ ] tests/DCPS/TransientDurability/run_test.pl
- [ ] tests/DCPS/PersistentDurability/run_test.pl
- [ ] tests/DCPS/StatusCondition/run_test.pl
- [ ] tests/DCPS/QueryCondition/run_test.pl
- [ ] tests/DCPS/ContentFilteredTopic/run_test.pl
- [ ] tests/DCPS/ContentFilteredTopic/run_test.pl nopub
- [ ] tests/DCPS/MultiTopic/run_test.pl
- [ ] tests/DCPS/Federation/run_test.pl
- [ ] tests/DCPS/Priority/run_test.pl
- [ ] tests/DCPS/SharedTransport/run_test.pl
- [ ] tests/DCPS/Ownership/run_test.pl
- [ ] tests/DCPS/GroupPresentation/run_test.pl
- [ ] tests/DCPS/ConfigFile/run_test.pl
- [ ] tests/DCPS/SubscriberCycle/run_test.pl
- [ ] tests/DCPS/PersistentInfoRepo/run_test.pl

**Comment by mitza-oci** [comment]
Seems like a lot of work to handle a situation that should never happen anyway.  If you want to make changes we can accept them but I don't know if it's worth the effort.

There is a newer style of test script using common functions from a Perl module (see grep for "new PerlDDS::TestFramework()").  If you're going to modify run_test.pl, the modified versions should use this new style.
