### ISSUE TITLE
Can we build opendds with gcc on windows

### ISSUE THREAD

**Issue by tantan1** [objectcomputing/OpenDDS#3533]
I need to integrate opendds with golang, I choose cgo to invoke  opendds client, the golang is built by gcc, when I build golang with opendds lib, it causes build error.
OS: window10
golang version 1.16 amd64
strawberry-perl-5.32.1.1-64bit
opendds3.16.1
run configure with vs2015 prompt comand line. 
build with vs2022 prompt comand line

**Comment by mitza-oci** [comment]
What's the error?

**Comment by tantan1** [comment]
@mitza-oci 
when I build test lib with gcc, it works fine, but when I build test dll with vs2022 v, it shows the error.

Build Error: go build -o myprojectdir\__debug_bin.exe -gcflags all=-N -l .
# myproject/dds
Warning: corrupt .drectve at end of def file
myprojectdir/testdll.lib(x64/Debug/ddsWrapper.obj):(.rtc$IMZ+0x0): undefined reference to `_RTC_InitBase'
myprojectdir/testdll.lib(x64/Debug/ddsWrapper.obj):(.rtc$TMZ+0x0): undefined reference to `_RTC_Shutdown'
collect2.exe: error: ld returned 1 exit status (exit status 2)

`package dds

//#cgo CFLAGS: -I.
//#cgo LDFLAGS: -L${SRCDIR}/ -ltestdll
//#include "ddsWrapper.h"
import "C"

func Sign(a int, b int, c int) int {
	r := C.number_add_mod(C.int(a), C.int(b), C.int(c))
	return int(r)
}`

**Comment by tantan1** [comment]
it's vs runtime check error, can resolve by vs compile setting change
