### ISSUE TITLE
OpenDDS doesn't compile with Visual Studio 2015 using nmake

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#354]
See http://buildlogs.remedy.nl/win_msvc14_opendds_debug/

**Comment by mitza-oci** [comment]
That is surprising since we have been running a build on vc14 since the time it was released
dds_doc_master_hornet_win7-x64_vc14_i1d1o0w1

**Comment by mitza-oci** [comment]
> DDS\\DDS_TAOv2_all.mwc -type nmake -base vc14nmake

The nmake support hasn't been kept up to date since it's rarely used.  If you want to use it, see the "specific" section in tools/monitor/Monitor.mpc and grep for similar constructs.  You could also switch to "-type vc14".

**Comment by mitza-oci** [comment]
Also 32-bit shouldn't have this problem with /bigobj.

**Comment by jwillemsen** [comment]
Fixed
