### ISSUE TITLE
Cleanup (deleting participant) code hangs indefinitely on some systems

### ISSUE THREAD

**Issue by dvucko** [objectcomputing/OpenDDS#3553]
I'm dealing with a problem where the following textbook-like cleanup code completes normally on some systems, but will often (but not always) hang indefinitely on others during runtime:

```
Publisher::~Publisher()
{
    // Only OpenDDS cleanup code is called inside a destructor.
    cleanup();
}


void Publisher::cleanup()
{
    log("OpenDDS cleanup in progress.");

    try {
	// m_participant is DDS::DomainParticipant_var assigned in ctor
        if (m_participant != nullptr) {
            log("OpenDDS cleanup: deleting contained entities.");
            m_participant->delete_contained_entities();
        }

	// m_participantFactory is DDS::DomainParticipantFactory_var assigned in ctor
        if (m_participantFactory != nullptr) {
            log("OpenDDS cleanup: deleting participant.");
            m_participantFactory->delete_participant(m_participant);  // This is where the execution hangs on some systems.
        }

        log("OpenDDS cleanup: shutting down.");
        TheServiceParticipant->shutdown();

        m_participant = nullptr;
        m_participantFactory = nullptr;        
        m_openDdsInitialized = false;

        ACE::fini(); // Not sure if this is needed. In ctor, there is an ACE::init() call at the start, but none of these seems to have an impact.
    }
    catch (std::runtime_error const &e) {		
        log("Runtime error while trying to shutdown OpenDDS", e);
        throw;
    }
    catch (CORBA::Exception const &e) {
        log("CORBA exception while trying to shutdown OpenDDS.", e);
        throw;
    }

    log("OpenDDS cleanup completed.");
}
```

This was tried on two different Ubuntu 20.04.3 LTS installations; one of them being a Dockerized development machine (where no issues occur), and another being a typical installation. None of them has firewall enabled, and the same configuration ini is used. The same binary was used for testing on both machines.

OpenDDS version used is 3.20.0, but this was already a problem in earlier versions.

Config.ini file used:
```
[common]
DCPSDebugLevel=0
DCPSDefaultDiscovery=the_rtps_discovery
DCPSGlobalTransportConfig=the_config
DCPSDefaultAddress=127.0.0.1

[config/the_config]
transports=the_transport

[transport/the_transport]
transport_type=rtps_udp
heartbeat_period=1

[rtps_discovery/the_rtps_discovery]
ResendPeriod=5
SedpLocalAddress=127.0.0.1:
SpdpLocalAddress=127.0.0.1

```

Any ideas what could be going on?

**Comment by dvucko** [comment]
Thank you, Timothy. Could you elaborate on what you mean by "trying to reassociate"? I will try what you propose.

**Comment by simpsont-oci** [comment]
As part of shutting down, unregister / dispose messages are sent for both the user and built-in endpoint instances. If a participant message is, for some reason, received after these unregister / dispose messages, the association process could be triggered again as if a new connection was being formed. Depending on the discovery mechanisms and transports involved, it can often be difficult to distinguish between these "late" messages and legitimate attempts to reconnect.

**Comment by dvucko** [comment]
DCPSPendingTimeout didn't completely resolve the issue by itself, so I implemented a workaround by initializing/cleaning OpenDDS on a separate thread and terminating gracefully in case of a surpassed timeout. The concept is the following one:

```
auto futureOpenDdsCleanup = std::async(std::launch::async, [&]() { openDdsCleanup(); }); // async call to the code that was previously in dtor

if (futureOpenDdsCleanup.wait_for(std::chrono::seconds(4)) == std::future_status::timeout) {
  std::terminate();
}
```

**Comment by mitza-oci** [comment]
Do you see the same behavior with the latest revision on the master branch?  There have been some changes since 3.20 that may impact it.

**Comment by dvucko** [comment]
Hi Adam, thank you for your proposal and please excuse my lack of response. I haven't tried the latest version yet: I will try to do that when possible and will let you know as soon as I have some results.
