### ISSUE TITLE
Cannot build DCPS Messenger example with C++17 or C++20

### ISSUE THREAD

**Issue by shinywong** [objectcomputing/OpenDDS#3565]
OpenDDS: v3.20
ACE+TAO: v2.2a_p23
OS: Windows 11 21H2 (22000.739)
IDE: Visual Studio 2022 v17.2.4
Platform Toolset: Visual Studio 2022 (v143)
Target plaform: Debug AMD64

I tried to build "DevGuideExamples\DCPS\Messenger\Messenger_Publisher.vcxproj" project.
Its default C++ standard is C++14. With C++14 the project was built succeeded.

But after changing C++ standard to C++17 or C++20, build will fail:

> Error C2039
> 'auto_ptr': is not a member of 'std'
> ACE_wrappers\ace\Auto_Ptr.h
> Line 81

The Auto_Ptr.h:

`#if defined (ACE_USES_STD_NAMESPACE_FOR_STDCPP_LIB) && \`
`            (ACE_USES_STD_NAMESPACE_FOR_STDCPP_LIB != 0)`
`using std::auto_ptr;` // Line 81.
`#endif /* ACE_USES_STD_NAMESPACE_FOR_STDCPP_LIB */`

I also tried to build it in Visual Studio 2019 with VS2019 Toolset (v142), the results were the same.

Apparently, std::auto_ptr was removed in C++17.
How can I build it with C++17?

The reason to use C++17 is that I want to use OpenDDS 3.20 in a Qt 6 application. And Qt 6 requires C++17.
Another question is, can I use OpenDDS in Qt 6? [qt.md](https://github.com/objectcomputing/OpenDDS/blob/master/docs/qt.md) only mentioned Qt 5.

**Comment by jwillemsen** [comment]
Try to rerun `configure` using `--doc-group3 ` to use ACE 7.0.x and TAO 3.0.x, these require C++11 and have much better support for the newer C++ versions. You have to remove your existing ACE tree first.

**Comment by shinywong** [comment]
@jwillemsen 

👍Thanks.

After configured OpenDDS with DOC ACE+TAO 7.0.6, the example project can now be compiled with C++17 or C++20.
