### ISSUE TITLE
Subscribers sometimes not getting any messages from a publisher on machines with lower memory/CPU count

### ISSUE THREAD

**Issue by dvucko** [objectcomputing/OpenDDS#3571]
I have a weird, hard-to-reproduce problem. On the same local host (Ubuntu), there's a publisher (DataWriter) process and a sample subscriber (DataReader) process. Normally, subscriber processes receive the messages sent by the publisher with high-frequency (10 Hz). However, when testing this on a VM with limited resources -- e.g. 2 GB of memory, 2 CPUs instead of the usual 8 GB/4 CPUs -- subscribers sometimes, maybe once per every 15 attempts/startups, won't receive any messages at all. Each subscriber initializes successfully and keeps running, but it seems as if it never establishes a subscription with the publisher. This problem never appears if a VM was assigned sufficiently high memory and CPU count.

I'm not quite sure what could be the reason for this, and where to begin looking, mostly because it's very hard to reproduce the issue. Any ideas what I should be looking at?  I realize it's hard to give specific answers without details, but perhaps there's something conceptual that could be obvious to someone with more knowledge.

The config.ini file:
```
[common]
DCPSDebugLevel=0
DCPSDefaultDiscovery=the_rtps_discovery
DCPSGlobalTransportConfig=the_config
DCPSDefaultAddress=127.0.0.1
DCPSPendingTimeout=4

[config/the_config]
transports=the_transport

[transport/the_transport]
transport_type=rtps_udp
heartbeat_period=1

[rtps_discovery/the_rtps_discovery]
ResendPeriod=5
SedpLocalAddress=127.0.0.1:
SpdpLocalAddress=127.0.0.1
```

**Comment by jrw972** [comment]
My first suggestion is to set the DCPSDebugLevel to at least 1.  What you are looking for is `Spdp::handle_participant_data - %C discovered %C lease %C from %C (%B)`.  This is the first message that is logged as part of discovery.  It will contain the the guid of the remote participant that you can use to trace the discovery process.

You can also post a sanitized log and that might provide some insight.

**Comment by dvucko** [comment]
Thank you for the tip. Both publisher and subscriber output the following at the start, but I'm not sure if that's indicative of any issue:
```
NOTICE: Service_Participant::load_domain_ranges(): config does not have a [DomainRange] section.
NOTICE: TransportRegistry::load_transport_templates(): config does not have a [transport_template] section.
NOTICE: Service_Participant::load_domain_configuration(): failed to open [domain] section - using code default.
NOTICE: StaticDiscovery::parse_topics no [topic] sections.
NOTICE: StaticDiscovery::parse_datawriterqos no [datawriterqos] sections.
NOTICE: StaticDiscovery::parse_datareaderqos no [datareaderqos] sections.
NOTICE: StaticDiscovery::parse_publisherqos no [publisherqos] sections.
NOTICE: StaticDiscovery::parse_subscriberqos no [subscriberqos] sections.
NOTICE: StaticDiscovery::parse_endpoints no [endpoint] sections.
NOTICE: Service_Participant::intializeScheduling() - no scheduling policy specified, not setting policy.
Service_Participant::get_domain_participant_factory: Creating LinuxNetworkConfigMonitor
```
I will investigate further.
