### ISSUE TITLE
Make install failure

### ISSUE THREAD

**Issue by WWjsnt10** [objectcomputing/OpenDDS#3573]
Hi，
I am trying to intsall the lib into the system. But it failed.

I used "./configure --prefix=/usr/local",  ->  >> command "make" ->>>>  "sudo make install".
I tried to export the INSTALL_PREFIX, but it failed, too.

Here is the log.
OpenDDS sudo make install
make[1]: Entering directory '/home/jianfeng/Myself/OpenDDS/dds/DCPS'

GNUmakefile: /home/jianfeng/Myself/OpenDDS/dds/DCPS/GNUmakefile.OpenDDS_Util MAKEFLAGS=w

The variable INSTALL_PREFIX must be set to install.
If binaries are already built and you want to use RPATH,
they must be rebuilt after changing INSTALL_PREFIX.
make[1]: *** [GNUmakefile.OpenDDS_Util:234: install] Error 1
make[1]: Leaving directory '/home/jianfeng/Myself/OpenDDS/dds/DCPS'
make: *** [GNUmakefile.dist:31: install] Error 2
➜  OpenDDS export INSTALL_PREFIX=/usr/local                                          
➜  OpenDDS sudo make install
make[1]: Entering directory '/home/jianfeng/Myself/OpenDDS/dds/DCPS'

GNUmakefile: /home/jianfeng/Myself/OpenDDS/dds/DCPS/GNUmakefile.OpenDDS_Util MAKEFLAGS=w

The variable INSTALL_PREFIX must be set to install.
If binaries are already built and you want to use RPATH,
they must be rebuilt after changing INSTALL_PREFIX.
make[1]: *** [GNUmakefile.OpenDDS_Util:234: install] Error 1
make[1]: Leaving directory '/home/jianfeng/Myself/OpenDDS/dds/DCPS'
make: *** [GNUmakefile.dist:31: install] Error 2

**Comment by iguessthislldo** [comment]
Can you run `./tools/scripts/show_build_config.pl` and post the output?

I'm curious about what's in `platform_macros.GNU`. Running `configure` again doesn't override that file by default. If there's something like `INSTALL_PREFIX=` in there, I imagine that would probably cause this even if you're explicitly exporting the `INSTALL_PREFIX` you want. If this is the case, then filling in that line with what you want would fix this.

**Comment by WWjsnt10** [comment]
OpenDDS ./tools/scripts/show_build_config.pl
=================================== setenv.sh ==================================
# OpenDDS configure script: ./configure --prefix=/usr/local
export ACE_ROOT="/home/jianfeng/Myself/OpenDDS/ACE_wrappers"
export CIAO_ROOT="unused"
export DANCE_ROOT="unused"
export DDS_ROOT="/home/jianfeng/Myself/OpenDDS"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/jianfeng/Myself/OpenDDS/ACE_wrappers/lib:/home/jianfeng/Myself/OpenDDS/lib"
export MPC_ROOT="/home/jianfeng/Myself/OpenDDS/ACE_wrappers/MPC"
export PATH="${PATH}:/home/jianfeng/Myself/OpenDDS/ACE_wrappers/bin:/home/jianfeng/Myself/OpenDDS/bin"
export TAO_ROOT="/home/jianfeng/Myself/OpenDDS/ACE_wrappers/TAO"
================================== VERSION.txt =================================
This is OpenDDS version 3.21.0-dev (NOT A RELEASE)
================================== ACE Version =================================
#define ACE_VERSION "6.2a_p24"
=============================== default.features ===============================
no_cxx11=0
============================== platform_macros.GNU =============================
optimize = 0
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
=================================== config.h ===================================
#include "ace/config-linux.h"


There is no information about  "INSTALL_PREFIX".

I add the "INSTALL_PREFIX=/usr/local" into the platform_macros.GNU. And it works.
