### ISSUE TITLE
Add support for IDL to C++11 generated user types

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#359]
It would be an interesting enhancement when OpenDDS would be able to support in addition to IDL to C++ defined types to also support IDL to C++11 defined types. This would at least need some extensions in the opendds idl compiler to support a different generated type system, maybe some more rework in the core.

**Comment by mitza-oci** [comment]
For FACE, opendds_idl generates the language mapping instead of counting on tao_idl to do it.  There is already support for this in dds/idl/langmap_generator.cpp.  The idea there is that (to some extent) different language mappings could be plugged in.

**Comment by jwillemsen** [comment]
In case of for example TAOX11 we already generate the type system, we only need to update the serializers and other helper methods that are generated around the type. This is something I am going to look into soon, feel free to label this as extension and assign this to me.

**Comment by mitza-oci** [comment]
Integrating with external software can be tricky, perhaps this should be a separate discussion.  I don't think it would be very hard for opendds_idl to generate what would be required -- I had this in mind when I wrote langmap_generator.cpp.

**Comment by jwillemsen** [comment]
Working on this first by manually adapting some generated code, as a result created #672, would simplify a lot of our code because we are using std::(w)string for IDL string/wstring

**Comment by jwillemsen** [comment]
Also see #686

**Comment by iguessthislldo** [comment]
Can this be closed now?
