### ISSUE TITLE
Error when building a VS2015 solution including 11 OpenDDS projects parallelly

### ISSUE THREAD

**Issue by mycrocs** [objectcomputing/OpenDDS#3590]
I create a VS2015 solution which includes 11 opendds projects. I build the idl project first and then build the other projects depending on the idl project parallelly to speed up compilation. However,  there are some errors and the solution building fail.

![AVIC1657030752903](https://user-images.githubusercontent.com/31428244/177353584-89218699-7bf7-4567-8355-de68fdd90730.png)
![AVIC1657030781024](https://user-images.githubusercontent.com/31428244/177353590-8ac90913-71e6-41f4-95bc-f6c42c543287.png)
![AVIC1657030758574](https://user-images.githubusercontent.com/31428244/177353604-7720aceb-c6af-4be2-9b14-877d202f8f82.png)
Could you help me solve the problem?

**Comment by mitza-oci** [comment]
Please use plain text instead of images so we can search, copy/paste, etc.

It seems like the code generator processes can't write to the filesystem.  Check for permissions problems and also check that each generated file is only generated by a single project.  If multiple projects have rules for generating code and they run in parallel, it won't work.

**Comment by mycrocs** [comment]
Here is the error message. 

1>------ Rebuild All started: Project: Messenger_Idl, Configuration: Debug x64 ------
1>  Invoking "D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl and "D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
1>  tao-idli_H4b24q.cpp
1>  tao-idli_IqfQQg.cpp
1>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
1>  tao-idli_GtX2Kr.cpp
2>------ Rebuild All started: Project: Messenger_Broker, Configuration: Debug x64 ------
3>------ Rebuild All started: Project: Messenger_Manage, Configuration: Debug x64 ------
4>------ Rebuild All started: Project: Messenger_Plane, Configuration: Debug x64 ------
5>------ Rebuild All started: Project: Messenger_Xeng, Configuration: Debug x64 ------
6>------ Rebuild All started: Project: Messenger_Xfmus, Configuration: Debug x64 ------
7>------ Rebuild All started: Project: Messenger_Xfmuw, Configuration: Debug x64 ------
8>------ Rebuild All started: Project: Messenger_Xhmi, Configuration: Debug x64 ------
9>------ Rebuild All started: Project: Messenger_Xmfd, Configuration: Debug x64 ------
10>------ Rebuild All started: Project: Messenger_Xnd, Configuration: Debug x64 ------
11>------ Rebuild All started: Project: Messenger_Xpfd, Configuration: Debug x64 ------
12>------ Rebuild All started: Project: Messenger_Xpfdlogic, Configuration: Debug x64 ------
2>  Broker.cpp
4>  DataShared.cpp
3>  Invoking "D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl and "D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
3>  tao-idli_Z4Xe6v.cpp
5>  DataShared.cpp
6>  DataShared.cpp
3>  ERROR - couldn't open MessengerTypeSupportImpl.h for writing.
3>  Fatal Error - Aborting
3>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
7>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
3>  tao-idli_RHUa9f.cpp
4>  MessengerC.cpp
7>  tao-idli_jS4YR0.cpp
7>  be_visitor_root_ch::init - Error opening client header file
7>  be_visitor_root_ch::init - failed to initialize
7>  BE_visit_root - client header for Root failed
7>  Fatal Error - Aborting
8>  DataShared.cpp
7>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
9>  DataShared.cpp
11>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
2>  BrokerReaderListenerImpl.cpp
3>  be_visitor_root_ch::init - Error opening client header file
3>  be_visitor_root_ch::init - failed to initialize
3>  BE_visit_root - client header for Root failed
3>  Fatal Error - Aborting
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
12>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
7>  tao-idli_Hazzse.cpp
11>  tao-idli_LcOnAW.cpp
10>  Invoking "D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl and "D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
11>  be_visitor_root_ch::init - Error opening client header file
11>  be_visitor_root_ch::init - failed to initialize
11>  BE_visit_root - client header for Root failed
11>  Fatal Error - Aborting
11>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
4>  MessengerS.cpp
5>  MessengerC.cpp
12>  tao-idli_67wLfn.cpp
7>  be_visitor_root_ch::init - Error opening client header file
7>  be_visitor_root_ch::init - failed to initialize
7>  BE_visit_root - client header for Root failed
7>  Fatal Error - Aborting
12>  be_visitor_root_ch::init - Error opening client header file
12>  be_visitor_root_ch::init - failed to initialize
12>  BE_visit_root - client header for Root failed
12>  Fatal Error - Aborting
12>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
10>  tao-idli_z31uuC.cpp
7>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
6>  MessengerC.cpp
11>  tao-idli_L8JLcM.cpp
12>  tao-idli_aZA62r.cpp
10>  ERROR - couldn't open MessengerTypeSupportImpl.h for writing.
10>  Fatal Error - Aborting
10>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
4>  MessengerTypeSupportC.cpp
4>c1xx : fatal error C1083: Cannot open source file: “MessengerTypeSupportC.cpp”: Permission denied
10>  tao-idli_2vbDOm.cpp
4>  MessengerTypeSupportImpl.cpp
5>  MessengerS.cpp
8>  MessengerC.cpp
11>  DataShared.cpp
6>  MessengerS.cpp
9>  MessengerC.cpp
2>  DataShared.cpp
12>  DataShared.cpp
10>  DataShared.cpp
5>  MessengerTypeSupportC.cpp
8>  MessengerS.cpp
6>  MessengerTypeSupportC.cpp
9>  MessengerS.cpp
8>  MessengerTypeSupportC.cpp
9>  MessengerTypeSupportC.cpp
2>  MessengerC.cpp
5>  MessengerTypeSupportImpl.cpp
11>  MessengerC.cpp
12>  MessengerC.cpp
6>  MessengerTypeSupportImpl.cpp
10>  MessengerC.cpp
2>  MessengerS.cpp
11>  MessengerS.cpp
12>  MessengerS.cpp
8>  MessengerTypeSupportImpl.cpp
9>  MessengerTypeSupportImpl.cpp
10>  MessengerS.cpp
2>  MessengerTypeSupportC.cpp
11>  MessengerTypeSupportC.cpp
12>  MessengerTypeSupportC.cpp
10>  MessengerTypeSupportC.cpp
11>  MessengerTypeSupportImpl.cpp
2>  MessengerTypeSupportImpl.cpp
12>  MessengerTypeSupportImpl.cpp
10>  MessengerTypeSupportImpl.cpp
4>  MessengerTypeSupportS.cpp
4>  Plane.cpp
5>  MessengerTypeSupportS.cpp
6>  MessengerTypeSupportS.cpp
9>  MessengerTypeSupportS.cpp
8>  MessengerTypeSupportS.cpp
5>  xEng.cpp
6>  xFmuS.cpp
4>  PlaneReaderListenerImpl.cpp
9>  xMfd.cpp
8>  xHmi.cpp
2>  MessengerTypeSupportS.cpp
12>  MessengerTypeSupportS.cpp
11>  MessengerTypeSupportS.cpp
5>  xEngReaderListenerImpl.cpp
4>  Generating Code...
10>  MessengerTypeSupportS.cpp
6>  xFmuSReaderListenerImpl.cpp
11>  xPfd.cpp
12>  xPfdLogic.cpp
2>  Generating Code...
9>  xMfdReaderListenerImpl.cpp
8>  xHmiReaderListenerImpl.cpp
10>  xNd.cpp
5>  Generating Code...
6>  Generating Code...
9>  Generating Code...
8>  Generating Code...
12>  xPfdLogicReaderListenerImpl.cpp
11>  xPfdReaderListenerImpl.cpp
10>  xNdReaderListenerImpl.cpp
12>  Generating Code...
11>  Generating Code...
10>  Generating Code...
5>  Generating Code...
5>  Messenger_Xeng.vcxproj -> C:\Users\AVICASGT\Desktop\111\.\xeng.exe
5>  Messenger_Xeng.vcxproj -> .\\xeng_exe.pdb (Full PDB)
2>  Messenger_Broker.vcxproj -> C:\Users\jack\Desktop\111\.\broker.exe
2>  Messenger_Broker.vcxproj -> .\\broker_exe.pdb (Full PDB)
6>  Messenger_Xfmus.vcxproj -> C:\Users\jack\Desktop\111\.\xfmus.exe
6>  Messenger_Xfmus.vcxproj -> .\\xfmus_exe.pdb (Full PDB)
8>  Messenger_Xhmi.vcxproj -> C:\Users\jack\Desktop\111\.\xhmi.exe
8>  Messenger_Xhmi.vcxproj -> .\\xhmi_exe.pdb (Full PDB)
9>  Messenger_Xmfd.vcxproj -> C:\Users\jack\Desktop\111\.\xmfd.exe
9>  Messenger_Xmfd.vcxproj -> .\\xmfd_exe.pdb (Full PDB)
11>  Messenger_Xpfd.vcxproj -> C:\Users\jack\Desktop\111\.\xpfd.exe
11>  Messenger_Xpfd.vcxproj -> .\\xpfd_exe.pdb (Full PDB)
12>  Messenger_Xpfdlogic.vcxproj -> C:\Users\jack\Desktop\111\.\xpfdlogic.exe
12>  Messenger_Xpfdlogic.vcxproj -> .\\xpfdlogic_exe.pdb (Full PDB)
10>  Messenger_Xnd.vcxproj -> C:\Users\jack\Desktop\111\.\xnd.exe
10>  Messenger_Xnd.vcxproj -> .\\xnd_exe.pdb (Full PDB)
========== Rebuild All: 9 succeeded, 3 failed, 0 skipped ==========

**Comment by mycrocs** [comment]
I find each project will generate the files below. Is it the reason why my solution building fail?
If so, how can i generate the files only once?

1>  MessengerC.cpp
1>  MessengerS.cpp
1>  MessengerTypeSupportC.cpp
1>  MessengerTypeSupportImpl.cpp
1>  MessengerTypeSupportS.cpp

**Comment by mitza-oci** [comment]
`Rebuild All` in Visual Studio doesn't do what we want because it's treating each project as a separate unit that can be cleaned and built on its own -- see https://stackoverflow.com/questions/1247457/difference-between-rebuild-and-clean-build-in-visual-studio for some useful details

Try `Clean Solution` (if needed) followed by `Build Solution`

**Comment by mycrocs** [comment]
I clean the solution and build it again, but don't solve the problem. Here is the error message.

1>------ Build started: Project: Messenger_Idl, Configuration: Debug x64 ------
1>  Invoking "D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl and "D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
1>  tao-idli_CUHaJJ.cpp
1>  tao-idli_A6gkUp.cpp
1>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
1>  tao-idli_VNhMmy.cpp
2>------ Build started: Project: Messenger_Broker, Configuration: Debug x64 ------
3>------ Build started: Project: Messenger_Manage, Configuration: Debug x64 ------
4>------ Build started: Project: Messenger_Plane, Configuration: Debug x64 ------
5>------ Build started: Project: Messenger_Xeng, Configuration: Debug x64 ------
6>------ Build started: Project: Messenger_Xfmus, Configuration: Debug x64 ------
7>------ Build started: Project: Messenger_Xfmuw, Configuration: Debug x64 ------
8>------ Build started: Project: Messenger_Xhmi, Configuration: Debug x64 ------
9>------ Build started: Project: Messenger_Xmfd, Configuration: Debug x64 ------
10>------ Build started: Project: Messenger_Xnd, Configuration: Debug x64 ------
11>------ Build started: Project: Messenger_Xpfd, Configuration: Debug x64 ------
12>------ Build started: Project: Messenger_Xpfdlogic, Configuration: Debug x64 ------
2>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
2>  tao-idli_WQ1V0W.cpp
2>  tao-idli_e1pKyc.cpp
3>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
2>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
4>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
3>  tao-idli_TLIcLJ.cpp
6>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
2>  tao-idli_3GXdJT.cpp
5>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
4>  tao-idli_n89IZY.cpp
3>  DataShared.cpp
3>c:\users\jack\desktop\111\messengertypesupportimpl.h(5): fatal error C1083: Cannot open include file: “MessengerC.h”: No such file or directory
3>  Manage.cpp
7>  Invoking "D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl and "D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
6>  tao-idli_PPdxmY.cpp
8>  Invoking "D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl and "D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
2>  Broker.cpp
5>  tao-idli_JgzX1U.cpp
4>  tao-idli_rjfAPN.cpp
7>  tao-idli_OZDBBL.cpp
4>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
6>  tao-idli_sH4YPx.cpp
9>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
8>  tao-idli_IyMP0B.cpp
5>  tao-idli_DLWEXn.cpp
6>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
11>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
5>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
3>  ManageReaderListenerImpl.cpp
4>  tao-idli_9hYM06.cpp
12>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" and D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl on Messenger.idl"
7>  tao-idli_AA0fnT.cpp
9>  tao-idli_BHVvI9.cpp
7>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
6>  tao-idli_X2kxZb.cpp
11>  tao-idli_BYfuU0.cpp
8>  tao-idli_jNxmSd.cpp
8>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
10>  Invoking "D:\Opendds316_64\OpenDDS-3.16\bin\opendds_idl and "D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on Messenger.idl"
5>  tao-idli_acz5zL.cpp
2>  BrokerReaderListenerImpl.cpp
6>  be_visitor_root_ch::init - Error opening client header file
6>  be_visitor_root_ch::init - failed to initialize
6>  BE_visit_root - client header for Root failed
6>  Fatal Error - Aborting
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
9>  tao-idli_COBXqn.cpp
12>  tao-idli_194bRn.cpp
4>  DataShared.cpp
11>  tao-idli_uy67GS.cpp
7>  tao-idli_QZio8O.cpp
9>  ERROR - couldn't open MessengerTypeSupportImpl.h for writing.
9>  Fatal Error - Aborting
10>  tao-idli_Wj2Wpz.cpp
9>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
8>  tao-idli_FmKkfr.cpp
11>  ERROR - couldn't open MessengerTypeSupportImpl.h for writing.
11>  Fatal Error - Aborting
3>  MessengerC.cpp
11>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
12>  tao-idli_Cx0gIk.cpp
10>  ERROR - couldn't open MessengerTypeSupportImpl.h for writing.
10>  Fatal Error - Aborting
5>  DataShared.cpp
10>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
9>  tao-idli_QbWkTp.cpp
4>c:\users\jack\desktop\111\messengertypesupportimpl.h(12): fatal error C1083: Cannot open include file: “MessengerTypeSupportC.h”: No such file or directory
4>  MessengerC.cpp
12>  ERROR - couldn't open MessengerTypeSupportImpl.h for writing.
12>  Fatal Error - Aborting
12>  Invoking ""D:\Opendds316_64\OpenDDS-3.16\ACE_wrappers\bin\tao_idl" on MessengerTypeSupport.idl"
11>  tao-idli_7jbLxV.cpp
10>  tao-idli_Wr6Hga.cpp
7>  DataShared.cpp
2>  DataShared.cpp
3>  MessengerS.cpp
11>  be_visitor_root_ch::init - Error opening client header file
11>  be_visitor_root_ch::init - failed to initialize
11>  BE_visit_root - client header for Root failed
11>  Fatal Error - Aborting
8>  DataShared.cpp
12>  tao-idli_HXX3x9.cpp
11>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
10>  be_visitor_root_ch::init - Error opening client header file
10>  be_visitor_root_ch::init - failed to initialize
10>  BE_visit_root - client header for Root failed
10>  Fatal Error - Aborting
10>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
9>  DataShared.cpp
4>  MessengerS.cpp
12>  be_visitor_root_ch::init - Error opening client header file
12>  be_visitor_root_ch::init - failed to initialize
12>  BE_visit_root - client header for Root failed
12>  Fatal Error - Aborting
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
3>  Generating Code...
5>  MessengerC.cpp
4>  MessengerTypeSupportC.cpp
7>  MessengerC.cpp
2>  MessengerC.cpp
8>  MessengerC.cpp
5>  MessengerS.cpp
9>  MessengerC.cpp
4>  MessengerTypeSupportImpl.cpp
7>  MessengerS.cpp
2>  MessengerS.cpp
5>  MessengerTypeSupportC.cpp
8>  MessengerS.cpp
9>  MessengerS.cpp
7>  MessengerTypeSupportC.cpp
2>  MessengerTypeSupportC.cpp
8>  MessengerTypeSupportC.cpp
9>  MessengerTypeSupportC.cpp
5>  MessengerTypeSupportImpl.cpp
7>  MessengerTypeSupportImpl.cpp
2>  MessengerTypeSupportImpl.cpp
8>  MessengerTypeSupportImpl.cpp
9>  MessengerTypeSupportImpl.cpp
4>  MessengerTypeSupportS.cpp
5>  MessengerTypeSupportS.cpp
4>  Plane.cpp
7>  MessengerTypeSupportS.cpp
8>  MessengerTypeSupportS.cpp
2>  MessengerTypeSupportS.cpp
5>  xEng.cpp
9>  MessengerTypeSupportS.cpp
7>  xFmuW.cpp
8>  xHmi.cpp
4>  PlaneReaderListenerImpl.cpp
2>  mysql.cpp
9>  xMfd.cpp
2>  Generating Code...
5>  xEngReaderListenerImpl.cpp
4>  Generating Code...
7>  xFmuWReaderListenerImpl.cpp
8>  xHmiReaderListenerImpl.cpp
9>  xMfdReaderListenerImpl.cpp
5>  Generating Code...
7>  Generating Code...
8>  Generating Code...
9>  Generating Code...
5>    Creating library .\xeng.lib and object .\xeng.exp
5>  Generating code
2>  Messenger_Broker.vcxproj -> C:\Users\jack\Desktop\111\.\broker.exe
2>  Messenger_Broker.vcxproj -> .\\broker_exe.pdb (Full PDB)
7>    Creating library .\xfmuw.lib and object .\xfmuw.exp
8>    Creating library .\xhmi.lib and object .\xhmi.exp
7>  Generating code
8>  Generating code
9>    Creating library .\xmfd.lib and object .\xmfd.exp
9>  Generating code
5>  Finished generating code
8>  Finished generating code
7>  Finished generating code
9>  Finished generating code
5>  Messenger_Xeng.vcxproj -> C:\Users\jack\Desktop\111\.\xeng.exe
5>  Messenger_Xeng.vcxproj -> .\\xeng_exe.pdb (Full PDB)
8>  Messenger_Xhmi.vcxproj -> C:\Users\jack\Desktop\111\.\xhmi.exe
8>  Messenger_Xhmi.vcxproj -> .\\xhmi_exe.pdb (Full PDB)
7>  Messenger_Xfmuw.vcxproj -> C:\Users\jack\Desktop\111\.\xfmuw.exe
7>  Messenger_Xfmuw.vcxproj -> .\\xfmuw_exe.pdb (Full PDB)
9>  Messenger_Xmfd.vcxproj -> C:\Users\jack\Desktop\111\.\xmfd.exe
9>  Messenger_Xmfd.vcxproj -> .\\xmfd_exe.pdb (Full PDB)
========== Build: 6 succeeded, 6 failed, 0 up-to-date, 0 skipped ==========

**Comment by mitza-oci** [comment]
The `Messenger_Idl` project builds completely first before the others can start to run in parallel.  So that part is working.  

What's not working is that the other projects run the code generators instead of seeing that the output files are already there (and newer than the inputs/dependencies).  Could you attach one of the vcxproj files?

Another thing to consider is that when you have 11 projects using the generated code it may be better to have the IDL project build a library (many tests in OpenDDS do this so there's lots of examples) instead of making each downstream project compile each translation unit on its own.

**Comment by mycrocs** [comment]
Here is the vcxproj file.
[Messenger_Broker.zip](https://github.com/objectcomputing/OpenDDS/files/9080470/Messenger_Broker.zip)

**Comment by mycrocs** [comment]
It works. Thank you!
