### ISSUE TITLE
exception specification throw (CORBA::SystemException) still used

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#361]
Lot of code still uses throw (CORBA::SystemException) in the method declaration as exception specification. This is not part of the IDL to C++ language mapping and doesn't add value, should be removed globally through all code

**Comment by jwillemsen** [comment]
@mitza-oci do you agree we should remove these exception specifications, if so, feel free to assign this to me

**Comment by mitza-oci** [comment]
I found instances of it in tests, examples, etc. so I think what happened is that they were removed from the core a long time ago but were not removed from tests.  I don't have a problem with removing them.

**Comment by jwillemsen** [comment]
Fixed
