### ISSUE TITLE
latency exception when using SHM and RTPS discovery to transport message of small size

### ISSUE THREAD

**Issue by ChYUYAO** [objectcomputing/OpenDDS#3614]
When I was using RTPS discovery and SHM to test the latency of two processes in one host,I found when testing the small size of 10 Byte as well as 1K,the latency will be biger than 1M,10M and 100M.Is this a bug?
The result seems as belllow:

| 消息数据量\运行情况 | average | mdian|
| --- | --- | --- |
|10B | 100.657 | 100.666|
|1K | 100.67 | 100.665|
|1M | 2.4538 | 2.4538|
|10M | 27.9316 | 27.2585|
|100M | 286.431 | 274.735|

As the same time,my sleep_for()'s parameter is exactly 100ms,and the latency of 10B and 1K will change as long as my sleep_for() changes.Is there any relations?
Here is one part of my code:
```
    for (int i = 0; i < 100; ++i) {
      uint64_t sys_time=std::chrono::duration_cast<std::chrono::microseconds>
                                (std::chrono::system_clock::now().time_since_epoch()).count();
      message.sendTime = sys_time;
      DDS::ReturnCode_t error = message_writer->write(message, DDS::HANDLE_NIL);
      ++message.cnt;
      std::this_thread::sleep_for(std::chrono::milliseconds(100));
```
after all message are sent,there is a warning in pub:
```
Block until subscriber is available
Subscriber is available
(613222|613224) WARNING: TransportSendStrategy::stop() - terminating with 72 unsent bytes.
(613222|613224) WARNING: TransportSendStrategy::stop() - terminating with 0 unsent elements.
(613222|613224) WARNING: TransportSendStrategy::stop() - terminating with 0 queued elements.
```

**Comment by ChYUYAO** [comment]
Oh!I find when I run ./Publisher first,and then run ./Subscriber,the latency will be normal.That's Why?

**Comment by jrw972** [comment]
It depends on how the programs are structured and coordinate.  A common pattern we use when testing is
1. Publisher waits for subscriber to start.
2. Publisher publishes the messages.
3. Subscriber terminates when it has all of the messages.
4. Publisher waits for the subscriber to go away.

This assumes that the subscriber is reliable and it knows the number of messages to expect.

It is certainly possible that the shared memory transport has issues.

**Comment by ChYUYAO** [comment]
> It depends on how the programs are structured and coordinate. A common pattern we use when testing is
> 
> 1. Publisher waits for subscriber to start.
> 2. Publisher publishes the messages.
> 3. Subscriber terminates when it has all of the messages.
> 4. Publisher waits for the subscriber to go away.
> 
> This assumes that the subscriber is reliable and it knows the number of messages to expect.
> 
> It is certainly possible that the shared memory transport has issues.

Thank you for your explainations.There may be some issues in the shared memory transport,I will try to find out where the problem is.By the way,I want to comfirm to you that whether SHM transport will be ignored in one host or between hosts when there is another transport,such as rtps_udp transport, in the "transport" option.(transports=myshmem,myrtpsudp)

**Comment by ChYUYAO** [comment]
I have saw the OpenDDS Developer's Guide,and Based on the description the participants on the same host will attempt shared memory.But in my test,when I use transports=myshmem,myrtpsudp,the latency will be higher than the latency when I use transports=myshmem.Is that a normal situation？And why does this happend?
My test result are as follows:
"transports=myshmem":
Payload\situations | average | median
10byte | 0.3784 | 0.3985
1K | 0.59546 | 0.7075
1M | 2.4538 | 2.4538
10M | 27.9316 | 27.2585
100M | 286.431 | 274.73

compare to only make "transports=myshmem,myrtpsudp":
Payload\situations | 1p1s in same host | 1p1s in different host | 1p2s 2host
-- | -- | -- | --                       local | remote
10byte | 0.2375 | 0.872 | 0.335 | 1.152
1K | 0.244 | 0.423 | 0.3485 | 0.7075
1M | 3.2455 | 11.492 | 3.2425 | 11.378
10M | 39.3135 | 115.278 | 36.7225 | 113.148
100M | 490.618 | 1178.6 | 510.035 | 1189.7

(in the first column，we can see the latency will be higher between the participants on the same host）

**Comment by jrw972** [comment]
If you have a scenario where a publisher is communicating with a subscriber via shared memory and a subscriber via RTPS, then the publisher has to do twice the work.

I invite you to read the code and logs to verify.
