### ISSUE TITLE
OpenDDS shared memory transport?

### ISSUE THREAD

**Issue by h1r4n** [objectcomputing/OpenDDS#3617]
Does OpenDDS support shared memory transport? It is shortly mentioned in the developers guide, although i cannot seem to find any benchmarks done by anyone. Is it an implemented feature or is it planned for future implementation? Can someone point me to a benchmark or a comparison if it is available.

Thank you!

**Comment by jrw972** [comment]
OpenDDS does support shared memory.  However, it may have some bugs.  I'm not aware of a published benchmark.

**Comment by h1r4n** [comment]
That is great!. Is there a compiled list of known bugs for shared memory transport?

**Comment by h1r4n** [comment]
Thanks all for all the help!
