### ISSUE TITLE
No support for @key annotation

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#366]
DDS-XTypes/IDL4 now specify @key for annotating the key fields of an IDL type. Seems OpenDDS doesn't support this yet.

**Comment by mitza-oci** [comment]
There are lots of things in lots of other specs that OpenDDS doesn't support.  OpenDDS supports the specs that it is documented as supporting.  I'm not sure the usefulness of a GitHub issue for this sort of thing.

I'm sure we'll be adding more support for parts of XTypes and IDL4 in the future.  Does TAO_IDL_FE parse annotations?

**Comment by jwillemsen** [comment]
As far as I know tao_idl doesn't parse annotations, ridlc does

**Comment by mitza-oci** [comment]
I'm not sure how ridlc is relevant to this issue.  OpenDDS itself needs to know what the key fields are.  OpenDDS's IDL processing is based on the TAO_IDL_FE parser.

**Comment by jwillemsen** [comment]
I mentioned ridlc as alternative, no idea how much effort it would be to extend TAO_IDL_FE to handle the IDL4 annotations

**Comment by iguessthislldo** [comment]
Closing because #1067 was merged.
