### ISSUE TITLE
OpenDDS tests fail when using MinGW-64

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#367]
As far our automated testing shows OpenDDS tests fail when using MinGW-64. Created this issue to make people aware of this and work on analyzing this further and provide fixes.

**Comment by jwillemsen** [comment]
Attached log files from the DevGuideExamples/DCPS/Messenger/run_test.pl run. What I noticed is that it just runs very quickly to a failure, no visible wait time.

[subscriber.txt](https://github.com/objectcomputing/OpenDDS/files/668816/subscriber.txt)
[publisher.txt](https://github.com/objectcomputing/OpenDDS/files/668815/publisher.txt)

**Comment by jwillemsen** [comment]
Now a run with `-ORBVerboseLogging 1` to also get timestamps
[subscriber.txt](https://github.com/objectcomputing/OpenDDS/files/668824/subscriber.txt)
[publisher.txt](https://github.com/objectcomputing/OpenDDS/files/668823/publisher.txt)

**Comment by jwillemsen** [comment]
The call `ws->wait` returns with error number 10, which is a `RETCODE_TIMEOUT`

**Comment by mitza-oci** [comment]
I guess that means it's not waiting for the required time before returning RETCODE_TIMEOUT?

**Comment by jwillemsen** [comment]
Yes, seems to give a timeout directly

**Comment by mitza-oci** [comment]
The build you're running is
> gcc version 4.9.3 (x86_64-win32-seh-rev0, Built by MinGW-W64 project)

There seems to be a "rev1" version of this compiler now available.  I'm going to test that out...

**Comment by mitza-oci** [comment]
This doesn't look right in ACE:

> (gdb) p ACE_Time_Value::max_time
> $14 = {_vptr.ACE_Time_Value = 0x6d922f50 <vtable for ACE_Time_Value+16>,
>  tv_ = {tv_sec = 0, tv_usec = -1}}

That is causing OpenDDS::DCPS::duration_to_absolute_time_value() to return the wrong value.

**Comment by jwillemsen** [comment]
Interesting observation, will extend the ACE Time_Value unit test to check that for max_time sec shouldn't be zero

**Comment by jwillemsen** [comment]
Have extended the ACE time value test, our MinGW-64 ACE/TAO build will pick that up coming night

**Comment by jwillemsen** [comment]
ACE_Time_Value::max_time is correct when tested as part of the ACE_Time_Value test so something else is happening

**Comment by mitza-oci** [comment]
$ ./Time_Value_Test
ACE_ASSERT: file Time_Value_Test.cpp, line 140 assertion failed for 'd5 == ACE_Time_Value::max_time'.Aborting...

**Comment by mitza-oci** [comment]
Everything I've seen for this points to an ACE bug,  Possibly has to do with 32-bit long (in timeval)?

I ran Time_Value_Test under gdb with a hardware watchpoint on ACE_Time_Value::max_time.tv_.  It gets set as part of static init.
```
#0  ACE_Time_Value::set (this=0x6d970090 <ACE_Time_Value::max_time>,
    sec=9223372036854775807, usec=999999)
    at C:/oci/MinGW/ACE_TAO/ACE/ace/Time_Value.inl:59
#1  0x000000006d8a1984 in ACE_Time_Value::ACE_Time_Value (
    this=0x6d970090 <ACE_Time_Value::max_time>, sec=9223372036854775807,
    usec=999999) at C:/oci/MinGW/ACE_TAO/ACE/ace/Time_Value.inl:115
#2  0x000000006d8a2dc7 in __static_initialization_and_destruction_0 (
    __initialize_p=1, __priority=65535) at Time_Value.cpp:39
```
In set() before normalize():
> New value = {tv_sec = -1, tv_usec = 999999}

After normalize():
> New value = {tv_sec = 0, tv_usec = -1}

We haven't claimed compatibility with MinGW and I'm not aware of anyone using it.  I wouldn't mind adding it once the issue is resolved.  We'll have to consider the MinGW build "experimental" until then.
