### ISSUE TITLE
Extend OpenDDS TypeSupport with an unregister_type operation

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#368]
Currently OpenDDS doesn't provide the functionality to unregister a type from its type support. Other DDS vendors provide this and as far as I remember there should be an issue on the DDS specification to add this.

**Comment by mitza-oci** [comment]
I could not find an OMG issue for it here: http://issues.omg.org/issues/lists/dds-rtf5

What is the use case for unregsitering?  I agree that it's a good idea in general, but as long as there is a small number of types the overhead is small.

Is this for unloading and then loading a modified version of the type?  That would be difficult to coordinate across the network.

**Comment by jwillemsen** [comment]
It is for unloading components and its associated connectors from a running lwccm application, at that moment we also want to unload the dds type specific dll

**Comment by mitza-oci** [comment]
In this case is the DomainParticipant object deleted?  If so, the types are effectively unregistered anyway.  In the DDS API, types are registered "belonging" to a specific participant.

**Comment by jwillemsen** [comment]
Not always, we try to limit the amount of dp instances as much as we can

**Comment by mitza-oci** [comment]
You can add to the OpenDDS-specific interface in $DDS_ROOT/dds/DdsDcpsTypeSupportExt.idl.

**Comment by mathersm** [comment]
Working with containers we also came across this issue. Another place where it raises its head is with the interface for the OpenDDS::DCPS::Data_Types_Register. There is no unregister_type method available on the interface for that singleton. When the singleton itself goes to unregister all its registered types if any component has been unloaded (that also unloads the final reference to a type library) it will lead to access violations.

**Comment by mitza-oci** [comment]
@mathersm please clarify what you mean by "containers" here?

Data_Types_Register is an internal class (as you can see by the namespace), it only exists to meet the requirements of the spec.  If/when there is an enhancement made to DdsDcpsTypeSupportExt.idl, it can be changed as well.

Are you planning on contributing that change?

**Comment by mathersm** [comment]
@mitza-oci I'm referring to component containers. Probably why we've noted similar issues to @jwillemsen.

I have a branch with a simple change to the Data_Types_Register in a forked repo (https://github.com/mathersm/OpenDDS/tree/Issue-368_Extend_OpenDDS_TypeSupport_with_an_unregister_type_operation). I couldn't see an existing branch in the main repo to address this issue so I'm not sure how you would like to manage pull requests etc.

**Comment by jwillemsen** [comment]
Thanks for starting with this, also extend/add a unit test to test this functionality. Also the error case where a non-registered type is tried to unregister. At the moment you are ready with the change open a pull request to get this integrated into master

**Comment by mitza-oci** [comment]
Please create an issue against the spec: http://issues.omg.org/issues/create-new-issue

**Comment by jwillemsen** [comment]
@mathersm Any plans to complete this change? When this is ready I can remove some ifdefs from DDSX11 which is part of our AXCIOMA product

**Comment by mathersm** [comment]
I've been working on a test program but I've run into some issues with the virtual method table associated with the type support implementation. I seem to be able to routinely scrub the last entry in the table by the introduction of the new signature into the IDL. I can achieve this horrible feat by either adding the signature to DdsDcpsTypeSupportExt.idl or DdsDcpsTopic.idl (for curiosity to be the same as register_type). As a result, I can break spectacularly on either a call to has_dcps_key  (DdsDcpsTypeSupportExt.idl) or get_type_name (DdsDcpsTopic.idl) if they are the last signatures in those files.

**Comment by mathersm** [comment]
Ok, I've initiated a pull request now with a simple test. Please feel free to review and suggest improvements.

**Comment by mitza-oci** [comment]
Do you still have the "virtual method table" problem mentioned above?  That seems like it would be a symptom of not running "make depend" before rebuilding when headers/IDL are changed.

Also please don't forget the comment above about the OMG spec.  Please post the link or an issue number once one is assigned.

**Comment by mathersm** [comment]
I'm no longer seeing the virtual method table problem. I have submitted an issue to OMG.

**Comment by mitza-oci** [comment]
Do you have a link or issue number from OMG?

**Comment by mathersm** [comment]
http://issues.omg.org/browse/INBOX-372
