### ISSUE TITLE
Problem with inter-domain connection between Publisher and Subscriber using RTPS protocol

### ISSUE THREAD

**Issue by DusanStanisic99** [objectcomputing/OpenDDS#3681]
I am having a problem establishing an inter-domain connection between publisher and subscriber. 
The publisher is running on Ubuntu Linux 20.04 PC and the subscriber is running on Qualcomm 8155 board with Android 12 operating system(OpenDDS have also been built for Android using NDK). I want to use unicast instead of multicast and I can confirm connectivity between my PC and the board (ping and DDS over TCP are working)

//Configuration file for publisher
[common]
DCPSGlobalTransportConfig=$file
DCPSDebugLevel=0

[transport/relay1]
transport_type=rtps_udp
use_multicast=0
local_address=192.168.1.111:55555 //address of publisher

[domain/42]
DiscoveryConfig=application_rtps_discovery

[rtps_discovery/application_rtps_discovery]
SedpMulticast=0
ResendPeriod=2
SpdpSendAddrs=192.168.1.120:8410 //address of subscriber

//Configuration file for subscriber
[common]
DCPSGlobalTransportConfig=$file
DCPSDebugLevel=0

[transport/relay1]
transport_type=rtps_udp
use_multicast=0
local_address=192.168.1.120:8410 //subscriber address

[domain/42]
DiscoveryConfig=application_rtps_discovery

[rtps_discovery/application_rtps_discovery]
SedpMulticast=0
ResendPeriod=2
SpdpSendAddrs=192.168.1.111:55555 //publisher address

Am I missing some parameters or am I using the wrong values?

**Comment by jrw972** [comment]
I don't have confidence that `//` works as a comment character.  You should change it to `#` to be safe.

When using RTPS for transport and discovery, OpenDDS will create three ports:
* One for SPDP
* One for SEDP
* One for data transport (DATA)

You are currently configuring it so the SPDP from the publisher is being sent to the DATA port of the subscriber and vice versa.  To correct it, I would
* Not specify the local_address in the transports unless absolutely necessary.
* In the `rtps_discovery` sections, use the `SpdpLocalAddress` option to specify the local send and receive address.
* Change the `SpdpSendAddrs` to those in the previous step.
* Turn on debugging to ensure that discovery is happening.

**Comment by DusanStanisic99** [comment]
@jrw972 
Yes, I am aware that // doesn't work as a comment that was just for this post.
Anyway, in the meantime, I managed to confirm the communication between Qualcomm(subscriber) and the Virtual machine(publisher) with the following configurations, so maybe someone will find it helpful:

----------------------------------------------------------------------------
# Configuration file of a publisher
[common]
DCPSGlobalTransportConfig=$file
DCPSDebugLevel=10
DCPSLogLevel=debug

#publisher's IP address for avoiding warning for FQDN where you don't specify IP address explicitly
DCPSDefaultAddress =192.168.1.111

[transport/relay1]
transport_type=rtps_udp
use_multicast=0

[domain/42]
DiscoveryConfig=application_rtps_discovery

[rtps_discovery/application_rtps_discovery]
SedpMulticast=0
ResendPeriod=2

#subscriber's IP address for sending
SpdpSendAddrs=192.168.1.126:12345

#publisher's sedp and spdp for discovering
SpdpLocalAddress=192.168.1.111
SedpLocalAddress=192.168.1.111:
----------------------------------------------------------------------------
#Configuration file of a subscriber
[common]
DCPSGlobalTransportConfig=$file
DCPSDebugLevel=10
DCPSLogLevel=debug
DCPSSecurity=1

#subscriber's IP address for avoiding warning for FQDN where you don't specify IP address explicitly
DCPSDefaultAddress=192.168.1.126

[transport/rtps]
transport_type=rtps_udp
use_multicast=0

[domain/42]
DiscoveryConfig=application_rtps_discovery

[rtps_discovery/application_rtps_discovery]
SedpMulticast=0
ResendPeriod=2

#publisher's IP address for sending
#note: for some reason when I don't name port 17910 for some reason I can't establish communication(I discovered that port in #debug mode where the subscriber was trying to find this port but couldn't do it, so if this doesn't work you can try the same #thing)
SpdpSendAddrs=192.168.1.111:17910

#subscriber's sedp and spdp for discovering
SpdpLocalAddress=192.168.1.126
SedpLocalAddress=192.168.1.126:
#Change these 2 fields to the current machine's IP address

**Comment by jrw972** [comment]
@DusanStanisic99 Please close this issue if you think it is done.
