### ISSUE TITLE
Add (read|take)_instance_w_condition

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#369]
OpenDDS doesn't provide (read|take)_instance_w_condition. These are not yet part of the DDS specification but that seems to be an error, see http://issues.omg.org/browse/DDS15-26. 

It seems they where intended to be added but never ended up in the specification, not sure why. Other vendors do provide these operations, the lack in OpenDDS would trigger rework in user code when they want to switch.

**Comment by mitza-oci** [comment]
The issue was reported in 2011, any chance it will be fixed soon?  Not even any feedback from other vendors...

Rework of user code would be trivial unless QueryCondition is involved.  It shouldn't be hard to add to OpenDDS, are you planning on contributing it?

**Comment by jwillemsen** [comment]
No plans to contribute it on the short term, first need to do other some other work in order to get OpenDDS integrated into AXCIOMA.

**Comment by mitza-oci** [comment]
I asked on the OMG issues Jira for comments from other vendors.  I don't see a reason to keep this issue open since it's not a defect and it's not being actively worked.

**Comment by jwillemsen** [comment]
Looks most code is already there in the OpenDDS core, read_instance_i/take_instance_i already have a condition argument for which now zero is passed in read_instance/take_instance. @mitza-oci have you any plans to add this?

**Comment by jwillemsen** [comment]
I will try to implement this the coming days
