### ISSUE TITLE
Run run_test.pl failed.

### ISSUE THREAD

**Issue by wuxianshen** [objectcomputing/OpenDDS#3695]
OS: Win10
OpenDDS: 3.21
Perl: 5.32

After compilation, I run perl run_test.pl, it prompts:

D:\Tool\Software\OpenDDS\OpenDDS-3.21\DevGuideExamples\DCPS\Messenger>perl run_test.pl
fileparse(): need a valid pathname at D:/Tool/Software/OpenDDS/OpenDDS-3.21/ACE_wrappers/bin/PerlACE/TestTarget.pm line 122.

Here is perl -V:
@INC:
    D:\Tool\Software\OpenDDS\OpenDDS-3.21\bin
    D:/Tool/Software/OpenDDS/OpenDDS-3.21/ACE_wrappers/bin
    D:/Tool/Software/OpenDDS/OpenDDS-3.21/bin/PerlDDS
    D:/Software/Strawberry/perl/site/lib
    D:/Software/Strawberry/perl/vendor/lib
    D:/Software/Strawberry/perl/lib

How to fix this issue?

**Comment by iguessthislldo** [comment]
That looks like it corresponds to [this line in DOC Group ACE](https://github.com/DOCGroup/ACE_TAO/blob/280392c8b7831e1257f4c286a08a43685b9193ca/ACE/bin/PerlACE/TestTarget.pm#L121) which is running `dirname` on `%ACE_ROOT%`, which suggests something is wrong with that environment variable. Could you run `perl scripts/show_build_config.pl` and post the output?

**Comment by wuxianshen** [comment]
Thank you!
I run this command under scripts, which prompts:

D:\Tool\Software\OpenDDS\OpenDDS-3.21\tools\scripts>perl show_build_config.pl
================================== setenv.cmd ==================================
Couldn't open "setenv.cmd": No such file or directory
ACE_ROOT not found in setenv at show_build_config.pl line 65.

**Comment by wuxianshen** [comment]
Thanks for your instruction, and after I add the TAO and ACE environment variables, the command run smoothly with:

D:\Tool\Software\OpenDDS\OpenDDS-3.21\DevGuideExamples\DCPS\Messenger>perl run_test.pl
D:\Tool\Software\OpenDDS\OpenDDS-3.21\bin\.\DCPSInfoRepo.EXE -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
TAO (18836|18620) - Completed initializing the process-wide service context
TAO (18836|18620) - Default ORB services initialization begins
TAO (18836|18620) - ORBInitializer_Registry::register_orb_initializer 0 @00684D90
TAO (18836|18620) - ORBInitializer_Registry::register_orb_initializer 1 @00684BAC
TAO (18836|18620) - Default ORB services initialization completed
TAO (18836|18620) - We are the default ORB ...
TAO (18836|18620) - Initializing the orb-specific services
.\.\publisher.EXE  -ORBDebugLevel 10 -DCPSDebugLevel 10 -ORBVerboseLogging 1 -DCPSTransportDebugLevel 6  -ORBLogFile publisher.log
.\.\subscriber.EXE  -ORBDebugLevel 10 -DCPSDebugLevel 10 -ORBVerboseLogging 1 -DCPSTransportDebugLevel 6  -ORBLogFile subscriber.log
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 99
         from       = Comic Book Guy
         count      = 0
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 100
         from       = Comic Book Guy
         count      = 1
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 101
         from       = Comic Book Guy
         count      = 2
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 102
         from       = Comic Book Guy
         count      = 3
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 103
         from       = Comic Book Guy
         count      = 4
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 104
         from       = Comic Book Guy
         count      = 5
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 105
         from       = Comic Book Guy
         count      = 6
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 106
         from       = Comic Book Guy
         count      = 7
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 107
         from       = Comic Book Guy
         count      = 8
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = ALIVE_INSTANCE_STATE
Message: subject    = Review
         subject_id = 108
         from       = Comic Book Guy
         count      = 9
         text       = Worst. Movie. Ever.
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_DISPOSED_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_NO_WRITERS_INSTANCE_STATE
SampleInfo.sample_rank = 0
SampleInfo.instance_state = NOT_ALIVE_NO_WRITERS_INSTANCE_STATE
INFO: D:\Tool\Software\OpenDDS\OpenDDS-3.21/bin/DCPSInfoRepo being killed.

Do these msg mean that the check is passed?

**Comment by iguessthislldo** [comment]
> Do these msg mean that the check is passed?

Yes, although I'm a bit confused why it says `setenv.cmd` doesn't exist.
