### ISSUE TITLE
CMake build example failed.

### ISSUE THREAD

**Issue by wuxianshen** [objectcomputing/OpenDDS#3696]
OS: Win10
OpenDDS: 3.21
Perl: 5.32

I try to build example DevGuideExamples\DCPS\Messenger with CMake, but prompts:

Subscriber.cpp.obj : error LNK2019: Unresolved external symbol "__declspec(dllimport) public: __cdecl ACE_Main_Base::ACE_Main_Base(void)" (__imp_??0ACE_Main_Base@@QEAA@XZ)，function "public: __cdecl ACE_Main::ACE_Main(void)" (??0ACE_Main@@QEAA@XZ) 

If it is because I mess up with the configure options?

**Comment by mitza-oci** [comment]
I didn't have a problem running these steps.
- Start `x64 Native Tools Command Prompt for VS 2022`
- Set OpenDDS environment variables with `setenv.cmd`
- `cd %DDS_ROOT%\DevGuideExamples\DCPS\Messenger`
- `mkdir build & cd build`
- `cmake ..`
- `cmake --build .`
