### ISSUE TITLE
perl ./run_test.pl fails

### ISSUE THREAD

**Issue by sayajiraow** [objectcomputing/OpenDDS#3757]
Whenever  I run 'perl ./run_test.pl' command for the messenger project inside DevGuideExamples I get the following Error.

**Can't locate PerlACE/Run_Test.pm in @INC (you may need to install the PerlACE::Run_Test module) (@INC contains: /bin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /etc/perl/PerlDDS/Run_Test.pm line 10.
BEGIN failed--compilation aborted at /etc/perl/PerlDDS/Run_Test.pm line 10.
Compilation failed in require at ./run_test.pl line 13.**

This happens when I run './confogure' for OpenDDS with --prefix commandline option.
The file Run_Test.pm is present on my machine at below location still I get the error message mentioned above.
/home/<username>/OpenDDS/OpenDDS-3.22/bin/PerlDDS

Please help me to resolve this issue

**Comment by mitza-oci** [comment]
Scripts for testing are not installed.  You can run the example from the source tree.  See the `## Installation` section of `INSTALL.md` for details.  You can run the example from the source tree.  Steps to run the example are documented at https://opendds.org/quickstart/GettingStartedLinux.html

**Comment by sayajiraow** [comment]
I don't want to run the test from source tree. I want to run it from installation directory. Please tell me the method to install the PerlACE/Run_Test.pm or PerlDDS/Run_Test.pm so that the above mentioned error will not occur.

**Comment by mitza-oci** [comment]
The scripts were not designed for that.  Since it's all open source you certainly welcome to copy scripts around, change environment variables, edit them for your own use, etc.  You can also run the test/example application(s) without the help of Perl scripts.
