### ISSUE TITLE
Unitialized sample data when using XCDR2 with appendable

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#3767]
In our test when using appendable structs with XCDR2 I see that the subscriber receives uninitialized data when we have a subscriber that extended the type with some additional members. The reader uses take/read to get the samples from DDS.

The build is in release mode, when I modify the generated code to initialize the additonal members in the struct with 0 it does seem to work. 

Working on a reproducer, see #3766

**Comment by jwillemsen** [comment]
AXCIOMA does a take from OpenDDS and we get a random value back for the additional members, I get the impression that the sample is not set to default before deserializing into it.

**Comment by jwillemsen** [comment]
When I change in the generated code `bool operator>>(Serializer& strm,  ::DDS_Native::ShapeType& stru)` to call first `set_default(stru);` the unitialized data is gone, this is in release mode where not all members are automatically set to zero anymore. 

I can't find in the code any place where this is done explicitly, make sure that a sample we deserialize into is cleared. As alternative it could also be done that in case of XCDR2 and we don't get any value for a member it is set to default only at that moment, lot more generated code, but more performant.

**Comment by jwillemsen** [comment]
Looks my test addition #3766 does fail on the CI multiple times

**Comment by jwillemsen** [comment]
top of `bool operator>>` is not the correct place to call `set_default`, with nested types this will cause nested types to be initialized multiple times. In terms of performance best looks to only call `set_default` for the members which are skipped. At the moment OpenDDS supports `@default` it should also be tested that the skipped members are set to the specified `@default` value

**Comment by mitza-oci** [comment]
Yes, looks like this is a gap in the implementation.  For appendable `operator>>`, in order to have the codegen for each member to be independent of others I think we should have something like:

```
bool end_of_stream = false;

// for each member:
end_of_stream |= <existing expression that checks for the end>;
if (end_of_stream) {
  <set this member to its default>;
} else {
  <existing code block that reads this member from the stream>;
}
```
For `<set this member to its default>` there's the `type_to_default()` function in `dds_generator.h`.  This should allow extension to `@default` later.

**Comment by jwillemsen** [comment]
Thanks for the confirmation, please assign this issue to me, I will have a look at updating openddsidl

**Comment by jwillemsen** [comment]
Implemented the suggested approach as part of issue #3767

**Comment by mitza-oci** [comment]
Completed in #3766
