### ISSUE TITLE
[Example code](https://github.com/mitza-oci/OpenDDS/blob/issue865/java/tests/messenger/both/Both.java)

### ISSUE THREAD

**Issue by JefferyTW0831** [objectcomputing/OpenDDS#3787]
I refer the following steps on ubuntu command line, but it said :   
    

Error: Could not find or load main class Both
Caused by: java.lang.ClassNotFoundException: Both

what's wrong with it?
![image](https://user-images.githubusercontent.com/113592623/194843912-3591e59d-25d6-4c40-90ea-25408729dff3.png)

 [Example code](https://github.com/mitza-oci/OpenDDS/blob/issue865/java/tests/messenger/both/Both.java)

I modified one of OpenDDS's Java tests to show this scenario.  In this example, each process contains a Data Reader and a Data Writer for the same Topic.  When two processes are spawned, they will each receive both a "local" and a "remote" data sample.

To run:

1. Make sure that dynamic libraries can be loaded from directory java/tests/messenger/messenger_idl (on Windows, add it to PATH, on Linux add it to LD_LIBRARY_PATH)

2. Start two processes, each with the command line
Windows: `java -cp classes;%DDS_ROOT%/lib/i2jrt.jar;%DDS_ROOT%/lib/OpenDDS_DCPS.jar;../messenger_idl/messenger_idl_test.jar -Dopendds.native.debug=true Both -DCPSConfigFile ../rtps_disc.ini`
Linux: `java -cp classes:$DDS_ROOT/lib/i2jrt.jar:$DDS_ROOT/lib/OpenDDS_DCPS.jar:../messenger_idl/messenger_idl_test.jar Both -DCPSConfigFile ../rtps_disc.ini`

3. Manually stop the processes with Ctrl-C, no attempt was made to do a clean shutdown

_Originally posted by @mitza-oci in https://github.com/objectcomputing/OpenDDS/issues/865#issuecomment-387816246_

**Comment by mitza-oci** [comment]
Compile the Java source code `Both.java` using `javac` or a higher-level Java build system like ant, maven, or gradle.  That will result in a Java byte code file `Both.class` in the subdirectory `classes`.

**Comment by JefferyTW0831** [comment]
Thanks~~but after using javac to compile the file 'Both.java', It exists some errors. 
It seems that I haven't set env? or someting I missed?

![image](https://user-images.githubusercontent.com/113592623/194887894-c6479c3a-6b97-42f0-b584-9f8b0582156c.png)

**Comment by mitza-oci** [comment]
Assuming you've built OpenDDS with Java enabled, make sure the Java compiler's classpath includes the JAR files that come with OpenDDS.  There are Java test applications included, so I recommend using those as examples.
The Java bindings are documented in Chapter 10 of the OpenDDS Developer's Guide.

**Comment by JefferyTW0831** [comment]
sorry, how to find that java compiler's classpath includes the JAR files that come with OpenDDS

**Comment by JefferyTW0831** [comment]
So, I may to add the/java/tests/messenger/messenger_idl/libmessenger_idl_test.so to LD_LIBRARY_PATH ?

**Comment by simpsont-oci** [comment]
> So, I may to add the/java/tests/messenger/messenger_idl/libmessenger_idl_test.so to LD_LIBRARY_PATH ?

In general, you need to add the path to your jar files to classpath, and you need to add the path to the directory containing the shared object libraries (.so files) to LD_LIBRARY_PATH

**Comment by JefferyTW0831** [comment]
Thanks, after I compile it, there exists clssses folder.
But I still retry to enter the commamd on the command line:

java -cp classes:$DDS_ROOT/lib/i2jrt.jar:$DDS_ROOT/lib/OpenDDS_DCPS.jar:../messenger_idl/messenger_idl_test.jar Both -DCPSConfigFile ../rtps_disc.ini

It still say that I can't initialize the Both classes.

![image](https://user-images.githubusercontent.com/113592623/196031611-af4cd2cb-96a4-4c80-b6d3-f4a0dfa730ac.png)

**Comment by JefferyTW0831** [comment]
Thanks, this part I think is OK, but after typing the following into command line, it exists errors agian:

 java -cp classes:$DDS_ROOT/lib/i2jrt.jar:$DDS_ROOT/lib/OpenDDS_DCPS.jar:/home/jeffery/Desktop/src/OpenDDS-3.22/lib/i2jrt_corba.jar:../messenger_idl/messenger_idl_test.jarlib/i2jrt_corba.jar Both -DCPSConfigFile ../rtps_disc.ini

![image](https://user-images.githubusercontent.com/113592623/196034147-5f39ba12-f14a-4bc4-957b-e6f1473f64ed.png)

**Comment by JefferyTW0831** [comment]
Thanks, is this a right react?

![image](https://user-images.githubusercontent.com/113592623/196036725-1a03a147-f631-4074-8072-fb40afb7669d.png)

**Comment by simpsont-oci** [comment]
I don't have the test code in front of me at the moment, but that output looks correct to me.
