### ISSUE TITLE
Force compile to linux in 32bit

### ISSUE THREAD

**Issue by MarcoRoccagli** [objectcomputing/OpenDDS#3846]
As per title, how can i force compile to 32bit in a 64bit ubuntu environment?
I need this because og existing project that refers to 32bit libraries.
Thanks

**Comment by mitza-oci** [comment]
If you're using the configure script, include `--macros=buildbits=32` in the command line options.

**Comment by MarcoRoccagliSigma** [comment]
@mitza-oci Sorry to bother on this question, i've tried what you suggested but the flag seems to have no effect at all.
Thanks for your support and attention

**Comment by mitza-oci** [comment]
Were there any warnings from the configure script? Did you remove all generated files and start over from a completely clean checkout or release archive?

**Comment by mitza-oci** [comment]
It worked for me.  The generated `platform_macros.GNU` has `buildbits=32` so when make runs `g++` there's an additional `-m32` flag.

**Comment by MarcoRoccagliSigma** [comment]
Hi, where should i find platform_macros.GNU? In the main folder i can see user_macros.GNU only.
I'm just passing "./configure --macros=buildbits=32".
For your information i'm trying to do this on a WSL2 Ubuntu distro.
Thanks

**Comment by mitza-oci** [comment]
It's part of ACE.
Please run `tools/scripts/show_build_config.pl` and paste the plaintext output here.

**Comment by MarcoRoccagliSigma** [comment]
That's the output:

=================================== setenv.sh ==================================
# OpenDDS configure script: ./configure --macros=buildbits=32
export ACE_ROOT="/home/marcoroccagli/OpenDDS-3.22/ACE_wrappers"
export CIAO_ROOT="unused"
export DANCE_ROOT="unused"
export DDS_ROOT="/home/marcoroccagli/OpenDDS-3.22"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/marcoroccagli/OpenDDS-3.22/ACE_wrappers/lib:/home/marcoroccagli/OpenDDS-3.22/lib"
export MPC_ROOT="/home/marcoroccagli/OpenDDS-3.22/ACE_wrappers/MPC"
export PATH="${PATH}:/home/marcoroccagli/OpenDDS-3.22/ACE_wrappers/bin:/home/marcoroccagli/OpenDDS-3.22/bin"
export RAPIDJSON_ROOT="/home/marcoroccagli/OpenDDS-3.22/tools/rapidjson"
export TAO_ROOT="/home/marcoroccagli/OpenDDS-3.22/ACE_wrappers/TAO"
================================ user_macros.GNU ===============================
no_rapidjson=0
================================== VERSION.txt =================================
This is OpenDDS version 3.22.0, released Sep 16 2022
================================== ACE Version =================================
#define ACE_VERSION "6.2a_p25"
=============================== default.features ===============================
no_cxx11=0
no_rapidjson=0
no_rapidjson=0
============================== platform_macros.GNU =============================
buildbits=32
optimize = 0
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
=================================== config.h ===================================
#include "ace/config-linux.h"


So the flag seems to work. I will try to investigate further to solve the problem. I'll let you know the results. Yhanks for your kind support. Have a nice weekend.
