### ISSUE TITLE
Setting TopicData QOS Policy

### ISSUE THREAD

**Issue by MarcoRoccagliSigma** [objectcomputing/OpenDDS#3874]
Hi again,
I'm trying to set the 'value' field of TopicDataQosPolicy struct.
I've seen that the 'value' field requires an 'OctetSeq'.
I'm trying to set the field as follows:

                DDS::Topic_var topic;
		
		DDS::TopicQos topicqos;
		
		participant->get_default_topic_qos(topicqos);
		
		DDS::TopicDataQosPolicy  topicdataqos;
		
		
		char data[10] = "test";
		
		ACE_Message_Block * block = new ACE_Message_Block(data,10,0UL);
		
		DDS::OctetSeq * seq = new DDS::OctetSeq(10,block);
		topicdataqos.value = *seq;

		topic =
                participant->create_topic("TestTopic",
                    type_name,
                    topicqos,
                    0,
                    OpenDDS::DCPS::DEFAULT_STATUS_MASK);

Anyway when i try to set the 'value' field it seems that is not set (or at least set partially), because i can see that the 'mb' sub field is 0
I'm pretty sure that it is my fault, but i need some help to figure this out.
Thanks for your attention and support

**Comment by mitza-oci** [comment]
`topicqos` has an object of type `TopicDataQosPolicy` inside it, so there's no need to create a new one.
