### ISSUE TITLE
MAC OS Platform: Build failed

### ISSUE THREAD

**Issue by balajimohan80** [objectcomputing/OpenDDS#3896]
I am using a MAC machine, its OS version is **Ventura  13.0.1**.
When I am building an OpenDDS stack on my MAC machine build failed.
Configuration passed, but make failed.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/64716848/203619706-5e765734-3895-4b9b-ba71-e69886cc51f8.png">

**Comment by simpsont-oci** [comment]
ACE_TAO does not currently have support for macOS 13. Once that gets updated, you could try again using an updated version of ACE_TAO. https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/include/makeinclude/platform_macosx.GNU

**Comment by iguessthislldo** [comment]
DOC Group ACE/TAO should support it, but OCI ACE/TAO probably is missing [the fallback case which is a somewhat recent addition to DOC group ACE/TAO](https://github.com/DOCGroup/ACE_TAO/blob/0ac7674ea80eb14d47084ea54c778c05acbd667b/ACE/include/makeinclude/platform_macosx.GNU#L54-L55).

@balajimohan80 try again with `--doc-group3` configure script option.

**Comment by mitza-oci** [comment]
The other ACE versions had minor version fallback but not major version fallback.  It will make its way over to the other branches.

**Comment by jwillemsen** [comment]
I think this should work now with OpenDDS 3.23 and the latest OCI ACE/TAO patch release
