### ISSUE TITLE
Any way to set constructors values and equals operator in IDL?

### ISSUE THREAD

**Issue by MarcoRoccagliSigma** [objectcomputing/OpenDDS#3897]
Hello,
as per title, is there any way to set default values for struct values in constructor in IDL file definition?
Is there also a way to set the behavior for equals and NOT equals operator to automate equality operations?
Thanks

**Comment by mitza-oci** [comment]
The IDLv4 annotation `@default` is not yet supported.
Are you using the C++ classic mapping or C++11?

**Comment by MarcoRoccagliSigma** [comment]
I'm using C++ 11.
As a workaround for now I'm just deriving the generated structs in new ones and implement the equality operators by hand.
Thanks.
