### ISSUE TITLE
Reliable way to detect a topic subscriber

### ISSUE THREAD

**Issue by MarcoRoccagliSigma** [objectcomputing/OpenDDS#3917]
Hi again,
i'm trying to find a reliable way to detect when a subscriber, subscribes to topic.
Actually i'm using the code snippet in tutorials (waiting for status changes).
It seems to work (i can detect the change) but when a try to send something to the subscriber, the packet is not received( is lost).
To receive the packets, i need to wait some undefined time.
If for example i wait for 1 sec after receiving the subscribed status change, then the subscriber can start receiving the data.
For now, keep sending data until the subscriber does not receive the data is not a viable option because of existing code requires some sending data at 'one shot'.

Is there any way to have a reliabel way to detect the subscriber so that i can start immediately send the data?
Thanks for your attention and support

Regards

**Comment by simpsont-oci** [comment]
What discovery and transport are you using? What are your QoS settings? Does the publisher application exit immediately after writing data?

**Comment by MarcoRoccagliSigma** [comment]
Hi,
the discovery is automatic (no settings at all) and the trnasport that i'm using is TCP with default QOS settings (except for livelness set with 1 sec timeout). The publisher doesn't exit immediately after timeout.
Anyway, what i would do is detecting specific ip address connection/disconnection. I can see that when a peer, connects or disconnects this is logged, so is there a way to detect specific client connection/disconnection?
Thanks.

**Comment by mitza-oci** [comment]
Use Built-In Topics to be notified of changes in the DDS Domain.  To associate application-specific identity with "clients" (Domain Participants), populate their USER_DATA QoS policy.

**Comment by MarcoRoccagliSigma** [comment]
> Use Built-In Topics to be notified of changes in the DDS Domain. To associate application-specific identity with "clients" (Domain Participants), populate their USER_DATA QoS policy.

Thanks, i will try this approach that looks promising

**Comment by mitza-oci** [comment]
The DataReader for the DCPSParticipant built-in topic (like all data readers) is a cache of DDS Instances. Each participant is represented as its own instance.  When a participant leaves the domain, the corresponding instance in DCPSParticipant will be disposed.

**Comment by MarcoRoccagliSigma** [comment]
The problem is this.
It seems that is not possible to detect when a specific participant leaves the domain because none of the datareader event is called.

**Comment by mitza-oci** [comment]
Here's where it's updating the Built-In Topic in DCPSInfoRepo https://github.com/objectcomputing/OpenDDS/blob/d0e81ebf253bba2821f7c2b16b4c0e3e913dcb50/dds/InfoRepo/DCPS_IR_Domain.cpp#L1290

If this isn't working in your application please extend the test suite to demonstrate the problem.

**Comment by MarcoRoccagliSigma** [comment]
> Here's where it's updating the Built-In Topic in DCPSInfoRepo
> 
> https://github.com/objectcomputing/OpenDDS/blob/d0e81ebf253bba2821f7c2b16b4c0e3e913dcb50/dds/InfoRepo/DCPS_IR_Domain.cpp#L1290
> 
> If this isn't working in your application please extend the test suite to demonstrate the problem.

Sorry for giving you another question, but should this work only with a DCPSInfoRepo running?
Actually i'm working without it using the default rtps.ini with the rtps_udp transport so that there is no "centralized" server.


EDIT:
For testing purposes i left the main publisher opened (the one that monitors the DCPSParticipant) and the on_data_arrived was notified after a lot of time (maybe 5 minutes?). Is there any way to change this "timeout"?
Thanks

**Comment by mitza-oci** [comment]
I was answering about DCPSInfoRepo because that's what was specified in https://github.com/objectcomputing/OpenDDS/issues/3917#issuecomment-1346629160

RTPS Discovery does the same here https://github.com/objectcomputing/OpenDDS/blob/d0e81ebf253bba2821f7c2b16b4c0e3e913dcb50/dds/DCPS/RTPS/Spdp.cpp#L4679

**Comment by simpsont-oci** [comment]
For RTPS Discovery in particular,  you can also set `LeaseDuration` to be less than 5 minutes (the default) which governs when known / inactive entities are removed if no unregister or dispose is received for them.

**Comment by MarcoRoccagliSigma** [comment]
Thanks for both of those precious clarifications.
One last question is:
how to set this specific discovery qos? I can't find any example or doc for this.

Thank you

**Comment by simpsont-oci** [comment]
Check out table 7-5 in the OpenDDS Developer's guide for documentation, and the RtpsRelay smoke test (`tests/DCPS/RtpsRelay/Smoke`) has a couple .ini files that make use of this configuration parameter if you need an example.

**Comment by mitza-oci** [comment]
I'm not sure what you mean by "specific discovery QoS" so if the comment that @simpsont-oci wrote is not sufficient to answer the question, please clarify this.

**Comment by MarcoRoccagliSigma** [comment]
> 

Hi,
i'm trying to set the LeaseDuration as for linked example.
Anyway, seems that i receive a "disconnection event" also if the participant is currently active. (I'm constantly writing data)
Do i need to configure the LeaseDuration in either Subscriber and Publisher?

**Comment by jrw972** [comment]
The LeaseDuration sets a default for how long other participants think that participant and its entities are alive.
Thus, if you want the Subscriber to know that the Publisher is gone, then the lease duration for the Publisher can be set to a lower value.  Note that the resend period needs to set appropriately for a safety factor.
