### ISSUE TITLE
Unable to receive data with 2 or more created Data Readers at the same time

### ISSUE THREAD

**Issue by DusanStanisic99** [objectcomputing/OpenDDS#3918]
Greetings,

I have a problem with receiving data using 2 DataReaders integrated into the Android service (with the latest implementation of OpenDDS 3.22) at the same time.  Communication has been confirmed individually and both DataReaders receive data as they should but when I create them in the same process I receive the following warning/info in the terminal:

"RtpsUdpReceiveStrategy::handle_input: reallocating primary receive buffer based on reference count"

Note: 
1. Both of the DataReaders have been created by two subscribers (to achieve concurrent data reception) and have their own implementation of DataReaderListener implementation.
2. For confirming communication I used two DataWriters running in separate processes.

Is it possible at all to receive/send data by two DataReaders/DataWriters from a single process or am I missing something in the implementation?

**Comment by mitza-oci** [comment]
I don't think the warning you've shown here is related to a problem of not receiving expected data samples.

It is possible to receive data in multiple readers in the same process.  They don't need to be created from different Subscribers, but they could be.  They don't need to belong to different DomainParticipants, but they could be.  They don't need to be associated with different DataReaderListener objects (or use any listener at all), but they could be.

**Comment by DusanStanisic99** [comment]
Thank you for the quick response!

I think I haven't provided you with all the information. I think the problem is not in receiving the data with 2 or more created Data Readers at the same time, but something else. I cannot detect what is it precisely. I will try to explain to you two different scenarios where I'm getting the same behavior:

Two DataReaders(DR1 and DR2 with two different topics) are created within two different Subscribers in the same Android application. They are communicating with two DataWriters (DW1 and DW2) deployed within two different applications.

Scenario 1)
Both DR1 and DR2 are initialized. DW1 and DW2 started sending the data at the same time. Whichever DR received the data first will work correctly and the second DR which should receive the data won't associate with the DW (on_subscription_matched callback not called at all in DRListener ) and every time a message is sent from DW, in the Android application I receive the error pasted below.

Scenario 2)
Both DR1 and DR2 are initialized. DW1 started sending the data and DR1 is getting them correctly (DW2 is not sending anything yet). Then, I cleaned up and confirmed the disassociation between DR1 and DW1 and I terminated the DW1 process. Afterward, DW2 started sending the data. At this moment, DR2 also won't associate with DW2 (on_subscription_matched callback not called at all in DRListener ) and every time a message is sent from DW, in the Android application I receive the error pasted below.
However, if I stop the execution of the DW2 and restart the DW1 - data is received normally, like the publisher of the DW1 has taken all the resources in the receive_buffer even when it has executed clean-up.
Identical behavior is confirmed when DW2 is sending the data first (DR2 will work fine, but when DW1 starts sending the data - DR1 will not get the information properly).

ERROR:

**6313  6339 D ACE     : (6313|6339) DataLink::data_received_i:  discarding sample from publication 01030800.279af7f2.0b8df1f1.00000002(8c490cc9) due to no listeners.
6313  6339 I ACE     : (6313|6339) INFO: RtpsUdpReceiveStrategy::handle_input: reallocating primary receive buffer based on reference count
6313  6339 D ACE     : (6313|6339) DataLink::data_received_i: from publication 01030800.279af7f2.0b8df1f1.00000002(8c490cc9) received sample: SAMPLE_DATA (0x00), Length: 8, Byte order: Little Endian, CDR Encapsulation, Sequence: 0x05, Timestamp: 1670505841.522623999, Publication: 01030800.279af7f2.0b8df1f1.00000002(8c490cc9) to readerId 00000000.00000000.00000000.00000000(ecbb4b55) (SET_INCLUDED).**

I realize that "discarding sample from publication due to no listeners" is called because DR and DW haven't been associated (not found each other), but I'm having trouble understanding the message that suggests that if the newly selected receive_buffer still has a reference count (data writer that has been discovered sending data possibly), it should be expanded to receive an additional element for the read(Another DataWriter sending data). 

**Source: OpenDDS/dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp (Picture provided)**
![image](https://user-images.githubusercontent.com/85589407/206525194-62a958d6-6366-44f9-bb45-5e132826b9de.png)
![image](https://user-images.githubusercontent.com/85589407/206525333-59200639-52ad-4825-8c36-15c9ce5139fe.png)

Best regards!
Dušan

**Comment by DusanStanisic99** [comment]
Greetings,

I just wanted to provide you with the latest conclusion I discovered.

 I have tested the communication with two separate applications acting as publishers (each of them has one DP with the same domain_id, one publisher with one DW) and Android applications previously mentioned acting as a subscriber with two approaches:
    1. One DP, One subscriber, 2 DR
    2. One DP, two subscribers, and each of them with one DR (For maintaining concurrency)
Both of them work just fine.

However, problems arose because in my use case I must have separate publishing applications with different domain_id. Therefore, I have to make two DP in my Android application. Any previously attempted communication has not been achieved with both of them, but only with the first one to establish a connection. The second one writes the error message mentioned above.

Here is the example of rtps.ini that I use and that has been tested with two applications with the same domain_id:

[common]
DCPSGlobalTransportConfig=transport_configuration
DCPSDebugLevel=10
DCPSTransportDebugLevel=5
DCPSLogLevel=debug
DCPSDefaultDiscovery=application_rtps_discovery
DCPSDefaultAddress=192.168.1.101

[config/transport_configuration]
transports=domain_id_42,domain_id_44

[transport/domain_id_42]
transport_type=rtps_udp
use_multicast=0

[transport/domain_id_44]
transport_type=rtps_udp
use_multicast=0

[domain/42]
DomainId=42
DiscoveryConfig=application_rtps_discovery_42

[domain/44]
DomainId=44
DiscoveryConfig=application_rtps_discovery_44

[rtps_discovery/application_rtps_discovery_42]
SedpMulticast=0
ResendPeriod=2
SpdpSendAddrs=192.168.1.109:17910, 192.168.1.109:17912
SpdpLocalAddress=192.168.1.101
SedpLocalAddress=192.168.1.101:4000

[rtps_discovery/application_rtps_discovery_44]
SedpMulticast=0
ResendPeriod=2
SpdpSendAddrs=192.168.1.109:18410
SpdpLocalAddress=192.168.1.101
SedpLocalAddress=192.168.1.101:6000

Best regards!
Dušan

**Comment by mitza-oci** [comment]
This part of the configuration file doesn't look right to me:

```
[config/transport_configuration]
transports=domain_id_42,domain_id_44

[transport/domain_id_42]
transport_type=rtps_udp
use_multicast=0

[transport/domain_id_44]
transport_type=rtps_udp
use_multicast=0
```

This is a single "transport config" that has two different "transport instances" in it.  Instead, try two different transport configs.  Each domain participant needs to be assigned its own config, as shown in the Developer's Guide section 7.4.2.3 "Using Multiple Configurations".

**Comment by DusanStanisic99** [comment]
> This part of the configuration file doesn't look right to me:
> 
> ```
> [config/transport_configuration]
> transports=domain_id_42,domain_id_44
> 
> [transport/domain_id_42]
> transport_type=rtps_udp
> use_multicast=0
> 
> [transport/domain_id_44]
> transport_type=rtps_udp
> use_multicast=0
> ```
> 
> This is a single "transport config" that has two different "transport instances" in it. Instead, try two different transport configs. Each domain participant needs to be assigned its own config, as shown in the Developer's Guide section 7.4.2.3 "Using Multiple Configurations".

Sorry for the delayed response.

The part of the configuration that you mentioned was indeed the problem and I followed instructions in Developer's Guide section 7.4.2.3 "Using Multiple Configurations" for a solution.
