### ISSUE TITLE
use rtps.ini runs on two pc

### ISSUE THREAD

**Issue by 286897655** [objectcomputing/OpenDDS#413]
hello,i am newer into dds.
i want to test pub-sub on two indepent windows with rtps.ini like below:

[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS

[transport/the_rtps_transport]
transport_type=rtps_udp

but the pub-sub can't find each other.of course,it works(find each other)intra-host,but i want to test inter-host,how can i set the rtps.ini?

thank you very much!

**Comment by mitza-oci** [comment]
For RTPS discovery, the two hosts will need to be able to exchange multicast UDP/IP traffic.  Make sure there isn't a firewall blocking this.  If that doesn't work, enable debug logging to see if there are any errors.  Debug logging will also show you which multicast groups and ports are in use.  See section 7.5 of the developer's guide for details on logging.

**Comment by 286897655** [comment]
@mitza-oci i'm sure i have shutdown the firewall and the two system can ping each other。if the rtps.ini setting is right？i will test the log right now。

**Comment by 286897655** [comment]
@mitza-oci 
![image](https://cloud.githubusercontent.com/assets/16201246/22133500/730e4bc0-defb-11e6-8823-97bbab41dd90.png) 

sorry,from the faq, i don't know where i had set local_address,so that i asked whether my rtps.ini setting is right.

Thanks very much for you help~~~~
