### ISSUE TITLE
Unit tests don't run when default discovery is set to RTPS

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#414]
We are using RTPS by default for discovery and we did this through the ace/config.h file as below. We now notice that the OpenDDS unit tests don't run anymore, for example the ReadCondition test fails as below. Would be much easier if a user can set RTPS as default discovery but also that the unit tests work at that moment.

`#define DDS_DEFAULT_DISCOVERY_METHOD Discovery::DEFAULT_RTPS`

```
./run_test.pl 
DCPSInfoRepo  -o repo.ior -NOBITS -DCPSPendingTimeout 3 
InfoRepo PID: 6363
(6363|139668423190336) ERROR: DCPSInfoRepo::init: Unable to set the ORB in InfoRepoDiscovery.
Unexpected initialization Error: Unable to set the ORB in InfoRepoDiscovery.                                                                                                                  
```

**Comment by mitza-oci** [comment]
My suggested approach would be to use a -Config flag so that the test scripts are aware of this.  In $DDS_ROOT/bin/PerlDDS/Run_Test.pm, setup_discovery() would check this flag and not start DCPSInfoRepo.  This is already part of what's done for Safety Profile which has no DCPSInfoRepo.

**Comment by jwillemsen** [comment]
At the moment we default to RTPS we get another challenge, running multiple OpenDDS tests run on multiple VMs on the same network, these systems could interfere with each other. With DDS4CCM we solved this in the past by giving each system an unique domain id and set this as environment variable which is used by the tests to make sure they don't get data from other systems.

**Comment by mitza-oci** [comment]
Set the environment variable OPENDDS_RTPS_DEFAULT_D0 to a different value on each host.  That is how we have builds running on about 20 hosts in the OCI build farm.

**Comment by jwillemsen** [comment]
@mitza-oci Thanks, added that to our buildtools scripts

**Comment by jwillemsen** [comment]
Also it would be helpful to have a MPC feature to disable the InfoRepo completely at compilation, reduces footprint and dependencies

**Comment by jwillemsen** [comment]
And hopefully at some point we can make the default to not use the inforepo but rtps as default
