### ISSUE TITLE
No MPC base project that only provide the C++ compiler flags and libraries

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#428]
There is no MPC base project that only provides the C++ compiler flags and libraries without pulling in the automatic IDL_Files rules. Inheriting from dcps gives also the IDL compiler flags which requires the user to specify empty IDL_Files sections in his MPC file at the moment he has a project that only compiles/links with OpenDDS C++ code and there are other IDL files in the directory that are not for OpenDDS

**Comment by mitza-oci** [comment]
@jwillemsen I think this was fixed in #1196.  Please confirm and close this issue if there are no further changes needed.

**Comment by jwillemsen** [comment]
Currently busy with other work, will close and recheck at a later momen
