### ISSUE TITLE
QOS_XML_Handler and ACE XML_Utils dependency

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/OpenDDS#429]
Pull request #422 is now reverted from master.  After the OpenDDS 3.10 release, we can drop support for TAO 2.0a which has no XML_Utils.  This issue will be our reminder to effectively re-merge #422 after the release.

**Comment by jwillemsen** [comment]
Also #426 can be merged at that moment

**Comment by jwillemsen** [comment]
@mitza-oci Could you revert this PR, when you have done that I can update my fork and get my other changes ready

**Comment by mitza-oci** [comment]
Not sure what you mean by "revert this PR", this is on issue #429.

**Comment by jwillemsen** [comment]
Sorry, I meant re-merge the change of 422

**Comment by mitza-oci** [comment]
I created a branch "qos_xml" which starts at the current master and adds the two cherry-picked commits from #422.  We can use this as the basis for continuing work on the XML QoS handler.  We're not ready for a breaking change in master until we have a chance to reconfigure builds which are using TAO 2.0a.

**Comment by jwillemsen** [comment]
Thanks, more cleanup is on my current fork

**Comment by jwillemsen** [comment]
@mitza-oci Any idea when we are ready to merge this breaking change?

**Comment by mitza-oci** [comment]
I moved half of our 2.0a builds last night, will try to get to the other half tonight.  Does the branch qos_xml contain all the changes you need?  If not you can make a pull request targeting that branch.

**Comment by jwillemsen** [comment]
I have some more changes, will make another PR when the first set of changes are on master
