### ISSUE TITLE
Using multi dimensional arrays leads to non-compiling generated code

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#460]
When using multi dimensional arrays we get non compiling generated code, see PR #459 for a test extension that triggers this issue.

**Comment by jwillemsen** [comment]
Extended the unit test as part of #459 with more typedefs

**Comment by mitza-oci** [comment]
I will take a look at it.

**Comment by mitza-oci** [comment]
I haven't looked at the details yet but I searched for other multi-dim arrays.  Do you have any ideas on why this doesn't fail?
tests/DCPS/Compiler/idl_test1_lib/FooDef.idl:35:  typedef string MultiDimArray[2][3][4][5];

**Comment by jwillemsen** [comment]
I think string are read differently, it fails with multi dim arrays of basic types

**Comment by jwillemsen** [comment]
Looks tao_idl generates some additional casts in the code, see the BoundTestC.cpp, for example

```
::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Bound::DoubleArray_forany &_tao_array)
{
  return
    strm.write_double_array (
        reinterpret_cast <const ACE_CDR::Double *> (_tao_array.in ()),
        10);
}
```

**Comment by mitza-oci** [comment]
OK, shouldn't be too hard to fix.  I'm not sure if it makes sense to treat it as a 1-dimensional array or to just generate the nested loops like string does.

**Comment by jwillemsen** [comment]
Doing it in one copy as 1-dimensional array would maybe be just a bit faster?

**Comment by mitza-oci** [comment]
See PR #461

**Comment by jwillemsen** [comment]
Maybe we should add also 3 dimensional arrays to make sure they also compile

**Comment by mitza-oci** [comment]
3-dimensional now tested as well.  An arbitrary number of dimensions will work.
