### ISSUE TITLE
auto_ptr warnings from QOS_XML_Handler

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/OpenDDS#462]
Now that QOS_XML_Handler is enabled, the amount of extra warnings generated from its use of auto_ptr causes Travis CI builds to exceed the available log output space and fail.

@jwillemsen is there anything simple we can do to fix this?  Looks like it is XSC-generated code?  In the short term we may need to turn off xerces on Travis CI.

**Comment by jwillemsen** [comment]
My PR #427 has the fix for setting c++11=1, when that is in it should trigger the setting to suppress the auto_ptr deprecated setting which should reduce the amount of warnings to a level it is acceptable for travis

**Comment by mitza-oci** [comment]
I didn't realize that those two things were connected.  Now I see that ACE takes c++11=1 as a sign that we don't want deprecation warnings (you'd think that would be the reverse).

So the short-term problem isn't an issue since I merged #427.  Longer term it would be good to remove auto_ptr from QOS_XML_Handler since it has been removed from all other OpenDDS core code.

**Comment by jwillemsen** [comment]
In older gcc versions the deprecated warnings where only given when c++11 is enabled. Without disabling these warnings a full atcd build has thousands of warnings, just impossible to update all to unique_ptr or some macro construct

**Comment by mitza-oci** [comment]
It would be nice to use dds/DCPS/scoped_ptr.h but I'm not sure how best to integrate it due to XSC

**Comment by ocielliottc** [comment]
Resolved with https://github.com/objectcomputing/OpenDDS/pull/1181
