### ISSUE TITLE
configure script problem locating ACE

### ISSUE THREAD

**Issue by matthewpang** [objectcomputing/OpenDDS#478]
configure script gets confused if you have $ace_src defined (from previously run setenv.sh or because you've added stuff to your ~/.*rc files  ) and then download a fresh copy of OpenDDS and try to ./configure it. 

Possibly add a mention in INSTALL somewhere of running  ./configure --ace=download if ./configure complains "Can't find ACE at..." or change the error message it throws to say as much.

**Comment by mitza-oci** [comment]
Which version of OpenDDS?  Which platform and compiler?

The error message says "Can't find ACE", and you can learn more about how it finds ACE by reading the "./configure --help" usage documentation.  Based on your question, I think you have figured it out already.

If you'd like to make a specific suggestion on improving the error message or usage, please use a pull request.

**Comment by matthewpang** [comment]
@mitza-oci 3.10, Linux and GCC 6.3 . I'll submit a pull request.
