### ISSUE TITLE
No support for top-level union types

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#486]
OpenDDS lacks the support for unions as top-level union types. Where the DCPS specification is silent about union (not mentioning it at all) the DDS X-Types specification does mention unions as types for top-level, the discriminator may even be key. Below a small IDL example that is rejected by opendds_idl

```
module DDS_Native
{
  module Uni
  {
#pragma DCPS_DATA_TYPE "DDS_Native::Uni::TopUnionMessage"
    union TopUnionMessage switch (long) {
      case 4:
        short x;
      case 5:
      case 6:
        long y;
    };
  }; // module Uni
}; // module DDS_Native
```

**Comment by iguessthislldo** [comment]
Closing because #1067 was merged.
