### ISSUE TITLE
question about tcp transport and rtps discovery

### ISSUE THREAD

**Issue by 286897655** [objectcomputing/OpenDDS#505]
i'm puzzled about use rtps to discovery and tcp transport to delivery data,the first data will delay about 10 secondes,
help me~~~thank you.

**Comment by jwillemsen** [comment]
It could be a DNS resolve delay, try to run your application using `-DCPSTransportDebugLevel 6 -DCPSDebugLevel 10` to see what is happening exactly

**Comment by 286897655** [comment]
@jwillemsen thank you for you help。
my config file looks like this：
[common]
DCPSGlobalTransportConfig=tcp_trans
DCPSDefaultDiscovery=uni_rtps

[config/tcp_trans]
transports=tcptransport

[transport/tcptransport]
transport_type=tcp
local_address=10.0.8.237:

[rtps_discovery/uni_rtps]
SpdpLocalAddress=10.0.8.237
SedpMulticast=0
SedpLocalAddress=10.0.8.237:

the publisher and subscriber log file has attached,i couldn't find any help from these logs.
[log_pub_sub.zip](https://github.com/objectcomputing/OpenDDS/files/909177/log_pub_sub.zip)

**Comment by jwillemsen** [comment]
Please add also `-ORBVerboseLogging 1` so that we get timestamps in the log

**Comment by 286897655** [comment]
@jwillemsen 
thanks.

[log_pub_sub.zip](https://github.com/objectcomputing/OpenDDS/files/909223/log_pub_sub.zip)

**Comment by mitza-oci** [comment]
The second process starts at 14:51:15.
Also at 14:51:15, the two processes exchange SPDP messages (search for Spdp::data_received).
At 14:51:25 the reader and writer are associated, so I agree that there's a 10 second delay here.

Running a similarly configured test that comes with OpenDDS (tests/DCPS/Messenger with rtps_disc_tcp parameter), I don't see a similar delay.  Please take a look at that test and see if your program has some differences in terms of QoS or other API usage.

**Comment by 286897655** [comment]
@mitza-oci I will test it right now.thank you..
