### ISSUE TITLE
Issues in dp::delete_contained_entities and related operations

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#506]
The domain participant `delete_contained_entities` is going through the reactor to delete all contained entities and at the end it returns `shutdown_result_`. When I now check the DomainParticipantImpl::handle_exception implementation I notice that in several error conditions a return is done which returns the DDS retcode to the reactor instead of `shutdown_result_` is set to the error value. As far as I can tell this could lead to a problem that an error code is not returned to the caller which doesn't see the error. For debugging purposes it would also help if some logging is added in the calls to all delete_contained_entities to log what is deleted (especially when it fails)

**Comment by jwillemsen** [comment]
In `SubscriberImpl::delete_contained_entities` not all members maps are cleared, something to check in this class but also all others that implement `delete_contained_entities`

**Comment by jwillemsen** [comment]
This method and others use the `set_deleted` flag, but that flag is only reset at the moment there is no failure, shouldn't a guard be used so that the flag is also reset at the moment there is a failure?

**Comment by mitza-oci** [comment]
@jwillemsen since #692 was merged, is this issue resolved?

**Comment by jwillemsen** [comment]
Very likely, will close
