### ISSUE TITLE
Add user stories to the opendds.org website

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#512]
In order to let people know who is using opendds we should add an user stories page to the opendds.org website and ask users to contribute their story.

**Comment by mitza-oci** [comment]
Yes, we're open to adding any relevant content to [opendds.org](https://opendds.org).  One reason we moved the site to GitHub pages is that anybody can propose updates via Pull Requests.

If there's anyone following this issue that wants to contribute, please respond here.  If we get one or two of them started (and determine how we want to integrate into the site menus, etc.) we can also post on the mailing lists and/or include it with the release announcements.

**Comment by jwillemsen** [comment]
See #2341
