### ISSUE TITLE
Usage of ACE_NEW_MALLOC_NORETURN

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#582]
This operation uses ACE_NEW_MALLOC_NORETURN which means when the malloc fails we don't return but just continue which doesn't seem correct

**Comment by ocielliottc** [comment]
There are no instances of ACE_NEW_MALLOC_NORETURN in the OpenDDS source anymore.

**Comment by mitza-oci** [comment]
Looks like it was fixed in #739
