### ISSUE TITLE
Several tests still use throw(CORBA::SystemException)

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#585]

**Comment by jwillemsen** [comment]
Just assign to me, will create a new PR but one of the tests I am extending has these so I will do this after that test is ready

**Comment by jwillemsen** [comment]
See #587

**Comment by mitza-oci** [comment]
Looks like the only one left is a single class in FooTest3_0 (based on a simple grep, I could have missed some).

**Comment by jwillemsen** [comment]
Yes, FooTest3_0 is heavily changed for the querycondition/dispose testing, that cleanup is on another PR

**Comment by jwillemsen** [comment]
Final fixes are part of PR #900
