### ISSUE TITLE
How to implement TCP/IP

### ISSUE THREAD

**Issue by MengZn** [objectcomputing/OpenDDS#598]
Excuse me
How to implement TCP/IP in OpenDDS/DevGuideExamples/DCPS/Messenger/Publisher and Subscriber at different WAN .
Hope you help me.

**Comment by mitza-oci** [comment]
Please see the detailed description of a TCP-based scenario at http://opendds.org/faq#general-connections.  I hope that will give you a good start on a deploying OpenDDS on your network.  I have to admit I'm not sure what you mean by "different WAN".  If the FAQ is not sufficient to answer your question please provide more details of what you want to do.
