### ISSUE TITLE
OpenDDS (3.11) Bench - latency benchmark fails due to BadSync on localhost

### ISSUE THREAD

**Issue by PeterKleinTC** [objectcomputing/OpenDDS#599]
Creating a ticket as per [Johnny Willemsen's request](https://sourceforge.net/p/opendds/mailman/message/35871123/).

-------
Hi,

I was trying to run some OpenDDS benchmarks with the built-in Bench tool, but ran into the problem described below.

I’d appreciate if you could take a look and let me know if the issue is reproducible on your side.

Thank you for your help,
Peter Klein

This is OpenDDS version 3.11, released Fri May 12 20:38:26 UTC 2017

    OpenDDS VERSION: 3.11
    TAO VERSION: ACE+TAO-2.2a_with_latest_patches_NO_makefiles

    HOST MACHINE and OPERATING SYSTEM: HP Z220, Ubuntu 12.04

    TARGET MACHINE and OPERATING SYSTEM, if different from HOST: same
    COMPILER NAME AND VERSION (AND PATCHLEVEL): gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

    CONTENTS OF $ACE_ROOT/ace/config.h [if you use a link to a platform-
    specific file, simply state which one]: #include "ace/config-linux.h"

    CONTENTS OF $ACE_ROOT/include/makeinclude/platform_macros.GNU (unless
    this isn't used in this case, e.g., with Microsoft Visual C++): optimize = 0
    include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU

    CONTENTS OF $ACE_ROOT/bin/MakeProjectCreator/config/default.features
    (used by MPC when you generate your own makefiles): 

    LEVEL OF URGENCY (LOW, MEDIUM, or HIGH): MEDIUM

    AREA/CLASS/EXAMPLE AFFECTED: OpenDDS-Bench

    DOES THE PROBLEM AFFECT:
        EXECUTION: DDS Bench

    SYNOPSIS:
When running the OpenDDS Benchmark test it seems like the message count seems to be off by one (BadSync?), the test fails and no latency stats are available.
testprocess() - Test exception caught during processing: BadSync.
This is also reproducible on a Windows 10 host.

    DESCRIPTION:

    REPEAT BY:
Startup order:
1)	terminal1
2)	terminal2
3)	terminal3

terminal1:
$BENCH_ROOT/bin/run_test -S -h 127.0.0.1:2809

terminal2:
$BENCH_ROOT/bin/run_test -P -t 120 -h 127.0.0.1:2809 -i $BENCH_ROOT/etc/transport-rtps.ini -s $BENCH_ROOT/tests/latency/p2.ini

terminal3:
$BENCH_ROOT/bin/run_test -P -v -t 120 -h 127.0.0.1:2809 -i $BENCH_ROOT/etc/transport-rtps.ini -s $BENCH_ROOT/tests/latency/p1-2500.ini

The same happens when using transport-tcp.ini and/or different p1-xxx.ini files; and also happens on a Windows host (Windows 10).

Full output:
terminal1:
TEST PROCESS
/local/mnt/workspace/OpenDDS-3.11/bin/DCPSInfoRepo  -ORBListenEndpoints iiop://127.0.0.1:2809  -o /local/mnt/workspace/OpenDDS_Benchmark/repohost/repo.ior 

No Duration specified.  Hit Enter to end the processes and finish the test.

// looks fine

terminal2:
TEST PROCESS
/local/mnt/workspace/OpenDDS-3.11/performance-tests/Bench/bin/testprocess  -DCPSConfigFile /local/mnt/workspace/OpenDDS-3.11/performance-tests/Bench/etc/transport-rtps.ini -DCPSInfoRepo corbaloc:iiop:127.0.0.1:2809/DCPSInfoRepo -d 120  -f /local/mnt/workspace/OpenDDS-3.11/performance-tests/Bench/tests/latency/p2.ini 
(7772|140411399927616) loadPublication() - value for MessageRateType is unspecified, using FIXED value.
(7772|140411399927616) loadPublication() - value for MessageSizeType is unspecified, using FIXED value.
(7772|140411399927616) loadPublication() - value for InstanceType is unspecified, using FIXED value.
(7772|140411399927616) testprocess() - starting.
(7772|140411399927616) Process::run() - unblocked main thread: wait: Timer expired.
(7772|140411399927616) Process::run() - publication p3 stopping with results:
   test elapsed time: 0,
   messages     sent: 11823,
   messages timedout: 0.
(7772|140411232036608) DataReaderListener::on_data_available() - received a non-data sample.  After messages: total: 11824, valid: 11823.
  Writer[ 0x5869b3b1]: 11823 samples, 29557500 bytes.

SUBSCRIPTION s1 SUMMARY DATA
Total Messages Received: 11824
Valid Messages Received: 11823

--- last hop statistical summary for subscription s1 ---
  Writer[ 01030000.86398fe5.00000003.00000102(5869b3b1)]
     samples: 0
        mean: 0
     minimum: 0
     maximum: 0
    variance: 0
--- full path statistical summary for subscription s1 ---
// should those be all zeros? 

SUBSCRIPTION s1 SUMMARY DATA
Total Messages Received: 11824
Valid Messages Received: 11823

--- last hop statistical summary for subscription s1 ---
  Writer[ 01030000.86398fe5.00000003.00000102(5869b3b1)]
     samples: 0
       mean: 0
     minimum: 0
     maximum: 0
    variance: 0
--- full path statistical summary for subscription s1 ---
// should those be all zeros? 

(7772|140411399927616) testprocess() - terminating normally.
test PASSED. // really?

terminal3:
TEST PROCESS
/local/mnt/workspace/OpenDDS-3.11/performance-tests/Bench/bin/testprocess  -v -DCPSConfigFile /local/mnt/workspace/OpenDDS-3.11/performance-tests/Bench/etc/transport-rtps.ini -DCPSInfoRepo corbaloc:iiop:127.0.0.1:2809/DCPSInfoRepo -d 120  -f /local/mnt/workspace/OpenDDS-3.11/performance-tests/Bench/tests/latency/p1-2500.ini 
(7794|140100725364544) Options::Options() - Setting VERBOSE mode.
(7794|140100725364544) Options::Options() - processing argument: -d.
(7794|140100725364544) Options::Options() - processing argument: -f.
(7794|140100725364544) Options::configureScenarios() - configuring using file: /local/mnt/workspace/OpenDDS-3.11/performance-tests/Bench/tests/latency/p1-2500.ini.
(7794|140100725364544) Options::configureEntities() - configuring participant process1.
(7794|140100725364544) Options::loadParticipant() -   [participant/process1] DomainId == 2112.
(7794|140100725364544) Options::configureEntities() - configuring topic A.
(7794|140100725364544) Options::loadTopic() -   [topic/A] ReliabilityKind == RELIABLE.
(7794|140100725364544) Options::loadTopic() -   [topic/A] Participant == process1.
(7794|140100725364544) Options::configureEntities() - configuring publication p1.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] Partition == 1.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] ReliabilityKind == RELIABLE.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] ReliabilityMaxBlocking == 0.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] HistoryKind == LAST.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] HistoryDepth == 10.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] ResourceMaxSamplesPerInstance == 10.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] TransportPriority == 0.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] Topic == A.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] TransportConfig == 1.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] MessageRate == 100.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] MessageRateType == FIXED.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] MessageSizeType == FIXED.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] MessageSize == 2500.
(7794|140100725364544) loadPublication() - value for InstanceType is unspecified, using FIXED value.
(7794|140100725364544) Options::loadPublication() -   [publication/p1] Associations == 1.
(7794|140100725364544) Options::configureEntities() - configuring subscription s5.
(7794|140100725364544) Options::loadSubscription() -   [subscription/s5] Partition == 2.
(7794|140100725364544) Options::loadSubscription() -   [subscription/s5] Topic == A.
(7794|140100725364544) Options::loadPublication() -   [subscription/s5] TransportConfig == 2.
(7794|140100725364544) Options::loadSubscription() -   [subscription/s5] DataCollectionFile == latency-2500.data.
(7794|140100725364544) Options::loadSubscription() -   [subscription/s5] DataCollectionBound == 5000.
(7794|140100725364544) Options::loadSubscription() -   [subscription/s5] DataCollectionRetention == NEWEST.
(7794|140100725364544) Process::Process() - created participant process1 in domain 2112.
(7794|140100725364544) Process::Process() - created type Test::Data support in participant process1.
(7794|140100725364544) Process::Process() - created topic A in participant process1.
(7794|140100725364544) Process::Process() - created subscription s5 in participant process1.
(7794|140100725364544) Subscription::enable() - subscription s5: configured to capture 5000 latency measurements of type 1 per writer to file latency-2500.data.
(7794|140100725364544) Subscription::enable() - publication s5: obtained rtps_udp transport with config 2.
(7794|140100725364544) Subscription::enable() - subscription s5: attached transport with config 2 to subscriber.
(7794|140100725364544) Subscription::enable() - subscription s5: created reader.
(7794|140100725364544) Subscription::enable() - subscription s5: created reader listener.
(7794|140100725364544) Process::Process() - extracted StatusCondition for subscription s5 in participant process1.
(7794|140100725364544) Process::Process() - created publication p1 in participant process1.
(7794|140100725364544) Publication::enable() - publication p1: obtained rtps_udp transport with config 1.
(7794|140100725364544) Publication::enable() - publication p1: attached transport with config 1 to publisher.
(7794|140100725364544) Publication::enable() - publication p1: created writer.
(7794|140100725364544) Publication::enable() - publication p1: narrowed writer for Test::Data type.
(7794|140100725364544) Process::Process() - extracted StatusCondition for publication p1 in participant process1.
(7794|140100725364544) testprocess() - starting.
(7794|140100725364544) Process::run() - starting to publish samples.
(7794|140100725364544) Process::run() - blocking main thread for 120 seconds, from 1495757736 until 1495757856.
(7794|140100243003136) Publication::svc() - publication p1: processing starts on thread.
(7794|140100725364544) Process::run() - unblocked main thread: wait: Timer expired.
(7794|140100725364544) Process::run() - continuing main thread at 1495757856, starting to terminate.
(7794|140100243003136) Publication::svc() - publication p1: honoring termination request, stopping thread.
(7794|140100725364544) Process::run() - publication p1 stopping with results:
   test elapsed time: 120,
   messages     sent: 11823,
   messages timedout: 0.
(7794|140100289689344) DataReaderListener::on_data_available() - received a non-data sample.  After messages: total: 11824, valid: 11823.
  Writer[ 0x5869b3b1]: 11823 samples, 29557500 bytes.
(7794|140100725364544) Process::run() - waiting for 1 remote publications to finish.
(7794|140100725364544) ERROR: Process::run() - failed to synchronize subscription conditions.
(7794|140100725364544) testprocess() - Test exception caught during processing: BadSync.
Terminated test process.
ERROR: Test returned 1
test FAILED.

cat latency-2500.data
empty

**Comment by mitza-oci** [comment]
We are currently working on it.
