### ISSUE TITLE
BaseMessageUtils.h::marshal_key_hash

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#606]
marshal_key_hash looks only to be used in some unit tests to print a hex dump but not anywhere in the test code at all. Could we remove this method from the RTPS core? Any need to keep the test code that uses this function?

**Comment by mitza-oci** [comment]
It's part of the RTPS spec but key hashing is a very strange part of the spec (one of many I suppose).  Since it's an inline function we don't have any overhead for it in the code.  I'd rather keep it so we have it if we start adding key hashes.
