### ISSUE TITLE
guard.release()/guard.acquire()

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#615]
In the transport I found several times guard.release()/guard.acquire() being used, should be a reverse guard in those places

**Comment by mitza-oci** [comment]
`RtpsUdpDataLink::process_acked_by_all_i` seems to be one, but that will be gone once #1138 is merged.  Are there others?

**Comment by jwillemsen** [comment]
No idea, you have now checked and only one left, so closing
