### ISSUE TITLE
/docs/html/guidelines/guidelines.html outdated

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#618]
/docs/html/guidelines/guidelines.html needs to be updated with git, github issues, no changelog, etc

**Comment by jwillemsen** [comment]
File is generated but can't find the source of the file

**Comment by mitza-oci** [comment]
They use TiddlyWiki which includes within the document a JavaScript program for editing the document (so they are also the sources).
https://en.wikipedia.org/wiki/TiddlyWiki

**Comment by iguessthislldo** [comment]
[docs/guidelines.md](https://github.com/objectcomputing/OpenDDS/blob/master/docs/guidelines.md) is now in master if you want to take a look at it @jwillemsen.
