### ISSUE TITLE
InfoRepoDiscovery doesn't destroy its POAs and ORB

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#645]
As far as I can determine the InfoRepoDiscovery doesn't explicitly destroy its POAs and the ORB it could have been created. Not doing so could lead to a lot of reports by valgrind

**Comment by mitza-oci** [comment]
Was this already fixed with PR #646?

**Comment by jwillemsen** [comment]
PR #646 fixes the destroy of the ORB but I haven't checked the POA part

**Comment by mitza-oci** [comment]
All POAs are destroyed as part of ORB destroy.  They were already destroyed before #646 because ORB shutdown implies POA destroy.
