### ISSUE TITLE
OpenDDS is not interoperable with OpenSplice 6.7

### ISSUE THREAD

**Issue by matthewpang** [objectcomputing/OpenDDS#665]
OpenDDS does not interoperate with Opensplice 6.7
Companion issue on OpenSplice GitHub : 
https://github.com/PrismTech/opensplice/issues/36

DDS Vendor Interoperability Chart
https://github.com/matthewpang/dds-interop

**Comment by mitza-oci** [comment]
We use RTPS protocol version 2.2.  Nothing significant has changed in the protocol since 2.1, but it's the current version of the spec (which also says that all 2.x are interoperable).  When I force the OpenDDS side's protocol version back to 2.1 via a source code change, I get a much different response from OpenSplice -- doesn't quite work but a lot more messages are exchanged.  I haven't had time to investigate further as to what else needs to happen to make it work.

Is there a similar/symmetrical issue in the OpenSplice GitHub project we can link to?

**Comment by matthewpang** [comment]
@mitza-oci added .

**Comment by mfeliu** [comment]
@mitza-oci do you have a commit with the change you are proposing so that I can try it? Thanks.

**Comment by mitza-oci** [comment]
In dds/DCPS/RTPS/BaseMessageTypes.h, change the line
`const ProtocolVersion_t PROTOCOLVERSION = PROTOCOLVERSION_2_2;`

**Comment by RomainNaour** [comment]
Hi Adam,

Thanks for testing, I'm using this exactly this opensplice version.
Which version of opensplice have you used last month when you have successfully tested the interoperability ?

**Comment by mitza-oci** [comment]
I haven't seen a successful test with OpenSplice (VendorId 1.2) version 6.7.  This issue is open until that is resolved.  Note that there is a link to an open issue in splice's repository as well.

**Comment by RomainNaour** [comment]
Hi Adam,

I'm able to use two iShape demo using a different DDS implementation.
For that, I had to change the RTPS version used by OpenSplice:

diff --git a/src/services/ddsi2/code/q_protocol.h b/src/services/ddsi2/code/q_protocol.h
index b9b3f39..4b8583b 100644
--- a/src/services/ddsi2/code/q_protocol.h
+++ b/src/services/ddsi2/code/q_protocol.h
@@ -145,7 +145,7 @@ struct cdrstring {
 
 /* Only one specific version is grokked */
 #define RTPS_MAJOR 2
-#define RTPS_MINOR 1
+#define RTPS_MINOR 2

So, OpenSplice seems to drop RTPS frames using a higher version even if it's a minor version change.

Best regards,
Romain

**Comment by mitza-oci** [comment]
Thanks for reporting your findings.  I tried some tests before with the opposite change in OpenDDS (set it to RTPS 2.1) but wasn't able to spend enough time testing it.  Please see https://github.com/ADLINK-IST/opensplice/issues/36

**Comment by mitza-oci** [comment]
I confirmed that it worked when changing the OpenDDS protocol version back to 2.1.
