### ISSUE TITLE
DomainParticipantImpl::delete_topic_i

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#676]
The operation `DomainParticipantImpl::delete_topic_i` looks strange related to refcounting. This is called from `DomainParticipantImpl::delete_topic` which an argument of false, at that moment the refcount isn't deleted. Could this be a cause for the memory leaks we see?

**Comment by mitza-oci** [comment]
I don't see Topic objects leaked in asan or valgrind reports.  Let's close this for now unless there are more details available.  Also we can revisit once #753 is integrated.
