### ISSUE TITLE
Configure script should update config.h/platform_macros.GNU when they exist

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#682]
At the moment the configure script finds an existing ACE/TAO tree it only recreates default.features. It should also recreate config.h/platform_macros.GNU and safe the old version as backup. I did wanted to build with safety-profile and this requires modified files which where not updated by configure because I have an existing tree

**Comment by mitza-oci** [comment]
It may be a bug that default.features is being overwritten.  The configure script is not designed to re-configure.  You can start from a clean tree using `git clean` (or for an end-user, just removing the working directory and re-expanding the archive).

There are essentially two modes supported by configure:
- configure and build ACE+TAO along with OpenDDS
- use an existing build of ACE+TAO and just configure/build OpenDDS

If the latter mode is being used, we may not overwrite ACE's configuration.  OpenDDS will append to default.features (should be features that ACE+TAO doesn't user).

**Comment by jwillemsen** [comment]
Haven't checked, but could be it will append to default.features, but by appending there and not to platform_macros.GNU I think we get inconsistent configurations, especially when special flags are passed to configure

**Comment by mitza-oci** [comment]
user_macros.GNU was created for that reason.  It is used by configure.

**Comment by jwillemsen** [comment]
When using special configure flags and an existing build we could check if the necessary flags are available in the config.h/platform_macros.GNU/default.features, not that the user thinks he has enabled some special configuration but that it doesn't work due to an existing ACE tree
