### ISSUE TITLE
Make metaclass_generator configurable

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#686]
For using the IDL to C++11 language mapping for types we also need to generate a different meta class implementation, need to rework OpenDDS IDL to easily override some behavior.

**Comment by jwillemsen** [comment]
@mitza-oci is this part of #954 ?

**Comment by mitza-oci** [comment]
> @mitza-oci is this part of #954 ?

Yes, when `opendds_idl` is run in C++11-mode, all the generated code (for type support, marshaling, content-filter, etc.) is aware of the C++11 mapping rules.
