### ISSUE TITLE
Content-Subscription support with C++11 language mapping

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#687]
The generated getRawField::getRawField assumes we can take the address of a member to return as void*, with IDL to C++11 a struct is mapped to a class with accessors, you can't get the member itself, need to recheck this

**Comment by jwillemsen** [comment]
Maybe make use of `getValue` and use that as a way to get the rhs value

**Comment by jwillemsen** [comment]
Issue when trying to add #359

**Comment by jwillemsen** [comment]
@mitza-oci is this part of #954 ?

**Comment by mitza-oci** [comment]
There are still cases for MultiTopic that need to be fixed for C++11 (using std::string instead of TAO::String_Manager).

**Comment by mitza-oci** [comment]
Fixed in #1379
