### ISSUE TITLE
Adding Docker Support

### ISSUE THREAD

**Issue by raveious** [objectcomputing/OpenDDS#703]
How about creating an official Docker image to easily control the build environment and test out OpenDDS in multiple containers. It also would allow people to use it as a starting point to having OpenDDS in their own applications with all of the tools built in.

Docker Cloud and Docker Hub can be configured to automatically build the image in a variety of different ways, so keeping it up to date can be automatic.

**Comment by mitza-oci** [comment]
Sounds like a good idea.  What specific changes are required to make this happen?

**Comment by raveious** [comment]
Right off the top of my head, the inclusion of a [Dockerfile](https://docs.docker.com/get-started/part2/#define-a-container-with-a-dockerfile) to describe how to create a Docker Container with all of the tools needed to build OpenDDS, and maybe even run the examples. All of the requirements would be defined in the Dockerfile, and that content is already kind of captured in the configure script and the existing documentation.

Another very helpful thing to include, but is by no means necessary, would be a [Docker Compose](https://docs.docker.com/compose/gettingstarted/) file to make launching a container even easier.

**Comment by raveious** [comment]
I think the "ideal" scenario here might be to setup the include path to include OpenDDS out of the box, just like the any of the other standard libraries. We could create a variety of different Dockerfiles with different OSs (Ubuntu, CentOS, etc) for the base image, with the OpenDDS compiled and installed into their respective images.

The docker images can be build and distributed on [Docker Hub](https://hub.docker.com/). Make an account (and probably an organization) to house the docker image repository. Using the auto build feature, you can make different image tags for different OpenDDS releases for different OSs. That way, whenever there is a new release, [Docker Hub](https://hub.docker.com/) will automatically build the different images for that release. This also means, that if a developer wanted to extend the functionality of the image for their own project, they can create their own dockerfile for their project, and define one of the OpenDDS images as the base image.

For working with the Docker Container, a developer would want to use the Bind Volume feature to "mount" their source into the container and have it compiled with OpenDDS.

The only thing I haven't figured out is how allow the developer to configure to DCPSInfoRepo broker they way they want...

**Comment by jrw972** [comment]
We have had similar thoughts on creating OpenDDS development images and are starting down the path you outlined.  Are you willing to be our alpha tester? ;)

**Comment by raveious** [comment]
I don't see why not. It might me easier to just make a new Github repo under the same objectcomputing organization to collect dockerfiles from multiple projects. It's another way I've seen organizations group their dockerfiles together into one place without modifying the other repos.

**Comment by jrw972** [comment]
Check out https://github.com/objectcomputing/OpenDDS#quick-start-with-docker

**Comment by raveious** [comment]
So everything seems pretty much in good, here are a hand full of changes to follow a few of the Docker best practices. Functionally it is the same thing, just a little bit cleaner and leverages the docker builder caching more.

```diff
index 4a4d7a2dd..156765121 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,15 +1,26 @@
 FROM ubuntu

-RUN apt-get update && apt-get install -y perl-base perl-modules g++ make libwww-perl curl wget
+RUN apt-get update && apt-get install -y \
+    perl-base \
+    perl-modules \
+    g++ \
+    make \
+    libwww-perl \
+    curl \
+    wget
+
 ADD . /opt/OpenDDS
+
 WORKDIR /opt/OpenDDS
-RUN ./configure --prefix=/usr/local --no-tests
-RUN make
-RUN make install
-RUN cp -a /opt/OpenDDS/ACE_wrappers/MPC /usr/local/share/ace/MPC
-ENV ACE_ROOT /usr/local/share/ace
-ENV TAO_ROOT /usr/local/share/tao
-ENV DDS_ROOT /usr/local/share/dds
-ENV PATH ".:/usr/local/share/ace/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+
+RUN ./configure --prefix=/usr/local --no-tests && \
+    make && \
+    make install && \
+    cp -a /opt/OpenDDS/ACE_wrappers/MPC /usr/local/share/ace/MPC
+
+ENV ACE_ROOT=/usr/local/share/ace \
+    TAO_ROOT=/usr/local/share/tao \
+    DDS_ROOT=/usr/local/share/dds \
+    PATH=".:/usr/local/share/ace/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

 WORKDIR /opt/workspace
```

A few things to further note:
- Maybe pinning the versions of the tools to ones that are known compatible in order to build OpenDDS, like GCC, Perl, etc.?
- Any particular reason why the user and group are being set in README instructions? Everything is ran as root by default, but that is only within the container.
- The Ubuntu image has the `ENTRYPOINT` option set. Meaning that if you just run `docker run opencomputing/opendds` you will automatically be dropped into a bash shell. So by adding `/bin/bash` to the end of your `docker run command`, you're running bash within bash (which is kind of redundant). I believe most OS images have it set to a shell by default, but it's going to be the default shell that is normally set for that OS.

Another question I have is will there be a plan to support version pinning of the Docker Image? Meaning the I can use `docker run opencomputing/opendds:3.11` and I will always get the 3.11 release of OpenDDS. So for example, when 3.12 is released. `opencomputing/opendds:3.12 will automatically get the 3.12 version of OpenDDS.

**Comment by jrw972** [comment]
Thanks for the suggestions on the Dockerfile.  They will be incorporated.

We do not have plans to pin the base image or the versions of the dependencies.  We would prefer to strive for compatibility with the latest Ubuntu LTS packages as they represent a reasonable development environment.

The user was set on entry to the container so the generated files would be owned by the user instead of root.  I will remove this from the instructions.

I `docker inspect`ed the ubuntu image and it does not have an entrypoint set.  However, it does have command which enters a shell so the /bin/bash is superfluous and will be removed.

Moving forward, we have plans to version the Docker image for each release.

**Comment by mitza-oci** [comment]
Now that 3.12 is out (will be announced on the shortly on the mailing lists), see https://hub.docker.com/r/objectcomputing/opendds/tags

Is there anything else we should do before closing this issue?

**Comment by raveious** [comment]
I guess the only thing that is really needed is documentation of the difference between the different tags on Docker Hub? Other than that I don't see why this couldn't be closed.

**Comment by jrw972** [comment]
Add documentation to the README.
