### ISSUE TITLE
Images missing at http://opendds.org/perf/lab170830/latency_results.html

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#734]
Looks some images are missing or maybe wrong links?

**Comment by mitza-oci** [comment]
Thanks for reporting it. Huang-Ming is out of the office today so I'll take
a look.

**Comment by mitza-oci** [comment]
Should be fixed now (2939f9ccb1308e3ac04c9ff732d77566f6df3f4f)
