### ISSUE TITLE
New compile warnings

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#744]
New compile warnings, see http://buildlogs.remedy.nl/fc_opendds_versioned/index.html

<pre>
[Details] /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/dds/DCPS/ReceivedDataElementList.cpp: In static member function ‘static void* DDS_3_12_0::OpenDDS::DCPS::ReceivedDataElement::operator new(size_t, ACE_6_4_5::ACE_New_Allocator&)’:
[Details] /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/dds/DCPS/ReceivedDataElementList.cpp:36:63: warning: unused parameter ‘size’ [-Wunused-parameter]
[Details] /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/dds/DCPS/DataReaderImpl_T.h: In instantiation of ‘static void* DDS_3_12_0::OpenDDS::DCPS::DataReaderImpl_T<MessageType>::MessageTypeWithAllocator::operator new(size_t, ACE_6_4_5::ACE_New_Allocator&) [with MessageType = DDS_3_12_0::DDS::PublicationBuiltinTopicData; size_t = long unsigned int]’:
[Details] /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/dds/DCPS/DataReaderImpl_T.h:894:40: required from ‘DDS_3_12_0::DDS::InstanceHandle_t DDS_3_12_0::OpenDDS::DCPS::DataReaderImpl_T<MessageType>::store_synthetic_data(const MessageType&, DDS_3_12_0::DDS::ViewStateKind) [with MessageType = DDS_3_12_0::DDS::PublicationBuiltinTopicData; DDS_3_12_0::DDS::InstanceHandle_t = int; DDS_3_12_0::DDS::ViewStateKind = unsigned int]’
[Details] /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/dds/DCPS/StaticDiscovery.cpp:121:60: required from here
[Details] /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/dds/DCPS/DataReaderImpl_T.h:2364:84: warning: unused parameter ‘size’ [-Wunused-parameter]
</pre>

**Comment by mitza-oci** [comment]
Looks like this started with PR #739

**Comment by mitza-oci** [comment]
Can this issue be closed now that the PR is merged?
