### ISSUE TITLE
Communicate two hosts through public network (WAN) issue

### ISSUE THREAD

**Issue by redrabit** [objectcomputing/OpenDDS#760]
Rcently, I succeeded in communicating two hosts in same subnet by OpenDDS. However, I want to communicate other two hosts through public network or WAN. It doesn't work. How can I solve this problem??

Here is my communication enviroment:

I have two hosts. HostA and Host B is my Destktop(Ubuntu 16.04). Also, two hosts has public IP address and disable firewall. I already checked whether the specific port number was available by telnet command. like this:

`$ telnet <HostA IP's> 12345`
and it is fine connetion.

I used OpenDDS-3.11 and $OpenDDS_HOME/tests/DCPS/Messenger 's example.

In HostA, enable

`$ DCPSInfoRepo -ORBListenEndpoints iiop://:12345`
Subscriber operate like this:

`$ ./subscriber -DCPSInfoRepo <HostA's IP>:12345 -DCPSConfigFile sub_multicast.ini`
In HostB,

Directory is same subsceriber and then publisher operate like this:

`$ ./publisher -DCPSInfoRepo <HostA's IP>:12345 -DCPSConfigFile pub_multicast.ini`
Publisher's return error message here:

```
# ./publisher -DCPSInfoRepo <HostA's IP>:12345 -DCPSConfigFile pub_multicast.ini
Starting publisher
(8921|139698127107904) NOTICE: using DCPSInfoRepo value from command option (overrides value if it's in config file).
Starting publisher with 1 args
Reliable DataWriter
Creating Writer
Starting Writer
(8921|139697959323392) WARNING: SynWatchdog[transport=3]::on_timeout: timed out waiting on remote peer: 0x30c5d67200000007 local: 0x30c5d67200000005
```

I think my configuration file(such as sub_multicast.ini) is fault.
How to set configuration file properly??

P.S. When I use sub_udp.ini and pub_udp.ini file instead of pub_multicast.ini and sub_multicast.ini
The subscriber error appear like this:
```
# ./subscriber -DCPSInfoRepo <HostA's IP>:12345 -DCPSConfigFile sub_udp.ini
(23390|140462743689024) NOTICE: using DCPSInfoRepo value from command option (overrides value if it's in config file).
Transport is UN-RELIABLE
(23390|140462743689024) WARNING: Could not find FQDN. Using "127.0.0.1" as fully qualified hostname, please correct system configuration.
DataReaderListener.cpp:132: INFO: on_requested_incompatible_qos()
DataReaderListener.cpp:132: INFO: on_requested_incompatible_qos()
```
What's wrong my .ini file??

**Comment by mitza-oci** [comment]
Typically multicast traffic is not routed through to the WAN / public network.  You can use wireshark/tcpdump to verify that the traffic sent out on one host is received on the other host.

**Comment by mitza-oci** [comment]
The OpenDDS udp transport doesn't support reliability.  Your application's QoS will need to be changed to best-effort in order to use the udp transport.  Keep in mind the rtps_udp transport is capable of using both multicast and unicast udp.

**Comment by redrabit** [comment]
Then, what is the best ini file or configuraton??
I just want to sending and receiving some message between two hosts.

**Comment by mitza-oci** [comment]
I'm not sure how there could be such a thing as a "best" configuration.  Use the configuration that you need for your network.  The tcp and rtps_udp transports are both good options based on what you've described so far.

**Comment by redrabit** [comment]
I finally solve my problem. Thank you for your reply.
I Just change Discovery server host and use rtps_uni.ini file.
 like this:

`$DCPSInfoRepo -ORBListenEndpoints iiop://:12345`
subscriber side:

`$./subscriber -DCPSDebugLevel=5 -DCPSInfoRepo HostB:12345 -DCPSConfigFile rtps_uni.ini`
publisher side:

 `$./publisher -DCPSInfoRepo HostB:12345 -DCPSConfigFile rtps_uni.ini
`
But, still I don't know when I set HostA to Discovery server, it doesn't work!
