### ISSUE TITLE
Remote participants could not discovery each other 

### ISSUE THREAD

**Issue by redrabit** [objectcomputing/OpenDDS#761]
I try to communicate two hosts in different WAN environment.
But, always participant's could not discover each other.
I have used to example _$OpenDDS_HOME/tests/DCPS/Messenger_

Follow is my shell script commands:
Subscriber side
`$ DCPSInfoRepo -ORBListenEndpoints iiop://:12345`
`$ ./subscriber -DCPSInfoRepo HostA:12345 -DCPSConfigFile sub.ini`

Publisher side
`$ ./publisher -DCPSInfoRepo HostA:12345 -DCPSConfigFile pub.ini`

How can I make discover two hosts??
Has anyone implemented in remote WAN?
Somebody give me any hint to solve this problem??
Thank you.

**Comment by mitza-oci** [comment]
It's not clear from this what's failing.  Have you verified that the name "HostA" resolves correctly from host B?  Is port 12345 on HostA reachable from B?  Are there error messages logged from the DCPSInfoRepo or the applications?

**Comment by redrabit** [comment]
Yes. I already checked opening port. Such like that:

> telnet hostA 12345

 and `telnet hostB 12345`

It was always ok.

My DCPSInfoRepo log file contents:
```
TAO (10884|140304320468800) - TAO_Connector::connect: found a transport [9] busy_count = 0
TAO (10884|140304320468800) - TAO_Connector::connect: found a transport [9] busy_count = 0
TAO (10884|140304320468800) - TAO_Connector::connect: found a transport [9] busy_count = 0
TAO (10884|140304320468800) - TAO_Connector::connect: found a transport [9] busy_count = 0
TAO (10884|140304320468800) - Transport[9]::handle_input_parse_data, notify reactor
TAO (10884|140304320468800) - Transport[9]::notify_reactor, notify to Reactor
TAO (10884|140304320468800) - Transport[9]::process_queue_head, notify reactor
TAO (10884|140304320468800) - Transport[9]::notify_reactor, notify to Reactor
InfoRepo_Shutdown: shutting down on signal 2
TAO (10884|140304320468800) - Connection_Handler[9]::close_connection_eh, purging entry from cache
TAO (10884|140304320468800) - Connection_Handler[9]::close_connection_eh, removing from the reactor
TAO (10884|140304320468800) - Connection_Handler[9]::close_connection_eh, cancel all timers
TAO (10884|140304320468800) - Connection_Handler[9]::close_connection_eh end
(10884|140303621154560) we did not try to re-establish connection on transport: _OPENDDS_InfoRepoBITTCPTransportInst to 127.0.0.1:41047.
```
