### ISSUE TITLE
Install OpenDDS-3.12 on windows7 system issue

### ISSUE THREAD

**Issue by redrabit** [objectcomputing/OpenDDS#762]
I recently try to install OpenDDS-3.12 on my windows7 OS.

But, it has make trouble.

When I try to type configure on VS command prompt, it can't detect Visual C++ version!

Error code is like this:

```
Colud not detect Visual C++ version, try running this script from
 the Visual Studio Command Prompt.
Stopped at configure line 410.
Somebody help me my problem.
```
When I type the message "cl /?" in VS prompt, prompt print "version 19.00.24215.1".
(Active perl version is 5.24.1, VS version is 2017)

**Comment by mitza-oci** [comment]
Try running this command in the VS command prompt:
`cl /v 2>&1 | perl -ne"print qq($1 $2\n) if /version (\d+)\.(\d+)/i"`

When I run it I get "19 00" for VS2015 and "19 11" for VS2017.  If you see anything different please paste the complete and exact output of "cl /v" in your reply.

**Comment by mcint015** [comment]
I see 19 12

**Comment by jhenchen** [comment]
I also meet this erro.
When I run the command 
cl /v 2>&1 | perl -ne"print qq($1 $2\n) if /version (\d+)\.(\d+)/i"
with my vs2015 (Chinese version). I got nothing.

**Comment by mitza-oci** [comment]
@jhenchen please post the complete output of "cl /v"

**Comment by jhenchen** [comment]
/Volumes/NO NAME/d07716af290d7b7eec7e5c1688d23649.png

**Comment by jhenchen** [comment]
The output like this

**Comment by jhenchen** [comment]
![output](https://user-images.githubusercontent.com/18344904/56936802-dacacb80-6b2b-11e9-8cea-9a01454ee736.png)

**Comment by mitza-oci** [comment]
@jhenchen Please open a new issue, it will be easier to track than adding on to an issue closed a long time ago.  You can also modify the code in the configure script and submit a pull request for it.

**Comment by jhenchen** [comment]
ok.
