### ISSUE TITLE
OpenDDS_XML_QOS_XSC_Generation

### ISSUE THREAD

**Issue by zdftju** [objectcomputing/OpenDDS#763]
configure info: 
Skipping OpenDDS_XML_QOS_XSC_Generation (qos_xml_handler.mpc); it requires xsc.

I had add the xerces3 libs, but it still tell the infomation above when i executed configure script. I want to use the qos_xml_handler , but what is "xsc"?

**Comment by mitza-oci** [comment]
This is not an error, you can use the qos_xml_handler without the code generation step because the generated code is included in the repository.  https://github.com/DOCGroup/XSC
