### ISSUE TITLE
Multiple network interfaces configuration

### ISSUE THREAD

**Issue by zdftju** [objectcomputing/OpenDDS#766]
Hi:
     I have two computer with multiple network interfaces , and another one with a single network interface.
I start a repository on the single one,  start a publisher and a subscriber respectively on the other two multiple interfaces computers , I find the publisher and subscriber start( create entities ) very slowly, how this happened ? Have I  left some special configurations for multiple network interfaces?  Hope to get your replay and instructions, thank you!

**Comment by mitza-oci** [comment]
You can configure OpenDDS to use specific interfaces using the transport and discovery configuration options that are documented in chapter 7 of the developer's guide.  If it's still slow, make sure to enable debug logging to get a more detailed view of what's happening internally.

**Comment by zdftju** [comment]
The problem is still exist, the logs show that it always takes a longer times on creating a datawriter, the log is as follow:

> [LM_DEBUG] |2017-12-09 19:48:58.447485| start to regist publisher topic topicB 
(2548|3276) Messenger::MessageDataWriterImpl::enable_specific-data Dynamic_Cached_Allocator_With_Overflow 4f0580 with 20 chunks
(2548|3276) Messenger::MessageDataWriterImpl::enable_specific-mb Cached_Allocator_With_Overflow 4f05e0 with 200 chunks
(2548|3276) Messenger::MessageDataWriterImpl::enable_specific-db Cached_Allocator_With_Overflow 4f0640 with 20 chunks
(2548|3276) WriteDataContainer sample_list_element_allocator 54ebdc with 20 chunks
(2548|3276) WriteDataContainer transport_send_element_allocator 54ec18 with 20 chunks
(2548|3276) DataWriterImpl::enable-mb Cached_Allocator_With_Overflow 4f06a0 with 20 chunks
(2548|3276) DataWriterImpl::enable-db Cached_Allocator_With_Overflow 4f0700 with 20 chunks
(2548|3276) DataWriterImpl::enable-header Cached_Allocator_With_Overflow 534da8 with 20 chunks
(2548|3276) Service_Participant::get_discovery: returning repository for domain 0, repo DEFAULT_REPO.
(2548|1004) DataWriterRemoteImpl::add_association - local 01030000.a2ccb5c5.00000007.00000202(9847fd49) remote 01030000.a2ccb5c5.00000006.00000207(d54d2076)
(2548|1004) DataWriterImpl::add_association - bit 0 local 01030000.a2ccb5c5.00000007.00000202(9847fd49) remote 01030000.a2ccb5c5.00000006.00000207(d54d2076)
(2548|1004) DataWriterImpl::add_association(): adding subscription to publication 01030000.a2ccb5c5.00000007.00000202(9847fd49) with priority 0.
(2548|1004) DataLink::make_reservation() - creating association local publication  01030000.a2ccb5c5.00000007.00000202(9847fd49) <--> with remote subscription 01030000.a2ccb5c5.00000006.00000207(d54d2076).
(2548|1004) DataWriterImpl::transport_assoc_done:  writer 01030000.a2ccb5c5.00000007.00000202(9847fd49) succeeded in associating with reader 01030000.a2ccb5c5.00000006.00000207(d54d2076)
(2548|1004) DataWriterImpl::transport_assoc_done: marked 01030000.a2ccb5c5.00000006.00000207(d54d2076) as pending.
[LM_DEBUG] |2017-12-09 19:49:40.522146| complete to register publisher topic topicB 

[publisher.log](https://github.com/objectcomputing/OpenDDS/files/1544734/publisher.log)

**Comment by zdftju** [comment]
@mitza-oci 
seek for your help.

**Comment by mitza-oci** [comment]
If you add "-ORBVerboseLogging 1", every log message will have a timestamp automatically added.

Which transport type are you using?  We need to determine if the slowdown is happening in the DDS transport or within discovery (TAO since you are using DCPSInfoRepo).

**Comment by zdftju** [comment]
@mitza-oci 
I‘m so sorry for my delays in replying to your  messages ,here is the verbose logs.
[dds_init_part.log](https://github.com/objectcomputing/OpenDDS/files/1565737/dds_init_part.log)

**Comment by mitza-oci** [comment]
Here's what I can tell so far:
- Discovery type is DCPSInfoRepo
- Transport type is udp
- 21 second gap in the log between TransportImpl::configure() and "complete to register publisher"

Is it correct that between your log messages "start to regist publisher topic" and "complete to register publisher" DDS::Publisher::create_datawriter() is the only significant DDS API called?

Based on this and the timestamps of the other DDS transport log messages, I think we should look at TAO as the possible cause of the delays.  You can enable TAO's logging with "-ORBDebugLevel N" where N is a number 1-10.  4 or higher would be a good starting point.
