### ISSUE TITLE
Installation issue "Can't open perl script... No such file or directory" 

### ISSUE THREAD

**Issue by Funnjy** [objectcomputing/OpenDDS#767]
Execution of command `configure --java` with VS command prompt results in the following output: 
`ACE_ROOT/ace/config.h exists, skipping configuration of ACE+TAO
Running MPC to generate project files.
Can't open perl script "C:\Users\Anton": No such file or directory
ERROR: Error from MPC, stopped at configure line 1270.`

My username folder is `Anton Ilchenko`

How do I fix this issue?

**Comment by jwillemsen** [comment]
Do you have installed perl? If yes, can you try to use the script in a directory without space in it?

**Comment by mitza-oci** [comment]
You can add some strategic quotes to the configure script:

```
@@ -1254,7 +1254,7 @@
   print "ENV: saving current environment\n" if $opts{'verbose'};
   mergeToEnv($buildEnv);

-  my $mwcargs = "-type $mpctype $buildEnv->{'DDS_ROOT'}$slash$ws $static";
+  my $mwcargs = "-type $mpctype \"$buildEnv->{'DDS_ROOT'}$slash$ws\" $static";
   $mwcargs .= ' ' . join(' ', @{$opts{'mpcopts'}}) if defined $opts{'mpcopts'};
   if (!$buildtao && @features) {
     for my $feature (@features) {
@@ -1266,7 +1266,7 @@
   print 'Running MPC to generate ', ($mpctype eq 'gnuace' ? 'makefiles' :
                                      'project files'), ".\n";
   if (!$opts{'dry-run'}) {
-    if (system("perl $ENV{'ACE_ROOT'}/bin/mwc.pl $mwcargs") != 0) {
+    if (system("perl \"$ENV{'ACE_ROOT'}/bin/mwc.pl\" $mwcargs") != 0) {
       die "ERROR: Error from MPC, stopped";
     }
   }
```

**Comment by mitza-oci** [comment]
The `tao_idl` compiler doesn't work properly with spaces in the directory names.  Use a different directory or create a symlink that doesn't use a space.

**Comment by Funnjy** [comment]
Ok, I'll check it out.

**Comment by Funnjy** [comment]
@mitza-oci Thank you, editing configure script got it rolling!

**Comment by mitza-oci** [comment]
You'll probably get to a point where it errors out if the path to the root OpenDDS directory has a space.  I have some local changes to patch the IDL compiler but that's not a complete fix since there are also problems in the VS project files.
