### ISSUE TITLE
DDS within docker containers on different hosts

### ISSUE THREAD

**Issue by dhet** [objectcomputing/OpenDDS#768]
My plan is to deploy individual DDS participants within docker containers distributed on separate hosts. The hosts are connected via LAN. I'm currently using the standard messenger example for testing.
The example works perfectly fine when I run the participants on different hosts without containers. However, as soon as I deploy one of the participants within a container it doesn't work anymore: the participants can't find each other. The problem is that docker containers need to specify which ports to expose to the host. My idea was to set the discovery ports in the config file and expose a port range in the container.
My config file looks like this
```ini
[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=discoveryConf1

[rtps_discovery/discoveryConf1]
PB=8000
DG=10

[transport/transportConf1]
transport_type=rtps_udp
```
In my example this causes the participants to use ports 8420, 8422 and 8430 for service discovery. So I thought it would be enough to expose the port range from 8400 to 8500 like so:
```sudo docker run -p 8400-8500 -ti -v $(pwd):/opt/workspace kugele1337/qemu-raspbian-opendds```

Unfortunately, this doesn't change anything. The participants still can't find each other. What am I missing?

**Update:** I just realized I probably need docker swarm or kubernetes for this

**Comment by mitza-oci** [comment]
When you run on different hosts without containers, get a packet capture using a tool like tcpdump and make sure all the required ports are covered by your configuration.  Debug logging will also show you which ports are being used.

**Comment by jrw972** [comment]
RTPS discovery uses multicast which is not "well" supported in Docker.  See https://github.com/moby/moby/issues/3043 for a discussion.  The TLDR is
1. Container to container multicast on the same host is supported out of the box.
2. Otherwise, you need to use `--net=host` which has its own downsides.

As an alternative, you can use the InfoRepo for discovery.  We have explored using InfoRepo for discovery in Kubernetes.  If you are interested in this approach, let us know and we can make some documentation available to you.

**Comment by dhet** [comment]
Thanks for your input. I would love to hear about your attempts to use Kubernetes.

**Comment by jrw972** [comment]
@dhet I've created a repo with an example of running the Messenger example in Kubernetes.
 <https://github.com/jrw972/KubernetesMessenger>

**Comment by dhet** [comment]
Thank you @jrw972. I like the script to modify the config files... quite creative 😄 
I've spent some time trying to get cross host / cross container multicast to work with swarm. I've tested several network setups using different network drivers:
* [overlay](https://docs.docker.com/engine/userguide/networking/overlay-standalone-swarm/)
* [weave](weaveworks/weave)
* [macvlan](https://docs.docker.com/engine/userguide/networking/get-started-macvlan/) (swarm-scoped)

None worked. Multicast support seems to be a much requested feature in the docker community: docker/libnetwork/issues/552
