### ISSUE TITLE
Error in compiling on FreeBSD

### ISSUE THREAD

**Issue by sholla** [objectcomputing/OpenDDS#771]
I get the following errors in compiling 3.12.1 on FreeBSD:
gmake[1]: Leaving directory '/usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/TAO/tao/PI'
gmake[1]: Entering directory '/usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/TAO/tao/PortableServer'

GNUmakefile: /usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/TAO/tao/PortableServer/GNUmakefile.PortableServer_Idl MAKEFLAGS=w

gmake[1]: Leaving directory '/usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/TAO/tao/PortableServer'
gmake[1]: Entering directory '/usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/TAO/tao/PortableServer'

GNUmakefile: /usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/TAO/tao/PortableServer/GNUmakefile.PortableServer MAKEFLAGS=w

c++ -Wno-deprecated-declarations -fvisibility=hidden -fvisibility-inlines-hidden -g -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -I/usr/local/include   -I/usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers -D__ACE_INLINE__ -I../../.. -I../.. -DTAO_HAS_VALUETYPE_OUT_INDIRECTION -DTAO_PORTABLESERVER_BUILD_DLL  -c -fpic -o .shobj/Servant_Base.o Servant_Base.cpp
In file included from Servant_Base.cpp:4:
In file included from ../../tao/PortableServer/Servant_Base.h:24:
In file included from ../../tao/PortableServer/PS_ForwardC.h:44:
In file included from ../../tao/ORB.h:28:
In file included from ../../tao/orb_typesC.h:47:
In file included from ../../tao/Basic_Arguments.h:25:
../../tao/Any_Insert_Policy_T.h:44:14: error: no viable overloaded '<<='
        (*p) <<= x;
        ~~~~ ^   ~
../../tao/PortableServer/Object_SArgument_T.cpp:120:25: note: in instantiation
      of member function 'TAO::Any_Insert_Policy_Stream<CORBA::Object
      *>::any_insert' requested here
  Insert_Policy<S_ptr>::any_insert (any, this->x_.in ());
                        ^
Servant_Base.cpp:288:47: note: in instantiation of member function
      'TAO::Ret_Object_SArgument_T<CORBA::Object *,
      TAO_Pseudo_Var_T<CORBA::Object>,
      Any_Insert_Policy_Stream>::interceptor_value' requested here
  TAO::SArg_Traits< ::CORBA::Object>::ret_val retval;
                                              ^
../../tao/AnyTypeCode/Any.h:96:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'from_boolean' (aka
      'ACE_OutputCDR::from_boolean') for 1st argument
    void operator<<= (from_boolean);
         ^
../../tao/AnyTypeCode/Any.h:97:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'from_char' (aka
      'ACE_OutputCDR::from_char') for 1st argument
    void operator<<= (from_char);
         ^
../../tao/AnyTypeCode/Any.h:98:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'from_wchar' (aka
      'ACE_OutputCDR::from_wchar') for 1st argument
    void operator<<= (from_wchar);
         ^
../../tao/AnyTypeCode/Any.h:99:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'from_octet' (aka
      'ACE_OutputCDR::from_octet') for 1st argument
    void operator<<= (from_octet);
         ^
../../tao/AnyTypeCode/Any.h:100:10: note: candidate function not viable: no
      known conversion from 'CORBA::Object *const' to 'from_string' (aka
      'ACE_OutputCDR::from_string') for 1st argument
    void operator<<= (from_string);
         ^
../../tao/AnyTypeCode/Any.h:101:10: note: candidate function not viable: no
      known conversion from 'CORBA::Object *const' to 'from_wstring' (aka
      'ACE_OutputCDR::from_wstring') for 1st argument
    void operator<<= (from_wstring);
         ^
../../tao/AnyTypeCode/Any.h:171:10: note: candidate function not viable: no
      known conversion from 'CORBA::Object *const' to 'unsigned char' for 1st
      argument
    void operator<<= (unsigned char);
         ^
1 error generated.
gmake[1]: *** [/usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/include/makeinclude/rules.local.GNU:189: .shobj/Servant_Base.o] Error 1
gmake[1]: Leaving directory '/usr/home/shrolla/tools/OpenDDS-DDS-3.12.1/ACE_wrappers/TAO/tao/PortableServer'
gmake: *** [GNUmakefile.dist:684: PortableServer] Error 2

**Comment by jwillemsen** [comment]
Which FreeBSD version is this and which compiler, I would expect g++ as compiler? 

Are you using the DOC Group TAO version or the OCI TAO version?

**Comment by sholla** [comment]
FreeBSD version seems to be: 11.1-Release
G++ I believe
Also the TAO version is 2.2a_p13. I think it is the OCI version from looking at the VERSION file.
Essentially I ran configure in defaults i.e. just "./configure" and have no prior installation of TAO.

**Comment by jwillemsen** [comment]
Could you run ‘ c++ -version’ to get the compiler version. Try ‘ configure -doc_group’ to use the DOC group TAO version, run it in a fresh tree.

**Comment by sholla** [comment]
I tried it with doc_group. Error at the same place but this time it says the operator is private. Attached the output below.
Also the C++ version:
c++ --version
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: i386-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin
-------------------------------------------------------------------------------------------------------------------
c++ -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -g -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -I/usr/local/include   -I/usr/home/shrolla/tools/opendds-2/OpenDDS-3.12/ACE_wrappers -D__ACE_INLINE__ -I../../.. -I../.. -DTAO_HAS_VALUETYPE_OUT_INDIRECTION -DTAO_PORTABLESERVER_BUILD_DLL  -c -fpic -o .shobj/PolicyS.o /usr/home/shrolla/tools/opendds-2/OpenDDS-3.12/ACE_wrappers/TAO/tao/PortableServer/PolicyS.cpp
In file included from /usr/home/shrolla/tools/opendds-2/OpenDDS-3.12/ACE_wrappers/TAO/tao/PortableServer/PolicyS.cpp:34:
In file included from /usr/home/shrolla/tools/opendds-2/OpenDDS-3.12/ACE_wrappers/TAO/tao/PortableServer/PolicyS.h:34:
In file included from ../../tao/PolicyC.h:43:
In file included from ../../tao/ORB.h:26:
In file included from ../../tao/orb_typesC.h:45:
In file included from ../../tao/Basic_Arguments.h:23:
../../tao/Any_Insert_Policy_T.h:42:14: error: 'operator<<=' is a private member
      of 'CORBA::Any'
        (*p) <<= x;
        ~~~~ ^   ~
../../tao/PortableServer/Basic_SArgument_T.cpp:103:21: note: in instantiation of
      member function 'TAO::Any_Insert_Policy_Stream<unsigned int>::any_insert'
      requested here
  Insert_Policy<S>::any_insert (any, this->x_);
                    ^
/usr/home/shrolla/tools/opendds-2/OpenDDS-3.12/ACE_wrappers/TAO/tao/PortableServer/PolicyS.cpp:287:46: note: 
      in instantiation of member function 'TAO::Ret_Basic_SArgument_T<unsigned
      int, Any_Insert_Policy_Stream>::interceptor_value' requested here
  TAO::SArg_Traits< ::CORBA::ULong>::ret_val retval;
                                             ^
../../tao/AnyTypeCode/Any.h:169:10: note: declared private here
    void operator<<= (unsigned char);
         ^
1 error generated.
gmake[1]: *** [/usr/home/shrolla/tools/opendds-2/OpenDDS-3.12/ACE_wrappers/include/makeinclude/rules.local.GNU:189: .shobj/PolicyS.o] Error 1
gmake[1]: Leaving directory '/usr/home/shrolla/tools/opendds-2/OpenDDS-3.12/ACE_wrappers/TAO/tao/PortableServer'
gmake: *** [GNUmakefile.dist:683: PortableServer] Error 2

**Comment by jwillemsen** [comment]
It looks the ACE/TAO configuration file (ace/config-freesbd.h) assumes that the compiler is g++. Try to switch to another linux distro or try to fix config-freebsd.h, for clang probably a define of ACE_ANY_OPS_USE_NAMESPACE has to be added. As test maybe add `#define ACE_ANY_OPS_USE_NAMESPACE` to the `ACE/ace/config.h` file

**Comment by sholla** [comment]
Yes that worked but with a minor twist. Using configure with doc_group and added that constant above, produced an undefined symbol for that same operator. I had to use the default configure with that constant defined and it compiled and linked fine.

**Comment by mitza-oci** [comment]
We don't currently have a CI build on FreeBSD.  I added support to the configure script by starting a VirtualBox instance and contributing changes to the ACE configuration files to make it work.  The FreeBSD version was probably 10.2 at that time.  If you are using version 11 of FreeBSD, update the file $ACE_ROOT/include/makeinclude/platform_freebsd.GNU where it references the version number.

If you'd like first-class support for FreeBSD, we need a CI build somewhere.  We can help you set one up, or you can use our commercial support services to sponsor one.

**Comment by mitza-oci** [comment]
Also see https://github.com/objectcomputing/OpenDDS/pull/774

**Comment by sholla** [comment]
Ok @mitza-oci . Still evaluating DDS and OpenDDS at present. And did see the new file with #774
