### ISSUE TITLE
Example program fails

### ISSUE THREAD

**Issue by dreamtale90** [objectcomputing/OpenDDS#772]
I'm a newbie. After install OpenDDS, run example program under "$DDS_ROOT/DevGuideExamples/DCPS/Messenger" folder, I got following error:
[error.txt](https://github.com/objectcomputing/OpenDDS/files/1546977/error.txt)

Envirment infomation:
OS: debian8.6
kernel: 3.18.69rt75
gcc: 4.9.2
OpenDDS: 3.12
TAO: ACE+TAO-2.2a_with_latest_patches_NO_makefiles
CONTENTS OF $ACE_ROOT/ace/config.h:  #include "ace/config-linux.h"
[configure_info.txt](https://github.com/objectcomputing/OpenDDS/files/1547084/configure_info.txt)

Thanks in advance.

**Comment by mitza-oci** [comment]
Does the file /root/WorkSpace/OpenDDS-3.12/DevGuideExamples/DCPS/Messenger/publisher exist?  What was the output of running "make"?

**Comment by dreamtale90** [comment]
The publisher file exists, and make without error.
[make_result.txt](https://github.com/objectcomputing/OpenDDS/files/1549892/make_result.txt)

**Comment by dreamtale90** [comment]
@mitza-oci The output of ldd is OK. The strange things is that I run this example without error on another computer. So I think it might be a problem in my environment.
[ldd_result.txt](https://github.com/objectcomputing/OpenDDS/files/1553731/ldd_result.txt)

**Comment by dreamtale90** [comment]
I found following information in Line23 of the publisher.log file. But I still don't know what the problem is. I think this maybe useful.

_TAO (7426|140037397645120) - IIOP connection failed.
     This is most likely due to a hostname lookup failure._
[publisher.log](https://github.com/objectcomputing/OpenDDS/files/1553914/publisher.log)

**Comment by mitza-oci** [comment]
The publisher process is trying to connect to DCPSInfoRepo.  When the DCPSInfoRepo process starts up, it writes a file named "repo.ior".  You can use the utility tao_catior to interpret the binary data in repo.ior.  Run it as "tao_catior -f repo.ior".  The tao_catior utility is not included in the default build of OpenDDS, but you can build it (assuming the setenv.sh is in effect):
> cd $TAO_ROOT
> mwc.pl -type gnuace TAO_ACE.mwc
> make catior

**Comment by dreamtale90** [comment]
Aha, the problem is hostname. The “bogon” is used in hostname of repo.ior file.
```
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# hostname
rtse
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# hostname -A
bogon 
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# ping bogon
ping: unknown host bogon
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# ping rtse
PING rtse.rtse (127.0.1.1) 56(84) bytes of data.
64 bytes from rtse.rtse (127.0.1.1): icmp_seq=1 ttl=64 time=0.041 ms
64 bytes from rtse.rtse (127.0.1.1): icmp_seq=2 ttl=64 time=0.053 ms
^C
--- rtse.rtse ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.041/0.047/0.053/0.006 ms
```
So, I add my address into /etc/hosts file. It's OK.
```
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# echo "192.168.1.23 rtse" >> /etc/hosts
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# hostname
rtse
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# hostname -A
rtse 
root@rtse:~/WorkSpace/OpenDDS/DevGuideExamples/DCPS/Messenger# ping rtse
PING rtse.rtse (127.0.1.1) 56(84) bytes of data.
64 bytes from rtse.rtse (127.0.1.1): icmp_seq=1 ttl=64 time=0.031 ms
64 bytes from rtse.rtse (127.0.1.1): icmp_seq=2 ttl=64 time=0.053 ms
^C
--- rtse.rtse ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.031/0.042/0.053/0.011 ms
```
But I wonder know why use the result of "hostname -A" command, instead of the result of "hostname" command.

**Comment by dreamtale90** [comment]
@mitza-oci Thank you. I have another question about IDL. If I‘m not sure what type of data is sent（may be dynamic）， what should I do？

**Comment by mitza-oci** [comment]
TAO determines the address to use based on the IP interfaces on the host and if/how names resolve for those IP addresses.  TAO is configurable in a number of different ways to allow you to influence this process.

Re: your post on "another question about IDL," please create a separate issue so that others may find it in the future.

**Comment by dreamtale90** [comment]
OK. Thank you very much.
