### ISSUE TITLE
DCPSInfoRepo connection refused after Telnet

### ISSUE THREAD

**Issue by e55k4y** [objectcomputing/OpenDDS#775]
I was trying to setup DCPSInfoRepo server in a machine and then connect to it from multiple instances.
To check whether the DCPSInfoRepo server was accessible from the remote instances, I used Telnet to check the connection.
After I closed the Telnet connection, I wasn't able to connect to the DCPSInfoRepo from the same instance anymore, but from other instances, it was working okay. Once I restarted the said instance, I was able to create domain participant using the DCPSInfoRepo and everything was working fine.

I know this is not really a blocking issue, but could anyone tell me what could be the possible reason?
So that I can avoid such occurrences in future.

**Comment by mitza-oci** [comment]
I didn't see the same behavior in a quick test.  If you'd like to dig in to it, run the DCPSInfoRepo with "-ORBDebugLevel 10".

**Comment by e55k4y** [comment]
Looks like TCP layer traffic on a range of ports was blocked for my default network interface. I had to set the TCP port from .ini file specifically and allow it from AWS security group configuration. 
Closing the issue.
