### ISSUE TITLE
tools/dissector doesn't support Wireshark >= 2.x

### ISSUE THREAD

**Issue by RomainNaour** [objectcomputing/OpenDDS#776]
Hi,

It seems that the Wireshark OpenDDS dissector doesn't support the new API used by Wireshark 2.x.

First, tvb_get_string() must be replaced by tvb_get_string_enc().
Then, proto_tree_add_text() has been removed from Wireshark 2.x API and must be carefully replaced by proto_tree_add_bytes_format().
There is a script in Wireshark source tree (tools/convert_proto_tree_add_text.pl) but it doesn't work.

Do you plan to update this tool ? or it's deprecated ?

Best regards,
Romain

**Comment by mitza-oci** [comment]
We are developing wireshark 2.x support on a branch (https://github.com/objectcomputing/OpenDDS/tree/wireshark2), it's almost ready to merge to master.  If you'd like to give it a try please let us know how it goes.

**Comment by RomainNaour** [comment]
Hi,
Thanks, I'll give a try.

**Comment by iguessthislldo** [comment]
@RomainNaour I am the one working on the dissector for Wireshark 2. The canidate 2.x dissector is actually still in [my fork of the main repo](https://github.com/iguessthislldo/OpenDDS/tree/wireshark2), not the branch that @mitza-oci linked.  (@mitza-oci: Should it be in there?) I am interested in how it works out for you as well.

**Comment by mitza-oci** [comment]
Thanks, I forgot that branch was the old one.  Probably best just to create a pull request so we can easily reference it from here.  Even if it's not quite ready to merge yet, we can start the review process that way.

**Comment by iguessthislldo** [comment]
Alright done: #777 should be ready to merge if not Friday, then next week after school has released me from its grip.

**Comment by RomainNaour** [comment]
Hi,

Now #777 is merged in master (thanks!), I still have a build issue with the dissector:

../../tools/dissector/sample_dissector.h:47:11: error: looser throw specifier for ‘virtual OpenDDS::DCPS::Sample_Dissector_Error::~Sample_Dissector_Error()’
     class Sample_Dissector_Error : public std::exception {

It seems that the dissector is not build tested by travisCI.
Can you have a look?

Best regards,
Romain

**Comment by mitza-oci** [comment]
We haven't completed all of the changes needed for Wireshark 2.  We do see that error on sample_dissector.h:47 on our internal CI so it's on the list of things to do very soon.

Setting it up on Travis CI will probably require us to compile Wireshark from source as part of the build (since there are no -devel packages for 14.04 as far as I know), which may run into problems with the time limit.  Is that something you can help with?

**Comment by RomainNaour** [comment]
Ok thanks for the quick feedback!
I had the feeling that the changes for Wireshark 2 was complete with the #777 merge, so I wanted to report the issue.

I've looked quickly at the C++ issue, I need to look further...
I don't think I will have much time to look at the Travis CI for the Wireshark plugin.

**Comment by mitza-oci** [comment]
See #787

**Comment by iguessthislldo** [comment]
@RomainNaour #793 fixes that particular problem, I declared the destructor in #787 thinking that would fix the problem, but I didn't put in the `throw()` it wanted until #793.
