### ISSUE TITLE
Decreasing performance over time

### ISSUE THREAD

**Issue by dhet** [objectcomputing/OpenDDS#780]
I wrote a simple benchmark to test OpenDDS performance over time. The benchmark consists of a publisher which continually sends the current timestamp and a subscriber that also measures it's current time and then calculates the time delta using its own time and the received timestamp. In other words, the program measures the time between sending and receiving a message.

The publisher sends 1000 messages and waits 100 ms inbetween. I'm noticing a significant time drift that increases linearly with the run time of the program. When I plot the time deltas the result looks like this:

![drift](https://user-images.githubusercontent.com/2668621/34158325-2836dd9e-e4c5-11e7-8f34-c087ac8facc3.png)

I'm wondering where that drift comes from. Is it the QoS settings? QoS is throughout set to default but I also ran some tests with different `RESOURCE_LIMITS` settings but to no avail. I also tested the program for memory leaks and found nothing. CPU usage and memory consumption remains constant throughout the benchmark. Could something be wrong with the measurement method? (And yes I'm aware that the times might not be synchronized but that should cause a _drift_)

**Sending part of Publisher:**
```c++
    auto now = std::chrono::high_resolution_clock::now();
    auto micro_seconds = std::chrono::duration_cast<std::chrono::microseconds>(now.time_since_epoch()).count();
    Spammer::Message message;
    message.Data = "1234";

    for (int i = 0; i < 1000; i++)
    {
      now = std::chrono::high_resolution_clock::now();
      micro_seconds = std::chrono::duration_cast<std::chrono::microseconds>(now.time_since_epoch()).count();
      message.Timestamp = micro_seconds;

      DDS::ReturnCode_t error = message_writer->write(message, DDS::HANDLE_NIL);
      if (error != DDS::RETCODE_OK)
      {
        ACE_ERROR((LM_ERROR, ACE_TEXT("ERROR: %N:%l: main() -") ACE_TEXT(" write returned %d!\n"), error));
      }
      usleep(100000);
    }
```

**Subscriber listener:**
```c++
  int time;
  auto now = std::chrono::high_resolution_clock::now();
  auto micro_seconds = std::chrono::duration_cast<std::chrono::microseconds>(now.time_since_epoch()).count();
  
  DDS::ReturnCode_t error = reader_i->take_next_sample(message, info);
  if (error == DDS::RETCODE_OK && info.valid_data)
  {
    now = std::chrono::high_resolution_clock::now();
    micro_seconds = std::chrono::duration_cast<std::chrono::microseconds>(now.time_since_epoch()).count();
    time = micro_seconds - message.Timestamp;
    std::cout << time << std::endl;
  }
```

**IDL:**
```idl
module Spammer {
  #pragma DCPS_DATA_TYPE "Spammer::Message"
  #pragma DCPS_DATA_KEY "Spammer::Message Timestamp"
  struct Message {
    string Data;
    long Timestamp;
  };
};

```

**Comment by mitza-oci** [comment]
What OpenDDS configuration options (via command line, config file, code) are you using?

Making the Timestamp a key field significantly impacts the test.  Do you expect to create a new instance with every write() in an actual application?

**Comment by dhet** [comment]
The configuration is fairly standard:
```ini
[common]
DCPSGlobalTransportConfig=$file
DCPSDefaultDiscovery=DEFAULT_RTPS

[transport/RTPSconf]
transport_type=rtps_udp
```
I also tried shared memory transport and the effect is the same. So the network is definitely not the problem.

How exactly does the timestamp as key field impact the test? I'm not planning to do this in an actual application. This is just me messing around with a pseudo benchmark.

**Comment by dhet** [comment]
Alright, after removing the key the drift is gone. Does anyone mind explaining why?

**Comment by mitza-oci** [comment]
There is more overhead involved in creating instances than in updating them with new data samples.  Also since instance creation is relatively rare and not normally on the "hot path" it's not as well optimized in the implementation.

**Comment by taoyonggang** [comment]
I have test with the idl.

        @topic
        struct NodeReply {
            @key string uuid;  //消息唯一id
            @key string nodeId;  //回执节点
            string nodeName;    //节点名
            string group;      //所在组
            string replyUuid;  //回执消息uuid
            unsigned long status;    //0：成功 1：非法，执行失败 2：其它
            string desc;   //执行详情
            long long createdAt;  //创建消息时间
            long long updatedAt;  //发送消息时间
        };

**Comment by taoyonggang** [comment]
if i use @key before the string field.  It will cause memory leak.

uuid::UUID uuid1;
uuid = uuid1.generate();
CORBA::String_var uuid_var = CORBA::string_dup(uuid.c_str());
nodeCmdMsg->uuid = uuid_var.in();

......
if i use with CORBA::String_var uuid_var = CORBA::string_dup("......."); it's good work.

**Comment by taoyonggang** [comment]
The write qos are:

    writer_qos->reliability.kind = DDS::RELIABLE_RELIABILITY_QOS;
    writer_qos->reliability.max_blocking_time.sec = 10;
    writer_qos->reliability.max_blocking_time.nanosec = 1000 * 1000;
    writer_qos->history.kind = DDS::KEEP_LAST_HISTORY_QOS;
    writer_qos->history.depth = 500;
    writer_qos->resource_limits.max_samples = 100;
