### ISSUE TITLE
Configure Script can't locate Extracted ACE Dir on Windows 10

### ISSUE THREAD

**Issue by waheedejaz** [objectcomputing/OpenDDS#783]
OpenDDS VERSION: 3.12
TAO VERSION: 2.2a
Windows 10

The configure script can't extract the downloaded .zip file of ACE+TAO.

```
Extracting archive ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip
ERROR: Can't extract ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip, extract it to E:/OpenDDS
and run this script again.
Stopped at configure line 615.
```
I manually extracted it, placed it in the same folder and re-run but still it gives same message.

**Comment by waheedejaz** [comment]
One workaround to this is to manually define ACE_ROOT and TAO_ROOT in the environment variables and run configure script with --ace=%ACE_ROOT% --tao=%TAO_ROOT%

In my case: 
```
ACE_ROOT = OpenDDS/ACE+TAO-2.2a_with_latest_patches_NO_makefiles/ace_wrappers/
TAO_ROOT=%ACE_ROOT%/tao/
```
then I ran:
`configure --ace=%ACE_ROOT% --tao=%TAO_ROOT%`

**Comment by mitza-oci** [comment]
You can install the Perl module Archive::Extract to give it the ability to unzip from within the Perl script.

If you unzip it yourself make sure that ACE_wrappers is the directory directly under the OpenDDS root.  This is what the configure script message that you saw before ("extract it to...") indicates.
