### ISSUE TITLE
nitpick: perl warning on running configure

### ISSUE THREAD

**Issue by okellogg** [objectcomputing/OpenDDS#785]
This is a low prio issue.
On running
```
./configure
```
using [DOCGroup/ACE_TAO](https://github.com/DOCGroup/ACE_TAO) git, I get:
```
Use of uninitialized value $key in hash element at ./configure line 1199, <$fh> line 2.
Use of uninitialized value $key in hash element at ./configure line 1199, <$fh> line 4.
Use of uninitialized value $key in hash element at ./configure line 1199, <$fh> line 12.
[...]
Use of uninitialized value $key in hash element at ./configure line 1199, <$fh> line 109.
```
I made the warnings go away using the following patch:
```
--- configure.OpenDDS-3.12.1	2017-10-05 00:13:07.000000000 +0200
+++ configure	2018-01-15 11:01:33.039133140 +0100
@@ -1194,8 +1194,10 @@
         open(my $fh, '<', $file) or die "ERROR: Could not open $file: $!";
         while (my $row = <$fh>) {
           chomp $row;
-          unless ($row =~ /^include/) {
-            my ($key, $value) = split(/=/, $row);
+          next if ($row =~ /^\s*#/);
+          $row =~ s/\s*#.*$//;
+          if ($row =~ /^\s*(\w+)\s*=\s*(.*)$/) {
+            my ($key, $value) = ($1, $2);
             $existing_macros{$key} = $value;
           }
         }
```

I trust that `%existing_macros` shall only contain definitions of the form **X = Y**.
If it shall also contain symbols defined as **X := Y**, **X ?= Y**, **X += Y** then the pattern match should be changed to
```
          if ($row =~ /^\s*(\w+)\s*[:?+]=\s*(.*)$/) {
```

FYI, for `platform_macros.GNU` am using the [platform_linux.GNU](https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/include/makeinclude/platform_linux.GNU).

**Comment by mitza-oci** [comment]
Your platform_macros.GNU is literally platform_linux.GNU?  Isn't the recommended style to have a 1-line platform_macros.GNU consisting of an include of platform_linux?

**Comment by okellogg** [comment]
Good point. I don't know how I overlooked that.
Ergo the patch only applies to possible additions.

**Comment by jrw972** [comment]
See #786

**Comment by okellogg** [comment]
> See #786 

Thanks - and apology for the not quite optimal patch (see [comment](https://github.com/objectcomputing/OpenDDS/pull/786#pullrequestreview-88876593))

**Comment by okellogg** [comment]
If it's helpful, I offer to fork and make the pull request myself?

**Comment by mitza-oci** [comment]
@okellogg go ahead

Some background on this section of the configure script...
If there is an already-configured ACE (either from a previous run of this same script or from some external configuration), we should check if that configuration conflicts with what the user of the configure script has requested.  See #708 and the related #682 for some more info.
As you've seen, the parsing of the platform_macros.GNU file is very simplistic (nowhere close to a real makefile parser).  I agree that detecting comments is both useful and not too hard.  The variables we're looking for tend to be boolean so I'm not sure how much += will be of use.
