### ISSUE TITLE
Error Running DDS example

### ISSUE THREAD

**Issue by PRADEEPKJ** [objectcomputing/OpenDDS#809]
Hi All,

I did build the dds according to openDDS installation page on ubuntu.
When I run the test according to the http://opendds.org/about/articles/Article-Intro.html
I face the below issue. Please help me to resolve the issue.
./bin/DCPSInfoRepo -ORBListenEndpoints iiop://localhost:12345
./bin/DCPSInfoRepo: error while loading shared libraries: libOpenDDS_InfoRepoServ.so.3.12.0: cannot open shared object file: No such file or directory

The library is present in the dirctory
./lib/libOpenDDS_InfoRepoServ.so

-Pradep

**Comment by mitza-oci** [comment]
Please see the note about the setenv script on http://opendds.org/quickstart/GettingStartedLinux.html
