### ISSUE TITLE
OpenDDS Raspberry Pi

### ISSUE THREAD

**Issue by SyedAliZafar** [objectcomputing/OpenDDS#810]
I am working on OpenDDS and trying to run messenger example on my Raspberry Pi . Example Messenger Worked on my Ubuntu setup but when i am trying to run it on my Raspberry Pi , it's not working .
there were no problem in ./configure but when i ran the " make " command . I got the following error 

/home/pi/Desktop/OpenDDS-3.12/ACE_wrappers/include/makeinclude/rules.lib.GNU:244: recipe for target 'libOpenDDS_Dcps.so.3.12.0' failed
make[1]: *** [libOpenDDS_Dcps.so.3.12.0] Error 1
make[1]: Leaving directory '/home/pi/Desktop/OpenDDS-3.12/dds'
GNUmakefile.dist:1053: recipe for target 'OpenDDS_Dcps' failed
make: *** [OpenDDS_Dcps] Error 2

**Comment by mitza-oci** [comment]
There should be some error message before the part you've quoted here.  This is make telling us that something failed, but some step involving (probably) g++ was the actual failure.

**Comment by SyedAliZafar** [comment]
lTAO_BiDirGIOP -lTAO_PI -lTAO_CodecFactory -lTAO_AnyTypeCode -lTAO -lACE -ldl -lrt
.shobj/DdsDcpsCoreTypeSupportImpl.o: file not recognized: File truncated
**collect2: error: ld returned 1 exit status**
/home/pi/Desktop/OpenDDS-3.12/ACE_wrappers/include/makeinclude/rules.lib.GNU:244: recipe for target 'libOpenDDS_Dcps.so.3.12.0' failed
make[1]: *** [libOpenDDS_Dcps.so.3.12.0] Error 1
make[1]: Leaving directory '/home/pi/Desktop/OpenDDS-3.12/dds'
GNUmakefile.dist:1053: recipe for target 'OpenDDS_Dcps' failed
make: *** [OpenDDS_Dcps] Error 2

**Comment by mitza-oci** [comment]
If the file was indeed truncated, is there enough space on the filesystem?  Are you compiling directly on the Pi?  We don't recommend that, instead the code should be cross-compiled on a much more capable host.

**Comment by SyedAliZafar** [comment]
i did cleared my space in Pi removing aound 1 GB data . and Yes i am compiling directly on Pi . i am sorry I dont know how to cross compile with other host . If i work on Raspberry Pi 3 would that make a difference ?

**Comment by mitza-oci** [comment]
There is no model of Raspberry Pi that's a very capable computer for compiling large C++ codebases.  Cross-compilers are very useful and we've provided to the community the support in the configure script and makefiles for using a cross compiler (run ./configure --help and ./configure --target-help).  A cross-compiler for the Pi is available at https://github.com/raspberrypi/tools.git

**Comment by SyedAliZafar** [comment]
Thanks for the help. Hope this sort out things for me 👍

**Comment by mitza-oci** [comment]
See #812
