### ISSUE TITLE
Impact of TAO bug 2703: sequences of built-in types

### ISSUE THREAD

**Issue by pcoscia** [objectcomputing/OpenDDS#814]
I have recently attempted generating the OARIS IDL files to DDS types I can use over a DDS connection. I found that when running the IDL generator scripts over the files, most of the code generated from OARIS IDL was having a dll import issue on unbounded sequence types. 

I have found that rearranging the #include statements by editing the be_produce.cpp file fixed the problem for me. I have made the suggestion because it seemed like the easiest way to explain the issue I am having but I am not suggesting that my solution is well thought out or tested, it just solved my specific problem.

I hope this is clear enough explanation, but feel free to let me know if more information is requied to correctly diagnose and remedy the bug.

I have made a fork and an example solution at this link.
https://github.com/objectcomputing/OpenDDS/compare/master...pcoscia:patch-1

**Comment by pcoscia** [comment]
Just a note that I forgot, this issue only occured using Windows (VS2015). A Linux build went through without any changes being required.

**Comment by mitza-oci** [comment]
Do you have a link to OARIS?  I have no idea what that is.

The issue you're describing sounds like it could be fixed by http://opendds.org/faq#idl-builtin, have you tried that already?

**Comment by pcoscia** [comment]
Apologies, here is the link to OARIS. https://www.omg.org/spec/OARIS/About-OARIS/

I don't think the idl-builtin solution is what we need. As we do not control the IDL, the less medling we do with it the better.

**Comment by mitza-oci** [comment]
Thanks for the link.

The IDL contains `#pragma keylist` which is non-standard.  To make this work with OpenDDS you'll need to add the `#pragma` lines that are OpenDDS-specific.

You can read some more background on the "unbounded sequence of primitive type" issue here: http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2703

I'm not opposed to changing the generated include order, but we need to be very careful about potential breaking changes.  You can submit a pull request which we will set up to run a full test on our Jenkins server.

**Comment by pcoscia** [comment]
I am aware of the #pragma addition required, at this stage I have written a script to add the appropriate #pragmas for across all OARIS IDL files. 

Thanks for the link, I found the background on the issue an interesting read.

Absolutley agree, unfortunately I don't know enough about OpenDDS to have any idea what the changes could break. I am happy to put in a pull request and see how the testing goes.

**Comment by mitza-oci** [comment]
You can go ahead and submit the pull request.

Please post an example of what the compile error looks like (with the stock opendds_idl).

**Comment by pcoscia** [comment]
Just this morning I have found a breaking change to rebuilding OpenDDS with my included changes. I will hold off on the pull request temporarily until I have had a chance to go through properly and see the error. 

I will also post the errors building OARIS with the stock opendds_idl.

**Comment by pcoscia** [comment]
This is an axample of the errors I am finding when building using the stock opendds_idl. 
These are specifically from compiling the "Control_Battle_Override.idl" file (with no errors) then compiling the generated "Control_Battle_OverrideTypeSupportImpl.cpp" file. 

1>$(ACE_ROOT)\TAO\tao/StringSeqC.h(179): error C2961: 'TAO::unbounded_basic_string_sequence<charT>': inconsistent explicit instantiations, a previous explicit instantiation did not specify '__declspec(dllimport)'
1>          with
1>          [
1>              charT=char
1>          ]
1>$(ACE_ROOT)\TAO\tao/LongSeqC.h(178): error C2961: 'TAO::unbounded_value_sequence<CORBA::Long>': inconsistent explicit instantiations, a previous explicit instantiation did not specify '__declspec(dllimport)'
1>$(ACE_ROOT)\TAO\tao/UShortSeqC.h(178): error C2961: 'TAO::unbounded_value_sequence<CORBA::UShort>': inconsistent explicit instantiations, a previous explicit instantiation did not specify '__declspec(dllimport)'

I do not have this problem if I implement the change in #include order. 
However upon rebuilding OpenDDS with the alternate #include order from my change, I found that the 'OpenDDS_Dcps' project did not generate files correctly, did not build and caused most of OpenDDS to not build.
I also attempted a different change. I attempted to make the same change that fixed the OARIS code, by moving the "be_global->get_include_block(which)" function before the switch, but also leaving it after the switch (not commenting out the original). This is a dirty hack that doubles up the included files, but it worked for building OpenDDS and OARIS. I am not suggesting this is a solution, but i thought it was interesting and worth mentioning.

Ultimately I have no fix for the problem, so I do not expect to be making a pull request for this issue.

**Comment by mitza-oci** [comment]
It would be great to have a solution (not just workaround) for TAO bug 2703.  However, I don't think I'll have time to work on that in the near term.

Since you already have a script modifying the IDL, my suggestion is to have the script add 3 lines to the top of the IDL files (either just the impacted ones, or you could go ahead and add it to all).
```
#include <tao/LongSeq.pidl>
#include <tao/StringSeq.pidl>
#include <tao/UShortSeq.pidl>
```
Of course you could also introduce a `#include` of your own header that would contain those lines.
