### ISSUE TITLE
Using OpenDDS Java in Intellij with Gradle

### ISSUE THREAD

**Issue by blakenerdway** [objectcomputing/OpenDDS#837]
I have followed your instructions on how to build OpenDDS for Linux (Ubuntu 14.04) and worked on the "Setting up an OpenDDS Java project" but I am not able to link the libFoo.so to any jar for OpenDDS. The only jar that was compiled was the DDS_Foo_types.jar which contains the readers/writers, etc for the message type, but none of the core OpenDDS.

Is there a jar that I'm missing somewhere?

**Comment by mitza-oci** [comment]
Once you've built a java-enabled OpenDDS, you'll have these files in $DDS_ROOT/lib:
- i2jrt.jar
- OpenDDS_DCPS.jar
- tao_java.jar

**Comment by blakenerdway** [comment]
Great. You can mark as closed
