### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by blakenerdway** [objectcomputing/OpenDDS#838]
I am trying to run the Java example "Foo"in Intellij using Ubuntu 14.04. I have copied the 3 main jars--i2jrt.jar, tao_java.jar, and OpenDDS_DCPS.jar-- for OpenDDS into my ${PROJECT_ROOT}/libs so that I can include them in my gradle.build.

 I also ran the mwc.pl and set the _libout_  in the mpc file  to ${PROJECT_ROOT}/libs.

 I set LD_LIBRARY_PATH in my ~/.bashrc to be ${PROJECT_ROOT}/libs. The Gradle VM arguments and JVM arguments have specified "-Djava.library.path=${PROJECT_ROOT}/libs"

I get no compiler errors. But when I run the code and try to create a new _DomainParticipantFactory_ I receive a runtime error: 
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no OpenDDS_DCPS_Java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at OpenDDS.DCPS.TheParticipantFactory.loadNativeLib(TheParticipantFactory.java:35)
	at OpenDDS.DCPS.TheParticipantFactory.<clinit>(TheParticipantFactory.java:21)
	at main.TestPublisher.main(TestPublisher.java:40)`

**Comment by blakenerdway** [comment]
I just now added another classpath that links to ${DDS_ROOT}/lib for the  `.so`s found there, but run into a different problem: 
`Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/nomads/OpenDDS-3.12/java/dds/libOpenDDS_DCPS_Java.so.3.12.0: libOpenDDS_Dcps.so.3.12.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at OpenDDS.DCPS.TheParticipantFactory.loadNativeLib(TheParticipantFactory.java:35)
	at OpenDDS.DCPS.TheParticipantFactory.<clinit>(TheParticipantFactory.java:21)
	at main.TestPublisher.main(TestPublisher.java:62)`

**Comment by mitza-oci** [comment]
As it says, it's looking for the file `libOpenDDS_Dcps.so.3.12.0`.

**Comment by blakenerdway** [comment]
Yes, but it is looking for it under ${DDS_ROOT}/java.

When the classloader finds `libOpenDDS_DCPS_Java.so` under ${DDS_ROOT}/lib, it finds the versioned .so by running:
`name = file.getCanonicalPath()`
 which turns the name into `${DDS_ROOT}/java/libOpenDDS_Dcps.so.3.12.0` which doesn't exist

**Comment by mitza-oci** [comment]
The JVM needs to load a native library, `OpenDDS_DCPS_Java`, from somewhere.  It has some rules for determining the prefix and suffix, and which directory it's in.  Because you got past the earlier error message, let's assume that part (just finding that file, not loading it) is working properly.

Then the JVM calls the system `dlopen` function, giving it the full path to `libOpenDDS_DCPS_Java.so.$version`.  Now `dlopen` takes over and loads dependent libraries, including libOpenDDS_Dcps.so.  You can use the `ldd` command to do this same thing from the shell.

When I tried this on my system, `ldd` reports that it found the required library in `$DDS_ROOT/lib`.  In my case I believe it used LD_LIBRARY_PATH to locate the required library, but that's not the only way to do it.

**Comment by blakenerdway** [comment]
Sorry for the late reply. Yes, my _ldd_ command also specifies the required library is within _$DDS_ROOT/lib_ 

But when I try to run the code within IntelliJ, it canonicalizes the path to _libOpenDDS_DCPS_Java.so_ from _$DDS_ROOT/lib_ to $DDS_ROOT/java/dds_ which makes no sense.

I cannot figure out if the JVM in IntelliJ just doesn't use the _LD_LIBRARY_PATH_ (which I have set to the lib folder) or there is some other factor at play that I don't know about.

I also tried compiling the code to a jar to see if running it on the JVM of the system instead of IntelliJ would fix the issue, but it still reports the same error. I'm at a loss of what the issue could be

**Comment by blakenerdway** [comment]
UPDATE: I created a new .conf file under /etc/ld.so.conf.d and added _$DDS_ROOT/lib_ as well as _$ACE_ROOT/lib_ to the file (and ran `sudo ldconfig`).

It looks like it is running fine now--just need to start the DCPSInfoRepo so it can find others

**Comment by mitza-oci** [comment]
Glad you got it running.  Since the LD_LIBRARY_PATH setting didn't work, perhaps IntelliJ didn't launch the JVM with that environment.  I'm not an IntelliJ user so I don't know the details of how this works.
