### ISSUE TITLE
Mystery of the "StockQuoterTypeSupportC.h" file?

### ISSUE THREAD

**Issue by krhohio** [objectcomputing/OpenDDS#844]
Hi, I'm new to DDS, OpenDDS and GitHub so please excuse any poor execution...

I'm following the http://opendds.org/about/articles/Article-Intro.html document in attempt to create and execute the "StockQuoter" Example.  This document references a "StockQuoterTypeSupportC.h" file but I don't see any discrete instructions included about how to create it.  I've done both steps shown using the single "opendds_idl..." command line and both the "tao_idl..." command lines but no sign of a "StockQuoterTypeSupportC.h" file from any of these.

I've also entered Issue #843 about this but thought that entering an Issue would also be prudent.

Sincerely,
krhohio

**Comment by mitza-oci** [comment]
`StockQuoterTypeSupportC.h` is generated by running the tool `tao_idl` on input `StockQuoterTypeSupport.idl`.  This is described at the end of the "IDL Types" section, but the name of the file isn't explicitly listed there.  If you'd like to add it, please go ahead and put it in your pull request.

**Comment by krhohio** [comment]
@mitza-oci - Thanks for the fast comment!
I'll add the names of the output files from the tao_idl... lines to the pull request...

Maybe this is an unrelated issue needing (or already having) another issue entry -
but compiling the output files seems to require several .../dds/DdsDcps*.* files
that don't seem to be in OpenDDS-3.12.1, whereas they were in OpenDDS-3.11.1?
(DdsDcpsCoreC.cpp is one example of this)

**Comment by mitza-oci** [comment]
A file like `DdsDcpsCoreC.cpp` belongs to the OpenDDS installation itself, not the example code.  When you build OpenDDS (any version), these files will be generated and compiled.

**Comment by krhohio** [comment]
Sorry, I think I see a common trend here that I'm just learning in DDS 101 class...
The file mentioned above (DdsDcpsCore.cpp) seems to be present in a .gitignore file
and I think that it and the others might be generated by the "opendds_idl" project in Visual Studio?
https://github.com/objectcomputing/OpenDDS/search?utf8=%E2%9C%93&q=DdsDcpsCoreC.cpp&type=

@mitza-oci - Thanks for the above comment - you beat me to it!

**Comment by krhohio** [comment]
As one last question before closing this issue...
Has there been any thought about having these "intermediate/output files" being placed in a seperate folder equivalent to the .../bin and .../lib folders in their context?

**Comment by mitza-oci** [comment]
Did you follow the steps in http://opendds.org/quickstart/GettingStartedWindows.html?

The opendds_idl project compiles a code generation tool called `opendds_idl`.  This tool is then used to create some of the source code that's part of the OpenDDS implementation, and also the source code you need in an application that uses OpenDDS.

Speaking of DDS 101, we have that available: https://objectcomputing.com/training/catalog/middleware/opendds-programming-with-cpp

**Comment by mitza-oci** [comment]
> Has there been any thought about having these "intermediate/output files" being placed in a separate folder equivalent to the .../bin and .../lib folders in their context?

I don't think there's been any requests for that before.  I'm not necessarily opposed to it if someone were to contribute or sponsor work on it.
