### ISSUE TITLE
RTPS_udp not registered

### ISSUE THREAD

**Issue by blakenerdway** [objectcomputing/OpenDDS#845]
When trying to use auto-discovery between peers, I receive an error and cannot figure out why. The symlinks for RTPS and RTPS_UDP (4 total, 2 for each) point to the correct shared objects for RTPS and RTPS_UDP. 

`(7556|140677799872256) TransportRegistry::create_inst: transport_type=rtps_udp is not registered.
(7556|140677799872256) TransportRegistry::load_transport_configuration: Unable to create transport instance in [transport/the_rtps_transport] section.
(7556|140677799872256) ERROR: Service_Participant::load_configuration Unable to locate specified global transport config: $PROJ_ROOT/include/opendds/rtps.ini
(7556|140677799872256) ERROR: Service_Participant::get_domain_participant_factory: load_configuration() failed.`

**Comment by mitza-oci** [comment]
If you set the environment variable ACE_DEBUG=1, you should see ACE's logging including something like:

```
ACE (11903|139843831101248) SG::process_directive, repo=0xcadd20 - dynamic OpenDDS_Rtps_Udp Service_Object * OpenDDS_Rtps_Udp:_make_RtpsUdpLoader()
ACE (11903|139843831101248) SG::process_directives_i, repo=0xcadd20 - dynamic OpenDDS_Rtps_Udp Service_Object * OpenDDS_Rtps_Udp:_make_RtpsUdpLoader()
ACE (11903|139843831101248) - SCG:<ctor=0x7ffc895114a0> - config=0xcadc80 repo=0xcadd20 superseded by repo=0xcadd20
ACE (11903|139843831101248) SG::initialize - repo=0xcadd20, name=OpenDDS_Rtps_Udp - looking up in the repo
ACE (11903|139843831101248) STDG::<ctor>, repo=0xcadd20, name=OpenDDS_Rtps_Udp - beginning at [5]
ACE (11903|139843831101248) LN::open_dll - path=OpenDDS_Rtps_Udp
ACE (11903|139843831101248) SG::process_directive_i, repo=0xcadd20 - OpenDDS_Rtps_Udp, dll=<null>, force=0
ACE (11903|139843831101248) SR::insert - repo=0xcadd20 [5], name=OpenDDS_Rtps_Udp (new) (type=0xcd2470, object=0xcd2430, active=0)
ACE (11903|139843831101248) SG::add_processed_static_svc, repo=0xcadd20 - OpenDDS_Rtps_Udp
ACE (11903|139843831101248) DLL_Handle::open ("libOpenDDS_Rtps_Udp.so", 0x101) -> succeeded: no error
ACE (11903|139843831101248) DLL_Handle::open - OpenDDS_Rtps_Udp (13398960), refcount=1
ACE (11903|139843831101248) DLL_Handle::open - OpenDDS_Rtps_Udp (13398960), refcount=2
ACE (11903|139843831101248) SR::insert - repo=0xcadd20 [5], name=OpenDDS_Rtps_Udp (replacing) (type=0xcc70a0, object=0xcc72c0, active=1)
ACE (11903|139843831101248) ST::fini - destroying name=OpenDDS_Rtps_Udp, dll=(null)
ACE (11903|139843831101248) STDG::<dtor>, repo=0xcadd20 [5], name=OpenDDS_Rtps_Udp - updating dependents [5 - 6)
ACE (11903|139843831101248) DLL_Handle::get_handle: post call: handle valid, refcount 2
ACE (11903|139843831101248) DLL_Handle::get_handle: post call: handle valid, refcount 2
ACE (11903|139843831101248) SR::relocate_i - repo=0xcadd20 [5]: trying name=OpenDDS_Rtps_Udp, handle: 13398960 -> 13398960
ACE (11903|139843831101248) STDG::<dtor>, repo=0xcadd20 [5], name=OpenDDS_Rtps_Udp - loaded (type=0xcc70e0, impl=0xcc70a0, object=0xcc72c0, active=1)
ACE (11903|139843831101248) Dynamic_Node::apply - Did dynamic on OpenDDS_Rtps_Udp (yyerrno=0)
ACE (11903|139843831101248) DLL_Handle::close - OpenDDS_Rtps_Udp (handle=13398960, refcount=1)
ACE (11903|139843831101248) SCG:<dtor=0x7ffc895114a0> - new repo=0xcadd20
```

**Comment by blakenerdway** [comment]
Is there a specific file that ACE uses to look for ACE_DEBUG? I set ACE_DEBUG=1 in ~/.bashrc but did not see anything additional print

**Comment by blakenerdway** [comment]
I am also using this in a Java application, not a native C++--I'm not sure if that makes a difference for this

**Comment by mitza-oci** [comment]
ACE doesn't look in a file, just the environment.  Since the environment is managed by the OS, the choice of programming language doesn't matter.  Did you use the `export` keyword in bashrc?

**Comment by blakenerdway** [comment]
Yes, if I open another terminal (or just `source ~/.bashrc`) and type `echo $ACE_DEBUG` it will print 1 to the console

**Comment by mitza-oci** [comment]
I guess whatever problem you had before with setting the environment in the JVM for LD_LIBRARY_PATH is recurring here.

**Comment by blakenerdway** [comment]
It may be related to another issue. I copied the symlinks from $DDS_ROOT/lib and $ACE_ROOT/lib and copied them to my $projectroot/include along with all the shared objects that those sym links pointed to. Obviously the sym links were broken, so I created a script that edited the sym links to point to the new location of the shared objects. This way I would only need to include a small portion of the OpenDDS project in our git instead of all 2.7GB.
I got the project running using the DCPSInfoRepo (the executable located inside $DDS_ROOT/bin), and had everything connected to the info repo running on `localhost:12345`. Then I tried to use RTPS for connection, and got this error. 
I may have missed a shared object or sym link or something. I will continue to look and update when I figure it out. I posted only to see if there was an 'easy' answer to it :)

**Comment by mitza-oci** [comment]
Did you use `make install` to create an installed development kit?

**Comment by blakenerdway** [comment]
I didn't see that anywhere in the READMe's

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/OpenDDS/blob/60e99a16909522c42980eeac7e44a2243e7347ad/INSTALL#L58

**Comment by blakenerdway** [comment]
Ah thanks! I'll take a look into it. That should fix the issue
