### ISSUE TITLE
Missing libTAO.so.2.2a_p14

### ISSUE THREAD

**Issue by blakenerdway** [objectcomputing/OpenDDS#847]
I did a `make install` and set the prefix to $project_root/opendds. But it looks like it didn't include the libTAO.so.2.2a_p14 shared object. I don't see it in any subfolders after trying to do a find in my `opendds` folder. I do see a 'libtao_java.so.3.12.0' and 'libta_java.so' (that links to the first one). 

When I did `configure --java --prefix=$project_root/opendds` it didn't seem to do anything as I still had to run `export INSTALL_PREFIX=$root_project/opendds` after make, and then call `make install`. Not sure if this makes a different.

**Comment by mitza-oci** [comment]
When you started over with a new `configure`, was that on a completely clean workspace?

**Comment by blakenerdway** [comment]
It was not. I did that and it worked fine. Thanks! Everything is running smoothly.
