### ISSUE TITLE
Help with customized StockQuoter Example build?

### ISSUE THREAD

**Issue by krhohio** [objectcomputing/OpenDDS#848]
Greetings,

I'm new to OpenDDS but have some experience with Visual Studio and so I'm attempting to build the StockQuoter example using a combination of the IDL tools usage specified in  http://opendds.org/about/articles/Article-Intro.html and "native" *.sln and *.vcxproj files as a way to "learn more about how all this works".

My custom "myStockQuoter_Common.vcxproj" successfully builds a "32-bit static lib".
When using this *.lib as an "Additional dependency" to my custom "myStockQuoter_Pub.vcxproj"
the [unresolved external symbol] errors shown below are being generated.

I do have all the "Additional Dependencies" shown in the standard StockQuoter_Common.vcxproj file as well as the corresponding "Additional Library Directories".  Note that if I switch my "myStockQuoter_Common.vcxproj" back to being a DLL then the same [unresolved external symbol] errors appear there when attempting to build it that way.  (i.e. I seem to have a "missing code" issue that is independent of DLL / StaticLib usage)

Any suggestions to eliminate these errors would be greatly appreciated!

Sincerely,
@krhohio

1>------ Build started: Project: myStockQuoter_Pub, Configuration: Debug Win32 ------
1>publisher.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl ORBSVCS_Time::hrtime_to_TimeT(unsigned __int64 &,unsigned __int64)" (__imp_?hrtime_to_TimeT@ORBSVCS_Time@@SAXAA_K_K@Z) referenced in function "unsigned __int64 __cdecl get_timestamp(void)" (?get_timestamp@@YA_KXZ)
1>common_d.lib(StockQuoterTypeSupportImpl.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall OpenDDS::DCPS::DataWriterImpl::register_instance_i(int &,class OpenDDS::DCPS::unique_ptr<class ACE_Message_Block,struct OpenDDS::DCPS::Message_Block_Deleter>,struct DDS::Time_t const &)" (__imp_?register_instance_i@DataWriterImpl@DCPS@OpenDDS@@QAEHAAHV?$unique_ptr@VACE_Message_Block@@UMessage_Block_Deleter@DCPS@OpenDDS@@@23@ABUTime_t@DDS@@@Z) referenced in function "private: int __thiscall OpenDDS::DCPS::DataWriterImpl_T<struct StockQuoter::ExchangeEvent>::get_or_create_instance_handle(int &,struct StockQuoter::ExchangeEvent const &,struct DDS::Time_t const &)" (?get_or_create_instance_handle@?$DataWriterImpl_T@UExchangeEvent@StockQuoter@@@DCPS@OpenDDS@@AAEHAAHABUExchangeEvent@StockQuoter@@ABUTime_t@DDS@@@Z)
1>common_d.lib(StockQuoterTypeSupportImpl.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall OpenDDS::DCPS::DataWriterImpl::write(class OpenDDS::DCPS::unique_ptr<class ACE_Message_Block,struct OpenDDS::DCPS::Message_Block_Deleter>,int,struct DDS::Time_t const &,class OpenDDS::DCPS::GUIDSeq *)" (__imp_?write@DataWriterImpl@DCPS@OpenDDS@@QAEHV?$unique_ptr@VACE_Message_Block@@UMessage_Block_Deleter@DCPS@OpenDDS@@@23@HABUTime_t@DDS@@PAVGUIDSeq@23@@Z) referenced in function "public: virtual int __thiscall OpenDDS::DCPS::DataWriterImpl_T<struct StockQuoter::ExchangeEvent>::write_w_timestamp(struct StockQuoter::ExchangeEvent const &,int,struct DDS::Time_t const &)" (?write_w_timestamp@?$DataWriterImpl_T@UExchangeEvent@StockQuoter@@@DCPS@OpenDDS@@UAEHABUExchangeEvent@StockQuoter@@HABUTime_t@DDS@@@Z)
1>common_d.lib(StockQuoterTypeSupportImpl.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall OpenDDS::DCPS::DataWriterImpl::control_delivered(class OpenDDS::DCPS::unique_ptr<class ACE_Message_Block,struct OpenDDS::DCPS::Message_Block_Deleter> const &)" (__imp_?control_delivered@DataWriterImpl@DCPS@OpenDDS@@UAEXABV?$unique_ptr@VACE_Message_Block@@UMessage_Block_Deleter@DCPS@OpenDDS@@@23@@Z) referenced in function "[thunk]:public: virtual void __thiscall OpenDDS::DCPS::DataWriterImpl::control_delivered`vtordispex{980,52,4294967292,1684}' (class OpenDDS::DCPS::unique_ptr<class ACE_Message_Block,struct OpenDDS::DCPS::Message_Block_Deleter> const &)" (?control_delivered@DataWriterImpl@DCPS@OpenDDS@@$R4DNE@DE@PPPPPPPM@GJE@AEXABV?$unique_ptr@VACE_Message_Block@@UMessage_Block_Deleter@DCPS@OpenDDS@@@23@@Z)
1>common_d.lib(StockQuoterTypeSupportImpl.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall OpenDDS::DCPS::DataWriterImpl::control_dropped(class OpenDDS::DCPS::unique_ptr<class ACE_Message_Block,struct OpenDDS::DCPS::Message_Block_Deleter> const &,bool)" (__imp_?control_dropped@DataWriterImpl@DCPS@OpenDDS@@UAEXABV?$unique_ptr@VACE_Message_Block@@UMessage_Block_Deleter@DCPS@OpenDDS@@@23@_N@Z) referenced in function "[thunk]:public: virtual void __thiscall OpenDDS::DCPS::DataWriterImpl::control_dropped`vtordispex{980,52,4294967292,1684}' (class OpenDDS::DCPS::unique_ptr<class ACE_Message_Block,struct OpenDDS::DCPS::Message_Block_Deleter> const &,bool)" (?control_dropped@DataWriterImpl@DCPS@OpenDDS@@$R4DNE@DE@PPPPPPPM@GJE@AEXABV?$unique_ptr@VACE_Message_Block@@UMessage_Block_Deleter@DCPS@OpenDDS@@@23@_N@Z)
1>common_d.lib(StockQuoterTypeSupportImpl.obj) : error LNK2001: unresolved external symbol "protected: virtual enum OpenDDS::DCPS::SendControlStatus __thiscall OpenDDS::DCPS::DataWriterImpl::send_control(struct OpenDDS::DCPS::DataSampleHeader const &,class OpenDDS::DCPS::unique_ptr<class ACE_Message_Block,struct OpenDDS::DCPS::Message_Block_Deleter>)" (?send_control@DataWriterImpl@DCPS@OpenDDS@@MAE?AW4SendControlStatus@23@ABUDataSampleHeader@23@V?$unique_ptr@VACE_Message_Block@@UMessage_Block_Deleter@DCPS@OpenDDS@@@23@@Z)
1>C:\Users\kent.hamon.ctr\Documents\Working\16.05-ABSAA-khamon-opendds\mydoxygen\OpenDDS\byExample\StockQuoter\bin\pub.exe : fatal error LNK1120: 6 unresolved externals
1>Done building project "myStockQuoter_Pub.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by mitza-oci** [comment]
A DLL needs the complete list of libraries it depends on.  We recommend using MPC to generate your projects from simple and cross-platform build description files.  If you'd like to make your own projects, see one of the large number of examples in the OpenDDS source code tree for what those projects need to include.  An example DLL would be the project DDS_Messenger_Idl in %DDS_ROOT%\tests\DCPS\Messenger.
