### ISSUE TITLE
ERROR: Can't extract ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip...

### ISSUE THREAD

**Issue by krhohio** [objectcomputing/OpenDDS#849]
After cloning and switching to the DDS-3.12.2 tag I ran configure from the VS2017 Command Prompt and received the following output:
```
C:\...\3.12.x-OpenDDS>configure
Downloading ACE+TAO 2.2a with latest patches
Extracting archive ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip
ERROR: Can't extract ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip, extract it to C:/.../Working/3.12.x-OpenDDS
and run this script again.
Stopped at configure line 615.
```
I used 7zip to successfully extract the Zip contents but I'm wondering if  perhaps the non-existence of the (literal) Windows Zip program caused the above ERROR?  But then I think that Windows 10 has a build-in Zip capability?  Maybe I don't have *.zip files configured to open with my 7zip program?

**Comment by krhohio** [comment]
In addition I received the following output after extracting the Zip using 7zip:
(i.e. same error as above even though the files have been extracted)

` Directory of C:\Users\Kent\Documents\Working\3.12.x-OpenDDS

04/14/2018  10:37 PM        58,647,557 ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip
               1 File(s)     58,647,557 bytes
               0 Dir(s)  177,205,264,384 bytes free

C:\Users\Kent\Documents\Working\3.12.x-OpenDDS>
C:\Users\Kent\Documents\Working\3.12.x-OpenDDS>configure
Extracting archive ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip
ERROR: Can't extract ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip, extract it to C:/Users/Kent/Documents/Working/3.12.x-OpenDDS
and run this script again.
Stopped at configure line 615.`

**Comment by mitza-oci** [comment]
The configure script is working as designed.  If you'd like to contribute changes to it, of course we're open to that.
