### ISSUE TITLE
Use RTPS disc cross network segment

### ISSUE THREAD

**Issue by zdftju** [objectcomputing/OpenDDS#854]
hi:
I use the rtps discovery model between two computers named A and B, the two is in different network segment。The A node sends data and the B node  receives data。When the A and B nodes are started,there is no reaction to the B node. If the SpdpSendAddrs=receiver IP address:port number is added to the profile,the B node listener prompts "on_subscription", and no data can be received.
The proFile example lists bellow,thank you for help!
[common]
DCPSDebugLevel=10
DCPSTransportDebugLevel=5
ORBVerboseLogging=1
DCPSDefaultDiscovery=rtpsdisc
DCPSGlobalTransportConfig=rtpsconfig

[rtps_discovery/rtpsdisc]
ResendPeriod=5
SedpMulticast=0

[config/rtpsconfig]
transports=rtps_transport
[transport/rtps_transport]
transport_type=rtps_udp

**Comment by mitza-oci** [comment]
Try adding `use_multicast=0` to the [transport/*] section.

**Comment by zdftju** [comment]
it still doesn't work ,  does any special properties need to be set except the configurations below?
[common]
DCPSDebugLevel=10
DCPSTransportDebugLevel=5
ORBVerboseLogging=1
DCPSDefaultDiscovery=rtpsdisc
DCPSGlobalTransportConfig=rtpsconfig

[rtps_discovery/rtpsdisc]
ResendPeriod=5
SedpMulticast=0

[config/rtpsconfig]
transports=rtps_transport
[transport/rtps_transport]
transport_type=rtps_udp
use_multicast=0

**Comment by mitza-oci** [comment]
From your previous message I thought that you were using SpdpSendAddrs.  Is this still true?  Do the logs indicate that discovery is working?

**Comment by zdftju** [comment]
@mitza-oci if we use the SpdpSendAddrs, it Indeed works , but we have to specify the endpoinds Manually  , thus it seems to lose the automatically discovered ability  isn't it ? I am new about RTPS and I don't know much about RTPS  yet , I really don't know why this would happened , seek for your help , thanks !

**Comment by mitza-oci** [comment]
You can read more about RTPS in the OpenDDS Developer's Guide and the OMG DDSI-RTPS specification, both linked from http://opendds.org/documents/

Since RTPS Discovery is a peer-to-peer discovery system using multicast, you will need to either specify the unicast address manually or route multicast traffic between the two network segments.  Another option would be to use DCPSInfoRepo Discovery.

**Comment by zdftju** [comment]
@mitza-oci 
I have tryed the DCPSInfoRepo Discovery , but there is a problem at discoverying stage. Here is the scene:
A 、B、C three hosts，InfoRepo start at host A, and then I start 5 processes per host totally 15 processes at the same time, every process publishes 20 topics and also subscribe the 20 topics, that I find sometimes one of the processes would dead at the OpenDDS_InfoRepoDiscovery.dll , I debuged the dll into the InfoC.cpp at "DCPSInfo::add_publication()" function, finally I find it dead at "_tao_call.invoke()", then I continue to debug the TAO.dll , it dead at "Synch_Twoway_Invocation::wait_for_reply() "

**Comment by mitza-oci** [comment]
Please create a new GitHub Issue and include the relevant stack traces, log files, and source code required to reproduce the problem.
