### ISSUE TITLE
Generated typedefs not found

### ISSUE THREAD

**Issue by krhohio** [objectcomputing/OpenDDS#861]
Greetings,
I have two different OpenDDS implementations - one 3.11.1 and the other is the 3.12.1 version.

The "// TAO_IDL - Generated from..." as shown in the "*TypeSupportC.h" files are:
3.11.1 = c:\...\opendds-dds-3.11.1\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38
3.12.1 = c:\...\opendds-3.12.1\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

I'm wondering why the "module_ch.cpp" vs "be_visitor_arg_traits.cpp" file difference:
The root cause for this inquiry is that the 3.12.1 implementation is complaining about not finding:
the typedefs for ...MessageSequenceType; ...TypeSupportType; ...DataWriterType; and ...DataReaderType;

Any suggests would be appreciated,
@krhohio

**Comment by mitza-oci** [comment]
Let's focus on that "root cause for this inquiry" part.  Please post the error messages you see along with all relevant details for your build.

**Comment by krhohio** [comment]
Adam,
Thanks for the fast reply - I'm out-of-town for the rest of the week and will not have access to the computer involved - but will provide the details early next week.
Kent

**Comment by krhohio** [comment]
My appologies for being slow with this this reply (see above) but this concatenated screen shot should show the "wavy red underscored" [error C2039's (red underscored typedef) is not a member of Eaagles::OpenDds] as well as the use of opendds_idl.exe version 3.12.1 (ACE version 6.2a_p14).
![versions and undefined typedef s](https://user-images.githubusercontent.com/5304327/39709797-dc5efb7c-51e8-11e8-96a5-c95bfaa72a98.jpg)

**Comment by mitza-oci** [comment]
I can't tell what's going on here.  Visual Studio has an "Output" tab that appears at the bottom (not the "Error List"), that has the output from the compiler.  Please copy and paste the plaintext of the relevant section of compiler output.

**Comment by krhohio** [comment]
Here's the VS2017 Output Tab entries corresponding to the "red underscores" line number section shown above:
1>------ Build started: Project: OpenDDS (DDS\OpenDDS), Configuration: Debug Win32 ------
1>PfdTopicInterface.cpp
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(90): error C2039: 'pfdMessageSeq': is not a member of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(80): note: see declaration of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(90): error C3646: 'MessageSequenceType': unknown override specifier
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(90): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(91): error C2039: 'pfdMessageTypeSupport': is not a member of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(80): note: see declaration of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(91): error C3646: 'TypeSupportType': unknown override specifier
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(91): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(93): error C2039: 'pfdMessageDataWriter': is not a member of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(80): note: see declaration of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(93): error C3646: 'DataWriterType': unknown override specifier
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(93): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(94): error C2039: 'pfdMessageDataReader': is not a member of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(80): note: see declaration of 'Eaagles::OpenDds'
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(94): error C3646: 'DataReaderType': unknown override specifier
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(94): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\kent...castsopendds\idl\outputs\pfdtypesupportimpl.h(113): error C2065: 'pfdMessageTypeSupport': undeclared identifier

**Comment by mitza-oci** [comment]
The declaration of the sequence type comes from the corresponding *TypeSupport.idl and the C++ code generated from it.  You should have a file named PfdTypeSupport.idl, which itself is generated, that contains `typedef sequence<Module::SomeType> SomeTypeSeq;`.  From that, the IDL compiler generates in PfdTypeSupportC.h `typedef ImplementationDefinedTemplate<ImplementationDefinedArgs> SomeTypeSeq` which is used by the code you've shown.

The process of generating code from OpenDDS IDL is described in the Developer's Guide in section 2.1.2.

**Comment by krhohio** [comment]
Thanks for the inputs...
I think that we have now circled around to my original entry questioning the "tao_idl" usage of
...\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp
vs
...\\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp

I've now noticed that my "working code" generates the desireable code after the "TAO_IDL - Generated from ...module_ch.cpp" whereas my "non-working code" after the "TAO_IDL -Generated from ...be_visitor_arg_traits.cpp" just suspiciously contains the lines:
TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL

I've been using a #pragma DCPS_DATA_TYPE... line and just tried adding a #pragma DCPS_DATA_KEY... 
line to see if that made any difference in the code generated (it did not).

The "working code" "...desireable code" mentioned above contains a "nested namespace" (i.e. module) definition similar to that used in the "non-working code" so I don't think that is an issue.

Am I missing any similar critical "single lines of code" that might be causing this issue?

**Comment by krhohio** [comment]
Or maybe a problem with me using:
namespace Eaagles {
namespace OpenDds { ....

when generated code is using:
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {namespace DCPS {...

i.e. would my OpenDds conflict with OpenDSS?

**Comment by mitza-oci** [comment]
> would my OpenDds conflict with OpenDDS?

I wouldn't think so, since C++ is case sensitive.  But you may want to avoid calling things in your codebase OpenDDS (with any spelling) since that's bound to be confusing.

I don't have an answer for you on the details of the TAO IDL compiler.  We generally treat it as a black box in this project (though of course we maintain it in other projects).   If you're not getting the expected results you should check that all of the steps match what's described in the documentation and what the included test and example projects do.  If you are not generating the VC++ project with MPC I highly recommend you do so.  If you send the steps to reproduce the problem we can try to narrow it down here.

**Comment by krhohio** [comment]
@mitza-oci, Thanks for your patience with my questions!

I think that there was an issue with me using the namespace OpenDds;
as changing it to something else (or something else during this process)
caused the *TypeSupportC.h file to be generated with the expected code!

I'll be out-of-office again, until the end of the week, but will try to modify
one of the OpenDDS example programs to either confirm or deny.

Thanks Again,
Kent
