### ISSUE TITLE
Seek for help: Communicate between 192.168.1.2 and 192.168.2.3 with RTPS?

### ISSUE THREAD

**Issue by sandshaw** [objectcomputing/OpenDDS#881]
hi,
  how could i make it? 
  I have two applications, publisher and subscriber. Publisher's IP is "192.168.1.2" runs on machine A and subscriber's IP is "192.168.2.3" runs on machine B. 
  1. A and B can ping successfully
  2. A and B can match each other
  but the subscriber cannot recevice the publisher's data. thanks

**Comment by mitza-oci** [comment]
Does point 2 above mean that discovery completed successfully?

Are you using an .ini file to configure OpenDDS?  If so, please paste relevant contents here.

Any errors in the debug logs?
