### ISSUE TITLE
about DCPS_DATA_KEY

### ISSUE THREAD

**Issue by tilongzs** [objectcomputing/OpenDDS#887]
I modified the project in the DevGuidExamples/DCPS/Messager directory to use as this example.
When you run Publisher, two samples are published, in which the mssaeg.subject_id of each sample is unchanged, and the messages.count generates a random number. Run two Publisher processes one after the other, don't close, and then run Subscriber, then Subscriber will get two samples instead of the expected one.
QoS policies have been set as follows:
dataWriterQos.resource_limits.max_instance = 1;
dataWriterQos.resource_limits.max_samples = 1;
dataWriterQos.resource_limits.max_samples_per_insance = 1;

The address of the test project is:
https://github.com/tilongzs/opendds_error_test

**Comment by mitza-oci** [comment]
What does "releasing ID data" mean?  It would help if you would share your test code using the same format as the OpenDDS test suite (under tests/DCPS in the repository).

**Comment by tilongzs** [comment]
I re-described the problem and wrote a test case.

**Comment by mitza-oci** [comment]
Your comment refers to the dataWriterQos but perhaps more interesting is the dataReaderQos.  In this test it doesn't matter that the max_samples is 1 in the DataReader.  When using a listener, the application is notified of the first sample (whichever one that happens to be), and the listener implementation removes that sample from the DataReader before the next sample arrives.
