### ISSUE TITLE
About the Release version of RTPS

### ISSUE THREAD

**Issue by tilongzs** [objectcomputing/OpenDDS#889]
I compiled the Release version of the project DevGuidExamples/DCPS/Messager and started Publisher via RTPS, but TheParticipantFactoryWithArgs returned NULL. The Release version of a test project I created myself is the same problem.
There is also no error in the path to the rtps.ini file (I also tested the absolute path).
The Debug version is working fine. In addition, the Release version of the DCPS method of this project is no problem.

> publisher.exe -DCPSConfigFile rtps.ini

**Comment by mitza-oci** [comment]
Was there anything logged from the OpenDDS implementation?  Is debug logging enabled (section 7.5 of the developer's guide)?

Also note that mixing Debug and Release binaries in the same process is not supported.

**Comment by tilongzs** [comment]
> TransportRegistry::create_inst: transport_type=rtps_udp is not registtered.
> TransportRegistry::load_transport_configuration: Unable to create transport instance in [transport/the_rtps_transport] section.
> ERROR: Services_Participant::load_configuration Unable to locate specified global transport config: rtps.ini
> ERROR: Service_Participant::get_domain_participant_factory: load_configuration() failed.
> ERROR: Publisher.cpp:40: main() - TheParticipantFactoryWithArgs failed!

**Comment by mitza-oci** [comment]
The library `OpenDDS_Rtps_Udp.dll` was not loaded.  If it worked in Debug, the corresponding library was `OpenDDS_Rtps_Udpd.dll` so make sure that the Release library and all of its dependencies are available.
