### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by 360CodeSafe** [objectcomputing/OpenDDS#894]
dds/InfoRepo/PersistenceUpdater.cpp  in line 1065

int
PersistenceUpdaterSvc_Loader::init()
{
  return ACE_Service_Config::process_directive
         (ace_svc_desc_PersistenceUpdaterSvc);
  return 0;  //Dead code
}

**Comment by jwillemsen** [comment]
Please open a pull request that removes the dead code

**Comment by mitza-oci** [comment]
Fixed in e13244aee30d28128920ba184e2a17eb5ff205dc
