### ISSUE TITLE
Port to clang-based Android NDK

### ISSUE THREAD

**Issue by pepijndevos** [objectcomputing/OpenDDS#895]
I'm trying to build OpenDDS for Android, so first I made a toolchain:

    make_standalone_toolchain.py --arch arm --api 28 --stl=libc++ --install-dir ~/Android/toolchain28

Then I added that toolchain to the path, and configured the project as follows:

    ./configure --target linux-cross --target-compiler arm-linux-androideabi-clang++

This completes without errors, but does print out that it skipped several things, such as

    Skipping TAO_IDL_GEN (tao_idl_fe.mpc); it requires tao_idl_fe_gen.

Then I run `make` and I get the following error

```
make[2]: Entering directory '/home/rove/code/android/OpenDDS-master/build/target/ACE_wrappers/TAO/tao/Messaging'

GNUmakefile: /home/rove/code/android/OpenDDS-master/build/target/ACE_wrappers/TAO/tao/Messaging/GNUmakefile.Messaging_Idl MAKEFLAGS=w

make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'ExceptionHolderC.cpp'.  Stop.
make[2]: Leaving directory '/home/rove/code/android/OpenDDS-master/build/target/ACE_wrappers/TAO/tao/Messaging'
GNUmakefile.dist:566: recipe for target 'Messaging_Idl' failed
make[1]: *** [Messaging_Idl] Error 2
make[1]: Leaving directory '/home/rove/code/android/OpenDDS-master/build/target'
GNUmakefile:3: recipe for target 'all' failed
make: *** [all] Error 2

```
For comparison, a native build finishes without problems.

**Comment by jwillemsen** [comment]
In case of cross compilation the taoidl compiler should have been build statically in a host tree by the script, do you have a full build log from the start?

**Comment by mitza-oci** [comment]
Could be a bug, try moving the line CROSS-COMPILE=1 from user_macros.GNU to platform_macros.GNU in ACE.  This should apply to any ACE/TAO/OpenDDS project, not just to OpenDDS.

**Comment by pepijndevos** [comment]
I tried your suggestion, but no change.
Full build log: https://paste.ubuntu.com/p/bfMVHt9mTt/

**Comment by mitza-oci** [comment]
As far as I can tell, the dependency is conditional on the CROSS-COMPILE variable.  Did you change it in build/target?

I don't doubt there's a problem somewhere but I'm not sure yet where it is.  Please post all generated configuration files so we can see the state of the build.  I wrote a script that's included in OpenDDS for this, it's tools/scripts/show_build_config.pl.

I think the reason that there's a problem here is that we haven't tried this exact build configuration before.  Here's why:
- ACE's configuration system considers android a separate platform, not just an embedded Linux.  Our CI build uses this.
- OpenDDS's configure script doesn't have support for android so your build is treating at as an embedded Linux.

**Comment by mitza-oci** [comment]
Also the configuration is bad since compiling in build/target is using the host g++ and not the cross compiler.

**Comment by pepijndevos** [comment]
So what is "correct", using the ACE "android" target, or just using embedded linux?
Is there anything I did wrong in my setup why it did not use  `--target-compiler arm-linux-androideabi-clang++`?

**Comment by mitza-oci** [comment]
Our CI build for android uses this:
```
================ config.h ================
#include "ace/config-android.h"
================ default.features ================
cross_compile=1
================ platform_macros.GNU ================
debug=1
optimize=0
build_tao_idl_be=0
ANDROID_ABI=armeabi-v7a
HOST_ROOT=/directory/of/host/ACE
include $(ACE_ROOT)/include/makeinclude/platform_android.GNU
================ user_macros.GNU ================
OPENDDS_IDL=/directory/of/opendds_idl
```

**Comment by pepijndevos** [comment]
This is a fresh download with the steps outlines in the original post.
No further changes made.

Can I just download the pre-built binaries rather than going through this mess? I don't see anything on your downloads page about binaries.

Can I just overwrite these files you mentioned with these variables, or can I pass something to `./configure` to get the correct configuration?
```
Host Build:
================ setenv.sh ================
# OpenDDS configure script: ./configure --target linux-cross --target-compiler arm-linux-androideabi-clang++
export CIAO_ROOT=unused
export DANCE_ROOT=unused
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export PATH=${PATH}
export TAO_ROOT=/home/rove/code/android/OpenDDS-master/build/host/ACE_wrappers/TAO
export ACE_ROOT=/home/rove/code/android/OpenDDS-master/build/host/ACE_wrappers
export MPC_ROOT=/home/rove/code/android/OpenDDS-master/ACE_wrappers/MPC
export DDS_ROOT=/home/rove/code/android/OpenDDS-master/build/host
================ platform_macros.GNU ================
static_libs_only = 1
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
================ config.h ================
#include "ace/config-linux.h"
Target Build:
================ setenv.sh ================
# OpenDDS configure script: ./configure --target linux-cross --target-compiler arm-linux-androideabi-clang++
export PATH=${PATH}:/home/rove/code/android/OpenDDS-master/build/host/ACE_wrappers/bin:/home/rove/code/android/OpenDDS-master/build/host/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/rove/code/android/OpenDDS-master/build/target/ACE_wrappers/lib:/home/rove/code/android/OpenDDS-master/build/target/lib
export HOST_ACE=/home/rove/code/android/OpenDDS-master/build/host/ACE_wrappers
export TAO_ROOT=/home/rove/code/android/OpenDDS-master/build/target/ACE_wrappers/TAO
export DDS_ROOT=/home/rove/code/android/OpenDDS-master/build/target
export ACE_ROOT=/home/rove/code/android/OpenDDS-master/build/target/ACE_wrappers
export MPC_ROOT=/home/rove/code/android/OpenDDS-master/ACE_wrappers/MPC
export CIAO_ROOT=unused
export DANCE_ROOT=unused
export HOST_DDS=/home/rove/code/android/OpenDDS-master/build/host
================ user_macros.GNU ================
OPENDDS_IDL = $(HOST_DDS)/bin/opendds_idl
OPENDDS_IDL_DEP = $(OPENDDS_IDL)$(HOST_EXE_EXT)
IDL2JNI = $(HOST_DDS)/bin/idl2jni
IDL2JNI_DEP = $(IDL2JNI)$(HOST_EXE_EXT)
CROSS-COMPILE = 1
================ default.features ================
no_cxx11=0
cross_compile=1
================ platform_macros.GNU ================
optimize = 0
TAO_IDL = $(HOST_ACE)/bin/tao_idl
TAO_IDL_DEP = $(TAO_IDL)
TAO_IDL_PREPROCESSOR = g++
TAO_IDLFLAGS += -g $(HOST_ACE)/bin/ace_gperf
build_tao_idl_be = 0
LDFLAGS += -Wl,-rpath-link,$(ACE_ROOT)/lib
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
CC = g++
CXX = g++
LD = g++
================ config.h ================
#include "ace/config-linux.h"
```

**Comment by mitza-oci** [comment]
> Can I just download the pre-built binaries rather than going through this mess? I don't see anything on your downloads page about binaries.

We do not provide binaries in general.  We provide all of the code that implements DDS, RTPS, and DDS-Security for C++ and Java applications under an open source license.  We also provide [docker images](http://opendds.org/quickstart/GettingStartedDocker.html).  We can do custom builds as part of our commercial support services.

> Can I just overwrite these files you mentioned with these variables

Yes, just make sure to remove any generated files from previous attempts (like .o files).

> or can I pass something to ./configure to get the correct configuration?

Not that I know of, but I haven't tried it yet.  Since this is a new use case for the configure script I'd suggest getting it going first with manual configuration, then enhancing `configure` by adding a new entry to `%platforminfo`.

**Comment by pepijndevos** [comment]
These are the steps a master student at my university took to compile for Android. I'm not convinced it's entirely correct, but it may be helpful. [qin2017msc.pdf](https://github.com/objectcomputing/OpenDDS/files/2287457/qin2017msc.pdf)

In your example, is `ANDROID_ABI` the prefix for the compiler? Because you don't set `CXX` anywhere.
What is `HOST_ROOT` supposed to point to? My best guess would be `build/host/ACE_wrapper`?

I'm currently getting
```
build/target/ACE_wrappers/ace/os_include/os_ucontext.h:40:13: error: typedef redefinition with different types
      ('int' vs 'struct ucontext')
typedef int ucontext_t;

toolchain28clang/bin/../sysroot/usr/include/sys/ucontext.h:101:3: note: previous definition is here
} ucontext_t;

```

**Comment by mitza-oci** [comment]
> In your example, is ANDROID_ABI the prefix for the compiler?

It is used by ACE's platform_android.GNU.

> What is HOST_ROOT supposed to point to?

HOST_ROOT is the ACE_ROOT directory of the host build (may be named ACE_wrappers or just ACE, depending on the version and if you get it from git or from an archive/package).

> [... error message from ucontext...]

Step A.1.8 of the PDF seems to address that one.

Please consider contributing ACE and OpenDDS changes as pull requests, we'll make sure they get integrated.

**Comment by pepijndevos** [comment]
> It is used by ACE's platform_android.GNU.
```
$ git grep ANDROID_ABI
$ grep -R ANDROID_ABI .
$ 
```
I don't see any mention of this. The file does mention that it needs several environment variables related to the NDK, but I don't see you setting these in your file.

It also sets `CROSS-COMPILE` to `arm-linux-androideabi-`, which I hope will eventually set `CXX` somewhere. Although the only place where I can see that happening is in some `g++` code, while for android you'd definitely want `clang++`

**Comment by pepijndevos** [comment]
I made several changes to ACE, but it does not appear to have a nice Github page or anything where I can send my PR. It seems Android support in ACE is quite dated, because It only supports API versions 8 and 9, while mine is 28.

First of all, GCC is deprecated on Android, so in `platfrom_android.GNU` I changed the following line

    include $(ACE_ROOT)/include/makeinclude/platform_clang_common.GNU

but `platform_clang_common.GNU` is unaware of `CROSS_COMPILE`, so I copied that chunk of code from `platform_g++_common.GNU`, replacing `gcc` and `g++` as needed.

That caused the right compiler to be used, but I ran again into the aforementioned errors. But instead of taking the hammer to the code is question I added the following macros to `config-android.h`

```
#elif __ANDROID_API__ == 28
# define ACE_HAS_UCONTEXT_T
# define ACE_HAS_CPU_SET_T
# undef ACE_LACKS_FD_MASK
```

This got me a bit further, but now I'm facing the following error:

```
../../tao/Any_Insert_Policy_T.h:44:14: error: no viable overloaded '<<='
        (*p) <<= x;
        ~~~~ ^   ~
../../tao/PortableServer/Object_SArgument_T.cpp:120:25: note: in instantiation of member
      function 'TAO::Any_Insert_Policy_Stream<CORBA::Object *>::any_insert' requested
      here
  Insert_Policy<S_ptr>::any_insert (any, this->x_.in ());
                        ^
Servant_Base.cpp:288:47: note: in instantiation of member function
      'TAO::Ret_Object_SArgument_T<CORBA::Object *, TAO_Pseudo_Var_T<CORBA::Object>,
      Any_Insert_Policy_Stream>::interceptor_value' requested here
  TAO::SArg_Traits< ::CORBA::Object>::ret_val retval;
                                              ^
../../tao/AnyTypeCode/Any.h:96:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'CORBA::Any::from_boolean' (aka
      'ACE_OutputCDR::from_boolean') for 1st argument
    void operator<<= (from_boolean);
         ^
../../tao/AnyTypeCode/Any.h:97:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'CORBA::Any::from_char' (aka
      'ACE_OutputCDR::from_char') for 1st argument
    void operator<<= (from_char);
         ^
../../tao/AnyTypeCode/Any.h:98:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'CORBA::Any::from_wchar' (aka
      'ACE_OutputCDR::from_wchar') for 1st argument
    void operator<<= (from_wchar);
         ^
../../tao/AnyTypeCode/Any.h:99:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'CORBA::Any::from_octet' (aka
      'ACE_OutputCDR::from_octet') for 1st argument
    void operator<<= (from_octet);
         ^
../../tao/AnyTypeCode/Any.h:100:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'CORBA::Any::from_string' (aka
      'ACE_OutputCDR::from_string') for 1st argument
    void operator<<= (from_string);
         ^
../../tao/AnyTypeCode/Any.h:101:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'CORBA::Any::from_wstring' (aka
      'ACE_OutputCDR::from_wstring') for 1st argument
    void operator<<= (from_wstring);
         ^
../../tao/AnyTypeCode/Any.h:171:10: note: candidate function not viable: no known
      conversion from 'CORBA::Object *const' to 'unsigned char' for 1st argument
    void operator<<= (unsigned char);
         ^
```

**Comment by jwillemsen** [comment]
The DOC Group version of ACE/TAO is available at https://github.com/DOCGroup/ACE_TAO, that has support newer Android versions.

Switching to clang should be done based on the NDK version, older versions do support gcc

**Comment by jwillemsen** [comment]
The configure script has an option --doc_group but that will download an older version, not the most recent code, probably it is best to clone ACE_TAO and do a git checkout directly so that you can easily propose some PRs

**Comment by jwillemsen** [comment]
For the Any errors try to add the following to your config-android.h file:
```

#ifdef __clang__
# define ACE_ANY_OPS_USE_NAMESPACE
#endif /* __clang__ */

```

**Comment by mitza-oci** [comment]
@jwillemsen:
>  but that will download an older version

Are there changes after 2.5.1 that are relevant?

**Comment by jwillemsen** [comment]
@mitza-oci No changes after 2.5.1 but when he uses a stable release it will download the ACE/TAO release that we validated at that moment

**Comment by pepijndevos** [comment]
So DOC group's ACE also only supports GCC. When I make a GCC toolchain, I get a deprecation warning, and weird missing includes. So pretty much ACE does not support clang properly, and Android does not support GCC properly anymore.

Android API 16 with gnustl gives

    fatal error: bits/c++config.h: No such file or directory

Android API 16 with libstl++ gives another missing include, `stddefs.h` IIRC, because Clang's libstl++ is just not compatible with GCC it seems. Marked as wontfix upstream, IIRC.

I guess the only way forward *right now* is to use an old NDK with non-broken GCC support. But indeed as the title suggests, the long term solution is to support Clang on Android.

**Comment by jwillemsen** [comment]
clang on Linux does work, maybe you can check there what defines we set

**Comment by mitza-oci** [comment]
Please open an issue in https://github.com/DOCGroup/ACE_TAO
