### ISSUE TITLE
Can not Edit TiddlyWikis

### ISSUE THREAD

**Issue by iguessthislldo** [objectcomputing/OpenDDS#926]
Tangential to #618 

After editing the monitor documentation for #924 I discovered I can't save the result (In Chrome or Firefox). They both produce this error:

> It's not possible to save changes. Possible reasons include:
> - your browser doesn't support saving (Firefox, Internet Explorer, Safari and Opera all work if properly configured)
> - the pathname to your TiddlyWiki file contains illegal characters
> - the TiddlyWiki HTML file has been moved or renamed

Using the [tiddlywiki.com](https://tiddlywiki.com/) I can do it for their site, so I'm thinking the wikis need to be upgraded. This could be done through [https://tiddlywiki.com/upgrade.html](https://tiddlywiki.com/upgrade.html) but it results in this error:

> It looks like you are trying to load a plugin designed for TiddlyWiki Classic. Please note that these plugins do not work with TiddlyWiki version 5.x.x. TiddlyWiki Classic plugins detected:
>
> - PublishMacro

I think I could rip that plugin out manually and try again but probably not in the time I have before I checkout for today.

Alternatively we could rewrite them in Markdown which I'm in favor of.

**Comment by mitza-oci** [comment]
> Alternatively we could rewrite them in Markdown which I'm in favor of.

As long as it can be done in a relatively short time, I don't have a problem with this.  Seems like it would be easier to maintain going forward.

**Comment by iguessthislldo** [comment]
I  was going to close this issue on my own because of #1008, but decided to see if there was anymore TiddlyWikis, and there is one last one: [tools/modeling/docs/user_guide](https://github.com/objectcomputing/OpenDDS/tree/master/tools/modeling/docs/user_guide).

**Comment by mitza-oci** [comment]
> I was going to close this issue on my own because of #1008, but decided to see if there was anymore TiddlyWikis, and there is one last one: [tools/modeling/docs/user_guide](https://github.com/objectcomputing/OpenDDS/tree/master/tools/modeling/docs/user_guide).

- [ ] tools/excelRTD/doc/userguide.html
- [ ] tools/modeling/docs/user_guide/index.html
- [ ] tools/modeling/docs/design_notes/codegen.html
- [ ] tools/modeling/docs/design_notes/plugins.html
- [ ] tools/monitor/doc/userguide.html
- [ ] performance-tests/Bench/doc/userguide.html

Modeling info may already be in the DevGuide.  Bench may be taken care of by the project that Tim's working on.

**Comment by iguessthislldo** [comment]
> Modeling info may already be in the DevGuide.

The `user_guide/index.html` has nothing of value in and can be deleted, so the devguide is the only place that has that information.

**Comment by iguessthislldo** [comment]
As previously discussed, `tools/modeling/docs/design_notes/plugins.html` can stay how it is for now as it shouldn't need to be edited. A partial conversion had been started [here](https://github.com/iguessthislldo/OpenDDS/blob/igtd/model_design_convert/tools/modeling/docs/design_notes/plugins.md) though. `performance-tests/Bench/doc/userguide.html` will be deleted at some point along with the rest of the bench when it is replaced. Because #1203 was merged, this issue can now be closed.
