### ISSUE TITLE
Entity reference count is not decreased in the TopicDescriptionImpl when deleting a data reader

### ISSUE THREAD

**Issue by jmmorato** [objectcomputing/OpenDDS#935]
The entity_refs_ is not drecreased when calling `delete_datareader`, therefore when trying to call `delete_topic` I receive `RETCODE_PRECONDITION_NOT_MET`.

Similar in the `delete_contentfilteredtopic`, in this case is drecreased for the related topic but never for the filtered topic.

On the other hand, the `delete_multitopic` never increase the reference count for the multitopic itself (It does for the related topics), therefore I never receive `RETCODE_PRECONDITION_NOT_MET` even if I didn't delete the data reader.

Attached a fix proposal.
[Patches.zip](https://github.com/objectcomputing/OpenDDS/files/2407919/Patches.zip)

**Comment by iguessthislldo** [comment]
This was actually something I discovered yesterday and was going to be working on soon. It would be great if you opened a pull request with the patches you made so tests can be run with it.
