### ISSUE TITLE
OpenDDS security couldn't work in WAN

### ISSUE THREAD

**Issue by redrabit** [objectcomputing/OpenDDS#937]
I try to use OpenDDS SSL in WAN communication.
If I use rtps_uni.ini just no security, It work properly in WAN. But, when I use rtps_disc_sec.ini, It dosen't work! 
If I use rtps_disc_sec.ini configuration file, they can't discovery each other in WAN. (After packet capture by wireshark, I found that they do not communicate through GIOP protocol)
 How can I communicate two hosts using SSL in WAN?? Here is my communicate command:

Host A

```
$DCPSInfoRepo -ORBListenEndpoints iiop://:12345
$./publisher -DCPSInfoRepo HostA's IP:12345 -DCPSConfigFile rtps_disc_sec.ini

```
HostB

`$./subscriber -DCPSInfoRepo HostA's IP:12345 -DCPSConfigFile rtps_disc_sec.ini`

And follow is HostA's rtps_disc_sec.ini's contents:

> [common]
> DCPSGlobalTransportConfig=$file
> DCPSSecurity=1
> 
> [domain/4]
> DiscoveryConfig=uni_rtps
> 
> [rtps_discovery/uni_rtps]
> SedpMulticast=0
> ResendPeriod=2
> 
> [transport/the_rtps_transport]
> transport_type=rtps_udp
> use_multicast=0
> local_address=HostA's IP:56789

Follow is HostB's rtps_disc_sec.ini's contents:

> [common]
> DCPSGlobalTransportConfig=$file
> DCPSSecurity=1
> 
> [domain/4]
> DiscoveryConfig=uni_rtps
> 
> [rtps_discovery/uni_rtps]
> SedpMulticast=0
> ResendPeriod=2
> 
> [transport/the_rtps_transport]
> transport_type=rtps_udp
> use_multicast=0
> local_address=HostB's IP:55555

Please give me any idea to solve this problem.

**Comment by mitza-oci** [comment]
Is this distinct from #934?

**Comment by redrabit** [comment]
No, It is same thing.
