### ISSUE TITLE
Std string/wstring extraction should make use of contiguous memory with c++11

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#942]
With c++11 and newer std::(w)string contain contiguous memory, the serialization could make use of this on extraction

**Comment by jwillemsen** [comment]
See #672

**Comment by mitza-oci** [comment]
I think it's already done for narrow strings.  Wide strings may need more work, but they also need to handle byte order.

**Comment by mitza-oci** [comment]
@jwillemsen anything left to do for this one?
