### ISSUE TITLE
ERROR: Could not detect Visual C++ version, try running this script from the Visual Studio Command Prompt.

### ISSUE THREAD

**Issue by floatingbit** [objectcomputing/OpenDDS#945]
I am facing the following issue while trying to configure OpenDDS-3.13: "ERROR: Could not detect Visual C++ version, try running this script from the Visual Studio Command Prompt."

When I run cl from the VS2015 x64 Native Tools Command Prompt, it shows that a C++ compiler is being found: "Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]"

Am I missing something?

I tried to run configure in version 3.9 without any problems. I was also able to build the solution successfully. I have ActivePerl-5.24.3.2404-MSWin32-x64-404865 installed. I am using Visual Studio 2015.

**Comment by mitza-oci** [comment]
This was fixed by e03928265bd67674b370202963c32d73381c55f4 after the 3.13 release.  You should be able to use a newer version of `configure` from the repository.

**Comment by floatingbit** [comment]
Thank you very much for your quick response. That worked! Sorry I wasn't able to test this out sooner.

**Comment by floatingbit** [comment]
Here's the output from the console when I run perl run_test.pl

OpenDDS-3.13\bin\.\DCPSInfoRepo.EXE -ORBDebugLevel 10 -ORBLogFile DCPSInfoRepo.log -o repo.ior
TAO (23256|18772) - Completed initializing the process-wide service context
TAO (23256|18772) - Default ORB services initialization begins
TAO (23256|18772) - ORBInitializer_Registry::register_orb_initializer 0 @00000278F0D84A60
TAO (23256|18772) - ORBInitializer_Registry::register_orb_initializer 1 @00000278F0D34BD8
TAO (23256|18772) - Default ORB services initialization completed
TAO (23256|18772) - We are the default ORB ...
TAO (23256|18772) - Initializing the orb-specific services
.\.\publisher.EXE  -ORBDebugLevel 10 -DCPSDebugLevel 10 -ORBLogFile publisher.log
.\.\subscriber.EXE  -ORBDebugLevel 10 -DCPSDebugLevel 10 -DCPSTransportDebugLevel 6 -ORBLogFile subscriber.log
ERROR: publisher returned 3221225785
ERROR: subscriber returned 3221225785
INFO: C:<path to openDDS>/bin/DCPSInfoRepo being killed.

**Comment by mitza-oci** [comment]
There are two ReceivedDataElement constructors.  One is a copy constructor, the other takes multiple arguments.  Try the following commands and let us know if you get different results.

```
dumpbin /exports lib\OpenDDS_Dcpsd.dll | findstr ??0ReceivedDataElement@
        465  1D0 0049CA70 ??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBUDataSampleHeader@12@PEAXPEAVACE_Recursive_Thread_Mutex@@@Z = @ILT+178795(??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBUDataSampleHeader@12@PEAXPEAVACE_Recursive_Thread_Mutex@@@Z)
        466  1D1 0047EEB7 ??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBV012@@Z = @ILT+57010(??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBV012@@Z)
```
```
undname ??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBUDataSampleHeader@12@PEAXPEAVACE_Recursive_Thread_Mutex@@@Z ??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBV012@@Z
Microsoft (R) C++ Name Undecorator
Copyright (C) Microsoft Corporation. All rights reserved.

Undecoration of :- "??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBUDataSampleHeader@12@PEAXPEAVACE_Recursive_Thread_Mutex@@@Z"
is :- "public: __cdecl OpenDDS::DCPS::ReceivedDataElement::ReceivedDataElement(struct OpenDDS::DCPS::DataSampleHeader const & __ptr64,void * __ptr64,class ACE_Recursive_Thread_Mutex * __ptr64) __ptr64"

Undecoration of :- "??0ReceivedDataElement@DCPS@OpenDDS@@QEAA@AEBV012@@Z"
is :- "public: __cdecl OpenDDS::DCPS::ReceivedDataElement::ReceivedDataElement(class OpenDDS::DCPS::ReceivedDataElement const & __ptr64) __ptr64"
```

**Comment by floatingbit** [comment]
You can ignore this. My bad.

I had previously added a few of the OpenDDS3.9 paths to the system path due to which it was linking the incorrect DLL. Just removed them, logged back in and it's working great! 

Thank you for your support!
