### ISSUE TITLE
The delete_datareader call must return RETCODE_PRECONDITION_NOT_MET if the DataReader contains attached ReadConditions

### ISSUE THREAD

**Issue by jmmorato** [objectcomputing/OpenDDS#957]
According to the standard:

> The deletion of a DataReader is not allowed if there are any existing ReadCondition or QueryCondition objects that are attached to the DataReader. If the delete_datareader operation is called on a DataReader with any of these existing objects attached to it, it will return PRECONDITION_NOT_MET.

**Comment by jwillemsen** [comment]
Can you extend an existing unit test as reproducer?

**Comment by jmmorato** [comment]
Working on it ;)

I found another side-effect during the test, the `delete_contained_entities` doesn't clean-up the ReadConditions either
