### ISSUE TITLE
cannot run in security with static

### ISSUE THREAD

**Issue by sandshaw** [objectcomputing/OpenDDS#961]
I configured with  "--static --security" , and run  "publisher.exe" with  "rtps_disc_sec.ini", it comes:
(6644|18792) ERROR: DomainParticipantImpl::enable, DCPSSecurity flag is set, but unable to load security plugin configuration.
(6644|18792) ERROR: DomainParticipantFactoryImpl::create_participant, unable to enable DomainParticipant.
d:\hlddds_3.13\tests\dcps\messenger\publisher.cpp:106: main() ERROR: create_participant failed!
thanks

**Comment by sandshaw** [comment]
where shoud i load lib:  `load_security_plugin_lib(DEFAULT_PLUGIN_NAME);` in static?

**Comment by mitza-oci** [comment]
Security with static is not something we've tested in the 3.13 release.  I have some work on a local branch (not quite ready for a PR yet) that seems to work.

Just like other static libraries, make sure that the header for the library (in this case `dds/DCPS/security/BuiltInPlugins.h`) is included in the cpp file that has main.  The only other fix it required to initialize the Xerces XML parser.  Watch this repo for a new pull request which will include these changes.

**Comment by sandshaw** [comment]
@mitza-oci  Thanks，i will try.

**Comment by mitza-oci** [comment]
Should be fixed in https://github.com/objectcomputing/OpenDDS/pull/967
