### ISSUE TITLE
ERROR: Requested feature xerces3 not defined for ACE/TAO at configure line 1486.

### ISSUE THREAD

**Issue by xfroll00** [objectcomputing/OpenDDS#977]
Recently I try to use OpenDDS 3.13 Security on Win10x64 platform. I also followed the OpenDDS security manual and used configure --security --xerces3 --verbose I have got this output: ERROR: Requested feature xerces3 not defined for ACE/TAO at configure line 1486. (with build succeeded 0 warnings and errors)

Also when trying to run DDS_Security.mpc at OpenDDS_ROOT\tests\security I am getting following output: Generating 'vs2017' output using DDS_Security.mpc
Skipping AuthenticationTest (DDS_Security.mpc); it requires xerces.
Skipping AccessControlTest (DDS_Security.mpc); it requires xerces.
Skipping CryptoKeyFactoryTest (DDS_Security.mpc); it requires xerces.
Skipping CryptoKeyExchangeTest (DDS_Security.mpc); it requires xerces.
Skipping CryptoTransformTest (DDS_Security.mpc); it requires xerces.
Generation Time: 1s

EDIT: I have got similar problem with Ubuntu 16.04 after evoking ./configure --security --no-tests --verbose: ERROR: Can't find xerces3 at /usr (using include/xercesc/dom/DOM.hpp).

Please could anyone help me with som possible advice or solution?
Thank you very much in advance,
MF

**Comment by mitza-oci** [comment]
The error from the Windows build looks like you are attempting to use an already-configured ACE+TAO.  Please run the OpenDDS configure script on a completely clean source tree (no generated or modified files present) including ACE+TAO.  If there are still errors please copy/paste the output from configure with `--verbose` into your response here.

On Ubuntu, you can use the system's package manager to install the Xerces-C++ development package which will put the include files in `/usr/include` or you can build your own Xerces and provide its location to the configure script `--xerces3=<install root for xerces>`

**Comment by xfroll00** [comment]
Thank you very much, it seems like previous error from the Windows is solved, however I have got another error while starting publisher or subscriber in /tests/DCPS/Messenger on Windows with <-DCPSConfigFile rtps_disc_sec.ini> I am getting <ERROR: DomainParticipantImpl::enable, DCPSSecurity flag is set, but unable to load security plugin configuration> and I could not google anything about that.

Also when I publish samples from Windows and subscribe them on RPi with rtps.ini config file it works well, but when I subscribe them on Win an publish on RPi, subscriber on Windows justs prints datareaderlistener.cpp:146: INFO: on_subscription_matched() and no samples are printed after that. I do not understand because it worked few days ago.

May I ask you for some possible reasons of this behavior?

Thanks

**Comment by mitza-oci** [comment]
> Thank you very much, it seems like previous error from the Windows is solved

Closing this issue.  Please open a separate issue if there are ongoing problems.
