### ISSUE TITLE
security got “PEM_read_bio_X509_AUX failed”

### ISSUE THREAD

**Issue by sandshaw** [objectcomputing/OpenDDS#978]
I generated a self_signed RSA CA with:
`openssl genrsa -out identity_ca_private_key.pem 2048`
`openssl req -config openssl.cnf -new -key identity_ca_private_key.pem -out identity_ca.csr`
`openssl x509 -req -days 3650 -in identity_ca.csr -signkey identity_ca_private_key.pem -out identity_ca_cert.pem`

Run a test application with it and i got：
`(17900|4164) LocalAuthCredentialData::load: Number of Properties: 6`
`(17900|4164) LocalAuthCredentialData::load: property 0: dds.sec.auth.identity_ca: file:./security/identity_ca_cert.pem`
`(17900|4164) WARNING: '(null)' PEM_read_bio_X509_AUX failed `
`(17900|4164) SSL::Certificate::load: WARNING: Failed to load document supplied with URI 'file:./security/identity_ca_cert.pem'`
What happened？ 
Thanks for your help.

**Comment by mitza-oci** [comment]
OpenSSL was not able to open that file.  Is the relative path still valid (based on the process's current working directory)?  You could also use an absolute path.

**Comment by sandshaw** [comment]
Thanks mitaz.
The relative path is still valid and `Certificate::load_cert_bytes()` is successful. But failed in `Certificate::x509_from_pem` what cause `PEM_read_bio_X509_AUX failed`. I will try again with an absolute path.

**Comment by sandshaw** [comment]
I tried with absolute path, but it comes the same way.  I think i have something wrong with the
 file. But i have not found yet

**Comment by sandshaw** [comment]
> OpenSSL was not able to open that file. Is the relative path still valid (based on the process's current working directory)? You could also use an absolute path.

In  \dds\DCPS\security\SSL\Certificate.cpp

`X509* Certificate::x509_from_pem(const DDS::OctetSeq& bytes,
                                 const std::string& password)
{
  X509* result = NULL;

  BIO* filebuf = BIO_new(BIO_s_mem());
  do {
    if (filebuf) {
      if (0 >= BIO_write(filebuf, bytes.get_buffer(), bytes.length())) {
        HLDDDS_SSL_LOG_ERR("BIO_write failed");
        break;
      }
      if (password != "") {
        result = PEM_read_bio_X509_AUX(filebuf, NULL, NULL,
                                       (void*)password.c_str());
        if (!result) {
          HLDDDS_SSL_LOG_ERR("PEM_read_bio_X509_AUX failed");
          break;
        }

      } else {
        result = PEM_read_bio_X509_AUX(filebuf, NULL, NULL, NULL);
        if (!result) {
          HLDDDS_SSL_LOG_ERR("PEM_read_bio_X509_AUX failed");
          break;
        }
      }

    } else {
      std::stringstream errmsg;
      errmsg << "BIO_new failed";
      HLDDDS_SSL_LOG_ERR(errmsg.str().c_str());
      break;
    }

  } while (0);

  BIO_free(filebuf);

  return result;
}`
It is weird that `BIO_write(filebuf, bytes.get_buffer(), bytes.length())` returns OK, but `PEM_read_bio_X509_AUX(filebuf, NULL, NULL, NULL)` returns NULL, and in `PEM_read_bio_X509_AUX`, i got `BIO_gets` returns -2... 
I have no idea why this happened. Any help, thanks.

**Comment by mitza-oci** [comment]
What's different between your use case and the included tests?  Is the password string empty?

**Comment by sandshaw** [comment]
OK, i got it. I have multi-version openssl. I use openssl 1.1.1 is ok.
