### ISSUE TITLE
RTPS Discovery not working

### ISSUE THREAD

**Issue by rcmcminn** [objectcomputing/OpenDDS#979]
I am new to OpenDDS. I am testing with separate publisher and subscriber applications. When I run with DEFAULT_REPO and the DCPSInfoRepo process, all is good, the subscriber receives all topics published. When I switch to an RTPS-based ini file (DEFAULT_RTPS), the publisher continues to publish but the subscriber receives no incoming topics. When I enable debug output in the ini file, I see that the subscriber enables all DataReader (see a line specific for each topic).  The debug output for the subscriber shows "no association" indications.

I have no idea where to go from here. Is it an issue with the options for configuring the build of OpenDDS? Is it a call missing in my code? ???

OpenDDS Version: OpenDDS 3.12.2
OS                           CentOS v7 64 bit

[subscriber.log.rtps.txt](https://github.com/objectcomputing/OpenDDS/files/2592867/subscriber.log.rtps.txt)

**Comment by mitza-oci** [comment]
RTPS peer-to-peer discovery bootstraps by sending multicast traffic between the two processes.  Based on the log this traffic is not getting through.  Check that your system is configured to allow multicast.

**Comment by rcmcminn** [comment]
My system is configured for multicast. Here is a later log file and the ini file I am using. I enabled transport debug for this run.
[ste_rtps.ini.txt](https://github.com/objectcomputing/OpenDDS/files/2598315/ste_rtps.ini.txt)
[subscriber.log.txt](https://github.com/objectcomputing/OpenDDS/files/2598322/subscriber.log.txt)

**Comment by mitza-oci** [comment]
Our CentOS 7 build server is configured like so:
```
$ systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

**Comment by rcmcminn** [comment]
Bingo!!

The firewalld service was active.

I issued sudo systemctl stop firewalld then reran the RTPS test and the messages came through. 

Many thanks for the assistance.
