### ISSUE TITLE
Error while cross-compile on linux ARM

### ISSUE THREAD

**Issue by qjqjqjj** [objectcomputing/OpenDDS#992]
Hi, 

I am compiling opendDDS for my jetson TX2 which is linux ARM. I followed the same step as Rasberry PI.

When I configure it with the tool chain it have no issue but when I make it, it throws out error.

`~/openDDS/OpenDDS-3.13$ ./configure --target=linux-cross --target-compiler=/home/quanjie/Documents/JetsonTX2/Cross-compile/install/aarch64-unknown-linux-gnu/bin/g++` 

Error I got after make it:

`touch .depend.PortableServer_Idl_Idl5
touch .depend.PortableServer_Idl_Idl4
touch .depend.TAO_Core_idl_Idl11
touch .depend.PortableServer_Idl_Idl3
touch .depend.TAO_Core_idl_Idl10
touch .depend.PortableServer_Idl_Idl2
touch .depend.TAO_Core_idl_Idl9
touch .depend.PortableServer_Idl_Idl1
touch .depend.TAO_Core_idl_Idl8
touch .depend.PortableServer_Idl
touch .depend.TAO_Core_idl_Idl7
touch .depend.TAO_Core_idl_Idl6
touch .depend.TAO_Core_idl_Idl5
touch .depend.TAO_Core_idl_Idl4
touch .depend.TAO_Core_idl_Idl3
touch .depend.TAO_Core_idl_Idl2
touch .depend.TAO_Core_idl_Idl1
touch .depend.TAO_Core_idl
TAO_IDL_BE_VIS_C will not be built due to the following disabled make macros: build_tao_idl_be`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/TAO_IDL/GNUmakefile.TAO_IDL_BE_VIS_C MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/TAO_IDL'`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/IORTable/GNUmakefile.IORTable_Core_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: Entering directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/PI_Server'
make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'IORTableS.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/IORTable'
GNUmakefile.dist:773: recipe for target 'IORTable_Core_Idl' failed
make[1]: *** [IORTable_Core_Idl] Error 2
make[1]: *** Waiting for unfinished jobs....`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/Valuetype/GNUmakefile.Valuetype_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'StringValueA.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/Valuetype'
GNUmakefile.dist:573: recipe for target 'Valuetype_Idl' failed
make[1]: *** [Valuetype_Idl] Error 2`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/Codeset/GNUmakefile.Codeset_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'CodeSetContextS.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/Codeset'
GNUmakefile.dist:589: recipe for target 'Codeset_Idl' failed
make[1]: *** [Codeset_Idl] Error 2
GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/AnyTypeCode/GNUmakefile.AnyTypeCode_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'AnySeqS.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/AnyTypeCode'
GNUmakefile.dist:581: recipe for target 'AnyTypeCode_Idl' failed
make[1]: *** [AnyTypeCode_Idl] Error 2`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/CodecFactory/GNUmakefile.CodecFactory_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'IOP_CodecC.cpp'.  Stop.
GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/IORManipulation/GNUmakefile.IORManipulation_Idl MAKEFLAGS=w -j --jobserver-fds=4,5
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/CodecFactory'
GNUmakefile.dist:645: recipe for target 'CodecFactory_Idl' failed
make[1]: *** [CodecFactory_Idl] Error 2`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'IORC.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/IORManipulation'
GNUmakefile.dist:749: recipe for target 'IORManipulation_Idl' failed
make[1]: *** [IORManipulation_Idl] Error 2`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/PI/GNUmakefile.PI_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'PI_includeC.cpp'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/PI'
GNUmakefile.dist:637: recipe for target 'PI_Idl' failed
make[1]: *** [PI_Idl] Error 2`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/IORTable/GNUmakefile.Async_IORTable_Core_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'Async_IORTableS.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/IORTable'
GNUmakefile.dist:765: recipe for target 'Async_IORTable_Core_Idl' failed
make[1]: *** [Async_IORTable_Core_Idl] Error 2`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/Messaging/GNUmakefile.Messaging_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'ExceptionHolderS.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/Messaging'
GNUmakefile.dist:565: recipe for target 'Messaging_Idl' failed
make[1]: *** [Messaging_Idl] Error 2`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/PortableServer/GNUmakefile.PortableServer_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'ForwardRequestA.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/PortableServer'
GNUmakefile.dist:669: recipe for target 'PortableServer_Idl' failed
make[1]: *** [PortableServer_Idl] Error 2`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/GNUmakefile.TAO_Core_idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../lib/libTAO_IDL_BE.so', needed by 'GIOPC.cpp'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao'
GNUmakefile.dist:597: recipe for target 'TAO_Core_idl' failed
make[1]: *** [TAO_Core_idl] Error 2
touch .depend.PI_Server_Idl_Idl2
touch .depend.PI_Server_Idl_Idl1
touch .depend.PI_Server_Idl`

`GNUmakefile: /home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/PI_Server/GNUmakefile.PI_Server_Idl MAKEFLAGS=w -j --jobserver-fds=4,5`

`make[2]: *** No rule to make target '../../../lib/libTAO_IDL_BE.so', needed by 'ServerRequestInfoC.h'.  Stop.
make[2]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO/tao/PI_Server'
GNUmakefile.dist:805: recipe for target 'PI_Server_Idl' failed
make[1]: *** [PI_Server_Idl] Error 2
make[1]: Leaving directory '/home/quanjie/openDDS/OpenDDS-3.13/build/target'
GNUmakefile:3: recipe for target 'all' failed
make: *** [all] Error 2`

Does anyone know how to fix it? I am still new to openDDS on linux ARM so do pardon me for any mistake I make.

Thanks!

**Comment by mitza-oci** [comment]
Please run `tools/scripts/show_build_config.pl` and paste the output into your reply.

**Comment by qjqjqjj** [comment]
Hi @mitza-oci ,

Here is the output:

Host Build:
================ setenv.sh ================
# OpenDDS configure script: ./configure --target=linux-cross --target-compiler=/home/quanjie/Documents/JetsonTX2/Cross-compile/install/aarch64-unknown-linux-gnu/bin/gcc
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export MPC_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/ACE_wrappers/MPC
export DDS_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/build/host
export ACE_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/build/host/ACE_wrappers
export CIAO_ROOT=unused
export DANCE_ROOT=unused
export PATH=${PATH}
export TAO_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/build/host/ACE_wrappers/TAO
================ platform_macros.GNU ================
static_libs_only = 1
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
================ config.h ================
#include "ace/config-linux.h"
Target Build:
================ setenv.sh ================
# OpenDDS configure script: ./configure --target=linux-cross --target-compiler=/home/quanjie/Documents/JetsonTX2/Cross-compile/install/aarch64-unknown-linux-gnu/bin/gcc
export HOST_DDS=/home/quanjie/openDDS/OpenDDS-3.13/build/host
export TAO_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/TAO
export DANCE_ROOT=unused
export PATH=${PATH}:/home/quanjie/openDDS/OpenDDS-3.13/build/host/ACE_wrappers/bin:/home/quanjie/openDDS/OpenDDS-3.13/build/host/bin
export HOST_ACE=/home/quanjie/openDDS/OpenDDS-3.13/build/host/ACE_wrappers
export CIAO_ROOT=unused
export ACE_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers
export DDS_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/build/target
export MPC_ROOT=/home/quanjie/openDDS/OpenDDS-3.13/ACE_wrappers/MPC
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/quanjie/openDDS/OpenDDS-3.13/build/target/ACE_wrappers/lib:/home/quanjie/openDDS/OpenDDS-3.13/build/target/lib
================ user_macros.GNU ================
OPENDDS_IDL = $(HOST_DDS)/bin/opendds_idl
OPENDDS_IDL_DEP = $(OPENDDS_IDL)$(HOST_EXE_EXT)
IDL2JNI = $(HOST_DDS)/bin/idl2jni
IDL2JNI_DEP = $(IDL2JNI)$(HOST_EXE_EXT)
CROSS-COMPILE = 1
================ default.features ================
cross_compile=1
================ platform_macros.GNU ================
optimize = 0
TAO_IDL = $(HOST_ACE)/bin/tao_idl
TAO_IDL_DEP = $(TAO_IDL)
TAO_IDL_PREPROCESSOR = g++
TAO_IDLFLAGS += -g $(HOST_ACE)/bin/ace_gperf
build_tao_idl_be = 0
LDFLAGS += -Wl,-rpath-link,$(ACE_ROOT)/lib
include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
CC = g++
CXX = g++
LD = g++
================ config.h ================
#include "ace/config-linux.h"

Thanks

**Comment by mitza-oci** [comment]
First remove the `build` directory to start over.  Then try configuring with the target compiler set to `/home/quanjie/Documents/JetsonTX2/Cross-compile/install/bin/aarch64-unknown-linux-gnu-g++`.  The configure script is looking for a `-g++` suffix there.  Not sure that's correct but it's hard to determine exactly what would work in all cases for cross-compilers we haven't seen before.

**Comment by qjqjqjj** [comment]
Hi @mitza-oci ,

Thanks for your advise, I am able to make without any error. I have another question is to how am I going to transfer the file to my Jetson TX2 board (linux ARM). Do I just transfer the build/target file to my board? However, I notice inside build/target there is 'link to text' file and I could not transfer these over to my board. 

Thanks!

**Comment by mitza-oci** [comment]
Please see http://opendds.org/quickstart/GettingStartedPi.html for one method of moving data to an embedded Linux system (shouldn't matter if it's a Pi or something else).  I also recommend using shared filesystems (like NFS) during development.
