### ISSUE TITLE
C++11 mapping: DCPS_DATA_KEY for complex expressions

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/OpenDDS#994]
When using the new IDL-to-C++11 mapping, the code that's generated by DCPS_DATA_KEY is not yet aware of complex key expressions (those containing a `.` or `[]`).

**Comment by mmcparlane** [comment]
This issue is being worked in the following branch:
https://github.com/objectcomputing/OpenDDS/tree/issue-994-cpp11-mapping
